### ISSUE TITLE
thumbor:WARNING Malformed URL

### ISSUE THREAD

**Issue by rafaelmcouto** [thumbor/thumbor#1001]
### Thumbor request URL
http://localhost:8888/unsafe/300x200/https://www.fourseasons.com/content/dam/fourseasons/images/web/BOR/BOR_100_1280x486.jpg/jcr:content/renditions/cq5dam.web.1280.1280.jpeg ( It's OK )

http://localhost:8888/ETrwvKvOlIjk1PpOaY0-C_Ecom0=/https%3A//www.fourseasons.com/content/dam/fourseasons/images/web/BOR/BOR_100_1280x486.jpg/jcr%3Acontent/renditions/cq5dam.web.1280.1280.jpeg ( with malformed url )

### Expected behaviour
I made the install by pip and github, and I have the same problem with both.
$ thumbor --version
Thumbor v6.3.3rc (22-Jun-2017)

### Actual behaviour
The page cannot display the image

### Operating system
Ubuntu Server 16.04

### Your thumbor.conf
The default

**Comment by guilouro** [comment]
I got the same problem! Did you have a solution for this issue?

**Comment by Enalmada** [comment]
Can you try it without https:// in the image url?  I have had to strip that (http|https):// off all of my images to get thumbor to work.
 
`localhost:8888/2aYy6-yJ0J87gtwW0hFnU86LQD4=/www.fourseasons.com/content/dam/fourseasons/images/web/BOR/BOR_100_1280x486.jpg/jcr:content/renditions/cq5dam.web.1280.1280.jpeg`

**Comment by undertakingyou** [comment]
I am facing the same problems as this issue, which I have seen repeated in 666 and 897, which I that I always get malformed URL when I try to use the thumbor with a secure URL, but not when I try to use the unsafe URL. 

I use thumbor-url to get the URL ending part itself: 
```
thumbor-url --key='rHOtAiNfIceLderMiNealeCKerothmAkeyEveNankeyeFEsiAL' --width=100 --height=100 cdn-images-1.medium.com/max/800/1*tR_m1tLvYS8VXX1w5mHz5A.png
```
Which outputs 
```
/9I26I3rqf7rXegE3UHamP3WDJtU=/100x100/cdn-images-1.medium.com/max/800/1%2AtR_m1tLvYS8VXX1w5mHz5A.png
```

I have the following in a thumbor.conf file: 
```
## The security key thumbor uses to sign image URLs
## Defaults to: 'MY_SECURE_KEY'
SECURITY_KEY = 'whateverIwant'
```

I then run thumbor with this command: `thumbor --keyfile ./thumbor.conf` which points to the config file mentioned above. I still get the malformed URL. 
```
thumbor:WARNING Malformed URL: /ApJsXO6UrMnNWQRuGz2kNoKRmFc=/100x100/cdn-images-1.medium.com/max/800/1%2AtR_m1tLvYS8VXX1w5mHz5A.png
```

Is there any more on troubleshooting or anything that I can do here. I realize that currently I am testing, which allows me to use unsafe, but I would like to plan for the future and implement the secure URL sooner. I have yet to find an image where the secure URL works.

**Comment by Enalmada** [comment]
Incase it helps someone, I discovered that my NGINX proxy server is causing my problem with secure url.  It must be encoding something differently when processing urls.

**Comment by jamesabc** [comment]
We have the same problem that can be fixed by dropping `https://` from the URL.  Unfortunately to use it with S3 loader and http fallback, it's necessary to keep that due to https://github.com/thumbor-community/aws/blob/7b40255be6c846c6ed27a2ab037ed74d6c8d2c84/tc_aws/loaders/__init__.py#L73

When we look at debug logging, we see that the URL is missing a `/`, i.e. it has become `https:/`:

```
thumbor:WARNING Malformed URL: /6sMZFRp0ylMAYnxF-wRj4p6OdVk=/640x480/https:/upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/440px-Cat03.jpg
```

**Comment by pengliaoye** [comment]
anyone resolve this issue

**Comment by BenMorel** [comment]
I had a similar issue, but that was due to the fact that I was hashing the path starting with `/`, when you should omit the slash.

It's actually disturbing that Thumbor reports "Malformed URL" when the problem is actually an incorrect signature.
