### ISSUE TITLE
Python 3.x.x support for thumbor.

### ISSUE THREAD

**Issue by adnrs96** [thumbor/thumbor#1004]
Hey people!
This is a really nice project we came across and would like to use it in our app. I wanted to drop in and ask about the status of python 3.x.x support for thumbor (even request for its support). Are there any plans for adding this support or what needs to happen for thumbor to support python3?
Thanks!

**Comment by timabbott** [comment]
For context, we're hoping to use Thumbor in Zulip (https://github.com/zulip/zulip/) which just moved to Python 3 only.  We could of course run Thumbor in a separate virtualenv, but it'd be nice to be able to be fully on Python 3.  So if there's a relatively short list of work left, we might be able to help pitch in to make that happen.

**Comment by hugovk** [comment]
I can see tests are run on Travis for 3.5 and 3.6, which are failing right now, but that shows an intention and a good start to support Python 3.

I guess a good way to help out would be to jump in and start fixing some tests.

**Comment by heynemann** [comment]
We'll be rolling a python 3 compatible version soon. I think @rfloriano is working on it.

**Comment by timabbott** [comment]
Awesome, that's super exciting! :)

**Comment by marcelometal** [comment]
Hello! 

We are working to make it compatible as soon as possible. I've pushed some fixes to `master` and together with @rfloriano, we've started to fix the tests.

**Comment by Xrampino** [comment]
Hello,

I've seen a lot of work on Python 3 in the latest releases. What is the state of the support, is it production ready ?

**Comment by ElMoselYEE** [comment]
Python 2 will lose support at the end of 2019--10 months away. Is it a reasonable goal for Thumbor to support Python 3 before then?

**Comment by cristiandean** [comment]
Hello @ElMoselYEE, we are working on a branch with the aim of making a complete refactor in Thumbor. This already includes the support for Python 3.7. You can take a look at what we already have ready, and also we are open to pull requests =)

[thumbor/refactor](https://github.com/thumbor/thumbor/tree/refactor)

**Comment by sibelius** [comment]
@cristiandean python 3 support is done already?

**Comment by bourdeau** [comment]
Hi,

We are planning in using Thumbor in my company, but we can't go for it in Python 2.7. What is the the current progress of the [thumbor/refactor](https://github.com/thumbor/thumbor/tree/refactor) branch? Does anyone have a rough idea of when it will be merged? We could help with PR if needed, we have 50+ dev, half of them Pythonists, and Photography is our business :)

**Comment by cristiandean** [comment]
Hello @bourdeau It would be awesome if your team could contribute with us =D You can track the entire roadmap in the branch refactor Readme. This new version has been practically rewritten from scratch, we are using a different architecture from the current one, bringing the concept of blueprints into the project, and thus gaining much more extensibility in Thumbor.

Let me know if you need anything.

**Comment by sten0** [comment]
Hi @cristiandean,  What is the status of the Python 3 port at https://github.com/thumbor/thumbor/tree/refactor ?  I worry the package will be removed from Debian in the next month or two.  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=935450

**Comment by andreportela** [comment]
Can it be released as is? Maybe the first python 3 version doesn't even need to have feature parity with the 2.7 version. Basic stuff like a naive crop and resize already cover a lot of use cases.

**Comment by heynemann** [comment]
It's finally here! Python 3 support hit master. For more info check https://github.com/thumbor/thumbor/releases/tag/7.0.0a2

**Comment by MrTango** [comment]
Would be nice if the PyPi classifiers could be updated, so that people can see that it has Python3 support now ;).
Right now it just says Python2.7:
"Programming Language :: Python :: 2.7",

**Comment by hugovk** [comment]
> Would be nice if the PyPi classifiers could be updated, so that people can see that it has Python3 support now ;).
> Right now it just says Python2.7:
> "Programming Language :: Python :: 2.7",

Good idea, please see PR https://github.com/thumbor/thumbor/pull/1283 which also adds `python_requires` to help pip.
