### ISSUE TITLE
[Help] Crop

### ISSUE THREAD

**Issue by Krato** [thumbor/thumbor#1009]
Hello, I'm having problems croping an image. But I want learn how to do it.

I have this image: ![Default image](https://s3-eu-west-1.amazonaws.com/temply-tests/R65qzGLO5gDYvrnN/library/12/u0yz7o.jpg)

And I want t crop it to that:
![success](http://res.cloudinary.com/krato/image/upload/c_scale,h_1342,w_2182/c_crop,h_289,w_309,x_336,y_334/c_scale,h_516,w_552/v1510667309/06_rnzdb3.png)

In cloudinary the steps are easy: 

`
http://res.cloudinary.com/krato/image/upload/_c_scale_,h_1342,w_2182/c_crop,h_289,w_309,x_336,y_334/c_scale,h_516,w_552/v1510667309/06_rnzdb3.png
`     

So cloudinary does: 
```
Resize: 2182x1342
Crop an image of 309x289 from x336 and y334 from the resized image
Resize the crop to: 552x516
```

Ok, now, how can I reproduce that in thumbor?

I try to do it a lot of times,  but no luck.

Thanks so much in advance

**Comment by heynemann** [comment]
From http://thumbor.readthedocs.io/en/latest/usage.html#image-endpoint

http://*thumbor-server*/hmac/trim/AxB:CxD/fit-in/-Ex-F/HALIGN/VALIGN/smart/filters:FILTERNAME(ARGUMENT):FILTERNAME(ARGUMENT)/*image-uri*

So in your case:
http://*thumbor-server*/unsafe/336x334:645x623/552x516/v1510667309/06_rnzdb3.png

The part that matters to you is `336x334:645x623/552x516`.
The first part crops from point (336,334) to point (645,623). See, thumbor does not work with a point and dimensions like Cloudinary. We use two points, the top left point and the bottom right point.

After the image has been cropped, you just resize the crop to the size you want.

Hope this helps. Reopen this issue if you have any more questions about this, though you can always check the docs. They are very comprehensive.

**Comment by Krato** [comment]
Ok. Now I can understand. But I'm having other problem.

I'm trying to resize the original image to exactly 2182x1342 pixels. 

But the problem is that if I call `http://localhost:8000/unsafe/2182x1342/https://s3-eu-west-1.amazonaws.com/temply-tests/R65qzGLO5gDYvrnN/library/12/u0yz7o.jpg`.

The image is being cropped in the sides. How can I do it? Just resize it without crop?

Thanks so much in advance!

**Comment by Savar** [comment]
http://localhost:8000/unsafe/fit-in/2182x1342/https://s3-eu-west-1.amazonaws.com/temply-tests/R65qzGLO5gDYvrnN/library/12/u0yz7o.jpg

**Comment by Savar** [comment]
if you want to fill the borders to really have the full size requested:

http://localhost:8000/unsafe/fit-in/2182x1342/filters:upscale():fill(white)/https://s3-eu-west-1.amazonaws.com/temply-tests/R65qzGLO5gDYvrnN/library/12/u0yz7o.jpg

**Comment by Savar** [comment]
uh.. the `upscale()` filter might not be released yet.. just mentioning that...

**Comment by Krato** [comment]
Thanks @Savar but fit-in is not working. If you go to 
```
http://localhost:8000/unsafe/meta/fit-in/2182x1342/https://s3-eu-west-1.amazonaws.com/temply-tests/R65qzGLO5gDYvrnN/library/12/u0yz7o.jpg
````
you will see that the target is not 2182x1342

**Comment by Savar** [comment]
as I said.. the `upscale()` filter is inside master but isn't released yet.. so you have install the master branch or pull the single filter into your existing thumbor installation.

If I do it with my own thumbor (having the `upscale()` filter inside) I get the correct image:

http://localhost:8000/unsafe/fit-in/2182x1342/filters:upscale():fill(white)/https://s3-eu-west-1.amazonaws.com/temply-tests/R65qzGLO5gDYvrnN/library/12/u0yz7o.jpg

![with_upscale](https://user-images.githubusercontent.com/246341/32882786-c3879312-cab5-11e7-93bf-71cbc23ef7be.png)

besides that, the file name in S3 is misleading ... the file is not a JPEG but a PNG file.
