### ISSUE TITLE
Use thumbor as a component in a flask app

### ISSUE THREAD

**Issue by mengkuan** [thumbor/thumbor#101]
Is there a way to use thumbor as part of a flask app? Or can it be used as a module to perform smart cropping with face/feature detection given an image url?

Reason is that I already have a flask app running and I would prefer not running a separate instance of thumbor listening on a different port.

**Comment by vanchung1995** [comment]
@heynemann I have some code that convert jpg to avif image. Now I want to integrate it with thumbor. But I don't know how to do. Can you give some advices? Thanks
