### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by makoshim** [thumbor/thumbor#1010]
Hi, 

I know the license of thumbor is MIT, but I found a file below.
https://github.com/thumbor/thumbor/blob/master/thumbor/ext/filters/lib/wavelet_sharpen.c

The head comment states that this code is under GPL.

If thumbor contains GPL code, thumbor will have to change own license from MIT to GPL, I guess.

Could you confirm whether there is a problem or not?

**Comment by marcelometal** [comment]
Hi @makoshim,

I'm not a lawyer, but IMHO I think not, because MIT is [GPL-compatible](https://www.gnu.org/licenses/license-list.html#Expat).

Please, reopen this issue if you have any more questions about this.
