### ISSUE TITLE
Gifsicle not working on AWS Lambda

### ISSUE THREAD

**Issue by deadmantfa** [thumbor/thumbor#1012]
### Thumbor request URL
https://img.indiefolio.com/300x300/project/thumb/5b3f29c30fc4ba9d40149a4f9ae0b6fc.gif

### Expected behaviour
should resize the animated gif

### Actual behaviour
getting the following error
If using USE_GIFSICLE_ENGINE configuration to True, the `gifsicle` binary must be in the PATH and must be an executable

### Operating system
Amazon Lambda

## Defaults to: %(asctime)s %(name)s:%(levelname)s %(message)s
#THUMBOR_LOG_FORMAT = '%(asctime)s %(name)s:%(levelname)s %(message)s'

## Defaults to: %Y-%m-%d %H:%M:%S
#THUMBOR_LOG_DATE_FORMAT = '%Y-%m-%d %H:%M:%S'

################################################################################

from os.path import expanduser, join
home = expanduser("~")

## Defaults to: 0
#MAX_WIDTH = 0

## Defaults to: 0
#MAX_HEIGHT = 0

## Defaults to: 1
#MIN_WIDTH = 1

## Defaults to: 1
#MIN_HEIGHT = 1

## Defaults to: []
#ALLOWED_SOURCES = #    [
#    ]

## Defaults to: 80
QUALITY = 85
WEBP_QUALITY = 80

## Defaults to: 86400
MAX_AGE = 365 * 24 * 60 * 60

## Defaults to: 0
MAX_AGE_TEMP_IMAGE = 0

## Defaults to: False
#RESPECT_ORIENTATION = False

## Defaults to: True
#ALLOW_ANIMATED_GIFS = True
PRESERVE_EXIF_INFO = False
SEND_IF_MODIFIED_LAST_MODIFIED_HEADERS = False
ALLOW_ANIMATED_GIFS = True
AUTO_WEBP = True
OPTIMIZERS = [
   'thumbor_plugins.optimizers.pngquant',
   'thumbor.optimizers.gifv'
]
USE_GIFSICLE_ENGINE = True

GIFSICLE_PATH='/var/task/gifsicle'

PNGQUANT_PATH='/var/task/pngquant'
PNGQUANT_QUALITY=80
PNGQUANT_SPEED=3
################################################################################

## Defaults to: thumbor.loaders.http_loader
#LOADER = 'thumbor.loaders.http_loader'
LOADER = 'tc_aws.loaders.s3_loader'

## Defaults to: thumbor.storages.file_storage
#STORAGE = 'thumbor.storages.file_storage'
STORAGE = 'thumbor.storages.no_storage'

## Defaults to: None
#RESULT_STORAGE = None
RESULT_STORAGE = 'thumbor.result_storages.no_storage'

## Defaults to: thumbor.engines.pil
ENGINE = 'thumbor.engines.pil'

MAX_SOURCE_SIZE = 0

################################################################################

## Defaults to: MY_SECURE_KEY
SECURITY_KEY = 'MY_SECURE_KEY'

## Defaults to: True
ALLOW_UNSAFE_URL = True

## Defaults to: True
#ALLOW_OLD_URLS = True

################################################################################

## Defaults to: /tmp
#FILE_LOADER_ROOT_PATH = '/tmp'

################################################################################

## Defaults to: 2592000
#STORAGE_EXPIRATION_SECONDS = 2592000

## Defaults to: False
#STORES_CRYPTO_KEY_FOR_EACH_IMAGE = False
STORES_CRYPTO_KEY_FOR_EACH_IMAGE = True

## Defaults to: /var/folders/th/z6vmj34j1gngpvwl5fg5t9440000gp/T/thumbor/storage
#FILE_STORAGE_ROOT_PATH = '/var/folders/th/z6vmj34j1gngpvwl5fg5t9440000gp/T/thumbor/storage'
FILE_STORAGE_ROOT_PATH = join(home, 'thumbor', 'storage' )

################################################################################

## Defaults to: 0
#UPLOAD_MAX_SIZE = 0

## Defaults to: False
UPLOAD_ENABLED = False

## Defaults to: thumbor.storages.file_storage
UPLOAD_PHOTO_STORAGE = 'thumbor.storages.file_storage'

## Defaults to: False
UPLOAD_DELETE_ALLOWED = False

## Defaults to: False
UPLOAD_PUT_ALLOWED = False

## Defaults to: image
UPLOAD_DEFAULT_FILENAME = 'image'

################################################################################

## Defaults to: localhost
#MONGO_STORAGE_SERVER_HOST = 'localhost'

## Defaults to: 27017
#MONGO_STORAGE_SERVER_PORT = 27017

## Defaults to: thumbor
#MONGO_STORAGE_SERVER_DB = 'thumbor'

## Defaults to: images
#MONGO_STORAGE_SERVER_COLLECTION = 'images'

################################################################################

## Defaults to: localhost
#REDIS_STORAGE_SERVER_HOST = 'localhost'

## Defaults to: 6379
#REDIS_STORAGE_SERVER_PORT = 6379

## Defaults to: 0
#REDIS_STORAGE_SERVER_DB = 0

## Defaults to: None
#REDIS_STORAGE_SERVER_PASSWORD = None

################################################################################

## Defaults to: ['localhost:11211']
#MEMCACHE_STORAGE_SERVERS = #    [
#        'localhost:11211',
#    ]

################################################################################

## Defaults to: thumbor.storages.no_storage
#MIXED_STORAGE_FILE_STORAGE = 'thumbor.storages.no_storage'

## Defaults to: thumbor.storages.no_storage
#MIXED_STORAGE_CRYPTO_STORAGE = 'thumbor.storages.no_storage'

## Defaults to: thumbor.storages.no_storage
#MIXED_STORAGE_DETECTOR_STORAGE = 'thumbor.storages.no_storage'

################################################################################

## Defaults to: None
#META_CALLBACK_NAME = None

################################################################################

## Defaults to: []
#DETECTORS = #    [
#    ]

## Defaults to: haarcascade_frontalface_alt.xml
#FACE_DETECTOR_CASCADE_FILE = 'haarcascade_frontalface_alt.xml'

################################################################################

## Defaults to: []
#FILTERS = #    [
#    ]

################################################################################

## Defaults to: 0
#RESULT_STORAGE_EXPIRATION_SECONDS = 0
RESULT_STORAGE_EXPIRATION_SECONDS = 60 * 60 * 24  # one day

## Defaults to: /var/folders/th/z6vmj34j1gngpvwl5fg5t9440000gp/T/thumbor/result_storage
#RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/var/folders/th/z6vmj34j1gngpvwl5fg5t9440000gp/T/thumbor/result_storage'
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = join(home, 'thumbor', 'result_storage')

## Defaults to: False
RESULT_STORAGE_STORES_UNSAFE = False

################################################################################

## Defaults to: localhost
#REDIS_QUEUE_SERVER_HOST = 'localhost'

## Defaults to: 6379
#REDIS_QUEUE_SERVER_PORT = 6379

## Defaults to: 0
#REDIS_QUEUE_SERVER_DB = 0

## Defaults to: None
#REDIS_QUEUE_SERVER_PASSWORD = None

################################################################################

## Defaults to: None
#SQS_QUEUE_KEY_ID = None

## Defaults to: None
#SQS_QUEUE_KEY_SECRET = None

## Defaults to: us-east-1
#SQS_QUEUE_REGION = 'us-east-1'

################################################################################

## Defaults to: False
#USE_CUSTOM_ERROR_HANDLING = False

## Defaults to: thumbor.error_handlers.sentry
#ERROR_HANDLER_MODULE = 'thumbor.error_handlers.sentry'

################################################################################

## Defaults to:
#SENTRY_DSN_URL = ''

################################################################################

############################### AWS ################################
# AWS Region the bucket is located in.
TC_AWS_REGION='us-east-1'
# A custom AWS endpoint.
TC_AWS_ENDPOINT='http://s3.amazonaws.com'

# When using either tc_aws.loaders.s3_loader or tc_aws.loaders.presigning_loader.
TC_AWS_STORAGE_BUCKET='itest001' # S3 bucket for Storage
TC_AWS_STORAGE_ROOT_PATH='' # S3 path prefix for Storage bucket

# S3 bucket for Loader. If given, source urls are interpreted as keys
# within this bucket. If not given, source urls are expected to contain
# the bucket name, such as 's3-bucket/keypath'.
TC_AWS_LOADER_BUCKET='itest001'

# S3 path prefix for Loader bucket. If given, this is prefixed to
# all S3 keys.
TC_AWS_LOADER_ROOT_PATH=''

# Enable HTTP Loader as well?
# This would allow you to load watermarks in over your images dynamically through a URI
# E.g.
# http://your-thumbor.com/unsafe/filters:watermark(http://example.com/watermark.png,0,0,50)/s3_bucket/photo.jpg
TC_AWS_ENABLE_HTTP_LOADER=False

TC_AWS_ALLOWED_BUCKETS=False # List of allowed bucket to be requested

TC_AWS_STORAGE_BUCKET='' # S3 bucket for Storage
TC_AWS_STORAGE_ROOT_PATH='' # S3 path prefix for Storage bucket

# When tc_aws.storages.s3_storage is enabled.
# put data into S3 using the Server Side Encryption functionality to
# encrypt data at rest in S3
# https://aws.amazon.com/about-aws/whats-new/2011/10/04/amazon-s3-announces-server-side-encryption-support/
TC_AWS_STORAGE_SSE=False

# put data into S3 with Reduced Redundancy
# https://aws.amazon.com/about-aws/whats-new/2010/05/19/announcing-amazon-s3-reduced-redundancy-storage/
TC_AWS_STORAGE_RRS=False

# When tc_aws.result_storages.s3_storage is enabled.
TC_AWS_RESULT_STORAGE_BUCKET='' # S3 bucket for result Storage
TC_AWS_RESULT_STORAGE_ROOT_PATH='' # S3 path prefix for Result storage bucket
TC_AWS_MAX_RETRY=0 # Max retries for get image from S3 Bucket. Default is 0

TC_AWS_STORE_METADATA=False # Store result with metadata (for instance content-type)
################################################################################

I have compiled gifsicle but there is no way to set the path like we set the path for PNGQUANT it would be great if we had that option

**Comment by Enalmada** [comment]
@deadmantfa It is awesome AWS did that.  Do you feel like the latest version 2.2 is production ready? (I see you have your own fork so I just wanted to check on what you recommended new users use)

I am interested in your conclusions about blurry images before I jump in.  I see several open serverless tickets on image quality issues.  I am curious if blurry is a lambda issue or a thumbor issue, ie does an manual ubuntu thumbor install have the same problem?  (I say ubuntu because I believe that webp [may not work](https://github.com/thumbor/thumbor/issues/1061) on centos which would be a dealbreaker if serverless is really [failing to properly encode webp](https://github.com/awslabs/serverless-image-handler/issues/20#issuecomment-389944422)).   

Slightly off topic but since we are here, I have my own ec2 machine running with the [AUTO plugin](https://github.com/thumbor/thumbor-plugins/wiki/Auto).   Is it easy enough to get plugins working on serverless...I guess you just fork and change their build script?

**Comment by Enalmada** [comment]
I would be curious for samples of original/compressed images you find have quality issues so I can see if a server instance has the same problem.  I am assuming the quality issue has nothing to do with serverless but I just wanted to be able to rule that out.

**Comment by Enalmada** [comment]
It seems gif works now this issue can probably be closed and perhaps other tickets can be opened about sharpness/quality if it is really a thumbor issue and not some quirk of serverless.
