### ISSUE TITLE
Requesting original image, same size and quality 100, looks worse

### ISSUE THREAD

**Issue by Frexuz** [thumbor/thumbor#1017]
### Thumbor request URL
https://dev.img.flately.com/2U7Dk1P1Yl0YsyxB4MrMTC5RR6A=/0x0/filters:quality(100)/properties/996/4976-8ed210b5a63623077ad61b324a953e84.jpg

Original: (Made this one public, have to download it)
https://s3.amazonaws.com/flately-test-images/properties/996/4976-8ed210b5a63623077ad61b324a953e84.jpg

| original |
| --- |
| ![screen shot 2017-12-15 at 17 05 31](https://user-images.githubusercontent.com/49692/34034883-39ea6270-e1bb-11e7-9427-5320ddf032cf.png) |

| after |
| --- | 
| ![screen shot 2017-12-15 at 17 05 47](https://user-images.githubusercontent.com/49692/34034889-3cf287b8-e1bb-11e7-868e-8f1116ece1e2.png) |

### Expected behaviour
They should be identical.

0x0 should request original, right?
quality 100 should not do any compression, right?

### Actual behaviour
The thumbor image clearly has more noise (check sky)

### Operating system
AWS

### Your thumbor.conf
https://github.com/awslabs/serverless-image-handler/blob/master/source/image-handler/thumbor.conf

**Comment by andreaugusto** [comment]
Heya, @Frexuz! 

First, about your questions:
> quality 100 should not do any compression, right?

Yes, but it depends on the Engine used to process the image. One could use an engine that always adds some loss to the final image no matter what quality you use. This could happen if you try to do some kind of format conversion. Eg: GIFV to WEBM

> 0x0 should request original, right?

Yes.

About your problem, I am using the configuration you shared (removing the PNG optimizer and the AWS loader) and, locally, I could not reproduce the quality loss. The file you are generating is 77Kb, the original one is 105Kb and mine is actually higher 214Kb. This could have something to do with the loader... Don't know if it could add some loss to the image though.

Care to share your Thumbor and Pillow version?

**Comment by Frexuz** [comment]
Not sure exactly what versions are installed since Lambda is a closed environment.

All I know is `'thumbor>=6.2.1'`
https://github.com/awslabs/serverless-image-handler/blob/master/source/image-handler/setup.py

:/

**Comment by kkopachev** [comment]
jpeg decode+encode is lossy operation. Even at quality=100. 

In case of aws serverless image handler, things are worse. After receiving jpeg image bytes back from thumbor, [they for some reason decode and encode it again](https://github.com/awslabs/serverless-image-handler/issues/7). Which is done with default quality setting, [which is for jpeg is 75 for pillow](http://pillow.readthedocs.io/en/4.2.x/handbook/image-file-formats.html#jpeg)

**Comment by Enalmada** [comment]
FYI There is a note in ticket https://github.com/awslabs/serverless-image-handler/issues/7 that this is solved in the latest version so it is possible this ticket could be reconfirmed and closed now.
