### ISSUE TITLE
Unable to use opencv_engine as an ENGINE for thumbor

### ISSUE THREAD

**Issue by kutsav** [thumbor/thumbor#1018]
Getting below import error:
`import cv2.cv as cv`

I am able to import cv2 but this cv2.cv import happening from thumbor is throwing error

**Comment by Savar** [comment]
This is available from a submodule but to get this working you need to use the pull request https://github.com/thumbor/opencv-engine/pull/27

Am 17. Dezember 2017 18:20:21 MEZ schrieb Utsav Kumar <notifications@github.com>:
>Getting below import error:
>`import cv2.cv as cv`
>
>I am able to import cv2 but this cv2.cv import happening from thumbor
>is throwing error
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/thumbor/thumbor/issues/1018

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by davidverdejobluekiri** [comment]
For a clenan Ubuntu machine, the solution is:

sudo apt-get install -y python-opencv \ 
libjpeg-turbo-progs \ 
libboost-python-dev \ 
gifsicle \  
python-pip \ 
libcurl4-openssl-dev \ 
libssl-dev  
 
sudo pip install --upgrade pip 
 
pip install --use-wheel --no-cache-dir opencv-engine thumbor==6.3.2
