### ISSUE TITLE
Docs are outdated. Redis storage has moved to community plugin.

### ISSUE THREAD

**Issue by mrmachine** [thumbor/thumbor#1019]
Refs #999 

I just went through the same discovery, after diligently reading all the docs and setting up my config.

**Comment by thor27** [comment]
Hi, 
I will take a look into this. @heynemann do you think that is better to completely remove redis section from the docs, or update it to reflect the need to install a plugin now?

**Comment by heynemann** [comment]
I guess update it to reflect that the storage is in a different repo.

Very sorry for it @mrmachine
