### ISSUE TITLE
Using GPU

### ISSUE THREAD

**Issue by kutsav** [thumbor/thumbor#1020]
Is there any way so that i can use system's gpu with thumbor

**Comment by Savar** [comment]
I don't know about pillow but if you can use the opencv engine and you compile it in, then you should be able to do that..

Am 22. Dezember 2017 10:33:06 MEZ schrieb Utsav Kumar <notifications@github.com>:
>Is there any way so that i can use system's gpu with thumbor
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/thumbor/thumbor/issues/1020

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by kkopachev** [comment]
Probably data transfer speed to/from GPU would kill the idea.

**Comment by utsav2307** [comment]
Why? Shouldn’t this improve the performance?

**Comment by Arthien** [comment]
Check out openCV https://github.com/thumbor/opencv-engine/pull/32
