### ISSUE TITLE
thumborize.me bugged

### ISSUE THREAD

**Issue by Backenkoehler** [thumbor/thumbor#1024]
I stumpled uppon thumbor today and tried to enter a URL on the thumberize.me website. The Ajax call just responds a 500 error.

Beside this images on thumborize.me are not loading.

Is there any other way (like selfhosting) what thumborize.me does? Would be a nice experience to test it like this way before we integrate everything in code.

**Comment by caeugusmao** [comment]
Sorry for late answer!!! It's working!!!

**Comment by caeugusmao** [comment]
@heynemann Could you close this issue?
