### ISSUE TITLE
Thumbor + Datadog (statsd)

### ISSUE THREAD

**Issue by marceloboeira** [thumbor/thumbor#1030]
### Problem
For some reason, it seems thumbor is not sending data properly over statsd to datadog.

I've been using the same config on all my other services for the same cluster and the data goes to datadog, this service has the same config and it doesn't. Is there anything specific to do other than specify host, port, prefix?

The only debugging I could thing of was to switch the log level and check for possible error messages but nothing specific shows up, it does actually outputs all the metrics in the logs.

### Expected behaviour
Send statsd data over udp to the datadog statsd container

### Actual behaviour
Nothing gets ingested onto datadog

### Operating system
Ubuntu / K8s 

### Your thumbor.conf
```
STATSD_PORT = 8125
STATSD_HOST = "datadog-statsd.kube-system.svc.cluster.local"
STATSD_PREFIX = "image-proxy-service"
```

**Comment by kkopachev** [comment]
Did you enable module?
```
METRICS = 'thumbor.metrics.statsd_metrics'
```

**Comment by marceloboeira** [comment]
@kkopachev thanks, that solved it! We should add a section to the documentation 😀.

**Comment by yashmujumdar15** [comment]
HEy @marceloboeira  Can you help me here? from where did you find the STATSD_HOST = "datadog-statsd.kube-system.svc.cluster.local" value. 
Did you run the command "kubectl exec -it pod-name agent status -n namespace" ?
