### ISSUE TITLE
OpenCV engine update

### ISSUE THREAD

**Issue by Arthien** [thumbor/thumbor#1031]
The openCV engine is very powerful and is currently running on a deprecated version on the old C apis. 
The latest openCV has been submitted as a PR here: https://github.com/thumbor/opencv-engine/pull/32

I think it would be best to run some benchmarks as it is currently performing better than PIL for our use case. Also, this is a passing build that keeps the thumbor specific engine up to date with the latest deprecations and would benefit the community.

Thanks!

**Comment by thor27** [comment]
Hi!
As this PR has already been merged, could you please close this issue?

Thanks!
