### ISSUE TITLE
refactor branch: Can't install due to cyclical dependencies

### ISSUE THREAD

**Issue by tomsaleeba** [thumbor/thumbor#1032]
This is a bug report for the https://github.com/thumbor/thumbor/tree/refactor branch. Possibly most relevant to @heynemann. Not sure on the etiquette of reporting bugs on branch still under development, hopefully this is the right place for them.

### Steps
```bash
# create a new virtualenv
mkdir /thumbor-venv
cd /thumbor-venv
virtualenv -p python3 .
. bin/activate
# install thumbor into the virtualenv
cd /git/thumbor
git checkout 76c3d3bfa984501d8c5ba2067d300a1ef693f7d8 # assert same commit as bug report
python setup.py develop
```

### Expected behaviour
Thumbor and all the dependencies are installed.

### Actual behaviour
The install process fails. It's because `setup.py` imports the `thumbor` module, which imports other things. These other things don't existing yet because we're trying to install them. The error message is:
```bash
Processing /git/thumbor
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-7b8fx8y4-build/setup.py", line 12, in <module>
        from thumbor import __version__
      File "/tmp/pip-7b8fx8y4-build/thumbor/__init__.py", line 16, in <module>
        from thumbor.lifecycle.events import Events  # NOQA
      File "/tmp/pip-7b8fx8y4-build/thumbor/lifecycle/__init__.py", line 16, in <module>
        from thumbor.lifecycle.events import Events  # NOQA
      File "/tmp/pip-7b8fx8y4-build/thumbor/lifecycle/events.py", line 30, in <module>
        import tornado.gen
    ImportError: No module named 'tornado'
    
    ----------------------------------------
```

### Operating system
Linux Mint 18.1, Python 3.5.2.

**Comment by heynemann** [comment]
Thanks man.  Will look into it.

**Comment by heynemann** [comment]
The refactor branch has evolved a little bit. Did you still keep track of it (just curious)?

**Comment by tomsaleeba** [comment]
Hi @heynemann, I'm working on some other projects at the moment so I haven't been keeping up, sorry. I'll be coming back to this in a few months so I'll see how I go then.
