### ISSUE TITLE
Resizes that result in odd number of pixels breaks gifv filter

### ISSUE THREAD

**Issue by jonthemiller** [thumbor/thumbor#1034]
### Thumbor request URL
https://cnet1.cbsistatic.com/img/3We9bHArRT9t6_WDWGkXt4Jh0ks=/fit-in/270x0/filters:gifv()/2018/01/08/c3d9e76a-fbf8-438e-838e-2512f1f0123a/spacex-gif.gif

### Expected behaviour
gifv should load resized to 270px wide

### Actual behaviour
504 gateway timeout due to thumbor resizing the gif to 269px wide, which breaks ffmpeg

### Operating system
OSx, Ubuntu

### Your thumbor.conf
running v6.3.2 in docker

    ...
    IGNORE_SMART_ERRORS=True
    USE_GIFSICLE_ENGINE=True
    AUTO_WEBP=True
    OPTIMIZERS = [
        'thumbor.optimizers.jpegtran',
        'thumbor.optimizers.gifv',
    ]
    ...

When attempting to do a fit-in and gifv filter, the resulting image is resized to 269px wide. ffmpeg breaks on odd pixel sizes, and the request times out.

This is the source gif - 448x280 and 91 frames long: https://cnet1.cbsistatic.com/img/2oS3ns47MlcnjH1SQ7Ysjjir99c=/2018/01/08/c3d9e76a-fbf8-438e-838e-2512f1f0123a/spacex-gif.gif

fit-in/270x0 without gifv gets resized to 270x169:
https://cnet4.cbsistatic.com/img/ZzEZoZJm4vL2JM8XwSlbnpF_tcQ=/fit-in/270x0/2018/01/08/c3d9e76a-fbf8-438e-838e-2512f1f0123a/spacex-gif.gif

This seems similar to #903. I'm wondering if there is a way to force even pixel sizes for gifv requests? Or a way to know if a resize operation will result in odd pixel sizes before requesting it?

**Comment by kkopachev** [comment]
What version of ffmpeg do you use? 
I tried with latest master of thumbor (which should be same as latest release) and with ffmpeg 3.2.0.and it works fine. Was able to generate video.

**Comment by jonthemiller** [comment]
Thanks, I'll upgrade our instance and try again.

**Comment by jonthemiller** [comment]
Updated our dev instance to 6.4.1 and the fit in operation works. We'll be updating production within a week. Thanks, @kkopachev!
