### ISSUE TITLE
Cannot start thumbor (config security key was loaded as binary string not str)

### ISSUE THREAD

**Issue by Asoul** [thumbor/thumbor#1035]
### Expected behaviour
Run thumbor successfully

### Actual behaviour
```
Traceback (most recent call last):
  File "~/venv/bin/thumbor", line 11, in <module>
    sys.exit(main())
  File "~/venv/lib/python3.6/site-packages/thumbor/server.py", line 147, in main
    validate_config(config, server_parameters)
  File "~/venv/lib/python3.6/site-packages/thumbor/server.py", line 86, in validate_config
    'Please provide one using the conf file or a security key file.')
RuntimeError: No security key was found for this instance of thumbor. Please provide one using the conf file or a security key file.
```

### Operating system
OSX 10.12.6

### Your thumbor.conf
Original config

### Debugging

I dump the `server_parameters.security_key` to check, the `server_parameters.security_key` is load as a binary string, so not passed the `if not isinstance(server_parameters.security_key, basestring):` condition, is that something I misunderstood?

Fail if statement code:
https://github.com/thumbor/thumbor/blob/master/thumbor/server.py#L80

**Comment by JonathanHuot** [comment]
Worth to mention that I have the exact same issue.
New thumbor config, on ArchLinux with python 3.6.1.

**Comment by Savar** [comment]
Since when is python3 fully supported by thumbor? I thought this was planned for thumbor 7?

Am 18. Januar 2018 22:29:47 MEZ schrieb Jonathan Huot <notifications@github.com>:
>Worth to mention that I have the exact same issue.
>New thumbor config, on ArchLinux with python 3.6.1.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/thumbor/thumbor/issues/1035#issuecomment-358787680

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by JonathanHuot** [comment]
Confusion cames from documentation which is not mentionning that requirements. However, we can find other github issues already open about python 3. Thanks for your reply.

Duplicate of https://github.com/thumbor/thumbor/issues/1004

**Comment by Asoul** [comment]
Oops, thanks @Savar and @JonathanHuot,
I didn't notice thumbor hasn't support pyhton3 yet.
Sorry for the duplicate!

**Comment by alexislg2** [comment]
So what is the workaround for this?
I have the exact same issue. I filled the SECURITY_KEY field but I still have this issue. Can you help? I don't understand why you are talking about python 3 here

**Comment by piyushcrive** [comment]
Hi,
I am facing the same issue. Does anyone have a solution for this??

**Comment by thor27** [comment]
Thumbor supports only python 2.7. Anyone having this issue with python 2.7 ?

**Comment by p3k** [comment]
yes, me:

```
→ python --version
Python 2.7.15rc1
```

**Comment by cristiandean** [comment]
Yes, you need to create them, as we can see here: https://github.com/thumbor/thumbor/wiki/Configuration

> 
> thumbor's configuration file is just a regular python script that thumbor loads.
> 
> In order to get a commented configuration file, just run:
> 

`thumbor-config > ./thumbor.conf`

**Comment by p3k** [comment]
thanks for the hint, @cristiandean – i ran the `thumbor-config` command and now have a thumbor.conf file.

however, i still get the same error. i also set the `SECURITY_KEY` property to some arbitrary string and added the file thumbor.key containing the same string with no luck.

finally, i even tried to manually set the paths to config and key files, to no avail:

```
→ ls thumbor.*
thumbor.conf  thumbor.key

→ thumbor -c thumbor.conf -k thumbor.key 
Traceback (most recent call last):
  File "/home/tobi/.local/bin/thumbor", line 11, in <module>
    sys.exit(main())
  File "/home/tobi/.local/lib/python3.6/site-packages/thumbor/server.py", line 141, in main
    validate_config(config, server_parameters)
  File "/home/tobi/.local/lib/python3.6/site-packages/thumbor/server.py", line 85, in validate_config
    'Please provide one using the conf file or a security key file.')
RuntimeError: No security key was found for this instance of thumbor. Please provide one using the conf file or a security key file.
```

what am i missing?

(btw. maybe the docs could be slightly adapted to include these required steps because[ _Just install it with pip install thumbor and start the process with thumbor in a console_](https://thumbor.readthedocs.io/en/latest/getting_started.html) does not really apply.)

**Comment by cristiandean** [comment]
You should also pass by parameters the config and key file with path (If they aren't in the current directory):

`thumbor -k /path/to/key/key_file.key -c /path/to/conf/thumbor.conf`

**Comment by p3k** [comment]
did so, pls see my previous comment

**Comment by cristiandean** [comment]
You did: 
`thumbor -c thumbor.conf -k thumbor.key `

Try run with the file path this:

`thumbor -k /path/to/key/key_file.key -c /path/to/conf/thumbor.conf`

**Comment by cristiandean** [comment]
@p3k Are you running thumbor with python 3.6? Thumbor supports only python 2.7

**Comment by p3k** [comment]
thanks for spotting this… seems my virtualenv is b0rked, fixing now.

**Comment by p3k** [comment]
yay now it works, thanks again @cristiandean :cat:

**Comment by cristiandean** [comment]
Great!! =)

**Comment by onurardal** [comment]
Hi @cristiandean , I followed all the steps in the link(https://github.com/thumbor/thumbor/wiki/Hosting#thumbor-in-the-cloud) but I'm getting the same error.
I have created and can view thumbor.conf. But the result has not changed
![image](https://user-images.githubusercontent.com/6431040/50289288-714df880-0479-11e9-8c2f-013612e1c2ee.png)
![image](https://user-images.githubusercontent.com/6431040/50289313-7e6ae780-0479-11e9-9d9e-d5846382e66e.png)

**Comment by cristiandean** [comment]
Hello @onurardal, I can see you are using python 3.6, Thumbor doesn't support this version. Can you try again with python 2.7?

**Comment by premalpawar** [comment]
> 
> 
> yay now it works, thanks again @cristiandean cat

HI p3k,

can you please tell how you fix this?

Below python packages are installed in my system.
ubuntu@ip-172-31-10-4:~$ whereis python
python: /usr/bin/python2.7 /usr/bin/python2.7-config /usr/bin/python3.5m /usr/bin/python /usr/bin/python3.5 /usr/lib/python2.7 /usr/lib/python3.5 /etc/python2.7 /etc/python /etc/python3.5 /usr/local/lib/python2.7 /usr/local/lib/python3.5 /usr/include/python2.7 /usr/share/python /usr/share/man/man1/python.1.gz

i have same issue and don't know how to change python3.5 to python2.7 as per below error logs

Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/thumbor/server.py", line 141, in main
    validate_config(config, server_parameters)
  File "/usr/local/lib/python3.5/dist-packages/thumbor/server.py", line 85, in validate_config
    'Please provide one using the conf file or a security key file.')
RuntimeError: No security key was found for this instance of thumbor. Please provide one using the conf file or a security key file.

**Comment by p3k** [comment]
@premalpawar are you using a virtual python environment? if not, i recommend to do so, it makes things a lot easier. 

<https://help.dreamhost.com/hc/en-us/articles/115000695551-Installing-and-using-virtualenv-with-Python-3>

it bascially boils down to this:

```sh
virtualenv -p /path/to/python2.7 your_project
source your_project/bin/activate
pip install thumbor
```

**Comment by vhpoet** [comment]
Hey, I'm getting this error right now, not sure what I'm missing. The conf file exists and has the security key. See the screenshot.

![Screen Shot 2020-05-02 at 11 00 49 PM](https://user-images.githubusercontent.com/686185/80907123-c5512a00-8cc8-11ea-9e19-71f88a73e791.png)
