### ISSUE TITLE
Thinking about the future: Pillow 5

### ISSUE THREAD

**Issue by marcelometal** [thumbor/thumbor#1038]
Recently, [Pillow 5.0 was released](https://github.com/python-pillow/Pillow/releases/tag/5.0.0) and testing it against Thumbor some tests failed. 

IMHO, in the near future Ubuntu and [Debian](https://packages.debian.org/sid/python-pil) will be released with Pillow 5, it would be great if it was fixed.

**Comment by caeugusmao** [comment]
@marcelometal This issue is being handled in a PR(https://github.com/thumbor/thumbor/pull/1048). Could you close this issue?
