### ISSUE TITLE
Thumbor returns blank image for this jpg

### ISSUE THREAD

**Issue by karptonite** [thumbor/thumbor#1049]
### Thumbor request URL
https://cf.geekdo-images.com/LcZ2xAnzFTA3vGUKIjtQOhwztpc=/0x0/pic263134.jpg
The original can be found at:
https://cf.geekdo-images.com/images/pic263134.jpg

The same problem occurs with the test thumbor server:
http://thumbor.thumborize.me/unsafe/https://cf.geekdo-images.com/images/pic263134.jpg

### Expected behaviour
The image returned by thumbor should look like the original

### Actual behaviour
Thumbor returns a black box

### Operating system
(irrelevant, I think, since the problem also occurs on the test server?)

### Your thumbor.conf
The default conf generated for this docker: https://github.com/APSL/docker-thumbor
But since the bug also occurs with the thumbor.thumborize.me test server, the specifics of the conf file may be irrelevant. If you need more details to reproduce this, let me know. Our thumbor instance works fine for most images on our site, but this image was reported to us as "corrupt".

**Comment by kkopachev** [comment]
Looks like pillow issue. I'll report it there.

**Comment by kkopachev** [comment]
this is fixed now in master branch (awaiting release) as https://github.com/thumbor/thumbor/pull/1048 closed, which allows Pillow 5.1 to be installed, which has a fix for this issue.

**Comment by heynemann** [comment]
This has been released. Hope it is fixed.
