### ISSUE TITLE
ERROR retrieving image ... maximum recursion depth exceeded

### ISSUE THREAD

**Issue by ipmb** [thumbor/thumbor#1055]
### Thumbor request URL

`/unsafe/0x236:8198x5013/326x190/<s3bucket>.s3.amazonaws.com/path/to/file.jpg`

### Expected behaviour

The thumbnail should be created

### Actual behaviour

Errors like the following:

```
2018-03-22 13:55:43 thumbor:WARNING ERROR retrieving image http://<s3bucket>.s3.amazonaws.com/path/to/file.jpg: maximum recursion depth exceeded
2018-03-22 13:55:43 tornado.access:ERROR 504 GET /unsafe/0x236:8198x5013/326x190/<s3bucket>.s3.amazonaws.com/path/to/file.jpg (xxx.xx.xx.xxx) 418.42ms
```

Sometimes the error is `maximum recursion depth exceeded while calling a Python object`.

This only happens periodically, but happens consistently given certain input files. I can open the images manually with `PIL.Image.open` and read the info from them.

### Operating system

Ubuntu 14.04

### Your thumbor.conf

```
ALLOWED_SOURCES = [
    <s3bucket>.s3.amazonaws.com',
]
USE_GIFSICLE_ENGINE = True
ENGINE_THREADPOOL_SIZE = 3
RESULT_STORAGE = 'thumbor.result_storages.file_storage'
FILE_STORAGE_ROOT_PATH = '/mnt/thumbor/storage'
OPTIMIZERS = [
    'thumbor.optimizers.jpegtran'
]
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/mnt/thumbor/result_storage'
SENTRY_DSN_URL = 'https://xxx:xxx@sentry.io/xxxxxx'
```

Using thumbor 6.4.2 and Pillow-simd 4.3.0.post0

**Comment by heynemann** [comment]
This looks like an issue with the AWS Storage. Can someone confirm?

**Comment by ipmb** [comment]
It's not doing anything S3-native. Just fetching over HTTP (which happens to be hosted on S3). The endpoint is public.

**Comment by heynemann** [comment]
You are right. Sorry. Do you have an actual URL (without the bucket)? I wonder how long the file path is.

**Comment by ipmb** [comment]
I'll drop the URL in gitter for you (would leak some info otherwise). It is 103 characters long.

**Comment by heynemann** [comment]
No need to... You just need to count how many slashes... It looks like an issue with the file system.

**Comment by ipmb** [comment]
6 excluding the `http://`. I don't think that's it because I have other files with the same paths that work fine.

**Comment by kkopachev** [comment]
Is that an image related or url related? What if you copy image to another path and retry?

**Comment by ipmb** [comment]
Seems to be image related. Changing the path has no effect.

**Comment by kkopachev** [comment]
possible to share the image?

**Comment by ipmb** [comment]
I did some further testing and suspect the newrelic-python-agent I was wrapping thumbor's execution in might be to blame. I removed it and was able to successfully generate some images that were failing every time before. I'll close this and keep an eye on the logs to see if it comes back.
