### ISSUE TITLE
Cannot update image - 415 Unsupported Media Type

### ISSUE THREAD

**Issue by andypingliu** [thumbor/thumbor#1059]
### Thumbor request URL
PUT http://10.0.2.2:8888/image/fcb3ab31aa4149149ea49e8c8e0ee655/photo.jpg
Content-Type: multipart/form-data; boundary=30e851a9-1a9d-46ff-ae97-f02305b4e5c4
Content-Length: 14298
 Slug: photo.jpg
--30e851a9-1a9d-46ff-ae97-f02305b4e5c4
Content-Disposition: form-data; name="media"; filename="photo.jpg"
Content-Type: image/jpeg
Content-Length: 14095
������JFIF����������������C��
...
--30e851a9-1a9d-46ff-ae97-f02305b4e5c4--
--> END PUT (14298-byte body)

### Expected behaviour
Response should be following and picture should be updated

HTTP/1.1 204 No Content
Date: Thu, 05 Apr 2018 17:32:56 GMT
Server: TornadoServer/4.5.3

### Actual behaviour
 <-- 415 Unsupported Media Type http://10.0.2.2:8888/image/fcb3ab31aa4149149ea49e8c8e0ee655/photo.jpg (164ms)

Picture not updated

### Operating system
Mac OS

### Additional note
I am using multipartbody to attached a file.  Using the exactly same method on POSTing a new image works fine.  And using the curl for PUT also works.

curl -i -H "Content-Type: image/jpeg" -H "Slug: photo.jpg" -XPUT http://127.0.0.1:8888/image/fcb3ab31aa4149149ea49e8c8e0ee655/photo.jpg --data-binary "@aitouch.jpg"

HTTP/1.1 204 No Content
Date: Thu, 05 Apr 2018 17:32:56 GMT
Server: TornadoServer/4.5.3

thanks.

### Your thumbor.conf
Your config file (WARNING: replace your SECURITY_KEY key with a dummy key or your key will become public)

## Defaults to: %(asctime)s %(name)s:%(levelname)s %(message)s
#THUMBOR_LOG_FORMAT = '%(asctime)s %(name)s:%(levelname)s %(message)s'

## Defaults to: %Y-%m-%d %H:%M:%S
#THUMBOR_LOG_DATE_FORMAT = '%Y-%m-%d %H:%M:%S'

################################################################################

## Defaults to: 0
#MAX_WIDTH = 0

## Defaults to: 0
#MAX_HEIGHT = 0

## Defaults to: 1
#MIN_WIDTH = 1

## Defaults to: 1
#MIN_HEIGHT = 1

## Defaults to: []
#ALLOWED_SOURCES = #    [
#    ]

## Defaults to: 80
#QUALITY = 80

## Defaults to: 86400
#MAX_AGE = 86400

## Defaults to: 0
#MAX_AGE_TEMP_IMAGE = 0

## Defaults to: False
#RESPECT_ORIENTATION = False

## Defaults to: True
#ALLOW_ANIMATED_GIFS = True

################################################################################

## Defaults to: thumbor.loaders.http_loader
#LOADER = 'thumbor.loaders.http_loader'

## Defaults to: thumbor.storages.file_storage
#STORAGE = 'thumbor.storages.file_storage'

## Defaults to: None
#RESULT_STORAGE = None

## Defaults to: thumbor.engines.pil
#ENGINE = 'thumbor.engines.pil'

################################################################################

## Defaults to: MY_SECURE_KEY
#SECURITY_KEY = 'MY_SECURE_KEY'

## Defaults to: True
#ALLOW_UNSAFE_URL = True

## Defaults to: True
#ALLOW_OLD_URLS = True

################################################################################

## Defaults to: /tmp
#FILE_LOADER_ROOT_PATH = '/tmp'

################################################################################

## Defaults to: 2592000
#STORAGE_EXPIRATION_SECONDS = 2592000

## Defaults to: False
#STORES_CRYPTO_KEY_FOR_EACH_IMAGE = False

## Defaults to: /var/folders/th/z6vmj34j1gngpvwl5fg5t9440000gp/T/thumbor/storage
#FILE_STORAGE_ROOT_PATH = '/var/folders/th/z6vmj34j1gngpvwl5fg5t9440000gp/T/thumbor/storage'

################################################################################

## Defaults to: 0
#UPLOAD_MAX_SIZE = 0

## Defaults to: False
UPLOAD_ENABLED = True

## Defaults to: thumbor.storages.file_storage
#UPLOAD_PHOTO_STORAGE = 'thumbor.storages.file_storage'

## Defaults to: False
UPLOAD_DELETE_ALLOWED = True 

## Defaults to: False
UPLOAD_PUT_ALLOWED = True

## Defaults to: image
#UPLOAD_DEFAULT_FILENAME = 'image'

################################################################################

## Defaults to: localhost
#MONGO_STORAGE_SERVER_HOST = 'localhost'

## Defaults to: 27017
#MONGO_STORAGE_SERVER_PORT = 27017

## Defaults to: thumbor
#MONGO_STORAGE_SERVER_DB = 'thumbor'

## Defaults to: images
#MONGO_STORAGE_SERVER_COLLECTION = 'images'

################################################################################

## Defaults to: localhost
#REDIS_STORAGE_SERVER_HOST = 'localhost'

## Defaults to: 6379
#REDIS_STORAGE_SERVER_PORT = 6379

## Defaults to: 0
#REDIS_STORAGE_SERVER_DB = 0

## Defaults to: None
#REDIS_STORAGE_SERVER_PASSWORD = None

################################################################################

## Defaults to: ['localhost:11211']
#MEMCACHE_STORAGE_SERVERS = #    [
#        'localhost:11211',
#    ]

################################################################################

## Defaults to: thumbor.storages.no_storage
#MIXED_STORAGE_FILE_STORAGE = 'thumbor.storages.no_storage'

## Defaults to: thumbor.storages.no_storage
#MIXED_STORAGE_CRYPTO_STORAGE = 'thumbor.storages.no_storage'

## Defaults to: thumbor.storages.no_storage
#MIXED_STORAGE_DETECTOR_STORAGE = 'thumbor.storages.no_storage'

################################################################################

## Defaults to: None
#META_CALLBACK_NAME = None

################################################################################

## Defaults to: []
#DETECTORS = #    [
#    ]

## Defaults to: haarcascade_frontalface_alt.xml
#FACE_DETECTOR_CASCADE_FILE = 'haarcascade_frontalface_alt.xml'

################################################################################

## Defaults to: []
#FILTERS = #    [
#    ]

################################################################################

## Defaults to: 0
#RESULT_STORAGE_EXPIRATION_SECONDS = 0

## Defaults to: /var/folders/th/z6vmj34j1gngpvwl5fg5t9440000gp/T/thumbor/result_storage
#RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/var/folders/th/z6vmj34j1gngpvwl5fg5t9440000gp/T/thumbor/result_storage'

## Defaults to: False
#RESULT_STORAGE_STORES_UNSAFE = False

################################################################################

## Defaults to: localhost
#REDIS_QUEUE_SERVER_HOST = 'localhost'

## Defaults to: 6379
#REDIS_QUEUE_SERVER_PORT = 6379

## Defaults to: 0
#REDIS_QUEUE_SERVER_DB = 0

## Defaults to: None
#REDIS_QUEUE_SERVER_PASSWORD = None

################################################################################

## Defaults to: None
#SQS_QUEUE_KEY_ID = None

## Defaults to: None
#SQS_QUEUE_KEY_SECRET = None

## Defaults to: us-east-1
#SQS_QUEUE_REGION = 'us-east-1'

################################################################################

## Defaults to: False
#USE_CUSTOM_ERROR_HANDLING = False

## Defaults to: thumbor.error_handlers.sentry
#ERROR_HANDLER_MODULE = 'thumbor.error_handlers.sentry'

################################################################################

## Defaults to: 
#SENTRY_DSN_URL = ''

################################################################################

**Comment by andypingliu** [comment]
Anyone has any idea and solution?

**Comment by caeugusmao** [comment]
Hi @andypingliu,

How are you doing your request? I could reproduce your issue using jQuery to make the request.

In my case, the body in the request came with a weird prefix for Thumbor, added by jquery, '**------WebKitFormBoundaryZKArW3Nijpj3aplM\r\nContent-Disposition: form-data; name="media"; filename="world-cup.jpg"\r\nContent-Type: image/jpeg\r\n\r\n**\xff\xd8\xff\xe0. 

Because of this Thumbor cannot identify the mimetype and an error is raised. 'Unsupported Media Type'

Thumbor uses this prefix to identify the image mimetype. The body that comes in request should start with image content, in my case**\xff\xd8\xff\xe0**, and not with other things like I showed before. In my case this prefix means that the image mimetype is **image/jpeg**.

It worked for me changing the way to make the request. I switched jquery for pure js.  Maybe there are other ways to do this request preserving the body.

**Comment by caeugusmao** [comment]
@andypingliu Any news?

**Comment by andypingliu** [comment]
Hi Caeugusmao,

Thanks for your response and follow up.   I am using Retrofit, a well-known library, to make REST call in Android development.  And I am using MultipartBody to send image files as suggested in the community.  

    fun update(id: String?, file: File, preferFilename: String = "NONE"): Deferred<ImageMetadata>? {
        val requestFile = RequestBody.create(MediaType.parse("image/jpeg"), file)

        var filename = file.name
        if (preferFilename != "NONE") {
            filename = preferFilename
        }

        Log.d(TAG, "Filename: $filename")
        val body = MultipartBody.Part.createFormData(FORM_DATA_NAME, filename, requestFile)
        return mImageAPI?.update(id, filename, body)
    }

Below is the log for the request.

--> PUT http://10.0.2.2:8888/image/6021a7ebcf054c95ab2e53d11f7fe24b/fake-hills-1.jpg
 D/OkHttp: Content-Type: multipart/form-data; boundary=d7a72dd9-1bee-4e07-a881-0211c0b4d20f
D/OkHttp: Content-Length: 90135
D/OkHttp: Slug: photo.jpg
D/MainActivity: New Comment: testing
D/MainActivity: New comment posted!
D/OkHttp: --d7a72dd9-1bee-4e07-a881-0211c0b4d20f
D/OkHttp: Content-Disposition: form-data; name="media"; filename="fake-hills-1.jpg"
D/OkHttp: Content-Type: image/jpeg
D/OkHttp: Content-Length: 89925
D/OkHttp: ������JFIF����H��H��������C��
D/OkHttp: 
D/OkHttp: 		
D/OkHttp: %# , #&')*)-0-(0%()(����C
D/OkHttp: 
D/OkHttp: 
D/OkHttp: (((((((((((((((((((((((((((((((((((((((((((((((((((����j{"������������������������������������J����!1A"Qaq2�#��BR��3br�$C�S���%4���5Ds�c����������������������������������3����������!1AQ"a2q��BR���b�#���C��������?���8ߥ-#56zW��kܳ¢��zR~�>zW�*,(�J@zT�*@t�q�JZF:��t�p1��aD�H������{���XQ�� yD#E�3Җ7�S�3ҖzQaDߥ,oҦ��JX�@�HJ�4�TXQ��1S��<���<���R��*lt����XQ:R��M����A��H�J���H��E���JXߥL@�JX�E��g�,oҦ��JXߥB���J@*��@
D/OkHttp: VB�,t��T�1ҝ��n���J�)`c�C��R#Ҧ��JDt�H�G�L@�@�Hߥ,oҦ g�,�p3�KH�Z�=+�o�QaD�����yT��5�ʋ
D/OkHttp:  ҖM��^�1ҋ


Looks like I have  ������JFIF����H��H�� right after Content-Length .  Is that the common header part of a jpeg image file?

I am using Retrofit library to include the image file as multipartbody.  Is it possible for you to debug using the same library in Android and see if there is any solution to the problem?  Greatly appreciate your help.

Since there isn't a Android client for thumbor, I am writing it myself.  Unfortunately, I don't see anyone else experiencing the problem.  Is this an issue that a platform that needs to be address?

thanks
