### ISSUE TITLE
detector documentation

### ISSUE THREAD

**Issue by Enalmada** [thumbor/thumbor#1062]
Could an owner take just a minute to fill in a sentence or two on what each available detector does:
http://thumbor.readthedocs.io/en/latest/available_detectors.html

I am especially curious what is the difference between the face detector and profile detector.  Is profile detector looking for the side of a face?

**Comment by caeugusmao** [comment]
Hi Enalmada,

Follow de definitions:

**Feature Detector**
Detector used to find relevant focal points in the image. "Features" in this case and in other cases such as machine learning, are pieces of information (in this case, pieces of the image) that are relevant to solving a computational problem. For Thumbor we use this set of focal points to identify faces, for example. We use the first 10 set of points found.

**Face Detector**
It detects faces, It considers the frontal part of the face for detection.

**Profile Detector**
It detects faces, It considers the side part of the face for detection.

**Glasses Detector**
It detects glasses on the faces.

**Queued Detector**
Detector used to allow face detection process asynchronously.

Would you like to contribute with our docs? You can do this!!! :)

**Comment by Enalmada** [comment]
Thanks @caeugusmao that is exactly what I wanted to confirm.
