### ISSUE TITLE
Bypass pdf and svg's in thumbor

### ISSUE THREAD

**Issue by utsav2307** [thumbor/thumbor#1068]
Hi,

My current thumbor usecase: reads from s3 and returns the processed image.
 
Now, I know Thumbor does not support pdf as of now, svg's are also supported by installing the plugin:cairosvg which basically converts svg's to png format.

But, I would like a scenario where if there is a svg or pdf file(or any other format of file not supported by thumbor), thumbor should return the original  file as it is without processing.

Is there a solution already in place for this? or a known workaround?

**Comment by caeugusmao** [comment]
Any news @utsav2307?

**Comment by utsav2307** [comment]
i used haproxy in front of thumbor to solve the problem
