### ISSUE TITLE
Allow for pillow-simd

### ISSUE THREAD

**Issue by Globegitter** [thumbor/thumbor#1072]
I want to have thumbor running with pillow-simd rather than pillow.

### Expected behaviour
I want it to be easy to have thumbor depend on pillow-simd rather than pillow, probably by making it an external engine. Also seems to make more sense, because if I e.g. want to use the opencv engine we would still have to install pillow which I suppose should be unneeded then

### Actual behaviour
To get it to work one currently would have to do install thumbor and pillow-simd and then uninstall pillow, which seems a bit of a hack and also not so easily possible in all environments (e.g. a docker container created by the bazel build system).

### Operating system
Ubuntu 16.04

**Comment by heynemann** [comment]
The issue here is that we need one default engine. We could change the default engine to be Pillow-SIMD. Comments by the community here would be great.

**Comment by gingerlime** [comment]
It's a tricky one. Take a look at https://github.com/uploadcare/pillow-simd/issues/17

As far as I understand it, Pillow-SIMD used to use the same name (Pillow), so if you define Pillow as a dependency, either of those would work. Unfortunately they changed the name, and now this fails. There's a workaround that @kkopachev suggested and it works. I also implemented it [here](https://github.com/MinimalCompact/thumbor/blob/master/thumbor/Dockerfile#L50-L53) and [here](https://github.com/MinimalCompact/thumbor/blob/master/thumbor/docker-entrypoint.sh#L26). The latter would launch thumbor without going through `entry_points` and is functionally equivalent (but it feels a bit like a hack)

I'm not really familiar with SIMD, but I think not all platform support it, so if the base thumbor only uses Pillow-SIMD I would suspect it would fail to work on some platforms, but no clue which/how many. I would err on the side of caution here, and keep it as an option.

Sorry to keep plugging my new [pet project](https://github.com/MinimalCompact/thumbor) :), but if you're running thumbor with docker, then I would recommend it. it supports both standard and SIMD options (you simply choose the [tag](https://hub.docker.com/r/minimalcompact/thumbor/tags/) you want).

Hope this helps :)
