### ISSUE TITLE
HTTP 599: gnutls_handshake() failed: Handshake failed

### ISSUE THREAD

**Issue by guilouro** [thumbor/thumbor#1075]
### Expected behavior
I want to convert some images using Thumbor but I got errors when I try to convert image by domain netfla.com.br. This error happens only this domain. When I use with another domain, it works!

### Actual behavior
I've received 504 error with the message below

```
2018-05-25 11:36:52 thumbor:WARNING ERROR retrieving image https://netfla.com.br/media/escudos/fla.png: HTTP 599: gnutls_handshake() failed: Handshake failed
2018-05-25 11:36:52 tornado.access:ERROR 504 GET /MjrKtn9WtuTBrjSf6zeQPUbfwEs=/0x75/https://netfla.com.br/media/escudos/fla.png (108.162.212.72) 72.58ms
```

### Operating system
Ubuntu 14.04.5 LTS

### Your thumbor.conf

```
QUALITY = 70
PROGRESSIVE_JPEG = True
AUTO_WEBP = True
ALLOW_ANIMATED_GIFS = True
USE_GIFSICLE_ENGINE = True
HTTP_LOADER_CURL_ASYNC_HTTP_CLIENT = True
FACE_DETECTOR_CASCADE_FILE = 'haarcascade_frontalface_alt.xml'
```

**Comment by guilouro** [comment]
I solve this issue following [this steps](http://blog.thisisfeifan.com/2015/01/fix-tornado-http-599-issue.html)

In case of the someone else has the same problem

**Comment by caeugusmao** [comment]
Tks for the tip @guilouro? Can we close this issue?

**Comment by guilouro** [comment]
Yes @caeugusmao! tks!
