### ISSUE TITLE
how can i configure thumbor to store only uploaded file

### ISSUE THREAD

**Issue by alioygur** [thumbor/thumbor#1079]
Hello,

I have installed thumbor and set `UPLOAD_ENABLED = True`

I want to store only uploaded files, don't store files that have been loaded as http. store them at result storage.

can you help me?

**Comment by heynemann** [comment]
Just configure your STORAGE to NoStorage, like so:

```
STORAGE = 'thumbor.storage.no_storage'
```
And that's it. If it's what you were looking for, please close this issue.

**Comment by alioygur** [comment]
@heynemann I have tried but it's didn't work.

my config

```
LOADER = 'thumbor.loaders.http_loader'
STORAGE = 'thumbor.storages.no_storage'

FILE_STORAGE_ROOT_PATH = '/tmp/upload'
FILE_LOADER_ROOT_PATH = '/tmp/upload'

RESULT_STORAGE = 'thumbor.result_storages.file_storage'
RESULT_STORAGE_STORES_UNSAFE = True
RESULT_STORAGE_EXPIRATION_SECONDS = 86400
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH='/tmp/result'

UPLOAD_ENABLED = True
AUTO_WEBP = True
```

Upload file

```
➜  Desktop curl -i -H "Content-Type: image/jpeg" -H "Slug: photo.jpg" -XPOST http://cdn.tatil.local/image --data-binary "@IMG_1263.JPG"
HTTP/1.1 100 Continue

HTTP/1.1 201 Created
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Sun, 27 May 2018 11:32:10 GMT
Location: /image/86cc98b8c6434f8f825683a17fe15800/photo.jpg
Server: TornadoServer/4.5.1
```

get file

```
➜  Desktop curl -i -XGET http://cdn.tatil.local/unsafe/86cc98b8c6434f8f825683a17fe15800/photo.jpg
HTTP/1.1 504 Gateway Timeout
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Sun, 27 May 2018 11:36:27 GMT
Server: TornadoServer/4.5.1
```

**Comment by heynemann** [comment]
I do understand you. But in order to achieve what you want you have to either:

a) Serve the files thumbor is storing in the filesystem via HTTP somehow (nginx?) so HTTP loader can find them;
b) Implement your own storage that can LOAD images from the filesystem, but does not STORE new ones;
c) Just use a file loader and then you won't be able to load images using HTTP.

Does that make sense?

**Comment by caeugusmao** [comment]
@alioygur Any news?
