### ISSUE TITLE
Expiration of signed URLs?

### ISSUE THREAD

**Issue by anpr** [thumbor/thumbor#1085]
Hello,

I'm considering to use thumbor as thumbnail service for sensitive images.
I'm glad to see that URL signing is supported. However, it seems the signature only takes the `path` as input (see [here](https://github.com/thumbor/thumbor/wiki/security#hmac-method)).

Is it possible to generate signed URLs that expire after some time, i.e. that the signature takes an expiration time as input, too? 
In that way, a user couldn't just share a thumbor-URL to thumbor with somebody else to get perpetual access. 

If that's not supported, do you accept pull requests for that?

Thanks

**Comment by heynemann** [comment]
For now, what you can do is:

* Create a new application class that inherits from thumbor's;
* Handle the hash verification on your own in a handler that calls thumbor's;
* Pass the app class to thumbor upon initialization using -a 'fullname.of.your.application.class'

Does that make sense?

**Comment by heynemann** [comment]
Did you get this working?

**Comment by anpr** [comment]
I didn't come to try it yet, will let you know. If you want, you can close the ticket.

**Comment by anpr** [comment]
Just to update the issue, we ended up implementing our own URL signer that has an expiration.
Here's [a gist](https://gist.github.com/anpr/38b19090cb2299658a7d9ad1714e4977).
