### ISSUE TITLE
Thumbor doesn't sent an HTTP Accept header

### ISSUE THREAD

**Issue by MattBlissett** [thumbor/thumbor#1087]
When retrieving images, Thumbor doesn't set an HTTP Accept header.

Usually that's no problem, but compare these:

```
curl -H 'Accept: image/*' https://api.aucklandmuseum.com/id/media/v/105387
(Image returned)

curl -H 'Accept:' https://api.aucklandmuseum.com/id/media/v/105387
(JSON returned)
```

I've added to [http_loader.py](https://github.com/thumbor/thumbor/blob/master/thumbor/loaders/http_loader.py#L125)

```
headers['Accept'] = 'image/*;q=0.9,*/*;q=0.1'
```

Is there any reason not to have this header? If it's OK, I'll make a pull request.

**Comment by heynemann** [comment]
It is ok, can you make a PR?
