### ISSUE TITLE
HTTP Basic Auth support for the HTTP Loader?

### ISSUE THREAD

**Issue by mpdude** [thumbor/thumbor#1100]
I am using Thumbor in reverse proxy mode. I pass it URLs to various backend systems that are protected with HTTP Basic Auth.

Obviously, I don't want to include the username and password in the URL.

Is there any way I could configure Thumbor to use a HTTP username and password for the HTTP loader? A fixed username/password would suffice for a basic solution.

A more advanced solution would be to have something like a `.netrc` file, that is, a file where I can keep usernames/passwords to be used for different hosts.

I must admit that I am not a Python developer. But I have seen that the `http_loader` makes use of `tornado.httpclient.HTTPRequest` ([here](https://github.com/thumbor/thumbor/blob/c80a24a4a121de66f7e637d8d4dd1c4fa63b6fb1/thumbor/loaders/http_loader.py#L146)), so maybe this is something "already there" and just not documented because it is obvious for the initiated?

**Comment by gingerlime** [comment]
I'm not 100% sure, but I don't think it's supported currently. A few options off the top of my head:

* Whitelist your thumbor IP from requiring basic authentication on your backend (I would personally go for this one intuitively, if it's a possibility for you)
* set up a proxy in front of thumbor, and inject the authentication header. For example, using nginx, it should be something like `proxy_pass http://thumbor; proxy_set_header Authorization "Basic {{user:pass|base64 encoded}}";`, as well as allow passing the authorization header in thumbor, using `HTTP_LOADER_FORWARD_HEADERS_WHITELIST = ['Authorization']`
* Create a custom `http_loader`

**Comment by mpdude** [comment]
Maybe adding this feature this is not too difficult, as it should be pretty much the same as for proxy authentication (which is already supported)?

**Comment by gingerlime** [comment]
It should be relatively straight-forward, but not sure if it's considered important enough to be part of the default http_loader. Judging by https://github.com/thumbor/thumbor/pull/1021#issuecomment-391350175 at least, it might not be, but it's not my call :)

**Comment by heynemann** [comment]
@gingerlime is right @mpdude. It's pretty easy to just create your own custom http loader. Thumbor's default http loader is already too complex for its own good and might merit a refactor to split into many other loaders (ProxiedHTTPLoader perhaps),

Just take a look at how the loader is implemented and it should be straightforward to implement your own.

**Comment by gingerlime** [comment]
@heynemann I agree it makes sense to keep core thumbor lean. 

I'm wondering though, is there any official or semi-official community repo for contributed loaders, filters, etc. I found https://github.com/thumbor-community/core and https://github.com/thumbor/thumbor-plugins - but not sure there are any community-contributed loaders in there, or what's the exact connection between those repos (plus, perhaps clearer instructions on what/how to contribute, and how to load those contributed extensions into your own thumbor setup).

If there are any "approved" repos that are easy to load and then people can simply add config directives for them, then this could work well with the docker images at https://github.com/MinimalCompact/thumbor (and of course if people host differently, as well).

Just curious :)

**Comment by heynemann** [comment]
@gingerlime I do agree with you that we need better directions for "approved" plug-ins. I just think we need someone stewarding this. I would say thumbor-community is definitely the way to go, since thumbor-aws works pretty well there.

It would be great to have the docker image at thumbor-community org as well. Do you want access to thumbor-community and help us improve in that area?

**Comment by gingerlime** [comment]
@heynemann I'd be happy to. I would definitely need some guidance though, especially in the beginning.
