### ISSUE TITLE
AutoWebP not working with Result Storage

### ISSUE THREAD

**Issue by rahijain** [thumbor/thumbor#1103]
Hi,
We are using memcache result storage and nginx proxy to run thumbor. Whenever are opening both the flags of Result Storage and Auto WebP we are getting download option on firefox. Its working fine on chrome but showing download on the firefox. Meaning jpg format served by the server for Firefox is not recognized by Firefox.

STORAGE = 'thumbor_memcached.storage'
RESULT_STORAGE = 'thumbor_memcached.result_storage'

RESULT_STORAGE_EXPIRATION_SECONDS = 86400
RESULT_STORAGE_STORES_UNSAFE = True
RESULT_STORAGE_EXPIRATION_SECONDS = 86400
MEMCACHE_SKIP_STORAGE_EXCEEDING_ITEM_SIZE_MAX = False
MEMCACHE_ITEM_SIZE_MAX = 1048576

AUTO_WEBP = True

**Comment by rahijain** [comment]
I think there is some issues of header proxy passed. 

		proxy_set_header HOST $http_host;
		proxy_set_header X-NginX-Proxy true;
		rewrite ^(.*)$ unsafe/$1 break;
		proxy_pass http://thumbor;
		proxy_redirect off;

This is my nginx configuration for jpg / png images.

**Comment by cristiandean** [comment]
Another tip is if you will use nginx as caching proxy, you must set proxy_cache_key varying by http_accept, like this:

`proxy_cache_key $request_uri$http_accept";`

**Comment by rahijain** [comment]
Thanks for the help. But it's not working in the case of result storage cache. So i think memcache is not taking into consideration the accept headers. Will raise the same ticket in the memcache thumbor library.

**Comment by rahijain** [comment]
Also, accept headers are going into the thumbor via proxy otherwise auto_webp will not work in the first place. In second hit memcache is returning the cached version without taking consideration of accept headers.

**Comment by rahijain** [comment]
https://github.com/thumbor-community/redis/blob/master/tc_redis/result_storages/redis_result_storage.py

https://github.com/thumbor-community/thumbor-memcached/blob/master/thumbor_memcached/result_storage.py

In redis we have code for webp while creating keys while same is not in the memcache extension. 

https://github.com/thumbor-community/redis/blob/master/tc_redis/result_storages/redis_result_storage.py#L115

if self.is_auto_webp():
            path += '/webp'

**Comment by heynemann** [comment]
@rahijain can you open an issue in the memcached plugin repo and close this one?
