### ISSUE TITLE
Segfault with certain max_bytes sizes when using AutoWebP

### ISSUE THREAD

**Issue by bjaworski3** [thumbor/thumbor#1104]
### Thumbor request URL
unsafe/512x400/filters:quality(100):max_bytes(20400):fill(white)/https://upload.wikimedia.org/wikipedia/commons/5/5e/G_logo_of_Google.jpg

### Expected behaviour
Should return a WebP image with specified filters/size.

### Actual behaviour
Thumbor crashes with a segfault or memory corruption. Seems to happen when the `max_bytes` size is similar to the actual returned size. In the example above, a `max_bytes` size of 20000 returns a 8.4 KB image and a `max_bytes` size of 20500 returns a 20 KB image. The `max_bytes` size of 20400 crashes Thumbor. 

Above url will only crash Thumbor when `Accept: image/webp` is set.

On Alpine 3.8 Thumbor will segfault with exit code 139. No logs.

On Debian Thumbor will crash with:
`*** Error in `/usr/local/bin/python': double free or corruption (out): 0x00000000023f2b00 ***`

### Operating system
Tried on Alpine3.8 and Debian Jessie

### Your thumbor.conf
Running Thumbor 6.5.1

All default except:
AUTO_WEBP = True
STORAGE = 'thumbor.storages.no_storage'

**Comment by kkopachev** [comment]
Is this using PIL engine? What Pillow version?

**Comment by bjaworski3** [comment]
@kkopachev Yup using PIL engine. Pillow version 5.1.0.

**Comment by kkopachev** [comment]
yeah, after reducing quality to fit into bytes it then tries to increase quality to get biggest Q, which fit into bytes. Unfortunately it tries to go beyond quality=100 and that's where it fails.

```diff
Index: thumbor/handlers/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- thumbor/handlers/__init__.py	(revision c80a24a4a121de66f7e637d8d4dd1c4fa63b6fb1)
+++ thumbor/handlers/__init__.py	(date 1533332192000)
@@ -507,8 +507,8 @@
             results = engine.read(extension, quality)
 
         prev_result = results
-        while len(results) <= max_bytes:
-            quality = int(quality * 1.1)
+        while len(results) <= max_bytes and quality < 100:
+            quality = max(100, int(quality * 1.1))
             logger.debug('Trying to upsize image with quality of %d...' % quality)
             prev_result = results
             results = engine.read(extension, quality)
 ```

that should fix it meanwhile. I am looking into making this behave as binary search instead.

**Comment by heynemann** [comment]
Very likely my bad!!! :) Sorry guys! Probably an easy fix, though. Can you create an MR @kkopachev ?

**Comment by bjaworski3** [comment]
Thanks for the quick fix @kkopachev! Haven't had any issues after the above changes.

**Comment by kkopachev** [comment]
I submitted 2 PRs, I think binary search would result in highest quality, but might be more iterations in some circumstances. Pick your evil, @heynemann :)

@bjaworski3 Looks like crash was fixed in later Pillow (or libwebp). That could be another fix too.
