### ISSUE TITLE
Malformed HTTP request line

### ISSUE THREAD

**Issue by medaamarnadh** [thumbor/thumbor#1109]
### Thumbor request URL
https://app.lincsphere.com:8888/unsafe/fit-in/49x49/https%3A%2F%2Fapp.lincsphere.com%2Fuploads%2Fuser_images%2F16_0_0%2F16_2259_9.jpg

### Expected behaviour
The cropped image

### Actual behaviour
2018-08-25 15:36:59 tornado.general:INFO Malformed HTTP message from 223.230.101.167: Malformed HTTP headers: ''

### Operating system
CentOS Linux release 7.5.1804 (Core)

## Defaults to: None
#THUMBOR_LOG_CONFIG = None

## Defaults to: '%(asctime)s %(name)s:%(levelname)s %(message)s'
#THUMBOR_LOG_FORMAT = '%(asctime)s %(name)s:%(levelname)s %(message)s'

## Defaults to: '%Y-%m-%d %H:%M:%S'
#THUMBOR_LOG_DATE_FORMAT = '%Y-%m-%d %H:%M:%S'

################################################################################

## Defaults to: 0
#MAX_WIDTH = 0

## Defaults to: 0
#MAX_HEIGHT = 0

## Defaults to: 75000000.0
#MAX_PIXELS = 75000000.0

## Defaults to: 1
#MIN_WIDTH = 1

## Defaults to: 1
#MIN_HEIGHT = 1

## Defaults to: #    [
#    ]

#ALLOWED_SOURCES = #    [
#    ]

## Defaults to: 80
#QUALITY = 80

## Defaults to: True
#PROGRESSIVE_JPEG = True

## Defaults to: None
#PILLOW_JPEG_SUBSAMPLING = None

## Defaults to: None
#PILLOW_JPEG_QTABLES = None

## Defaults to: 'LANCZOS'
#PILLOW_RESAMPLING_FILTER = 'LANCZOS'

## Defaults to: None
#WEBP_QUALITY = None

## Defaults to: 6
#PNG_COMPRESSION_LEVEL = 6

## Defaults to: True
#PILLOW_PRESERVE_INDEXED_MODE = True

## Defaults to: False
#AUTO_WEBP = False

## Defaults to: 150
#SVG_DPI = 150

## Defaults to: 86400
#MAX_AGE = 86400

## Defaults to: 0
#MAX_AGE_TEMP_IMAGE = 0

## Defaults to: False
#RESPECT_ORIENTATION = False

## Defaults to: False
#IGNORE_SMART_ERRORS = False

## Defaults to: False
#SEND_IF_MODIFIED_LAST_MODIFIED_HEADERS = False

## Defaults to: False
#PRESERVE_EXIF_INFO = False

## Defaults to: True
#ALLOW_ANIMATED_GIFS = True

## Defaults to: False
#USE_GIFSICLE_ENGINE = False

## Defaults to: False
#USE_BLACKLIST = False

## Defaults to: 0
#ENGINE_THREADPOOL_SIZE = 0

################################################################################

## Defaults to: 'thumbor.metrics.logger_metrics'
#METRICS = 'thumbor.metrics.logger_metrics'

## Defaults to: 'thumbor.loaders.http_loader'
#LOADER = 'thumbor.loaders.http_loader'

## Defaults to: 'thumbor.storages.file_storage'
#STORAGE = 'thumbor.storages.file_storage'

## Defaults to: None
#RESULT_STORAGE = None

## Defaults to: 'thumbor.engines.pil'
#ENGINE = 'thumbor.engines.pil'

## Defaults to: 'thumbor.engines.gif'
#GIF_ENGINE = 'thumbor.engines.gif'

## Defaults to: 'libthumbor.url_signers.base64_hmac_sha1'
#URL_SIGNER = 'libthumbor.url_signers.base64_hmac_sha1'

################################################################################

## Defaults to: 'MY_SECURE_KEY'
#SECURITY_KEY = 'MY_SECURE_KEY'

## Defaults to: True
ALLOW_UNSAFE_URL = True

## Defaults to: True
#ALLOW_OLD_URLS = True

################################################################################

## Defaults to: True
#ENABLE_ETAGS = True

################################################################################

## Defaults to: 32
#MAX_ID_LENGTH = 32

################################################################################

## Defaults to: None
#GC_INTERVAL = None

################################################################################

## Defaults to: None
#STATSD_HOST = None

## Defaults to: 8125
#STATSD_PORT = 8125

## Defaults to: None
#STATSD_PREFIX = None

################################################################################

## Defaults to: '/root'
#FILE_LOADER_ROOT_PATH = '/root'

################################################################################

## Defaults to: 5
#HTTP_LOADER_CONNECT_TIMEOUT = 5

## Defaults to: 20
#HTTP_LOADER_REQUEST_TIMEOUT = 20

## Defaults to: True
#HTTP_LOADER_FOLLOW_REDIRECTS = True

## Defaults to: 5
#HTTP_LOADER_MAX_REDIRECTS = 5

## Defaults to: 10
#HTTP_LOADER_MAX_CLIENTS = 10

## Defaults to: False
#HTTP_LOADER_FORWARD_USER_AGENT = False

## Defaults to: False
#HTTP_LOADER_FORWARD_ALL_HEADERS = False

## Defaults to: #    [
#    ]

#HTTP_LOADER_FORWARD_HEADERS_WHITELIST = #    [
#    ]

## Defaults to: 'Thumbor/6.4.2'
#HTTP_LOADER_DEFAULT_USER_AGENT = 'Thumbor/6.4.2'

## Defaults to: None
#HTTP_LOADER_PROXY_HOST = None

## Defaults to: None
#HTTP_LOADER_PROXY_PORT = None

## Defaults to: None
#HTTP_LOADER_PROXY_USERNAME = None

## Defaults to: None
#HTTP_LOADER_PROXY_PASSWORD = None

## Defaults to: None
#HTTP_LOADER_CA_CERTS = None

## Defaults to: None
#HTTP_LOADER_VALIDATE_CERTS = None

## Defaults to: None
#HTTP_LOADER_CLIENT_KEY = None

## Defaults to: None
#HTTP_LOADER_CLIENT_CERT = None

## Defaults to: False
#HTTP_LOADER_CURL_ASYNC_HTTP_CLIENT = False

################################################################################

## Defaults to: 0
#HTTP_LOADER_CURL_LOW_SPEED_TIME = 0

## Defaults to: 0
#HTTP_LOADER_CURL_LOW_SPEED_LIMIT = 0

## Defaults to: 'thumbor.app.ThumborServiceApp'
#APP_CLASS = 'thumbor.app.ThumborServiceApp'

################################################################################

## Defaults to: 2592000
#STORAGE_EXPIRATION_SECONDS = 2592000

## Defaults to: False
#STORES_CRYPTO_KEY_FOR_EACH_IMAGE = False

## Defaults to: '/tmp/thumbor/storage'
#FILE_STORAGE_ROOT_PATH = '/tmp/thumbor/storage'

################################################################################

## Defaults to: 0
#UPLOAD_MAX_SIZE = 0

## Defaults to: False
#UPLOAD_ENABLED = False

## Defaults to: 'thumbor.storages.file_storage'
#UPLOAD_PHOTO_STORAGE = 'thumbor.storages.file_storage'

## Defaults to: False
#UPLOAD_DELETE_ALLOWED = False

## Defaults to: False
#UPLOAD_PUT_ALLOWED = False

## Defaults to: 'image'
#UPLOAD_DEFAULT_FILENAME = 'image'

################################################################################

## Defaults to: #    [
#        'localhost:11211',
#    ]

#MEMCACHE_STORAGE_SERVERS = #    [
#        'localhost:11211',
#    ]

################################################################################

## Defaults to: 'thumbor.storages.no_storage'
#MIXED_STORAGE_FILE_STORAGE = 'thumbor.storages.no_storage'

## Defaults to: 'thumbor.storages.no_storage'
#MIXED_STORAGE_CRYPTO_STORAGE = 'thumbor.storages.no_storage'

## Defaults to: 'thumbor.storages.no_storage'
#MIXED_STORAGE_DETECTOR_STORAGE = 'thumbor.storages.no_storage'

################################################################################

## Defaults to: None
#META_CALLBACK_NAME = None

################################################################################

## Defaults to: #    [
#    ]

#DETECTORS = #    [
#    ]

## Defaults to: 'haarcascade_frontalface_alt.xml'
#FACE_DETECTOR_CASCADE_FILE = 'haarcascade_frontalface_alt.xml'

## Defaults to: 'haarcascade_eye_tree_eyeglasses.xml'
#GLASSES_DETECTOR_CASCADE_FILE = 'haarcascade_eye_tree_eyeglasses.xml'

## Defaults to: 'haarcascade_profileface.xml'
#PROFILE_DETECTOR_CASCADE_FILE = 'haarcascade_profileface.xml'

################################################################################

## Defaults to: #    [
#    ]

#OPTIMIZERS = #    [
#    ]

## Defaults to: '/usr/bin/jpegtran'
#JPEGTRAN_PATH = '/usr/bin/jpegtran'

## Defaults to: '/usr/local/bin/ffmpeg'
#FFMPEG_PATH = '/usr/local/bin/ffmpeg'

################################################################################

## Defaults to: #    [
#        'thumbor.filters.brightness',
#        'thumbor.filters.colorize',
#        'thumbor.filters.contrast',
#        'thumbor.filters.rgb',
#        'thumbor.filters.round_corner',
#        'thumbor.filters.quality',
#        'thumbor.filters.noise',
#        'thumbor.filters.watermark',
#        'thumbor.filters.equalize',
#        'thumbor.filters.fill',
#        'thumbor.filters.sharpen',
#        'thumbor.filters.strip_exif',
#        'thumbor.filters.strip_icc',
#        'thumbor.filters.frame',
#        'thumbor.filters.grayscale',
#        'thumbor.filters.rotate',
#        'thumbor.filters.format',
#        'thumbor.filters.max_bytes',
#        'thumbor.filters.convolution',
#        'thumbor.filters.blur',
#        'thumbor.filters.extract_focal',
#        'thumbor.filters.focal',
#        'thumbor.filters.no_upscale',
#        'thumbor.filters.saturation',
#        'thumbor.filters.max_age',
#        'thumbor.filters.curve',
#        'thumbor.filters.background_color',
#        'thumbor.filters.upscale',
#    ]

#FILTERS = #    [
#        'thumbor.filters.brightness',
#        'thumbor.filters.colorize',
#        'thumbor.filters.contrast',
#        'thumbor.filters.rgb',
#        'thumbor.filters.round_corner',
#        'thumbor.filters.quality',
#        'thumbor.filters.noise',
#        'thumbor.filters.watermark',
#        'thumbor.filters.equalize',
#        'thumbor.filters.fill',
#        'thumbor.filters.sharpen',
#        'thumbor.filters.strip_exif',
#        'thumbor.filters.strip_icc',
#        'thumbor.filters.frame',
#        'thumbor.filters.grayscale',
#        'thumbor.filters.rotate',
#        'thumbor.filters.format',
#        'thumbor.filters.max_bytes',
#        'thumbor.filters.convolution',
#        'thumbor.filters.blur',
#        'thumbor.filters.extract_focal',
#        'thumbor.filters.focal',
#        'thumbor.filters.no_upscale',
#        'thumbor.filters.saturation',
#        'thumbor.filters.max_age',
#        'thumbor.filters.curve',
#        'thumbor.filters.background_color',
#        'thumbor.filters.upscale',
#    ]

################################################################################

## Defaults to: 0
#RESULT_STORAGE_EXPIRATION_SECONDS = 0

## Defaults to: '/tmp/thumbor/result_storage'
#RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/tmp/thumbor/result_storage'

## Defaults to: False
#RESULT_STORAGE_STORES_UNSAFE = False

################################################################################

## Defaults to: 'localhost'
#REDIS_QUEUE_SERVER_HOST = 'localhost'

## Defaults to: 6379
#REDIS_QUEUE_SERVER_PORT = 6379

## Defaults to: 0
#REDIS_QUEUE_SERVER_DB = 0

## Defaults to: None
#REDIS_QUEUE_SERVER_PASSWORD = None
####      REDIS STORAGE #######
#RESULT_STORAGE='tc_redis.result_storages.redis_result_storage'

#REDIS_RESULT_STORAGE_IGNORE_ERRORS = True
#REDIS_RESULT_STORAGE_SERVER_PORT = 6379
#REDIS_RESULT_STORAGE_SERVER_HOST = 'localhost'
#REDIS_RESULT_STORAGE_SERVER_DB = 0
#REDIS_RESULT_STORAGE_SERVER_PASSWORD = None

################################################################################

## Defaults to: None
#SQS_QUEUE_KEY_ID = None

## Defaults to: None
#SQS_QUEUE_KEY_SECRET = None

## Defaults to: 'us-east-1'
#SQS_QUEUE_REGION = 'us-east-1'

################################################################################

## Defaults to: False
#USE_CUSTOM_ERROR_HANDLING = False

## Defaults to: 'thumbor.error_handlers.sentry'
#ERROR_HANDLER_MODULE = 'thumbor.error_handlers.sentry'

## Defaults to: None
#ERROR_FILE_LOGGER = None

## Defaults to: False
#ERROR_FILE_NAME_USE_CONTEXT = False

################################################################################

## Defaults to: ''
#SENTRY_DSN_URL = ''

################################################################################

**Comment by caeugusmao** [comment]
Hi @medaamarnadh,

Try to load with http instead of https. If you need to deal with https you can add in your environment an web server in front of you app(thumbor), such as nginx for example.

Let us know if it works!

**Comment by cristiandean** [comment]
Works for me on latest version.

![image](https://user-images.githubusercontent.com/25023177/55506923-f924d080-562c-11e9-8c09-04c65934976f.png)

I will close the issue, feel free to reopen if the problem persists.
