### ISSUE TITLE
Thumbor change destination filename

### ISSUE THREAD

**Issue by JordanGS** [thumbor/thumbor#1111]
message = `fit-in/580x250/smart/filters:cb(1235):fill(e7e7e7)/source.com/image.jpg`

`http://destination.com/<HMAC-SHA1 of message>/fit-in/580x250/smart/filters:cb(1235):fill(e7e7e7)/`

`http://destination.com/<HMAC-SHA1 of message>/fit-in/580x250/smart/filters:cb(1235):fill(e7e7e7)/source.com/image.jpg`

i simply create the final image URL and open that without a direct call to thumbor to upload the image to my destination server from the source. 

My source image name is called image.jpg, how do i tell thumbor to change the final image name to picture.jpg instead?

Thank you!

**Comment by caeugusmao** [comment]
Hi @JordanGS ,

If I understood you case, you want to process an external image and store it with other name.

By default you can not. To do that, you have to implement your own result storage class, specifically develop the put and get methods on your result storage module.

[Storage Plugins](https://thumbor.readthedocs.io/en/latest/plugins.html#storages)
