### ISSUE TITLE
Using percentage to resize

### ISSUE THREAD

**Issue by udleinati** [thumbor/thumbor#1112]
Hi Guys, I have a situation where I need to request image based on proportion like 30%, 80%, 100%, 400%, etc. Has someone an idea how I can solve it just on thumbor?

**Comment by caeugusmao** [comment]
Hi @udleinati 

Thumbor does not have this feature. You have to calculate the proportions before generate the thumbor url and pass the sizes in the url.

You can see how to crop and resize images here: [Crop and resize](https://thumbor.readthedocs.io/en/latest/crop_and_resize_algorithms.html?highlight=crop)

**Comment by udleinati** [comment]
Hi @caeugusmao, I opened a pull request adding a filter to do that. [Link](https://github.com/thumbor/thumbor/pull/1113)

Thanks for your help :)

**Comment by caeugusmao** [comment]
@udleinati 

I will close this issue. Let's deal with this in PR #1113.

tks!!
