### ISSUE TITLE
Writing new EXIF data to image

### ISSUE THREAD

**Issue by freedawilson** [thumbor/thumbor#1114]
I'm trying to get a better understanding of how EXIF is handled within Thumbor - with the end goal been to add additional custom EXIF values to the image before it is returned to the user.

(Note: python noob)

Having browsed the site, explored the metadata documentation, and browser EXIF related issues from the past - for experimentation purposes only I tried the following:

Created a filter which accepts a single argument, this argument is then used as the value for the software EXIF tag.

The theory been when you run the filter as part of the URI, it'll add to any existing EXIF and return the new image with the new value for Software.

I can extract existing EXIF tags from self.engine.metadata, and I can set them - but they don't ever seem to be applied to the final image.  PRESERVE_EXIF_INFO = True - although if this filter was set I'd like to think even if it was False - EXIF data would be removed, then the custom values still added.

Not sure if this is a limitation of my knowledge of Thumbor or a limitation of Thumbor or one of it's dependencies - I'd love if someone with a bit more expertise could point me in the right direction here. Thanks

Usage: filter:tagtest(SomeTextHere)

tagtest.py:   

```
from thumbor.filters import BaseFilter, filter_method
from thumbor.utils import logger
class Filter(BaseFilter):
    @filter_method(
        BaseFilter.String #word
    )
    def copyright(self, notice):
        key = "Exif.Image.Software"
        self.engine.metadata[key] = notice
        self.engine.metadata.write()
```

**Comment by caeugusmao** [comment]
HI @freedawilson,

By default, to preserve EXIF_INFO you have to set this conf = True. This way Thumbor will preserve exif info from original image, the right place to seek this kind of information. 

We have two concerns in your approach:

1 - In terms of product does not make sense override this kind of information which should be present in the original images

2 - In technical terms add free character is not url-safe and could generate problems.

tks
