### ISSUE TITLE
Install fails on brand new debian

### ISSUE THREAD

**Issue by thomasd3** [thumbor/thumbor#1115]
I get this:

Processing pycurl-7.43.0.2.tar.gz
Writing /tmp/easy_install-YizUfE/pycurl-7.43.0.2/setup.cfg
Running pycurl-7.43.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-YizUfE/pycurl-7.43.0.2/egg-dist-tmp-XXOUPU
Traceback (most recent call last):
  File "setup.py", line 136, in <module>
    run_setup()
  File "setup.py", line 125, in run_setup
    ext_modules=extension_modules
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
.....

  File "/tmp/easy_install-YizUfE/pycurl-7.43.0.2/setup.py", line 913, in <module>
    
  File "/tmp/easy_install-YizUfE/pycurl-7.43.0.2/setup.py", line 582, in get_extension
    
  File "/tmp/easy_install-YizUfE/pycurl-7.43.0.2/setup.py", line 99, in __init__
    "pycryptodome >= 3.4.7",
  File "/tmp/easy_install-YizUfE/pycurl-7.43.0.2/setup.py", line 227, in configure_unix
    
setuptools.sandbox.UnpickleableException: ConfigurationError('Could not run curl-config: [Errno 2] No such file or directory',)

Brand new Debian install; did an update, installed git, pulled Thumbor and tried to build with sudo python setup.py install

**Comment by thor27** [comment]
Hi!
You need to install all dependencies that are missing. If you just want to run thumbor, you should try pre-built packages that you can find here: https://thumbor.readthedocs.io/en/latest/installing.html

But if you still want to build from source, you can install using make setup, or if you prefer, you can manually install the packages:

```
sudo apt install imagemagick webp coreutils gifsicle libvpx? \
                         libvpx-dev libimage-exiftool-perl libcairo2-dev \
                         ffmpeg libcurl4-openssl-dev libffi-dev \
                         python-dev python3-dev
```

Pay attention that those package are for Ubuntu, it might have some small differences in package name with Debian.

**Comment by thomasd3** [comment]
Great! thanks a lot.
I'm trying to build it because I want to use a subset of the functionalities.

**Comment by marcelometal** [comment]
Hi @thomasd3,

Thumbor is in [Debian unstable repository](https://packages.debian.org/sid/thumbor), so you can use this package or you can build it from the [package source](https://salsa.debian.org/python-team/modules/thumbor), but it only works if you build [piexif package](https://salsa.debian.org/python-team/modules/piexif) too (piexif package has already been uploaded to the [NEW qeuee](https://ftp-master.debian.org/new.html) 3 months ago)

cheers!

**Comment by thomasd3** [comment]
Thanks for the info!

**Comment by gingerlime** [comment]
Correct me if I'm wrong, but isn't this a fairly old version of thumbor in debian unstable?

I'm maintaining a docker-based thumbor image at https://github.com/MinimalCompact/thumbor. 

You can see the [list of OS dependencies here](https://github.com/MinimalCompact/thumbor/blob/16589c06d5126a364bd3d38630b2a3a745673134/thumbor/Dockerfile#L9-L28) some [small tweaks](https://github.com/MinimalCompact/thumbor/blob/16589c06d5126a364bd3d38630b2a3a745673134/thumbor/Dockerfile#L47-L48) as well as the pip [requirements.txt file](https://github.com/MinimalCompact/thumbor/blob/master/thumbor/requirements.txt).

Hope this helps.

**Comment by marcelometal** [comment]
@gingerlime you are right, we are waiting for piexif package. But as I said, you can build Thumbor from the [package source](https://salsa.debian.org/python-team/modules/thumbor) (6.5.1-1).
