### ISSUE TITLE
Is there a way to remove expired images?

### ISSUE THREAD

**Issue by romulowspp** [thumbor/thumbor#1117]
The problem:
On our infrastructure, we are running Thumbor in a docker cluster. Our instances doesn't have much storage and we can't mount a huge volume shared between dockers (Some infrastructure best practices - keeping the containers stateless). We use a CDN along with their caching to prevent high throughput to Thumbor.

We have 3 solutions:
1. **Use Redis:** I'm not sure if this is okay because we have a lot of big pictures and this is not a cheap solution.

2. **Use S3:** I think this will be a good solution, we can use a bucket with life-cycle. I'm afraid of this solution because we will do a lot of requests to S3.

3. **Remove expired files:** If we put a cron cleaning the storage dir, we can solve this problem (Actually, we restart the docker instances to clean all files).

I need to know the best approach to solve this problem.

**Comment by thor27** [comment]
Hi,

I agree that Redis might not be the best approach for large images. S3 or using some storage solution with a cleaning cronjob are both good options. About the quantity of requests to S3, you can use a cache in proxy solution in front of thumbor that could significant reduce result storage access.

**Comment by gingerlime** [comment]
I'm using monit to trigger clean-up after a certain threshold, together with shorter expiry settings. (`STORAGE_EXPIRATION_SECONDS` and `RESULT_STORAGE_EXPIRATION_SECONDS`).

My setup is based on https://github.com/MinimalCompact/thumbor with `docker-compose`. But the same principles can apply in other ways.

```
# docker-compose.yml
...
  monit:
    image: vimagick/monit
    volumes:
      - ./monit:/etc/monit
      - ./data:/data
```

and the monit folder has

```shell
$ tree monit/
monit/
├── conf.d
│   └── diskspace.cfg
└── monitrc

$ cat monit/monitrc
###############################################################################
## Monit control file
###############################################################################

set daemon  30
set logfile /dev/stdout
set pidfile /var/run/monit.pid
set idfile /var/lib/monit/monit.id
set statefile /var/lib/monit/monit.state
set eventqueue basedir /var/lib/monit/events slots 5000
include /etc/monit/conf.d/*.cfg

$ cat monit/conf.d/diskspace.cfg
check filesystem rootfs with path /data/
    if space usage > 90% then exec "/bin/sh -c 'find /data/result_storage/v2/ -mindepth 1 -mmin +60 |xargs rm -rf'"
```

This would check for low diskspace and clear files in your result storage only when needed. You can also adapt it to clear the storage folder, change thresholds, just use a cron job without monit etc.

Hope this helps :)

**Comment by bagipriyank** [comment]
We have CDN backed by S3, which redirects to Thumbor on 404, which will save the image to S3 so subsequent requests will at worst go to S3 and bulk of the throughput is coming from CDN. 

We use the following properties to make sure we don't save any files to disk as we are using docker containers as well

```
Name: STORAGE
Value: "thumbor.storages.no_storage"
Name: RESULT_STORAGE
Value: "thumbor.result_storages.no_storage"
```

**Comment by gingerlime** [comment]
Hi @bagipriyank. I'm not entirely sure why you're using thumbor this way (although I'm sure you have good reasons to choose this, and thumbor is flexible to accommodate). However, if you're not letting thumbor manage your results storage, then it obviously won't allow you to remove expired images, which is I believe what the original question was about?

**Comment by bagipriyank** [comment]
Sorry about the delayed response. I agree that not every one wants to not let thumbor manage results storage. Thumbor will save original image on the container as well and not just the "expired" images. The point I am trying to make is that by chosing no storage we are not caching / saving any images on the thumbor containers, and by serving off of s3 we don't have to worry about caching / saving images on container to begin with.

**Comment by gingerlime** [comment]
> In case of expired images, since CDN is providing bulk of the throughput, requests to S3 should only happen on misses from CDN which should be same as what happens without S3 in the mix.

Yes, but the nature of (at least some) CDNs is that if they cache things on the edge. This means that if you have some requests from one edge, or region, it's cached there, but if you get requests on other edges/regions, it won't be cached. So for a single image you might get quite a few requests, even if they are cached by your CDN. And typically the performance of generating the thumbnail on thumbor is much worse than serving it from local cache. That's the main advantage of *also* having local caches, which the result storage allows you to do. This is what MinimalCompact/thumbor is supporting. It allows you to use results storage + nginx caching.

I guess your question wasn't geared to me, but rather to @Ablankzin, so I'll let them answer :)

**Comment by bagipriyank** [comment]
@gingerlime i agree with your argument completely. we decided to save the result image in s3 instead of caching locally. Also I do like MinimalCompact/thumbor. We were planning to use it but since we also need to provide jpeg2000 support ended up creating our own container with thumbor plugins as well.

@kkopachev you nailed it pretty much. the only difference is instead of returning from thumbor right away we redirect back to CDN so that edge now caches the result image from s3. this way the first request is definitely slower, but after that thumbor is just out of the picture for the same result image. 

when we get a request for images by one instance of client, it's not for just one image but for multiple images together and that's why we didn't want to have lot of requests going to thumbor containers.

**Comment by bagipriyank** [comment]
unfortunately no auto webp this way via server. our clients do request webp images explicitly though via format fllter. (along with jp2 for jpeg200 depending on the platform etc)

**Comment by gingerlime** [comment]
> Also I do like MinimalCompact/thumbor. We were planning to use it but since we also need to provide jpeg2000 support, we ended up creating our own container with thumbor plugins as well.

I'm happy to accept PRs to add more library support, plugins etc. As long as they don't clash with existing functionality.

I mostly treat the docker image as a mini-vm. The docker philosophy is to keep images small, but at the same time interoperability between containers is rather limited, so the container-as-a-vm seems like a reasonable compromise to me in the case of thumbor.
