### ISSUE TITLE
Question: Is it possible to use thumbor to just do processing

### ISSUE THREAD

**Issue by thomasd3** [thumbor/thumbor#1118]
I was wondering if thumbor could be used the following way:
- submit an image with some parameters
- get back the thumbnail and the faces coordinates
- nothing gets stored on the server

essentially just as an image processor with a rest interface.

**Comment by heynemann** [comment]
Yep! :) Just use the [NoStorage](https://thumbor.readthedocs.io/en/latest/image_storage.html) storage for both image storage and result storage.

I would advise against it as it will be rather slow, but I don't know your specific use case.

Hope it helps.
