### ISSUE TITLE
Feature Request: stretch/scale to dimensions, disregarding aspect ratio 

### ISSUE THREAD

**Issue by timkelty** [thumbor/thumbor#1123]
I want to be able to resize an image to exact dimensions, disregarding the image's aspect ratio (resize the image, without cropping).

With [Imgix](https://docs.imgix.com/apis/url/size/fit), this is done with `fit=scale`
https://assets.imgix.net/examples/kingfisher.jpg?fit=scale&h=200&w=900

Anything I try with Thumbor, it always seems to crop:
https:/[redacted]/900x200/filters:upscale()/examples/kingfisher.jpg

**Comment by timkelty** [comment]
@thor27 I tried that as well… with a 1000x1000 source image and `fit-in/900x200`, I just end up with a proportionally scaled, 200x200 image.

**Comment by thor27** [comment]
Hi,
Well, fit-in actually doesn't crop the image as you asked. To resize not respecting the aspect ratio, as far as I know, thumbor doesn't do that. You can actually achieve that stretching the image with css.

**Comment by timkelty** [comment]
@thor27 Ok, that's what I thought, thanks!

And you're right about being able to do that with css (and its generally not something you'd really need anyhow)…I'm actually just writing an adapter that maps some functionality from other resizers (e.g. imgix, cloudinary)

I suspect it is a fairly easy thing to do under the hood, its just that it is an odd request. It is support by most other resizing systems, so maybe I should leave this open as a feature request?

**Comment by caeugusmao** [comment]
@timkelty You can use stretch filter which is available from version 6.6.0.

**Comment by timkelty** [comment]
lovely, I'll try it out! Thanks @caeugusmao

**Comment by timkelty** [comment]
There doesn't seem to be any documentation on stretch? https://thumbor.readthedocs.io/en/latest/filters.html

**Comment by heynemann** [comment]
Very true, @timkelty Sorry for that. We need to update docs to include it.

**Comment by cristiandean** [comment]
#1134 PR merged and with docs.
