### ISSUE TITLE
Piexif works with 1.1.1?

### ISSUE THREAD

**Issue by jluttine** [thumbor/thumbor#1127]
I ran unit tests with piexif 1.1.1 and everything passed. Why is there an upper bound for the version: 
https://github.com/thumbor/thumbor/blob/c1f61802ff2fc1f401edd619ec85b9ce679562f2/setup.py#L103

**Comment by caeugusmao** [comment]
Hi @jluttine,

Do you need something specific which comes on this version?

**Comment by jluttine** [comment]
@caeugusmao Nope. I'm just packaging Piexif for a Linux distro and wanted to upgrade it. Well, it caused problems because Thumbor (which is also packaged in the distro) doesn't support Piexif 1.1.1. I just made a patch for Thumbor to accept newer Piexif version but I was wondering if there was some known issue with newer Piexif why it was constrained out.

**Comment by marcelometal** [comment]
Hi @jluttine, what distro?

For Debian/Ubuntu there is a [Piexif package](https://salsa.debian.org/python-team/modules/piexif) (piexif package has already been uploaded to the NEW qeuee 4 months ago)

**Comment by jluttine** [comment]
@marceloboeira NixOS.

**Comment by jluttine** [comment]
@marcelometal NixOS.
