### ISSUE TITLE
Oficial docker image

### ISSUE THREAD

**Issue by rturk** [thumbor/thumbor#1132]
Looks like APSL docker thumbor is no longer updated. Should we create and maintain official docker image

**Comment by kkopachev** [comment]
There is this one https://github.com/MinimalCompact/thumbor and another one https://github.com/hey-car/thumbor

**Comment by rturk** [comment]
Hi folks I vote to re-open this, external repos can't be audited, neither controlled by the community. Should be effort-less to create a official Docker file and use free CI (ie. Circle-ci) automatic main the image

**Comment by gingerlime** [comment]
@kkopachev and me are maintaining https://github.com/MinimalCompact/thumbor and it's fully auditable and community-driven. We welcome contributions and it's actively maintained and updated in-line with thumbor. I'd be more than happy to add more members who show commitment and can contribute to the project with commit access as well.
