### ISSUE TITLE
MAX_AGE 4xx

### ISSUE THREAD

**Issue by snakecharmer** [thumbor/thumbor#1133]
Is it possible to send a max_age for 4xx response? 
Right now we have many request for missing origin content (404) and we want it to cache it for a few minutes on our CDN. 

Should we write a plugin or will be included in the standard package?

**Comment by cristiandean** [comment]
One way to do this is by using a reverse proxy in the front, like an nginx.

**Comment by snakecharmer** [comment]
Right now I'm using an ingress Nginx (Kubernetes) and I don't want to have a double nginx (in container and on Kube). Right now is possible to configure a max_age for 200 in the thumbor configuration, shouldn't be possible to do it for missing content / errors too?
