### ISSUE TITLE
cache-control immutable

### ISSUE THREAD

**Issue by Enalmada** [thumbor/thumbor#1136]
I am no expert but I see immutable on everything now.  I believe adding cache-control immutable would improve performance.  Apparently even with max age set, browsers will revalidate on a page reload and immutable helps stop that from happening: https://www.keycdn.com/blog/cache-control-immutable

### Expected behaviour
responses should be `cache-control: max-age=31536000,public,immutable`

### Actual behaviour
responses are `cache-control: max-age=31536000,public`

I don't think there is any harm in setting it if public and max-age > 0.

**Comment by caeugusmao** [comment]
Hi @Enalmada,

We will analyze this possibility, but you can have immutable option for cache control when you have a web server in the front end layer.

http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header

There are other options to do this using nginx, with external modules.

https://github.com/openresty/headers-more-nginx-module

**Comment by heynemann** [comment]
I do find it to be a good addition to thumbor, though.

Thanks for the report! @Enalmada do you think you could come up with a PR?

**Comment by Enalmada** [comment]
@caeugusmao Thanks for the nginx tip.  I think that is a great suggestion for everyone until it it is officially supported.  I am adding it using the following commands:
```
   proxy_hide_header Cache-Control;
   add_header Cache-Control "public, max-age=31536000, immutable";
```
(I am no nginx expert and there is likely a better way to append immutable to the existing header but I found it easiest to hide the current one and add the new one to avoid duplicate)

Yes, if it is something you would want I will send a PR eventually.  I wouldn't be sad if one of you savants added the ", immutable" to the cache string if you happen to be in the code area though.

**Comment by caeugusmao** [comment]
@heynemann @Enalmada 

Any consideration?

**Comment by kkopachev** [comment]
This seems like a useful feature.
