### ISSUE TITLE
Some guidance on (Phyton) logging configuration?

### ISSUE THREAD

**Issue by mpdude** [thumbor/thumbor#1145]
I've seen that #415 added the possibility to configure logging at great detail.

For those of us not at home in the Python world, could someone leave some pointers how this can be leveraged?

I'll be running Thumbor in a docker container, so the default output via stdout/stderr should be fine. What would be more interesting is if there are different handlers/channels/modules available so that we could log things at various levels – for example, just basic request information, but everything for result storage or the HTTP client at `debug` level.

Or, log the value of HTTP Request headers (Request-/Trace-IDs)?

Is that possible?

Regarding documentation, what is the best way to contribute such additions? Is a PR for the `doc/` directory the way to go?

Thanks!

**Comment by okor** [comment]
Closing because this is very old and hasn't had any activity in a long time.
