### ISSUE TITLE
why the remove() method doesn't need yield?

### ISSUE THREAD

**Issue by Tideorz** [thumbor/thumbor#1150]
Recently, I'm looking at thumbor code, and in the https://github.com/thumbor/thumbor/blob/master/thumbor/handlers/image_resource.py#L71

```
    @tornado.web.asynchronous
    @tornado.gen.coroutine
    def delete(self, id):
        id = id[:self.context.config.MAX_ID_LENGTH]
        # Check if image deleting is allowed
        if not self.context.config.UPLOAD_DELETE_ALLOWED:
            self._error(405, 'Unable to delete an uploaded image')
            return

        # Check if image exists
        exists = yield gen.maybe_future(self.context.modules.storage.exists(id))
        if exists:
            self.context.modules.storage.remove(id)
            self.set_status(204)
        else:
            self._error(404, 'Image not found at the given URL')
```
I'm curious about why this remove() method doesn't need yield before it? The remove() method may
also need to time to finish before it returns?

**Comment by heynemann** [comment]
It should have. But if we add it now we'll break a LOT of storages.

**Comment by Tideorz** [comment]
@heynemann and also for the def put() method in this file, which doesn't have the 
@tornado.web.asynchronous and @tornado.gen.coroutine, I thinks it will stuck the 
tornado main thread when doing the put api stufff :/
