### ISSUE TITLE
JSON logging

### ISSUE THREAD

**Issue by anton-johansson** [thumbor/thumbor#1152]
Is it possible to get JSON output in the logs? For example, the following log line:
```
2019-01-10 12:15:07 root:DEBUG thumbor running at 0.0.0.0:8001
```

... would be awesome to be able to have as:
```json
{
  "timestamp": "2019-01-10 12:15:07",
  "name": "root",
  "level": "DEBUG",
  "message": "thumbor running at 0.0.0.0:8001"
}
```

I guess I could just tweak the format, but I'd need to escape the message, in case the message would have qoutes in it. Ideas?

**Comment by heynemann** [comment]
Would be good to have structured logging in thumbor, but I think the best way to go about this is to use thumbor's own mechanisms for extensibility and allow people to implement their own loggers. 

What do I mean by that?

We could change all logging in thumbor to be something like:

```python
logger.debug('Something happened.', image_url=image_url)
```

Then we'd implement the `StdoutLogger` that just prints these as:

```
2019-01-10 12:15:07 Something happened (image_url='/something.jpg')
```

As well as the `JSONLogger`, that prints:
```json
{
  "timestamp": "2019-01-10 12:15:07",
  "level": "DEBUG",
  "message": "Something happened",
  "image_url": "/something.jpg"
}
```

What do you guys think?

**Comment by mbarouski** [comment]
@heynemann are there any updates for JSON logging planned?
