### ISSUE TITLE
Zoom to face

### ISSUE THREAD

**Issue by developdeez** [thumbor/thumbor#1155]
I selected a size for the crop then selected smart.
I was expecting it to crop to the face using Smart detection but instead it shrunk the image to the crop dimensions.

Seems any time you use square dimensions it simply shrinks the image while if not square it will try to crop towards the face. Am I missing something?

**Comment by kkopachev** [comment]
Could you provide urls you are trying and result images?

**Comment by SamGoody** [comment]
Not OP, but am completely stymied about focus in Thumbor, so would LOVE some tips.

According to the homepage: 
> Everytime a face is detected, it will crop the image around it, making sure the most important parts of the picture are preserved. 

In my test example using, I tried to load `http://localhost:8888/unsafe/200x200/smart/https%3A%2F%2Fgithub.com%2Fthumbor%2Fthumbor%2Fraw%2Fmaster%2Fexample.jpg`

Despite the `/smart/`filter, it shows exactly the same as if I had done  `http://localhost:8888/unsafe/200x200/http..`, the output image is not smartly cropped

How do I zoom into the face and crop around it?

![https _github com_thumbor_thumbor_raw_master_example](https://user-images.githubusercontent.com/47037/145391655-0cbfd6c0-ade2-498b-a54f-3bdc9ac0e5f2.jpg)

**Comment by pfcodes** [comment]
Did you figure this out?
