### ISSUE TITLE
Multiple loaders configured at once

### ISSUE THREAD

**Issue by bkonetzny** [thumbor/thumbor#1157]
It would be nice to be able to configure multiple loaders at once, e.g. URL & S3 loader like we do with the detectors:
```
LOADER = [
    'tc_aws.loaders.s3_loader',
    'thumbor.loaders.http_loader'
]
```
Thus the following URLs would get handled differently:

> https://thumbor-server/fit-in/400x300/my/s3/image.png -> handled by tc_aws.loaders.s3_loader
> https://thumbor-server/fit-in/400x300/https://example.com/my/url/image.png -> handled by thumbor.loaders.http_loader, as tc_aws.loaders.s3_loader failed to load the image

This would allow for stacking multiple loaders and would make the `thumbor.loaders.file_loader_http_fallback` obsolete, as this could be handled by configuring the file and http loader.

We currently need this feature for the s3 loader and this loader has no fallback, like the default file loader. This change in handling loaders would it make obsolete to have a fallback for each loader implementation.

What do you guys think?

_Edit: Correction, the s3 loader actually has a http fallback (TC_AWS_ENABLE_HTTP_LOADER), see https://github.com/thumbor-community/aws_

**Comment by caeugusmao** [comment]
Hi @bkonetzny,

How would you handle with more than one loader in terms of execution order? 

Depending on the case you would add an unnecessary step to load images, decreasing Thumbor's performance.

**Comment by bkonetzny** [comment]
Hi @caeugusmao,

I'd expect order of execution as defined in the config, so first loader gets executed first, and if that loader executes, all others are skipped. Only if a loader doesn't execute, the next loader in line will take over and try.
Not sure how this is internally handled, but I'd expect the loader to quit early if the URL/path of the image is invalid for this loader.
E.g. the `thumbor.loaders.http_loader` should quit early on image `https://thumbor-server/fit-in/400x300/my/s3/image.png`, as this is not a valid URL. Same for `tc_aws.loaders.s3_loader` and `https://thumbor-server/fit-in/400x300/https://example.com/my/url/image.png`, as this contains https and thus seems not to be a s3 path.

Of course this will decrease performance with the more loaders you configure, but it will reduce complexity, as for now you need a special "fallback" loader like `thumbor.loaders.file_loader_http_fallback` to handle this, and for s3 it's not even solved, so one needs to create a special s3/http fallback handler. And the next project needs a s3/filesystem fallback handler, and you start all over again...

For backwards compatibility: Maybe the `LOADER` config property should stay as-is, and a new `LOADERS` property should be introduced to define more than one loader. So existing configs will still work, and only if LOADERS is set, it will overrule LOADER in config.

**Comment by kkopachev** [comment]
One option for now could be to create new loader plugin which will be able to handle check and proxy call to appropriate loader. Sort of router.

**Comment by heynemann** [comment]
Hey @bkonetzny I prefer to keep it simpler. If we introduce this logic, we would have to change our loaders to actually perform the logic you described whereas if we just introduce a new loader (`FallbackLoader`?) we can be explicit on what the user wants.

Something like you described would be the config for this loader:
```
FALLBACK_LOADER_LOADERS = [
    'thumbor.loaders.file_loader',
    'thumbor.loaders.http_loader',
]
```

That way we keep thumbor working the way it is, this pattern already exists in the codebase (`MixedStorage`) and it keeps working with whatever loader is out there.

The first loader that responds without error "wins". What do you guys think?

**Comment by chrisandchris** [comment]
+1 for the proposal of @heynemann

**Comment by rafaeleyng** [comment]
Is anyone working on this? I would like to try to implement it 😃. You could assign it to me

**Comment by heynemann** [comment]
Go ahead! :)
