### ISSUE TITLE
Document/Clarify WEBP_QUALITY

### ISSUE THREAD

**Issue by timkelty** [thumbor/thumbor#1164]
### Thumbor request URL
https://d3v5ux74ykdcrl.cloudfront.net/1920x510/filters:quality(50)/hero/Hero_InsightPage_5000x1800-high-rez-3.png

### Expected behaviour
As the source image is a PNG, I expected the quality filter to be ignored.

### Actual behaviour
However, since I have `AUTO_WEBP = true`, it appears to be using the `filters:quality(50)` to compress the image when it serves as webp.

Is this the expected behavior?

I've noticed `WEBP_QUALITY` in issues, but it seems to be undocumented. Is this only relevant when there is NO quality filter in the URL?

...or is there an analogous to go with that setting? e.g. `filters:quality(50):webp-qualty(80)`

**Comment by caeugusmao** [comment]
Hi @timkelty,

This is the part of code that handles the QUALITY:
```
        quality = self.context.request.quality
        if quality is None:
            if image_extension == '.webp' and self.context.config.WEBP_QUALITY is not None:
                quality = self.context.config.get('WEBP_QUALITY')
            else:
                quality = self.context.config.QUALITY
```

There is no webp-qualty filter. You can set standard value for WEBP_QUALITY specifically. If you do not set, Thumbor will consider QUALITY config if you do not pass quality as a filter in the image url.

**Comment by timkelty** [comment]
Thanks for the explanation, @caeugusmao.
I'll leave the issue open as `WEBP_QUALITY` is still undocumented.

**Comment by caeugusmao** [comment]
Would you like to contribute with this documentation?

**Comment by timkelty** [comment]
Yep - I'll put it on my list.

**Comment by timkelty** [comment]
Feel free to assign to me.

**Comment by caeugusmao** [comment]
tks
