### ISSUE TITLE
HTTPError: HTTP 405: Method Not Allowed

### ISSUE THREAD

**Issue by kishan-cc** [thumbor/thumbor#1165]
Traceback (most recent call last):
  File "/home/kishan.garodhara/.local/lib/python2.7/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/kishan.garodhara/.local/lib/python2.7/site-packages/tornado/web.py", line 229, in post
    raise HTTPError(405)
HTTPError: HTTP 405: Method Not Allowed

I am using curl method in postman to get the response it is showing this error

**Comment by kkopachev** [comment]
Can you share request you're making?

**Comment by kishan-cc** [comment]
sure @kkopachev     curl -i -H "Content-Type: image/jpeg" -H "Slug: photo.jpg" 
        -X POST http://localhost:8001/image --data-binary "@vows/crocodile.jpg"

**Comment by kkopachev** [comment]
I tried with thumbor version 6.6.1 and it works. 
What version are you running? what's your config looks like?

**Comment by kishan-cc** [comment]
@kkopachev  thank you and yes your are right problem with version
