### ISSUE TITLE
Banding on PNG images

### ISSUE THREAD

**Issue by xpicio** [thumbor/thumbor#1166]
Hello, we are working on PNG images with the following URL:

https://[my-domain]/DtXK2jc-I69jFJkLN7uEt_3QmxQ=/fit-in/375x/filters:fill(transparent):sharpen(1.0,1.0,true)/[my-domain]/z8dVCCXti5ss8vauXR4QIfHanEw=/trim/[my-domain]/vn5ugTXzFXr1uWII2V_zNeu1CKk=/375x/https://[my-domain]/catalog/shoeproduct/fall-winter-2018/main/2ADD208_F0_00001_side.png

on thumbor 6.1.0 and everything is working well, but after updating to thumbor 6.4.2 the same pipeline is not working any more. The actual link is working on 6.1.0 and is the desired behaviour.

The expected behaviour generated with 6.1.0:
<img width="1361" alt="thumbor-6 1 0" src="https://user-images.githubusercontent.com/2994719/52427119-a2ed5280-2aff-11e9-8487-eae13fdd7030.png">

So we did some test on 6.4.2 with the following results:

# Test 1 - resize then trim

### Thumbor request URL
https://[my-domain]/yD73um3faRB790IqAd63e65B920=/trim/[my-domain]/EYQb-DCYURMvUQspdze6pVq8yt8=/750x/https://[my-domain]/catalog/shoeproduct/fall-winter-2018/gallery/29100206_F0_00001_side.png

Generated image with 6.4.2:  
<img width="1361" alt="thumbor-6 4 2-resize-then-trim" src="https://user-images.githubusercontent.com/2994719/52425306-05dcea80-2afc-11e9-9399-3a40ca608506.png">

### Expected behaviour
Shadow below the shoes with a good quality

### Actual behaviour
Shadow below the shoes is corrupted. We had the same behaviour on browser with webp support and on a png image downloaded by wget client.

### Operating system
Debian stretch with python 2.7

# Test 2 - trim then resize

### Thumbor request URL
https://[my-domain]/7Gx1_v8o65OQL-ToRalnLrjcxzw=/750x/[my-domain]/-FKdkTMkksZeGe7zQLeQXhV3x1c=/trim/https://[my-domain]/catalog/shoeproduct/fall-winter-2018/gallery/29100206_F0_00001_side.png

Generated image with 6.4.2:  
<img width="1361" alt="thumbor-6 4 2-trim-then-resize" src="https://user-images.githubusercontent.com/2994719/52425535-800d6f00-2afc-11e9-82d6-55662da20b6b.png">

### Expected behaviour
Shadow below the shoes with a good quality

### Actual behaviour
Shadow below the shoes is corrupted. We had a different behaviour on browser with webp support and on a png image downloaded by wget client. The webp image is ok, but the png is corrupted.

### Operating system
Debian stretch with python 2.7

# Test 3 - trim

### Thumbor request URL
https://[my-domain]/-FKdkTMkksZeGe7zQLeQXhV3x1c=/trim/https://[my-domain]/catalog/shoeproduct/fall-winter-2018/gallery/29100206_F0_00001_side.png

### Expected behaviour
Shadow below the shoes with a good quality

### Actual behaviour
It is ok

### Operating system
Debian stretch with python 2.7

# Test 4 - resize

### Thumbor request URL
https://[my-domain]/xBCvZiT1FtEMufoBm9UbhzVp05w=/751x/https://[my-domain]/catalog/shoeproduct/fall-winter-2018/gallery/29100206_F0_00001_side.png

### Expected behaviour
Shadow below the shoes with a good quality

### Actual behaviour
It is ok

### Operating system
Debian stretch with python 2.7

**Comment by kkopachev** [comment]
Can you post original image so it's easier to repro?

**Comment by xpicio** [comment]
Here the original image:
![29100206_f0_00001_side](https://user-images.githubusercontent.com/2994719/52438561-d89f3500-2b19-11e9-90be-3fa7385ca122.png)

**Comment by kkopachev** [comment]
I didn't have a chance to reproduce the issue yet, however, I think this reported previously and fixed by https://github.com/thumbor/thumbor/pull/1046
Try setting `PILLOW_PRESERVE_INDEXED_MODE = False` and see if it helps.

**Comment by xpicio** [comment]
The fix about #1046 has been released on 6.4.2 ... and we tested with that version. Anyway we will try with `PILLOW_PRESERVE_INDEXED_MODE = False`

**Comment by xpicio** [comment]
PILLOW_PRESERVE_INDEXED_MODE doesn't change the behaviour. I see where this setting is used in code: 

``if self.context.config.PILLOW_PRESERVE_INDEXED_MODE and requested_extension in [None, '.png', '.gif'] 
                and self.original_mode in ['P', '1'] and self.original_mode != self.image.mode:``

My png are not in P mode but are in RGBA mode so this setting is irrelevant.

Any more ideas?

**Comment by kkopachev** [comment]
The image you posted is in P mode. 
```
root@7dca4824e339:/usr/src# python
Python 2.7.15 (default, Jan  9 2019, 04:45:50) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> Image.open('52438561-d89f3500-2b19-11e9-90be-3fa7385ca122.png')
<PIL.PngImagePlugin.PngImageFile image mode=P size=3000x3713 at 0x7F8B16360610>
>>> 
```

I'll try to repro the issue a bit later.

**Comment by kkopachev** [comment]
The image you posted is in P mode. 
```
root@7dca4824e339:/usr/src# python
Python 2.7.15 (default, Jan  9 2019, 04:45:50) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> Image.open('52438561-d89f3500-2b19-11e9-90be-3fa7385ca122.png')
<PIL.PngImagePlugin.PngImageFile image mode=P size=3000x3713 at 0x7F8B16360610>
>>> 
```

I'll try to repro the issue a bit later.

**Comment by kkopachev** [comment]
I've tried on 6.6.1.
I can see banding with default config.
However, `PILLOW_PRESERVE_INDEXED_MODE = False` solves the problem.

If you're still seeing the problem, maybe you're getting image from result storage or other cache?

**Comment by kkopachev** [comment]
Please reopen if problem persists.
