### ISSUE TITLE
How can I install thumbor on MacOS Mojave?

### ISSUE THREAD

**Issue by araujoyuri** [thumbor/thumbor#1169]
I'm trying to run thumbor on a MacOS Mojave 10.14.3 but I can't start it. I could install it using pip and I did generated the config file using thumbor-config > thumbor.conf and starting the process with thumbor -c thumbor.conf, but it wasn't finding the key, even when I change the SECURITY_KEY on the conf file.

**Comment by cristiandean** [comment]
Hello @araujoyuri, what error are you getting?

**Comment by araujoyuri** [comment]
@cristiandean RuntimeError: No security key was found for this instance of thumbor. Please provide one using the conf file or a security key file.

**Comment by cristiandean** [comment]
@araujoyuri Can you check if you're running Thumbor with python 2.7?

**Comment by achandnanimt** [comment]
Hi @cristiandean , I am getting the same error I am running Thumbor with python 3.7. 
Requesting you to please guide me for the same.

**Comment by araujoyuri** [comment]
@cristiandean sorry for taking so long to answer. I've tried to run with python 3.7 too

**Comment by cristiandean** [comment]
Thumbor supports only python 2.7. Can you try again with this version? @araujoyuri @achandnanimt

**Comment by araujoyuri** [comment]
I'll try it again sometime and I'll tell if it's working properly. Also, do you have plans to support python 3, since this year python loses it's official support?

**Comment by cristiandean** [comment]
@araujoyuri We are working to make it compatible ASAP. You can check the progress on [Refactor branch](https://github.com/thumbor/thumbor/tree/refactor).

**Comment by araujoyuri** [comment]
@cristiandean Awesome man! :D

**Comment by cristiandean** [comment]
As the problem seems to have been resolved, I will close the issue.
