### ISSUE TITLE
Data Migration issue

### ISSUE THREAD

**Issue by marblerun** [thumbor/thumbor#1176]
Folks

For some time, my company has run a thumbor based image server in AWS, which has worked very well. This year, we decided to update the setup to run behind an ALB, and took the opportunity to bring all the software components up to the latest versions. 

It transpired we had been running a very old version (4.10.1 or so) in a python virtual env, and made a big leap to 6.3.3, but kept the existing config. Testing has gone well, but we discovered that on our original instance, we were managing to cache a number of files that had long since been deleted from the original source, which of course were not available to the new servers. 

It's reasonably easy to snapshot a copy of the results_storage area and make it available to the new instances, but the question is, where should the data by copied to and which files ?

The original instance appears to store data in a directory structure based on the first four characters of the  28 character encoded signature, though my efforts to reproduce this signature given a file name failed.

e.g; 

_root@ip-172-30-0-225:/mnt/data/results_storage/v2# ls -l FF/Mi/FFMiLCKNn5CpegBqIhZ3XvdP0tM=/full-fit-in/924x552/files.******.com/image
total 96
-rw-r--r-- 1 ubuntu ubuntu 95715 Feb 19  2018 5fb1f81aadb157cfcdd3f039769675b7.jpg_

The new instances are using auto_webp as the top level results_storage area, and I'm attempting to work out where to put migrated data. Here the encoding appears to work, but now the directory structure and filenames are totally different.

The only option seems to be to run both results_storage directories side by side, but the old style seems very much more inefficient.

I would open to any suggestions.

Many thanks,

Mike

**Comment by cristiandean** [comment]
Are you trying to migrate to which version of thumbor? You said 6.3.3 but I can't find this version in the releases.

**Comment by marblerun** [comment]
Forgive me if I was less than clear.

The aim was to update the image processing environment, bringing both operating system (Ubuntu) and image processing software (Thumbor) to current releases. After creating a new AWS instance with a current version of Ubuntu  16.04.6 LTS, a snapshot copy of the existing data was brought over, and the virtual Thumbor environment was also updated to current, which was probably 6.7

My question related to how the new version of Thubor would find files created by version 4.10.1.

As it stands, we have created new instances running the old version of Thumbor behind an AWS ALB till we get a chance to resolve the issue.

Thanks

**Comment by cristiandean** [comment]
@marblerun you can check the storage rule here:

https://github.com/thumbor/thumbor/blob/master/thumbor/result_storages/file_storage.py
```
        digest = hashlib.sha1(unquote(path)).hexdigest()

        return "%s/%s/%s/%s/%s" % (
            self.context.config.RESULT_STORAGE_FILE_STORAGE_ROOT_PATH.rstrip('/'),
            'auto_webp' if self.is_auto_webp else 'default',
            digest[:2],
            digest[2:4],
            digest[4:]
```


As we can see, the path is formed by a sha1 generated from older path.

But on `get` method we have a migration from legacy path to new path, as we can see:

```

        if not exists(file_abspath):
            legacy_path = self.normalize_path_legacy(path)
            if isfile(legacy_path):
                logger.debug("[RESULT_STORAGE] migrating image from old location at %s" % legacy_path)
                self.ensure_dir(dirname(file_abspath))
                move(legacy_path, file_abspath)
            else:
                logger.debug("[RESULT_STORAGE] image not found at %s" % file_abspath)
                return callback(None)
```
