### ISSUE TITLE
Thumbor returns 502 error when requesting for not-existing S3 object

### ISSUE THREAD

**Issue by sviklim** [thumbor/thumbor#1178]
There is a Thumbor installation using S3 storage. If I send a request for an image, which doesn't exist in the bucket, then I receive 502 error, instead of 404 response, since the object (image) doesn't exist. 

### Thumbor request URL
wget http://my-thumbor-domain.com/unsafe/meta/game-stag/1374389543321/not-existed-url

### Expected behaviour
Returns 404 since the key does not exist

### Actual behaviour
Returns 502 Bad Gateway 

### Operating system
Ubuntu, Docker from python:2.7.15, Thumbor 6.6.0

**Comment by cristiandean** [comment]
As we can see [here](https://github.com/thumbor-community/aws/blob/f2a4a08c89682710bb614c2e8667b12965f34393/tc_aws/loaders/s3_loader.py#L96) the thumbor check if s3 HTTPStatusCode is 404 for return this status code, if it isn't 503 is delivered.

Can you check your s3 response and post here?

**Comment by sviklim** [comment]
Hi,

We have finally found out what caused this issue. It turns out, that you need to have `s3:ListBucket` permission for the user (role) which is used by Thumbor to connect to the storage. In our case the bucket was not exclusively dedicated for Thumbor therefore access rights were restricted based on object prefix. When a list permission for the whole S3 bucket was granted the server received proper 404 response, which was propagated to the client.

I believe this issue might be closed, since this case is more relevant to AWS configuration and integration rather than actual service code or behaviour. Maybe a special notice in the wiki will help others to avoid such setup in the future.
