### ISSUE TITLE
Correct content type when using webp version from cache storage

### ISSUE THREAD

**Issue by luison** [thumbor/thumbor#1180]
We are trying to fine tune the image type header when serving images from a proxy cache in nginx in front of thumbor.

When the image is served via thumbor proxy images are correctly set (if browser supports)
_content-type: image/webp_

When the image is served from the nginx proxy cache on the second call the image header is set to:
_content-type: image/jpeg_
alltough we have confirmed that the image after requesting:  .../900x500/image.jpg is the webp on the cache storage by a debug header on the response.

The way we implemented the proxy cache is following some guidance for nginx confs using a map to modify the path to thumbors cache storage so nginx can serve it locally:

        map $http_accept $webp_prefix {      
                default   "";                        
                "~*webp*"  "/webp";                   
        }

and then try_file $webp_prefix/...rest of path to storage
We also have the Vary Header setup.

But we believe the issue is related to nginx deciding that as the file name is .jpeg this is the autocontent type.  We are trying to clone de map above and use more_set_headers to force the correct content-type only if the browser supports it.

If we rename the cached file to .jpg.webp nginx does its job correctly. So the question is... any easy way to force thumbor to write webp images adding that extension within the webp storage cache? 

Any alternative solution? Should I worry at all about not having a correct content type if the browser is rendering correctly?

**Comment by cristiandean** [comment]
You can try something like this in your proxy cache:

```
proxy_cache_path /tmp/thumbor levels=1:2 keys_zone=thumbor_zone:10m inactive=60m;
proxy_cache_key "$request_uri$http_accept";

more_set_headers 'Vary: Origin, Accept';

server {
  listen 80;
  server_name _;

  location / {
    proxy_cache thumbor_zone;
    proxy_pass http://localhost:8080;
  }
}	
```

**Comment by luison** [comment]
Thanks but no difference. Return headers if filename ends in .jpg remains when we server de webp one.
```
cache-control: max-age=2592000
content-encoding: br
content-type: image/jpeg
date: Fri, 15 Mar 2019 10:48:42 GMT
debug-section: thumbor-results-cache: 
expires: Sun, 14 Apr 2019 10:48:42 GMT
last-modified: Fri, 15 Mar 2019 10:44:31 GMT
status: 200
vary: Accept-Encoding
vary: Origin, Accept
```
As said, either we force thumbor to save with an additional .webp extension so Nginx would auto setup or we find a way of doing it conditionally via nginx. Please note this is the output of our nginx serving thumbor storage cache.

**Comment by gingerlime** [comment]
I think I bumped into a similar problem before with the way caching is set-up. See #986
