### ISSUE TITLE
documentation not in sync

### ISSUE THREAD

**Issue by christophlingg** [thumbor/thumbor#1182]
I was interested to get more information about those configuration options: `MAX_WIDTH` and `MAX_HEIGHT`. There are two stories told:

> These define the box that the resulting image for thumbor must fit-in. This means that no image that thumbor generates will have a width larger than MAX_WIDTH or height larger than MAX_HEIGHT.
https://github.com/thumbor/thumbor/wiki/Configuration#max_width-and-max_height

and

> the max width of the resized image
> use 0 for no max width
> if the original image is larger than MAX_WIDTH x MAX_HEIGHT,
> it is proportionally resized to MAX_WIDTH x MAX_HEIGHT
> https://github.com/thumbor/thumbor/blob/master/thumbor/thumbor.conf#L21

I believe the wiki is more up to date than the config, but I am not sure. Could you please fix the docu?

**Comment by HectorNM** [comment]
Hi @christophlingg , thank you for noticing this!

I opened a PR to change update docs accordingly, which seems to be already merged. So I believe project members can already close this issue.

**Comment by christophlingg** [comment]
@HectorNM to my understanding it is not fixed, because `thumbor.conf` still talks about the "original" image but it is about the scaled image.
