### ISSUE TITLE
Incorrect Resizing of Image

### ISSUE THREAD

**Issue by abhisheksarka** [thumbor/thumbor#1185]
### Thumbor request URL
https://t.THUMBOR_SERVER.com/rlHzP7uLm2bYFinMuBKrBJnhQs8=/1365x768/filters:format(jpg):fill(transparent)/https://s3-us-west-2.amazonaws.com/images.verifymybiz.com/location_photos/photos/000/642/538/original/MMmpc7m2Qzap2VT

### Expected behaviour
Image width should be 1365 and height 768

### Actual behaviour
Image width is 768 and height is 1365

**Comment by kkopachev** [comment]
Works for me on latest version.

**Comment by cristiandean** [comment]
@abhisheksarka Which version of thumbor are you using?
