### ISSUE TITLE
Thumbor: images directory Access denied

### ISSUE THREAD

**Issue by abhisheksoni27** [thumbor/thumbor#1186]
Thumbor stores the images in `/var/www/thumbor/images`. However, I cannot access that folder as it gives me Persmission Denied.

We are planning to move all our images to S3 and hence need access to that folder.

Can you tell me how I can extract those images, or remove the access denied error?

**Comment by cristiandean** [comment]
Hello @abhisheksoni27, can you give more information? Where is your thumbor hosted? Do you have sudo rights?
