### ISSUE TITLE
Using security with a mobile app?

### ISSUE THREAD

**Issue by soren121** [thumbor/thumbor#1187]
I would like to use Thumbor with my iOS and Android apps, but the [security documentation](https://github.com/thumbor/thumbor/wiki/Security) has led to some confusion.

It seems to imply strongly that URL signing was designed for a traditional server-side website, where the server would know ahead of time which Thumbor parameters are used on the page that's served. But this isn't really the case with mobile clients, because the API server does not define the presentation of the images, so images that are requested from Thumbor may vary by OS and device.

**Is there an ideal way to implement some sort of security for Thumbor with mobile clients, where the dimensions are not known to my client API?** Right now, I only see two options here that involve using URL signing:

1. Include the signing key in the app source code and hope that no one extracts it from the binaries.
2. Offer a limited range of available sizes with pre-signed URLs to the client apps. This wouldn't allow client app developers the freedom to use Thumbor's other features though.

**Comment by cristiandean** [comment]
Thumbor has a multitude of libraries in many different languages. What you can do is an API that you send an unsafe URL and it returns a signed URL that you can use in your application. Then the whole security part, such as authorization and authentication, in the url generation would be on the side of your API.

**Comment by Tokenyet** [comment]
I believe this would be mentioned in docs! Can't believe all the open source about image proxy never mention this 😞 Just try a whole day to find the discussion 😩 

Whatever, thanks for the answer and the question.
