### ISSUE TITLE
Bad image quality

### ISSUE THREAD

**Issue by mariansedivy** [thumbor/thumbor#1188]
Hello,

we want to switch to Thumbor but we have some problems with some images that have low quality after using Thumbor. I have this special test image to demonstrate it. 
Original 125KB
![Original](https://cwcdn.sk/test/original_1.jpg)

### Thumbor request URL
http://localhost:8000/unsafe/1920x960/filters:quality(90)/https://cwcdn.sk/test/original_1.jpg

### Expected behaviour
This is converted with php ImageMagick (60% quality) size 124KB no artifacts
![ImageMagic](https://cwcdn.sk/test/php_60_imagemagick.jpg)

### Actual behaviour
You have to open each image to see real quality of it with all artifacts

All images are converted with docker apsl/thumbor:

100% quality size 151KB
![thumbor100](https://cwcdn.sk/test/thumbor_100_basic.jpg)
90% quality size 77KB
![thumbor99](https://cwcdn.sk/test/thumbor_90_basic.jpg)
100% quality graphicsmagick size 294KB
![thumbor99](https://cwcdn.sk/test/thumbor_100_graphicsmagick_engine.jpg)
90% quality graphicsmagick size 116KB
![thumbor99](https://cwcdn.sk/test/thumbor_90_graphicsmagick_engine.jpg)
### Operating system
OSx with docker image apsl/thumbor 

Can you please tell me if there is any way how to improve image quality?

**Comment by cristiandean** [comment]
Hello @mariansedivy, using the JPG format for this type of image can cause loss of quality. One of the factors that can cause this is the [Subsampling](https://en.wikipedia.org/wiki/Chroma_subsampling)  - "Subsampling is the practice of encoding images by implementing less resolution for chroma information than for luma information.".

You can set the Subsampling with:

```
PILLOW_JPEG_SUBSAMPLING=0
```

Another option is to use `filters:format(png)`.

**Comment by mariansedivy** [comment]
Hi @cristiandean thank you for your reply. Unfortunately this setting overrides quality filter and thus result in nice image but bigger than original. I have found this closed pull request where it is discussed https://github.com/thumbor/thumbor/pull/730

**Comment by mariansedivy** [comment]
Nobody has a solution, please?

**Comment by kkopachev** [comment]
@mariansedivy can you show code for php ImageMagick you used?

**Comment by mariansedivy** [comment]
Hello @kkopachev, thank you. I will look at it. I'm using php-imagick, but there is nothing special. I just load image, stripImage() to remove EXIF, setImageCompressionQuality(), setInterlaceScheme(Imagick::INTERLACE_PLANE), cropThumbnailImage() to resize it and then setImageFormat(JPEG). That's all.

**Comment by mariansedivy** [comment]
Hello, I was trying to set `PILLOW_JPEG_QTABLES`, but I get this error:

```
docker run -p 8000:8000 -e PILLOW_JPEG_QTABLES='keep' apsl/thumbor
Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/thumbor/server.py", line 121, in main
    config = get_config(server_parameters.config_path)
  File "/usr/local/lib/python2.7/site-packages/thumbor/server.py", line 42, in get_config
    return Config.load(config_path, conf_name='thumbor.conf', lookup_paths=lookup_paths)
  File "/usr/local/lib/python2.7/site-packages/derpconf/config.py", line 75, in load
    return cls.__load_from_path(conf, path)
  File "/usr/local/lib/python2.7/site-packages/derpconf/config.py", line 94, in __load_from_path
    six.exec_(code, module.__dict__)
  File "/usr/local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 67, in <module>
NameError: name 'keep' is not defined
```

**Comment by kkopachev** [comment]
Try setting it as ‘“keep”’

**Comment by mariansedivy** [comment]
This worked, but again, processed image is bigger than original. It ignores quality filter same as `PILLOW_JPEG_SUBSAMPLING=0`

**Comment by tinder-calvinliu** [comment]
Just ran into this problem. When loading the image from s3 (88kB) without any filters or transformations via thumbor, the fetched image size is larger than the original which doesn't seem to make sense (116kB)
