### ISSUE TITLE
Failing to process Facebook profile pictures 

### ISSUE THREAD

**Issue by marblerun** [thumbor/thumbor#1190]
When attempting to process facebook profile pics, it would appear that Thumbor behaves like the Chrome browser, which can't process the image, possibly due to a missing file type in the image header, and offers to download rather than display the file.

Instead, a hidden file is placed in the profilepic directory, and a mixture of errors results.

eg

2019-04-17 11:18:40 tornado.access:ERROR 500 GET /EUIiB4MyxL20Fu9HTKt_6LAK87M=/160x160/smart/https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10157080611364447&height=900&width=900&ext=1557184889&hash=AeQbx5mI4g-Val3w (127.0.0.1) 1.86ms
2019-04-17 11:18:40 thumbor:WARNING ERROR retrieving image https://lookaside.facebook.com/platform/profilepic/?asid=10210846110821782&height=900&width=900: HTTP 404: Not Found
2019-04-17 11:18:40 tornado.access:WARNING 404 GET /x0KIuxnaM7w7bvmgRfpb3Z7rBU4=/160x160/smart/https://lookaside.facebook.com/platform/profilepic/?asid=10210846110821782&height=900&width=900 (127.0.0.1) 113.09ms
2019-04-17 11:18:54 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/var/www/thumbor-env/local/lib/python2.7/site-packages/tornado/web.py", line 1320, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/var/www/thumbor-env/local/lib/python2.7/site-packages/tornado/web.py", line 1503, in wrapper
    result = method(self, *args, **kwargs)
  File "/var/www/thumbor-env/local/lib/python2.7/site-packages/thumbor/handlers/imaging.py", line 100, in get
    self.check_image(kw)
  File "/var/www/thumbor-env/local/lib/python2.7/site-packages/thumbor/handlers/imaging.py", line 96, in check_image
    return self.execute_image_operations()
  File "/var/www/thumbor-env/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 60, in execute_image_operations
    result = self.context.modules.result_storage.get()
  File "/var/www/thumbor-env/local/lib/python2.7/site-packages/thumbor/result_storages/file_storage.py", line 55, in get
    with open(file_abspath, 'r') as f:
IOError: [Errno 21] Is a directory: '/mnt/thumbor2/results_storage/v2/CS/NO/CSNOc_vDgeoEkCQQk7Lw48ptTWA=/160x160/smart/https://platform-lookaside.fbsbx.com/platform/profilepic/'

### Operating system
 Ubuntu 16.04.6 LTS, thumbor version 4.10.1, http_loader in use

As an unscientific test, chrome fails to display the image, and offers a download option, while Slack displays the image.

Is there a config option that can avoid this, or is this a known issue ?

Thanks

**Comment by cristiandean** [comment]
Is it possible for you to upgrade the thumbor? I tested it on the latest and it worked.

**Comment by marblerun** [comment]
Hi,

Sorry for the delay - we ran up an instance with 6.7 installed on it this week, we now get the "Malformed Url" error and a http 400 error rather than a 504.  Attempts at url encoding to deal with special characters have also failed.

I am currently accessing through nginx, which may be having an influence, so we are going to go through the config in detail to see if there is an issue we can spot.

One final point, in trying thumbor-url, I do not seem to be able to generate the same output that the application itself is doing. As a test, I'm choosing a successful file from the logs, displaying it in my browser, and then using the matching options to try and produce a matching result.

for instance

http://imagetest2.viewranger.com:9000/9Y69_WMy2Qjy8z-kgjC9yVS02Tw=/fit-in/0x80/https://files.viewranger.com/image/649442bb8b5a84a856e9b2378ead5022.jpeg will produce an image of the words "Wild Trails"

with the url taken from the nginx logs.

while

./thumbor-url  -n -e 80 -k "key removed" https://files.viewranger.com/image/649442bb8b5a84a856e9b2378ead5022.jpeg

produces the following
URL:
/OB6Sy1pj9U_IoMCEIetSotxcYSk=/fit-in/0x80/https%3A//files.viewranger.com/image/649442bb8b5a84a856e9b2378ead5022.jpeg
/OB6Sy1pj9U_IoMCEIetSotxcYSk=/fit-in/0x80/https%3A//files.viewranger.com/image/649442bb8b5a84a856e9b2378ead5022.jpeg

Which can be seen to not match, and fails in a browser. URL encoding also fails to work.

Any ideas where we might be going wrong ? All other images than FB seem to work fine.

Mike

**Comment by cristiandean** [comment]
I tried run:

`thumbor-url -n -e 80 -k "my-security-key-file" https://files.viewranger.com/image/649442bb8b5a84a856e9b2378ead5022.jpeg`

And I had as a return:

`/qS556ynY7s0P_O319uDhoDF2inU=/fit-in/0x80/https%3A//files.viewranger.com/image/649442bb8b5a84a856e9b2378ead5022.jpeg`

So I ran thumbor with the following command for startup the server:

`thumbor -l debug -d -c ./thumbor/thumbor.conf -k thumbor.key`
(The thumbor.key content was: **my-security-key-file**)

And finally I accessed:
`http://localhost:8888/qS556ynY7s0P_O319uDhoDF2inU=/fit-in/0x80/https%3A//files.viewranger.com/image/649442bb8b5a84a856e9b2378ead5022.jpeg`


Can you see something different you've done? Is the key correct?

**Comment by marblerun** [comment]
Hi Cristian,

I have managed to get this working using both the -k and -l options to generate the url, and then successfully load the file in question. Our issue appears to be specifically with facebook profile images, which thumbor, in the main, appears to be unable to encode properly.

Your help is much appreciated, going to have a bit of a break due to this being a holiday weekend. If you fancy a challenge, try getting one of the images presented here through Thumbor.

https://www.facebook.com/media/set/?set=a.373507249340&type=3

They claim to be Sample Facebook profile pictures, and so far I've had no luck.

Thanks again

Mike

**Comment by kkopachev** [comment]
Do you have url of an image?
