### ISSUE TITLE
When Thumbor hosted in subdirectory, getting WARNING URL does not have hash or unsafe, or has both

### ISSUE THREAD

**Issue by joncarlson** [thumbor/thumbor#1195]
### Thumbor request URL
GET http://localhost/images/image/HASH/image.png

The key part above being the /images subdirectory Thumbor is hosted in

### Expected behaviour
Thumbor loads the expected image

### Actual behaviour
No image is loaded, Thumbor throws the error:

thumbor:WARNING URL does not have hash or unsafe, or has both: /images

### Operating system
python:2-alpine3.6 Docker image
x86_64

### Your thumbor.conf

STORAGE=tc_aws.storages.s3_storage
STORAGE_EXPIRATION_SECONDS=86400
UPLOAD_ENABLED=True
UPLOAD_PHOTO_STORAGE=tc_aws.storages.s3_storage
SECURITY_KEY=1234567890
TC_AWS_ENDPOINT="'https://ENDPOINT_URL'"
TC_AWS_STORAGE_BUCKET=images
LOG_LEVEL=debug
AWS_ACCESS_KEY_ID=AccessKey
AWS_SECRET_ACCESS_KEY=SecretKey

**Comment by cristiandean** [comment]
By default the thumbor use base path (/) to handle with your urls. Is there any chance of you using thumbor in a subdomain? I think it would be best for this situation.

**Comment by kkopachev** [comment]
Or you could use nginx or other reverse proxy in front with url rewrite.

**Comment by joncarlson** [comment]
Thanks @cristiandean and @kkopachev. Can't use a subdomain unfortunately so I looked into handling this with nginx and it works great!

In case anyone else needs this, in my location block for Thumbor I added this chunk which grabs everything after /images and does a proxy_pass to the Thumbor upstream:

`
if ($request_uri ~* /images/(.*)){
    set $thumborpath /$1;
    proxy_pass http://thumbor$thumborpath;
}
`
