### ISSUE TITLE
HTTP loader still working when disabled.

### ISSUE THREAD

**Issue by icoum** [thumbor/thumbor#1199]
Hello !

First, thank you for your tool, i'm amazed by how well it works.

However, I do have a little problem. It may be a misunderstanding from my side.
I want to use file-loader, and disable http-loader.
Thus, I have set LOADER variable to 'thumbor.loaders.file_loader'.

### Expected behaviour
Requests with filesystem path should work. (Ex: like http://my-server/my/file.jpg)
Requests with http path shouldn't work. (like http://my-server/https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Coffee_berries_1.jpg/1200px-Coffee_berries_1.jpg)

### Actual behaviour
Requests with filesystem path are working.
Requests with http path are working too.

### Operating system
Raspbian

### Your thumbor.conf
LOADER = 'thumbor.loaders.file_loader'
RESULT_STORAGE = 'thumbor.result_storages.file_storage'
SECURITY_KEY = 'MY_KEY'
FILE_LOADER_ROOT_PATH = '/home/thumbor/source/'
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/home/thumbor/result'
RESULT_STORAGE_STORES_UNSAFE = True

Thanks in advance for your help,
Bye !

PS : I already tried flushing my "RESULT_STORAGE_FILE_STORAGE_ROOT_PATH" folder in case the image was still cached there and it doesn't fix the problem.

**Comment by cristiandean** [comment]
Hello @icoum, thanks =)?

I just tested Thumbor in the latest version (6.7.0) and everything seems to work fine. Using your configuration file I am not able to use http path. You could confirm me which version you are using and try to clean the `/home/thumbor/` directory again. 

Just one more question, how are you running thumbor?

**Comment by icoum** [comment]
Hi again,

I guess I'm using quite an unique way of running thumbor :
- I'm using a raspberry pi, with Raspbian 9 (Stretch) installed
- I couldn't make a docker way working, for architecture reasons (I'm not sure about the details, but my pi is running an arm architecture, which is not compatible with the available images)
- I couldn't make the `apt-get install` way working, since the thumbor deb packages are not available for Raspbian
- Thus, I used the `pip install thumbor` way. Then, I use "thumbor -c thumbor.conf" or a systemd service running that same command.

FYI, the installation with `pip install` wasn't that straightforward. I had to install a few libs manually (with `apt-get`) after the `pip install` crashed telling some dependency was missing. (libjpeg-dev and libopenjp2-7) as far as I remember.

I also have version 6.7.0 (`Thumbor v6.7.0 (17-Jan-2019)`).

I've just tried again to flush my result directory again, and it doesn't help. I'm pretty sure my issue is related to my way of running thumbor.
Good luck if you have the courage to investigate into my issue.

Good night!

**Comment by cristiandean** [comment]
You said you tried to flush your result storage. Have you done the same with FILE_LOADER_ROOT_PATH?

**Comment by icoum** [comment]
Yeah ! Got it thanks to you.

I found it awkward to flush FILE_LOADER_ROOT_PATH since this is where I get my images in the first place, but I tried still.
And then... thumbor still works completely well. I can still access my images from file loader or http loader, even though I have not a single image in my FILE_LOADER_ROOT_PATH.

Actually, I found out that all the images I had already accessed were cached in the FILE_STORAGE_ROOT_PATH folder (defaulted to `/tmp/thumbor/storage`).

Then, I flushed this folder (and filled my FILE_LOADER_ROOT_PATH with my images again), and everything works as expected : I can only access images from file loader and not from http loader.

Thanks for your help !

I still have a last question: what is the best practice about the STORAGE variable when using file_loader ?
In my case, I will always have all my images in the FILE_LOADER_ROOT_PATH, so I guess `STORAGE=‘thumbor.storages.no_storage’` could be a good idea for me, so as not to keep a useless exact copy of each image.
But in the docs, `no_storage` is described as "intended for debugging or benchmarking purposes". Is there a reason why I shouldn't use it in my case ?

Thanks again and bye !

**Comment by cristiandean** [comment]
@icoum I'm glad to have helped =)

I think for you it makes sense to use no_storage as your STORAGE. Just be aware that STORAGE can be used for other things, this is the case of `thumbor.storages.mixed_storage` that allows you to save the crypto key and detecting detection results from the original file.

If you believe that these things will not be necessary to you, feel free not to use them.

**Comment by icoum** [comment]
Thanks a lot, I'm closing the issue, bye !
