### ISSUE TITLE
README example does not work - expired image

### ISSUE THREAD

**Issue by eenchev** [thumbor/thumbor#1203]
### Thumbor request URL
http://<thumbor-server>/300x200/smart/s.glbimg.com/et/bb/f/original/2011/03/24/VN0JiwzmOw0b0lg.jpg

### Expected behaviour
Smart scale the image to 300x200 pixels size

### Actual behaviour
HTTP Response 400, as there is no image on that URL anymore

### Operating system
Irrelevant

### Your thumbor.conf
Irrelevant

**Comment by caeugusmao** [comment]
@eenchev The original image does not exist and you have to add "unsafe" in the url at least.

http://unsafe/300x200/smart/s.glbimg.com/et/bb/f/original/2011/03/24/VN0JiwzmOw0b0lg.jpg
