### ISSUE TITLE
gif image flashes

### ISSUE THREAD

**Issue by neekey** [thumbor/thumbor#1206]
### Thumbor request URL
The request url for the issue you are having, you can swap the host name with a fake

https://d1hjm9fqhagczz.cloudfront.net/workspace_template_thumbnails/08b27aa02a9a4d7d8157380f9b4dd732.gif

### Expected behaviour
Tell us what should happen

It should looks normal

### Actual behaviour
Tell us what happens instead

The gif image flashes

### Operating system

it's a lambda function

### Your thumbor.conf

I setup the service using https://github.com/awslabs/serverless-image-handler lol

### The original pic 

![1_4jmNhEhEK7UvPBZRkqDS_g](https://user-images.githubusercontent.com/499870/59744458-f6458d80-92b5-11e9-8733-be74661d362d.gif)

**Comment by kkopachev** [comment]
Serverless Image Handler  recently got an update and new version does not use Thumbor anymore, but uses SharpJS instead. 
If yours is still using Thumbor, you might to try to enable gifsicle engine.

**Comment by okor** [comment]
Closing since this doesn't appear to be relevant to Thumbor.
