### ISSUE TITLE
Failed to stop thumbor.service: Unit thumbor.service not loaded.

### ISSUE THREAD

**Issue by sbhatiya** [thumbor/thumbor#1211]
When I tried to start the thumbor service with command "sudo service thumbor start" getting this error and If run "sudo apt-get update" command getting this error(Err:11 http://ppa.launchpad.net/mutate/ppa/ubuntu bionic Release            
  404  Not Found [IP: - ]
Err:12 http://ppa.launchpad.net/thumbor/ppa/ubuntu bionic Release
  404  Not Found [IP: -]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/mutate/ppa/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/thumbor/ppa/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
) Please help...

**Comment by kkopachev** [comment]
You should install thumbor using pip or use [pre-built docker image ](https://github.com/MinimalCompact/thumbor)
Seem like ppa was not updated in a long time.

**Comment by okor** [comment]
Closing this as the issue seems have been solved. The solution being `install thumbor via pip or use a prebuilt docker image`
