### ISSUE TITLE
is it possible to do transparent gradient with thumbor

### ISSUE THREAD

**Issue by bagipriyank** [thumbor/thumbor#1213]
essentially what i want to be able to do is https://www.mediacollege.com/adobe/photoshop/transparent/gradient.html

i am wondering if this should be possible with watermark filter?

**Comment by kkopachev** [comment]
Should be possible. Did you try watermarking png with transparency over an image?

**Comment by bagipriyank** [comment]
I did, but it didn't produce expected result. alpha transparency doesn't seem to work the same way as it does in the tutorial above.

original:
![original](https://user-images.githubusercontent.com/3229967/63122036-afdd7980-bf5a-11e9-817a-d056c168818c.jpg)

image used for gradient alpha:
![gradient](https://user-images.githubusercontent.com/3229967/63122062-be2b9580-bf5a-11e9-99f5-61ce9b833ae9.png)

expected:
![expected](https://user-images.githubusercontent.com/3229967/63121908-6f7dfb80-bf5a-11e9-89b1-c9d1b061e566.jpg)

actual:
![actual](https://user-images.githubusercontent.com/3229967/63121916-73aa1900-bf5a-11e9-8ca3-c2af299db191.png)

So I am blurring the original image for the left part and applying the image used for gradient and resized original to create the actual image. what i am trying to get is the expected image. i've tried it with black on the right in the image used for gradient alpha. i've also tried with white instead of black with both on the left and on the right but i haven't been able to get the desired effect.
