### ISSUE TITLE
Watermark does not works with alpha property

### ISSUE THREAD

**Issue by hrhitesh** [thumbor/thumbor#1219]
### Thumbor request URL
https://upload.xxxxx.com/unsafe/300x300/filters:watermark(https://upload.xxxxx.com/unsafe/100x100/cat.jpeg,10p,20p,80,10,10)/cat.jpeg

### Expected behavior
It should return an image with 80% opacity of the watermark.

### Actual behaviour
It does not return image and giving error '400: Bad Request'

### Operating system
Ubuntu

### Your thumbor.conf
Your config file (WARNING: replace your SECURITY_KEY key with a dummy key or your key will become public)

**Comment by bagipriyank** [comment]
https://upload.xxxxx.com/unsafe/300x300/filters:watermark(https://upload.xxxxx.com/unsafe/100x100/cat.jpeg,10p,20p,80)/cat.jpeg should work. try that
