### ISSUE TITLE
How do i apply image filter to another uploaded image path?

### ISSUE THREAD

**Issue by hrhitesh** [thumbor/thumbor#1220]
Hi All,

I want to apply Thumbor image filter to another image which is stored in another server.
For example:
My Thumbor server URL is:
[My Thumbor](https://myupload.example.com)
And the image path, to which I want to apply the filter is
[My Exiting image](https://myimage.example.com/my.jpeg)

How do apply the Thumbor filter on this existing image?

Thanks

**Comment by cristiandean** [comment]
Just append image url using **http_loader**.

https://myupload.example.com/unsafe/200x200/filters:filterName(filterParams)/https://myimage.example.com/my.jpeg
