### ISSUE TITLE
thumborize.me is not working

### ISSUE THREAD

**Issue by BigFoppa** [thumbor/thumbor#1226]
Just wanted to explore what thumbor could do.

But it is not working. I can see you have old reports that are closed with same issues. 502 on load of the static images and 500 on analyze site.

/Big

**Comment by marcelometal** [comment]
Hi @BigFoppa , done! Thank you!

**Comment by adrianoresende** [comment]
Why this URL (https://br.ciandt.com/sites/br.ciandt.com/files/public/2019-05/Facebook_Linkedin%20(2).png) doesn't work? I tested with 4 images and it doesn't work.

**Comment by garchaaman19** [comment]
http://thumborize.me/ Is not working. It's showing error could not reach the site. 
Can anyone help?

**Comment by marcelometal** [comment]
@garchaaman19 thank you, I will fix it soon
