### ISSUE TITLE
Image is getting cropped accidentally. 

### ISSUE THREAD

**Issue by Manish-Muttreja-Bose** [thumbor/thumbor#1236]
### Thumbor request URL
(host removed) https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png image gets cropped when you select 100x100 or 1000x1000 sizes.

### Expected behaviour
Image should get resized properly

### Actual behaviour
Image gets cropped on sides
1000x1000 -> <img width="1015" alt="Screen Shot 2019-11-26 at 8 28 29 PM" src="https://user-images.githubusercontent.com/44621092/69685700-56bdcf80-108b-11ea-826e-1bf590cf2d09.png">

100x100
<img width="329" alt="Screen Shot 2019-11-26 at 8 29 36 PM" src="https://user-images.githubusercontent.com/44621092/69685747-7bb24280-108b-11ea-9994-91e878d3447c.png">

### Operating system
Doesn't matter

### Your thumbor.conf
Default conf with a  new security  key.

**Comment by cristiandean** [comment]
You can try using fit-in:

**full-fit-in**

http://thumbor.thumborize.me/unsafe/full-fit-in/100x100/https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

http://thumbor.thumborize.me/unsafe/full-fit-in/1000x1000/https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

or 

**adaptive-fit-in**

http://thumbor.thumborize.me/unsafe/fit-in/100x100/https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

http://thumbor.thumborize.me/unsafe/fit-in/1000x1000/https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

**Comment by Manish-Muttreja-Bose** [comment]
> You can try using fit-in:
> 
> **full-fit-in**
> 
> http://thumbor.thumborize.me/unsafe/full-fit-in/100x100/https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
> 
> http://thumbor.thumborize.me/unsafe/full-fit-in/1000x1000/https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
> 
> or
> 
> **adaptive-fit-in**
> 
> http://thumbor.thumborize.me/unsafe/fit-in/100x100/https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
> 
> http://thumbor.thumborize.me/unsafe/fit-in/1000x1000/https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

Thanks a lot, that works !
