### ISSUE TITLE
Add a fallback image for inexistent files

### ISSUE THREAD

**Issue by ediazcomellas** [thumbor/thumbor#1245]
### Expected behaviour
When a request is made for a non existent file, I want to show a generic image. This way I can have  a fallback for ecommerce sites that show a default image and not an error. This must be optional, as it is an specific use case.

**Comment by kkopachev** [comment]
I think you should use reverse proxy for that. 
With nginx would be something like
```
proxy_intercept_errors on;
error_page 404 = /my/default/image.png;
```

**Comment by ediazcomellas** [comment]
But in that way the default image is not resized or filtered as thumbor does.
I think that having this in thumbor makes it simpler (only one piece of software) and more consistent.

**Comment by ediazcomellas** [comment]
BTW, I already produced a pull request for this. 

pull request #1246
