### ISSUE TITLE
Thumbor + remotecv does not save result

### ISSUE THREAD

**Issue by jangrewe** [thumbor/thumbor#1252]
### Thumbor request URL
https://thumbor.example.com/unsafe/256x256/smart/assets.example.com/foobar.jpg

### Expected behaviour
Thumbor should save the result after complete detection by remotecv and then serve that.

### Actual behaviour
Thumbor queues the image for detection on every request, even after remotecv succesfully processed it (according to the Redis DB content and `debug` log output)

### Operating system
Debian, Docker

### Your thumbor.conf
```
ENGINE_THREADPOOL_SIZE = 16
METRICS = 'tc_prometheus.metrics.prometheus_metrics'
LOADER = 'thumbor.loaders.https_loader'
STORAGE = 'thumbor.storages.file_storage'
RESULT_STORAGE = 'thumbor.result_storages.file_storage'
HTTP_LOADER_CONNECT_TIMEOUT = 60
STORAGE_EXPIRATION_SECONDS = 2592000
FILE_STORAGE_ROOT_PATH = '/tmp/thumbor/storage'
DETECTORS = [
    'thumbor.detectors.queued_detector.queued_complete_detector'
]
FACE_DETECTOR_CASCADE_FILE = 'haarcascade_frontalface_alt.xml'
GLASSES_DETECTOR_CASCADE_FILE = 'haarcascade_eye_tree_eyeglasses.xml'
PROFILE_DETECTOR_CASCADE_FILE = 'haarcascade_profileface.xml'
OPTIMIZERS = [
  'thumbor.optimizers.jpegtran'
]
RESULT_STORAGE_EXPIRATION_SECONDS = 31536000
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/tmp/thumbor/result_storage'
RESULT_STORAGE_STORES_UNSAFE = True
REDIS_QUEUE_SERVER_HOST = '172.17.0.1'
REDIS_QUEUE_SERVER_PORT = 6379
REDIS_QUEUE_SERVER_DB = 7
```

The `/tmp/thumbor/*` paths are mounted to storage directories on the host.
I'm running the latest releases as of now, but added an `https_loader.py` for remotecv, and use this patched `redis_store.py`, as remotecv doesn't work otherwise: https://github.com/rodolfo3/remotecv/commit/be1a8ae303be2f44c40d3d564e47598748950ca1

**Comment by michaelurban** [comment]
I'm interested in testing Thumbor 7.x in production but this (and the tc-aws module) are blockers.
