### ISSUE TITLE
Increase Test Coverage

### ISSUE THREAD

**Issue by heynemann** [thumbor/thumbor#1256]
Many parts in our codebase are lacking tests.

This is a great opportunity to jump in and help thumbor without requiring in-depth knowledge about how thumbor works.

**Comment by kkopachev** [comment]
There should be code coverage map somewhere showing which code is not executed during test run.

**Comment by EdimarJunior** [comment]
Hi, can you guide me to which part of Thumbor is most critical regarding the lack of testing?
