### ISSUE TITLE
Cache the detector results

### ISSUE THREAD

**Issue by calind** [thumbor/thumbor#1258]
Is it possible to cache only the results of the detectors?

I’m asking this because I need to serve few different sizes of the same image and I’m under the impression that the detectors run for each size.

What I’m trying to achieve is a pipeline like this:
1. User uploads a photo
2. When upload is complete, I hit the metadata endpoint to prime the cache
3. Now, requests can come in for any thumbnail size, with detected features in cache

If this is not implemented would you consider a PR?

**Comment by heynemann** [comment]
Detectors are not cached based on different sizes. They are run in the original, so they are already cached independently of the size.
