### ISSUE TITLE
Could I use Thumbor as a standalone package in my own project

### ISSUE THREAD

**Issue by tony612** [thumbor/thumbor#1260]
Thumbor is a web server, but we want to use it in our own web applications to process images, like resizing, smart cropping. I know we can use pillow to process images, but we like Thumbor's smart cropping. But I didn't find there's an API doc for the public API to call functions of Thumbor.

Is there a way to do so?

**Comment by heynemann** [comment]
Hmmm I guess you could do it, but thumbor was never intended to be used like that. Do you think you can try with the master branch? Maybe easier and I'd be interested in how you fare with it. We maybe able to change a few things here and there and support this use case, but no promises.

**Comment by tony612** [comment]
I can try the master branch, but I didn't see stable public API docs for functions, so I'm afraid it's hard to use it in our production system. I'll be happy to see the support for this.

Thank you all the same.
