### ISSUE TITLE
Trying to launch thumbor with a unix socket ends with "No such device or address"

### ISSUE THREAD

**Issue by gael-ian** [thumbor/thumbor#1269]
Hi,

I'm trying to make thumbor listen to an Unix socket instead of port (and to automate this _via_ systemd but that's another story).

```shell
$ ls -al /run/thumbor/
total 0
drwxr-xr-x  2 root    root      60 Feb 23 15:51 .
drwxr-xr-x 27 root    root     880 Feb 23 15:18 ..
srw-rw-rw-  1 thumbor www-data   0 Feb 23 15:18 thumbor.sock

$ sudo -u thumbor /usr/local/bin/thumbor --fd /run/thumbor/thumbor.sock
Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thumbor/server.py", line 147, in main
    server = run_server(application, context)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/server.py", line 118, in run_server
    with open(context.server.fd, 'r') as sock:
IOError: [Errno 6] No such device or address: '/run/thumbor/thumbor.sock'
```

A simple `/usr/local/bin/thumbor --fd /run/thumbor/thumbor.sock` ends the same, so I don't think it's a permission problem.

### Expected behaviour

The `--fd` option is announced to accept either a file descriptor or a path but it seems paths are not handled correctly.

I tried to use a simple file instead of a socket and ended with a "Bad file descriptor" error so I suppose the file has to be a socket. The `/run/thumbor/thumbor.sock` in my example has been created by systemd so I bet it's a valid Unix socket that should be supported out of the box.

I can see [a similar problems have been reported in the past](https://github.com/thumbor/thumbor/issues/929) but I can't use the same workaround as I'm not using Supervisor and the file descriptor for my socket will neither be 0 nor be predictible.

Am I missing something?

**Comment by kkopachev** [comment]
Seems legit. I don't see a workaround.

**Comment by heynemann** [comment]
Released under 6.7.3.

**Comment by gael-ian** [comment]
Works like a charm!
Thank you

**Comment by gael-ian** [comment]
After some more tests, I noticed Tornado's `bind_unix_socket` first destroy the socket then recreate it prior starting to listen. This can be a problem for someone who wants to use a socket stored in a directory where thumbor's process owner can't write, such as `/run`.

People may also want to manage the socket independantly. This allow thumbor to be restarted and bound to the same socket, able to resume all requests that come while it was down. With Tornado recreating the socket on every launch, this is impossible.

[Here is an example of a system socket unit](https://github.com/gael-ian/ansible-config-webservers/blob/master/roles/vendors/thumbor/templates/systemd/thumbor.socket.j2) I had to wrote to get thumbor up and running. The service template is in the same directory).

@heynemann I can't reopen this issue. Should I open an new one?

**Comment by gael-ian** [comment]
Thank you for reopening this issue, @heynemann.

Another problem with Tornado's socket handling: recreate sockets have their permissions set to `0600`. This prevents running the Tornado service (here thumbor) as a dedicated user while still allowing the web server to write to the socket (i.e.: with a socket owned by 'thumbor:www-data`).

**Comment by heynemann** [comment]
Thank you very much for the in-depth exploration! We really appreciate the time you took to dive into this. Do you think it would be a good idea to open an issue with these findings in tornado?

**Comment by gael-ian** [comment]
The question is: do Tornado handle sockets this way by design?
In this case, then I'm not doing something the right way and certainly miss some documentation at some point (as I don't use nor run Python apps usually, this is more than a probability).

At least, we can ask them for precisions. Do you want me to create an issue on [tornadoweb/tornado](https://github.com/tornadoweb/tornado/issues)?

**Comment by heynemann** [comment]
I think that would be a good idea!

**Comment by kkopachev** [comment]
Does not look like there is an explanation on why remove and recreate, but this seems to be where it was all added to tornado https://github.com/tornadoweb/tornado/pull/295. I say open issue with them and see what they think.

**Comment by gael-ian** [comment]
I opened [an issue in tornadoweb/tornado](https://github.com/tornadoweb/tornado/issues/2823) to ask for more details but also discovered that [`bind_unix_socket`](https://github.com/tornadoweb/tornado/blob/master/tornado/netutil.py#L193) already accepts a `mode` parameter. The default value is `0o600` but do you think it can be changed via a command line option?

This way, even if Tornado keeps on rebuilding sockets on startup, with more open permissions  thumbor can be runned with a dedicated user instead of the same user as the frontend web server.

**Comment by gael-ian** [comment]
Got an answer from @ploxiln in [the tornadoweb/tornado issue](https://github.com/tornadoweb/tornado/issues/2823):

> Most programs unlink the unix socket path before use, because the listener has to create the unix socket, otherwise it doesn't work. If systemd were to create it before-hand, it would pass the already opened file descriptor, and tornado would have to use that, rather than re-binding the path.

So people can either:

* Start a Tornado app with a network socket and only mind about port collision
* Start a Tornado app with a path as Unix socket descriptor and let Tornado handle the whole socket life cycle in a writable directory
* Use `systemd` (or Supervisor or anything else) to handle the Unix socket life cycle and starts a Tornado app with a file descriptor

I put a shortened copy of my `systemd` units in [tornadoweb/tornado#2823](https://github.com/tornadoweb/tornado/issues/2823) for future reference but I still have one problem...

nginx is set according to [Tornado documentation](http://www.tornadoweb.org/en/stable/guide/running.html#running-behind-a-load-balancer) to acts as a reverse proxy to thumbor but every request ends with a 502 (Bad Gateway) error. In thumbor.service's journal, here's what I can see:

```
2020-03-13 12:26:29 tornado.application:ERROR Error in connection callback
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/tornado/tcpserver.py", line 294, in _handle_connection
     future = self.handle_stream(stream, address)
   File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 190, in handle_stream
     self.trusted_downstream)
   File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 249, in __init__
     self.remote_ip = address[0]
 IndexError: string index out of range
```

**Comment by gael-ian** [comment]
To try to summarize:

* `thumbor --ip 127.0.0.1 --port 12`: will bind thumbor to an AF_INET | AF_INET6 socket opened automatically by Tornado _via_ its `HTTPServer.bind()` method.
* `thumbor --fd /path/to/sock`: will let Tornado handle recreation of a AF_UNIX socket _via_ `bind_unix_socket` (in Tornado's netutils.py).
* `thumbor --fd N`: is [handled by thumbor in server.py](https://github.com/thumbor/thumbor/blob/master/thumbor/server.py#L107) _via_ `socket.fromfd`.

In my use case, the socket family passed to `socket.fromfd` should be AF_UNIX (as [answered by @bdarnell](https://github.com/tornadoweb/tornado/issues/2823#issuecomment-598742285)).

It seems when a socket is passed as a file descriptor it can only be an AF_UNIX socket, instead of AF_INET | AF_INET6. (AF_CAN and AF_RDS sockets are totally different beasts, not to be used in this case.) If that's right, then the fix is simple (and attached as a PR).

If not, then thumbor need a way to detect the right family to be passed to `socket.fromfd` from the file descriptor or maybe [call `socket()` with the file descriptor as last argument](https://docs.python.org/3.5/library/socket.html#socket.socket) so everything else will be ignored and the same socket will be returned (turned from an int to a proper socket object? that's what the documentation doesn't say)
