### ISSUE TITLE
pycurl should be in dependencies instead of dev-dependencies

### ISSUE THREAD

**Issue by tony612** [thumbor/thumbor#1270]
### Expected behaviour
When I install Thumbor from source with
```
poetry install --no-dev
```
I found pycurl is not install, but it seems it's required to run Thumbor

### Actual behaviour
pycurl should not in dev-dependencies

### Operating system
Ubuntu

**Comment by heynemann** [comment]
Can you test with release 7.0.0a2?

**Comment by heynemann** [comment]
Just installed in a brand new virtualenv and was able to use without pycurl (I added a warning saying that pycurl usage is advised, though).

**Comment by tony612** [comment]
OK. It works now.
