### ISSUE TITLE
Please document 7.0.0a1

### ISSUE THREAD

**Issue by mvhirsch** [thumbor/thumbor#1271]
Just a few hours ago, 7.0.0a1 was released - yeah :tada: 
But I couldn't find anything like a release note, or upgrade-plan. Neither any changelog. 

The only hint I've found so far is the "warning"-box on this page: https://thumbor.readthedocs.io/en/docs-modernize/
It's stating about python3 upgrade (awesome!) and linking to the release-notes (which do not document anything :disappointed: )

Please consider:

1. Updating [CHANGELOG](https://github.com/thumbor/thumbor/blob/master/CHANGELOG) - last updated 2 years ago(!)
2. Writing release-notes [7.0.0a1](https://github.com/thumbor/thumbor/releases/tag/7.0.0a1)
3. Consider writing an UPGRADE.md for users/administrators guiding them how to upgrade their thumbor installation. This is also useful for docker-images like [thumbor-docker](https://hub.docker.com/r/mvhirsch/thumbor)

**Comment by heynemann** [comment]
https://github.com/thumbor/thumbor/releases/tag/7.0.0a2

Maybe having an upgrade route is worth it. Will work on adding that to the docs after the release notes are done.

**Comment by heynemann** [comment]
Also the docs are up-to-date at https://thumbor.readthedocs.io/en/7.0.0a2/
