### ISSUE TITLE
Response body size in THUMBOR_LOG_FORMAT?

### ISSUE THREAD

**Issue by jimas14** [thumbor/thumbor#1274]
This appears to be the list of vars available for Thumbor's log formatting https://docs.python.org/3.1/library/logging.html#formatter-objects. I know this is through the logging package, but has anyone tried adding response body size to their logging? i.e. the size of the resize output in bytes

**Comment by kkopachev** [comment]
What's your use case? Might use metrics instead?

**Comment by jimas14** [comment]
Use case is this: We sometimes notice high CPU and slow response times for our service and 99% of the time it's caused by 1 or 2 large images whose resize load causes new requests to 504 while it's still working. To find these images we've gone into Cloudwatch insights and ran a query on the most common requests with latency > 5 seconds. It would be great if we could find the most common requests with response size above a certain megabyte.

We do use statsd to report response body size, among other things. It's available in datadog as `arc.thumbor.response.bytes.avg` -- I'm wondering if that could be injected somehow as a variable in the log formatter.

**Comment by jimas14** [comment]
@kkopachev

**Comment by kkopachev** [comment]
I saw your comment @jimas14. It makes sense now, however I don't have bandwidth to investigate further. 
One more thought:
If you have nginx in front of thumbor, you could possibly configure it to report time to response (it records response bytes count by default). Would that be sufficient?

**Comment by jimas14** [comment]
@kkopachev I appreciate your help. Can those nginx values be injected to the log format for the application? The goal here is to get response bytes included in the application log itself.

**Comment by kkopachev** [comment]
I am not quite sure, but looks like it's impossible in stock thumbor. 
access lo logging is done in tornado's [tornado.web.Application.log_request](http://www.tornadoweb.org/en/stable/web.html#tornado.web.Application.log_request). You can define your own Application instance and override the method, or in your instance pass log_function as keyword argument.

There was a way somewhere to run thumbor using your own application class.
