### ISSUE TITLE
[Feature] Add ability to run multiple processes

### ISSUE THREAD

**Issue by kkopachev** [thumbor/thumbor#1275]
There should be ability to configure how many processes of thumbor should be running on startup. 
This would replace external solutions like supervisor/circus to manage thumbor processes.
This is built-in feature of tornado.
We could argue that app is asynchronous and should be just fine handling multiple requests at the same time, however there is GIL and blocking io (see file_storage). I have doubts that optimizers are fully async too.
In any case, even with fully async app, it still uses 1 CPU. There is no reason to not let user decide how many processes should be running on start.

[Docs on how to pass this to tornado](https://www.tornadoweb.org/en/stable/tcpserver.html#tornado.tcpserver.TCPServer.start)

/cc @gingerlime

**Comment by heynemann** [comment]
I tried it with the performance tests and didn't seem to matter :(

**Comment by kkopachev** [comment]
Let's see if @gingerlime can run his test. I am skeptical that all image operations are truly async and it was confirmed by @gingerlime 's test.
I have code for this feature ready for PR, just wanted to try running the server manually before opening one.

**Comment by gingerlime** [comment]
Hey @kkopachev @heynemann. Happy to help, but not sure exactly how? The benchmark I ran on https://github.com/MinimalCompact/thumbor/issues/14 with multiple processes vs threads were only testing [a tiny subset of image operations](https://github.com/MinimalCompact/thumbor/blob/1d9d783661d2659ff416ef92ddc2b3d80aa8675e/benchmarks/locust/scripts/benchmark.py#L9-L16), but they can be extended to cover a more diverse case. 

Can you let me know which operations you think I should cover, and how to run those against the new thumbor 7a2 with multiprocess enabled?

On the benchmark, I compared different number of processes against (the then) threads, against docker processes against "native" process [see here](https://github.com/MinimalCompact/thumbor/blob/1d9d783661d2659ff416ef92ddc2b3d80aa8675e/benchmarks/locust/run_benchmark#L6-L10). I guess in this case, we'll replace the threads with thumbor internal processes, right?

**Comment by heynemann** [comment]
Oh, btw don't get me wrong. I'm not saying multiple processes won't speed up. That's how we ran thumbor at globo.com (24 thumbor processes per server). I'm saying that using server.start(0) didn't make any difference from server.start(1).

**Comment by kkopachev** [comment]
@gingerlime multiprocess replaces circus directly and compliments thread pool. 

I suggest you can run your benchmarks using `--processes` arg when installing thumbor from my branch. 
Here is a sample script to get it up and running. Adjust as needed.
```
apt-get update && apt-get install build-essential -y
mkdir -p /usr/src/app
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
source $HOME/.poetry/env
cd usr/src/app
git clone https://github.com/kkopachev/thumbor.git .
git checkout kk-multiprocess
poetry install  --no-dev
poetry run thumbor -l debug --processes=X
```

**Comment by kkopachev** [comment]
@heynemann how many CPUs per server?

**Comment by heynemann** [comment]
We used to do 2 proc per cpu at globo.com, but my test was 1 per cpu.

**Comment by gingerlime** [comment]
@kkopachev I'm trying to run those commands in the Dockerfile, but getting an error for a missing `$HOME/.poetry/env`

Here's the Dockerfile I'm trying to build

```
FROM python:3.8

LABEL maintainer="MinimalCompact"

VOLUME /data

ENV HOME /app
ENV SHELL bash
ENV WORKON_HOME /app
WORKDIR /app

RUN pip install envtpl

COPY conf/thumbor.conf.tpl /app/thumbor.conf.tpl

ARG SIMD_LEVEL

RUN PILLOW_VERSION=$(python -c 'import PIL; print(PIL.__version__)') ; \
    if [ "$SIMD_LEVEL" ]; then \
      pip uninstall -y pillow || true && \
      CC="cc -m$SIMD_LEVEL" pip install --no-cache-dir -U --force-reinstall --no-binary=:all: "pillow-SIMD<=${PILLOW_VERSION}.post99" \
      # --global-option="build_ext" --global-option="--debug" \
      --global-option="build_ext" --global-option="--enable-lcms" \
      --global-option="build_ext" --global-option="--enable-zlib" \
      --global-option="build_ext" --global-option="--enable-jpeg" \
      --global-option="build_ext" --global-option="--enable-tiff" ; \
    fi ;

RUN apt-get update && apt-get install build-essential -y && \
    mkdir -p /usr/src/app && \
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python && \
    source $HOME/.poetry/env && \
    cd usr/src/app && \
    git clone https://github.com/kkopachev/thumbor.git . && \
    git checkout kk-multiprocess && \
    poetry install  --no-dev

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]

# running thumbor multiprocess via circus by default
# to override and run thumbor solo, set THUMBOR_NUM_PROCESSES=1 or unset it
CMD ["poetry", "run", "thumbor", "-l debug", "--processes=$THUMBOR_NUM_PROCESSES"]

EXPOSE 80 8888
```

And here's the error on build:

```
...
Preparing to unpack .../build-essential_12.6_amd64.deb ...
Unpacking build-essential (12.6) ...
Setting up build-essential (12.6) ...
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile file located at:

$HOME/.profile

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.0.5
  - Downloading poetry-1.0.5-linux.tar.gz (23.37MB)

Poetry (1.0.5) is installed now. Great!

To get started you need Poetry's bin directory ($HOME/.poetry/bin) in your `PATH`
environment variable. Next time you log in this will be done
automatically.

To configure your current shell run `source $HOME/.poetry/env`

/bin/sh: 1: source: not found
The command '/bin/sh -c apt-get update && apt-get install build-essential -y &&     mkdir -p /usr/src/app &&     curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python &&     source $HOME/.poetry/env &&     cd usr/src/app &&     git clone https://github.com/kkopachev/thumbor.git . &&     git checkout kk-multiprocess &&     poetry install  --no-dev' returned a non-zero code: 127
```
```

**Comment by gingerlime** [comment]
Ok, I managed to fix/workaround this issue by tweaking a few things ... :) 

Pushed to https://github.com/MinimalCompact/thumbor/tree/thumbor-7a-multiproc

I'll try to get some benchmarks running and keep you posted.

**Comment by gingerlime** [comment]
Ok, got some very initial benchmark results. Basically it works similarly to docker processes, perhaps slightly better (slightly higher req/s compared to docker processes). Intuitively it makes sense, because I imagine the docker processes / load-balancing will have a bit more overhead than internal processes.

**Comment by gingerlime** [comment]
[benchmark_stats.zip](https://github.com/thumbor/thumbor/files/4301700/benchmark_stats.zip)
[benchmark.txt](https://github.com/thumbor/thumbor/files/4301701/benchmark.txt)
