### ISSUE TITLE
I want add in "Who's using it"!

### ISSUE THREAD

**Issue by netonevess** [thumbor/thumbor#1278]
I want add my website https://thumbor.readthedocs.io/en/latest/whos_using_it.html

Our logo: https://cdn.dreamcasa.com.br/assets/img/logo_dreamcasa2colors.gz.svg
website is: dreamcasa.com.br

We receive images with a long size, and for a long time resize it was hard, but when we meet thumbor, it was solved! 
Amazing tool.

Thank you guys! 
mail me suporte@dreamcasa.com.br

**Comment by heynemann** [comment]
Just do a PR adding yourself :)
