### ISSUE TITLE
Feature request - means of removing both image and result storage for a given URL 

### ISSUE THREAD

**Issue by cameronbraid** [thumbor/thumbor#1292]
Please provide an api endpoint that allows us to removed records from both image and result storage for a given URL

One idea could be to prefix the path with /delete, also using the safe url signing technique so that urls cant be forged 

https://thumbor.drivenow.com.au/rPeFOujNcyl1DBDRpyKRgIMznVw=/delete/trim/https://www.drivenow.com.au/webdata/images/supplier/vehicles/east-coast-car-rentals-au/suv-ffbv.jpg

**Comment by heynemann** [comment]
There's no easy way for thumbor to do that as it is highly dependent on what storage and result storage you're using. What we did do at globo.com was to have our own storage and result storage implementation and use the original as a prefix for all the resulting images. Then we created an API (outside thumbor) to delete said images.

Sorry but I'm closing this as it is not a responsibility of thumbor.
