### ISSUE TITLE
Improve fallback logic of `max_bytes` filter

### ISSUE THREAD

**Issue by timonweber** [thumbor/thumbor#1298]
### Thumbor request URL
http://localhost:8888/unsafe/filters:max_bytes(7500)/https%3A%2F%2Fgithub.com%2Fthumbor%2Fthumbor%2Fraw%2Fmaster%2Fexample.jpg

### Expected behaviour
When I try to cap the maximal file size with an unreasonable small number in the `max_bytes` filter, I expect Thumbor to return an image with the **smallest possible** file size (current `results`).

### Actual behaviour
Thumbor stops the downsizing process when the quality drops under `10` and returns the initial image (`initial_results`), which leads to an unexpected high file size.

https://github.com/thumbor/thumbor/blob/af7954b72c5585b0081e49fd4ae25036fae41806/thumbor/handlers/__init__.py#L595-L601

**Comment by macrozone** [comment]
@timonweber noticed the same thing! Did you find any workarounds?

**Comment by timonweber** [comment]
@macrozone Unfortunately not. I had to increase my `max_bytes` filter, but that makes it almost unusable.

**Comment by macrozone** [comment]
@timonweber i saw that you can combine both quality and max_bytes filters. So at leasts you can define a "max quality" with quality.

At least a workaround in some cases
