### ISSUE TITLE
Preserve IPTC metadata

### ISSUE THREAD

**Issue by MaxNet75** [thumbor/thumbor#1301]
### Thumbor request URL
http://ThumborDomain:8888/unsafe/600x0/https://OtherDomain/image.jpg

### Expected behaviour
When I configure thumbor very basically and just indicate this parameter "PRESERVE_EXIF_INFO = True", I should find the **CopyrightNotice** and **Creator** in the final image.
CopyrightNotice is IPTC metadata. Is there a solution to preserve this metadata ?

### Actual behaviour
Unfortunately this fields are not kept.

### Operating system
CentOS 7.6
Python 2.7.5
Thumbor 6.7.5 and 7.0.0a5

### Your thumbor.conf
```
# -*- coding: utf-8 -*-

from os.path import expanduser, join
home = expanduser("~")

# thumbor imaging service
# https://github.com/thumbor/thumbor/wiki

# Licensed under the MIT license:
# http://www.opensource.org/licenses/mit-license
# Copyright (c) 2011 globo.com thumbor@googlegroups.com

# the domains that can have their images resized
# use an empty list for allow all sources
ALLOWED_SOURCES = ['OtherDomain']

# the max width of the resized image
# use 0 for no max width
# if the original image is larger than MAX_WIDTH x MAX_HEIGHT,
# it is proportionally resized to MAX_WIDTH x MAX_HEIGHT
# MAX_WIDTH = 800

# the max height of the resized image
# use 0 for no max height
# if the original image is larger than MAX_WIDTH x MAX_HEIGHT,
# it is proportionally resized to MAX_WIDTH x MAX_HEIGHT
# MAX_HEIGHT = 600

# the quality of the generated image
# this option can vary widely between
# imaging engines and works only on jpeg images
#QUALITY = 85
#WEBP_QUALITY = 80

# Automatically converts images to WebP if Accepts header present
#AUTO_WEBP = False

# Automatically converts PNG to JPG if PNG has no transparency.
# WARNING: Depending on case, this is not a good deal. This
# transformation maybe causes distortions or the size of image can increase.
# Images with texts, for example, the result image maybe will be distorced.
# Dark images, for example, the size of result image maybe will be bigger.
# You have to evaluate the majority of your use cases to take a decision about this conf.
#AUTO_PNG_TO_JPG = False

# Specify the ratio between 1in and 1px for SVG images. This is only used when
# rasterizing SVG images having their size units in cm or inches.
# SVG_DPI = 150

# Preserves exif information in generated images. Increases image size in kbytes, use with caution.
PRESERVE_EXIF_INFO = True

# enable this options to specify client-side cache in seconds
MAX_AGE = 24 * 60 * 60

# client-side caching time for temporary images (using queued detectors or after detection errors)
MAX_AGE_TEMP_IMAGE = 0

# Sends If-Modified-Since & Last-Modified headers; requires support from result storage
SEND_IF_MODIFIED_LAST_MODIFIED_HEADERS = False

# the way images are to be loaded
LOADER = 'thumbor.loaders.http_loader'
#LOADER = 'thumbor.loaders.file_loader'

# the path to find images
#FILE_LOADER_ROOT_PATH = './tests/fixtures/images'

# maximum size of the source image in Kbytes.
# use 0 for no limit.
# this is a very important measure to disencourage very
# large source images.
# THIS ONLY WORKS WITH http_loader.
MAX_SOURCE_SIZE = 0

# if you set UPLOAD_ENABLED to True,
# a route /upload will be enabled for your thumbor process
# You can then do a put to this URL to store the photo
# using the specified Storage
UPLOAD_ENABLED = False
UPLOAD_PHOTO_STORAGE = 'thumbor.storages.file_storage'
UPLOAD_PUT_ALLOWED = False
UPLOAD_DELETE_ALLOWED = False
UPLOAD_DEFAULT_FILENAME = 'image'

# how to store the loaded images so we don't have to load
# them again with the loader
#STORAGE = 'thumbor.storages.redis_storage'
# STORAGE = 'thumbor.storages.no_storage'
STORAGE = 'thumbor.storages.file_storage'
#STORAGE = 'thumbor.storages.mixed_storage'
#STORAGE = 'thumbor.storages.memcache_storage'

# root path of the file storage
FILE_STORAGE_ROOT_PATH = join(home, 'thumbor', 'storage' )

# If you want to cache results, use this options to specify how to cache it
# Set Expiration seconds to ZERO if you want them not to expire.
RESULT_STORAGE = 'thumbor.result_storages.file_storage'
RESULT_STORAGE_EXPIRATION_SECONDS = 60 * 60 * 24  # one day
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = join(home, 'thumbor', 'result_storage')

RESULT_STORAGE_STORES_UNSAFE = False

# stores the crypto key in each image in the storage
# this is VERY useful to allow changing the security key
STORES_CRYPTO_KEY_FOR_EACH_IMAGE = True

#MEMCACHE_STORAGE_SERVERS = ['localhost:11211']

# imaging engine to use to process images

ENGINE = 'thumbor.engines.pil'

# if you need to use the OpenCV engine please refer
# to https://github.com/thumbor/opencv-engine
#ENGINE = 'opencv_engine'

# if you need to use the GraphicsMagick engine please refer
# to https://github.com/thumbor/graphicsmagick-engine
#ENGINE = 'graphicsmagick_engine'


# The graphics engine (and any optimizers) will block the IOLoop.  If you want
# to increase the number of concurrent requests Thumbor can handle, increase
# ENGINE_THREADPOOLSIZE to use a thread pool.  Benchmarks indicate 1xnumber of
# cpus - 2x number of cpus gives the best results, but do some benchmarks with
# your workload.
#ENGINE_THREADPOOL_SIZE = 0

# detectors to use to find Focal Points in the image
# more about detectors can be found in thumbor's docs
# at https://github.com/thumbor/thumbor/wiki
DETECTORS = [
    #'thumbor.detectors.face_detector',
    #'thumbor.detectors.profile_detector',
    #'thumbor.detectors.glasses_detector',
    #'thumbor.detectors.feature_detector',
]

# Redis parameters for queued detectors
# REDIS_QUEUE_SERVER_HOST = 'localhost'
# REDIS_QUEUE_SERVER_PORT = 6379
# REDIS_QUEUE_SERVER_DB = 0
# REDIS_QUEUE_SERVER_PASSWORD = None

# AWS SQS parameters for queued detectors
# SQS_QUEUE_KEY_ID = ''
# SQS_QUEUE_KEY_SECRET = ''
# SQS_QUEUE_REGION = 'us-east-1'

# if you use face detection this is the file that
# OpenCV will use to find faces. The default should be
# fine, so change this at your own peril.
# if you set a relative path it will be relative to
# the thumbor/detectors/face_detector folder
#FACE_DETECTOR_CASCADE_FILE = 'haarcascade_frontalface_alt.xml'

# this is the security key used to encrypt/decrypt urls.
# make sure this is unique and not well-known
# This can be any string of up to 16 characters
SECURITY_KEY = "MY_SECURE_KEY"

# if you enable this, the unencryted URL will be available
# to users.
# IT IS VERY ADVISED TO SET THIS TO False TO STOP OVERLOADING
# OF THE SERVER FROM MALICIOUS USERS
ALLOW_UNSAFE_URL = True

# Mixed storage classes. Change them to the fullname of the
# storage you desire for each operation.
#MIXED_STORAGE_FILE_STORAGE = 'thumbor.storages.file_storage'
#MIXED_STORAGE_CRYPTO_STORAGE = 'thumbor.storages.no_storage'
#MIXED_STORAGE_DETECTOR_STORAGE = 'thumbor.storages.no_storage'


# This configuration indicates whether thumbor should use a
# custom error handler.
# Defaults to: False
#USE_CUSTOM_ERROR_HANDLING=False
#ERROR_HANDLER_MODULE='thumbor.error_handlers.sentry'
#SENTRY_DSN_URL=''
#SENTRY_ENVIRONMENT=None

#FILTERS = [
    #'thumbor.filters.brightness',
    #'thumbor.filters.colorize',
    #'thumbor.filters.contrast',
    #'thumbor.filters.rgb',
    #'thumbor.filters.round_corner',
    #'thumbor.filters.quality',
    #'thumbor.filters.noise',
    #'thumbor.filters.watermark',
    #'thumbor.filters.equalize',
    #'thumbor.filters.fill',
    #'thumbor.filters.saturation',
    #'thumbor.filters.sharpen',
    #'thumbor.filters.strip_exif',
    #'thumbor.filters.strip_icc',
    #'thumbor.filters.frame',
    #'thumbor.filters.grayscale',
    #'thumbor.filters.rotate',
    #'thumbor.filters.format',
    #'thumbor.filters.max_bytes',
    #'thumbor.filters.no_upscale',

    ## can only be applied if there are already points for the image being served
    ## this means that either you are using the local face detector or the image
    ## has already went through remote detection
    ## 'thumbor.filters.redeye',
#]

#OPTIMIZERS = [
    #'thumbor.optimizers.jpegtran',
    #'thumbor.optimizers.gifv',
#]

#JPEGTRAN_PATH = '/usr/bin/jpegtran'

# If the CurlAsyncHTTPClient should be used
# Defaults to: False
#HTTP_LOADER_CURL_ASYNC_HTTP_CLIENT = False

# If the CurlAsyncHTTPClient is being used and
# should timeout on slow download speed.
# SPEED in bytes/s and TIME in s
# Dfaults to: 0 (no timeout)
#HTTP_LOADER_CURL_LOW_SPEED_TIME = 0
#HTTP_LOADER_CURL_LOW_SPEED_LIMIT = 0
```

**Comment by kkopachev** [comment]
I think we might need an image to replicate.
Is metadata really in exif or it's in XMP data?

**Comment by MaxNet75** [comment]
Thanks for your answer @kkopachev.
Since my post i understood that Fields I need are not part of exif metadata but IPTC. So do you know if it's possible to preserve IPTC metadatas ?
Copyright is exif metadata and CopyrightNotice is IPTC metadata.

**Comment by jimas14** [comment]
Is https://github.com/thumbor/thumbor/pull/661 a solution to this issue?

**Comment by larrytsai1026** [comment]
interested in this as well. Is there a solution for preserving IPTC metadata?

**Comment by jimas14** [comment]
@kkopachev Here is an example image with IPTC data filled out https://getpmd.iptc.org/getpmd/html/stds/ipmd/?imgurl=https://www.iptc.org/std-dev/photometadata/examples/google-licensable/images/IPTC-GoogleImgSrcPmd_testimg01.jpg. Here's the same image sent through Thumbor with no metadata at all. https://getpmd.iptc.org/getpmd/html/stds/ipmd/?imgurl=http://thumbor.thumborize.me/unsafe/https://www.iptc.org/std-dev/photometadata/examples/google-licensable/images/IPTC-GoogleImgSrcPmd_testimg01.jpg. The `PRESERVE_EXIF_INFO` option only pertains to the few fields in that third section, but the data this issue is asking to preserve is the IPTC section.

https://github.com/thumbor/thumbor/pull/661 appears to resolve this halfway by exposing IPTC metadata to the engine, but it didn't create a config or filter to expose this metadata to output images.

@sbaechler references a filter he created https://github.com/sbaechler/thumbor-universalimages, but as far as I can tell this is only related to responsive metadata, not necessarily IPTC retention.

**Comment by kkopachev** [comment]
@jimas14 This is not possible now with default Pillow engine, as Pillow itself does not have a way to save IPTC/XMP data.

**Comment by larrytsai1026** [comment]
@kkopachev Thanks for the update. Not sure if you're the right person to be informed of this, but just an FYI: this will be an issue if you have any France based users that uses Thumbor to resize images that is then served to the public on the web. There is a law that was passed that requires the IPTC to be displayed and unmodified. 

Link to law: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000038835832/2019-10-24%20%5blegifrance.gouv.fr%5d

**Comment by scorphus** [comment]
You can try and use [thumbor-wand-engine](https://github.com/scorphus/thumbor-wand-engine), which is a new engine built on top of ImageMagick with support to IPTC/XMP data.

**Comment by jimas14** [comment]
@scorphus Thanks so much, I had no idea that existed! I'm working on getting that wrapped in a dockerfile now. I see the thumbor version linked in your repo is 6.7.5, but isn't 7.0 the first version supporting python 3+?

**Comment by scorphus** [comment]
I'm glad that's helpful, @jimas14. That engine does not require a specific version of Thumbor. As long as you manage to have Thumbor installed and running on Python 3, you should be good. In any case, don't hesitate to open an issue on that repo.

**Comment by jimas14** [comment]
@scorphus Do you have an example dockerfile/container for your engine using thumbor < 7? I'm hitting runtime issues when trying 6.7.5 and [this thread](https://github.com/thumbor/thumbor/issues/998#issuecomment-647618264) sounds like the only fix is using thumbor 7 if py3 is desired

**Comment by scorphus** [comment]
@jimas14, sorry for the delay.

You could try https://github.com/MinimalCompact/thumbor. If you still have issues, you're more than welcome to join the discussion on scorphus/thumbor-wand-engine#7 :slightly_smiling_face:

**Comment by jimas14** [comment]
@scorphus It took us a while, but we finally got a working implementation. It is indeed true that py3 is **required** to run Thumbor 7.0+. Our Dockerfile pulled from the latest python:3.6 image, installed imagemagick and wand-engine, and runs Thumbor.

**Comment by gdegoulet** [comment]
IPTC tags preservation is very important for european laws compliance

If you want to stay on Pil Engine, you can try https://github.com/gdegoulet/thumbor-piliptc-engine
I write my own JpegIPTC package (based on iptcinfo3 and modified for thumbor usage) and a patched version of Pil Engine.
I have hooked the "create_image" and the "read" function from original Pil Engine to fetch IPTC data from original image and inject on the legacy result.
You can try it with docker : https://hub.docker.com/repository/docker/gdegoulet/thumbor_piliptc_engine/general

If you accept to add a new requirement to thumbor (https://github.com/gdegoulet/JpegIPTC) , i can prepare a Pypip package for JpegIPTC and a Pull request here.

**Comment by jimas14** [comment]
Just commenting to reaffirm the urgency that images served in EU need to be metadata compliant, so using Thumbor for editorial purposes there is a risk.
