### ISSUE TITLE
Thumbor for Wordpress

### ISSUE THREAD

**Issue by mateusnds** [thumbor/thumbor#1302]
I am looking to use Thumbor in wordpress. Is this currently possible?

Thanks

**Comment by rmens** [comment]
Yes. You can rewrite the URL's to images in your theme to go trough Thumbor.

**Comment by markoheijnen** [comment]
Did started years ago with a plugin for it at https://github.com/CodeKitchenBV/Thumbor. Still would need a setting page for a wider usage of it.
