### ISSUE TITLE
Poor detection of faces with face mask

### ISSUE THREAD

**Issue by rmens** [thumbor/thumbor#1305]
In the "post-corona world" there are a lot of pictures of people with face masks. However Thumbor seems to have a hard time detecting faces with a mask.

Is there any way the algorithm can be tweaked to accommodate for this?

My latest example [can be found here](https://img.autovisie.nl/images/20Xw0qlnALq5RqE1KCmyMhj2gF0=/860x303/smart/filters:format(jpeg):quality(80)/https%3A%2F%2Fwww.autovisie.nl%2Fwp-content%2Fuploads%2F2020%2F07%2FMax-Verstappen-2020.jpg
).

**Comment by kkopachev** [comment]
Quick googling and found https://github.com/mk-gurucharan/Face-Mask-Detection 
You can try using their haar cascade in place of thumbor default one and see if it works.
You can specify which cascade file to use using config variable `FACE_DETECTOR_CASCADE_FILE`
