### ISSUE TITLE
How to use Thumbor 7.0.0a5 with AWS Lambda & Serverless?

### ISSUE THREAD

**Issue by haggcoder** [thumbor/thumbor#1306]

**Comment by heynemann** [comment]
That's a good question, I don't have a lot of expertise with Lambda :) Maybe someone else can help with this.

**Comment by paurullan** [comment]
I have been studying the possibility for a while but with the recent incorporation of the container image possibility I think we can make it work.
https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/

The important new step is that now should be easy to load a full Debian with opencv and other image processing bits - which was very hard with the only .zip code upload.

**Comment by gabn88** [comment]
@haggcoder @paurullan If you find a good tutorial on how to do this I would be happy to test this as a hobby project for myself. It looks like a super nice solution.

**Comment by pfcodes** [comment]
Bump
