### ISSUE TITLE
thumbor's filter proportion can not work? 

### ISSUE THREAD

**Issue by oucystong** [thumbor/thumbor#1308]
### Thumbor request URL
http://localhost:8000/unsafe/filters:proportion(0.5)/http://horan.cc/wp-content/uploads/2013/03/googleinfrastructure_r.jpg

### Expected behaviour
should proportion 50 percent

### Actual behaviour
can not work and it would be nothing changed

### Operating system
OSx, Ubuntu, etc

### Your thumbor.conf
Your config file (WARNING: replace your SECURITY_KEY key with a dummy key or your key will become public)

**Comment by oucystong** [comment]
attention: I have used the docker images apsl/thumbor， it can be find in hub.docker.com

**Comment by bagipriyank** [comment]
can you check if the proportion filter is enabled?

**Comment by oucystong** [comment]
others's filter is ok! only this can not work

**Comment by bagipriyank** [comment]
looking at https://github.com/APSL/docker-thumbor/blob/master/thumbor/conf/thumbor.conf.tpl#L540 i don't see proportion. you will have to add proportion to this list for it to work.

**Comment by oucystong** [comment]
thanks! I try it!

**Comment by oucystong** [comment]
modify the thumbor.conf and thumbor.conf.tpl,add the proportion,and it still not work

**Comment by oucystong** [comment]
got it! my docker images apsl/thumbor used the thumbor'version is 6.3.0 release.
![image](https://user-images.githubusercontent.com/54384675/89347536-912d4100-d6dd-11ea-94f8-9899076f3f93.png)
But proportion feature is add in [6.6.0 release](https://github.com/thumbor/thumbor/pull/1113),so i can't use this feature! have to update docker image!
