### ISSUE TITLE
I want to add header referer to the image download request params, how can I change the conf file? Or, which part of the code can I modify for my own use?

### ISSUE THREAD

**Issue by lapuadson** [thumbor/thumbor#1309]
### Thumbor request URL
The request url for the issue you are having, you can swap the host name with a fake

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Operating system
OSx, Ubuntu, etc

### Your thumbor.conf
Your config file (WARNING: replace your SECURITY_KEY key with a dummy key or your key will become public)

**Comment by heynemann** [comment]
I didn't quite understand what happened. Can you help here?
