### ISSUE TITLE
Is it possible to stick thumbor to one web server using http loader?

### ISSUE THREAD

**Issue by Oglan** [thumbor/thumbor#1311]
I would like to send requests with relative path (like for filesystem loader) but all images should be taken using http loader from one specific server. Is it possible?

For instance, let's assume that we have all images stored on the https://my-image-store.com, we have some cool image https://my-image-sotre.com/path-to-image/cool-image.jpg, we have thumbor running on https://my-thumbor-server.com.
If I want to resize cool-image.jpg normally I should send request to the following url:
`https://my-thumbor-server.com/unsafe/300x200/https://my-image-sotre.com/path-to-image/cool-image.jpg`.
What I want to do is to use relative path for the image:
`https://my-thumbor-server.com/unsafe/300x200/path-to-image/cool-image.jpg`.

**Comment by kkopachev** [comment]
There is no way to do this with existing loaders.
However, you can make your own loader pretty easy. Take a look at [https_loader.py](https://github.com/thumbor/thumbor/blob/branch-6.x/thumbor/loaders/https_loader.py) - you would need to supply your own `_normalize_url` function to prepend host.

**Comment by heynemann** [comment]
Hey Oglan, did you manage to get it working? Closing this. If you still need help, please reopen this issue.
