### ISSUE TITLE
Support Legacy Extensions as well as new

### ISSUE THREAD

**Issue by heynemann** [thumbor/thumbor#1313]
For storages, loaders, detectors and filters, thumbor now requires an async function.
I believe we can have a helper that knows how to invoke both sync and async functions. That way we would dramatically decrease the barrier for people upgrading to thumbor 7.

**Comment by amanagr** [comment]
We at @zulip are trying to upgrade thumbor to v7 but are stuck at upgrading tc_aws extension. We tried upgrading tc_aws from python2 to 3 ourselves, but the inevitable syntax change of thumbor from `@return_future` to `async` syntax has caused `tornado_botocore` (one of the dependencies used by tc_aws) to be incompatible with tc_aws with `async` syntax. We would greatly appreciate you guys making tc_aws compatible with thumbor's python3 version.

**Comment by heynemann** [comment]
Just a heads up that python offers a function for deciding if a method is awaitable `inspect.isawaitable` (https://stackoverflow.com/questions/36076619/test-if-function-or-method-is-normal-or-asynchronous)

**Comment by heynemann** [comment]
Working on this on the feat/compatibility branch. Already have loaders working. Going to start working on storage and result_storage next.

**Comment by heynemann** [comment]
@kkopachev if you want to check it out :)
