### ISSUE TITLE
Saving result storage to Digital Ocean Spaces

### ISSUE THREAD

**Issue by highoncarbs** [thumbor/thumbor#1316]
So thumbor is setup and running with digital ocean droplet and spaces , it has access to view files in my bucket , but it's storing the result on my droplet instead of my bucket.

### Expected behaviour
I want to save the file in my bucket rather than my droplet

### Actual behaviour
A `storage` file is created in my thumbor dir

### Operating system
 Ubuntu 18.04

### Your thumbor.conf

```RESULT_STORAGE = 'thumbor_spaces.result_storages.spaces_storage'
LOADER = 'thumbor_spaces.loaders.spaces_loader'

SPACES_REGION='ams3'

SPACES_ENDPOINT='ams3'

SPACES_KEY='***'

SPACES_SECRET='***'

SPACES_BUCKET='saas-space' #name of spaces instance

SPACES_ACL='public'

SPACES_RESULT_FOLDER='result_storage'

SPACES_LOADER_FOLDER='panya' # name of folder in my bucket
```

Used thumbor-spaces plugin , rest config is the default one.

Sorry if this is a very noob question , this is the first time i'm handling any CDN and s3 stuff , so very confusing for me.
Help is much appreciated

**Comment by jannejava** [comment]
Thumbor cannot write directly to a S3 bucket. Have a look on this extension, DO Spaces is compatible with S3. So it should work. 

 https://github.com/thumbor-community/aws

**Comment by highoncarbs** [comment]
Thanks , I'll give it a try . I am currently using thumbor-spaces plugin , which is able to get data from the bucket but not put into it

**Comment by highoncarbs** [comment]
Works great , although I have a question . Would you recommend saving the result storage on S3 or local server filesystem , there is a considerable lag when fetching images from result storage in S3 .

**Comment by jannejava** [comment]
I see the result as a cache and save the result locally for sure, much faster. Just keep the originals on S3.
