### ISSUE TITLE
Thumbor remove EXIF data , images displayed rotated

### ISSUE THREAD

**Issue by eliavmaman** [thumbor/thumbor#1319]
I'm applying thumbor filters on s3 stored images.
Original : https://d37aahii0nv5jf.cloudfront.net/filters:strip_exif()/0Zoxha2t9S1HR4oYGmSa/IMG_9292.JPG
filter url file : https://d37aahii0nv5jf.cloudfront.net/fit-in/1000x0/filters:strip_exif()/0Zoxha2t9S1HR4oYGmSa/IMG_9292.JPG

image displayed rotated on our website.
Original:
![image](https://user-images.githubusercontent.com/6911449/95635599-81432c00-0a95-11eb-8772-0e105e993478.png)
on Website:
![image](https://user-images.githubusercontent.com/6911449/95635627-96b85600-0a95-11eb-92c5-3e903337b879.png)
What should i do?
@heynemann , @guilhermef  Can u please help me?

**Comment by kkopachev** [comment]
Link to original is already rotated and already missing exif even if I remove filters. So can't reproduce.

But you could try setting `RESPECT_ORIENTATION = True` in config.

**Comment by eliavmaman** [comment]
@kkopachev i did it in the environment variable , it didn't helped.

![image](https://user-images.githubusercontent.com/6911449/95639602-bb1a2f80-0aa1-11eb-8908-9ba6d504c682.png)

**Comment by kkopachev** [comment]
@eliavmaman Could you share original image?
