### ISSUE TITLE
Fit-in filter not working in Production , but working on local machine. 

### ISSUE THREAD

**Issue by highoncarbs** [thumbor/thumbor#1330]
### Thumbor request URL
http://cdn.jaitexart.org/unsafe/fit-in/400x600/filters:quality(80):format(webp):fill(white,1)/https://saas-space.ams3.cdn.digitaloceanspaces.com/panya/fde97294-MG_8070.JPG

### Expected behaviour
Image returned should be of 400 by 600 px with white background for extra space

### Actual behaviour
Image is just resized and not according to the WxH provided , also without any extra background. On my local machine the same URL gives me the correct results.

### Operating system
Ubuntu 18.04

Would really appreciate the help. Thanks

**Comment by highoncarbs** [comment]
Fixed with thubmor==6.7.4 , can't fix on the latest version

**Comment by mvhirsch** [comment]
Did you find a solution yet?

If not, and you're running thumbor 7.0.0, please run `thumbor-doctor` and paste the result here.

**Comment by scorphus** [comment]
Working as expected. https://cdn.jaitexart.org/unsafe/fit-in/400x600/filters:fill(white,1)/https://picsum.photos/1620/1080

![image](https://user-images.githubusercontent.com/2112697/151695169-02ee79f2-1f86-4ba0-a2c3-fd0d52cfa0b6.png)

I also confirm it works as expected with latest release.

**Comment by highoncarbs** [comment]
Thanks, will update to the latest version and check if that fixes the issue.
