### ISSUE TITLE
Thumbor support sha256 or newer than sha1

### ISSUE THREAD

**Issue by nhha1602** [thumbor/thumbor#1332]
Dear All,

Could you please help to let me know if thumbor support sha256 or newer sha1 ? If yes, how to configure it?

Thanks and regards,

**Comment by mzimbres** [comment]
I would like to use the hmac implementation from libsodium on my backend. They only provide SHA-2 (https://libsodium.gitbook.io/doc/advanced/hmac-sha2). It would be nice to have this option in Thumbor.
