### ISSUE TITLE
How stable is Thumbor 7.0a5?

### ISSUE THREAD

**Issue by jannejava** [thumbor/thumbor#1334]
First of all, I apprecate all the effort put into this software! Have been using it for 6 months now.

However, on a brand new Ubuntu 20.04 VPS I am having a trouble of installing Thumbor, since Python2 is no more. Can I use Thumbor 7.0a5, since it works in Python 3, despite it's an alpha? 

Regards,

Jam

**Comment by heynemann** [comment]
Hey! Glad you appreciate it. Would be really cool if you could help us test the alpha :) We really want to move forward with it and all the help we can get is appreciated.

**Comment by jannejava** [comment]
Of course, I will certainly do that!

**Comment by heynemann** [comment]
Hey we're in the process of releasing a beta version that will have a compatibility layer for loaders, storages and result storages, making it simpler to migrate to thumbor 7.0.0. If you want to try it, check this PR: #1342

**Comment by heynemann** [comment]
Hey @fraenki can you help test the alpha?

**Comment by fraenki** [comment]
@heynemann We may deploy a pre-release in our test environment, but we would really need the compatibility layer to make this happen.

**Comment by heynemann** [comment]
Hey @fraenki just created a new [Thumbor AWS Extensions](https://github.com/thumbor/thumbor-aws) project to help users moving to Thumbor 7.0.0+. Would you give it a try? It would be very helpful!
