### ISSUE TITLE
How can I get more info like exif or Orientation ?

### ISSUE THREAD

**Issue by cnhuye** [thumbor/thumbor#1336]
First, thumbor is a great project ! 
Thanks for all devs!

I have a question now:
How can I get more info for a image, like EXIF  or Orientation info.

in /meta,  I can only get  width & height, no more other infos.

Is there a way to do this ?

**Comment by heynemann** [comment]
I think this is the first request for these metadata in the meta route. The way to do it would be to change meta to include it as well. Want to try implementing it?

**Comment by kkopachev** [comment]
Metadata is available as engine property `metadata` if you have `pyexiv2` library installed. You can write some code to expose this data on the meta endpoint.
