### ISSUE TITLE
Fit-in ZeroDivisionError exception

### ISSUE THREAD

**Issue by luizender** [thumbor/thumbor#1347]
Thumbor is crashing in my production environment (I can't show the image URL) with a division by zero error in fit-in resize.

Here is the Traceback of exception:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/thumbor/context.py", line 276, in _execute_in_foreground
    returned = operation()
  File "/usr/lib/python2.7/site-packages/thumbor/transformer.py", line 212, in img_operation_worker
    self.fit_in_resize()
  File "/usr/lib/python2.7/site-packages/thumbor/transformer.py", line 352, in fit_in_resize
    self.engine.resize(resize_width, resize_height)
  File "/usr/lib/python2.7/site-packages/thumbor/engines/pil.py", line 133, in resize
    self.image.draft(None, size)
  File "/usr/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 425, in draft
    scale = min(self.size[0] // size[0], self.size[1] // size[1])
ZeroDivisionError: integer division or modulo by zero

**Comment by kkopachev** [comment]
Can you share image dimensions and what fit-in dimensions it was trying to scale to?
Thumbor version would also be nice.

**Comment by luizender** [comment]
I don't have this information to share with you, sorry! I'm using the thumbor 6.7.5

I saw in the code that has a treatment to prevent division by zero in the resize method. Is it not necessary in the fit-in resize method?

**Comment by scorphus** [comment]
@luizender You must understand that, without a reproducible case, it is going to be very difficult — if even doable — to understand what may be wrong or not working as expected.

Without a precise URL and an image that fails with such error, there's little we can do to help.

**Comment by mvhirsch** [comment]
@luizender can this issue be closed? Did you find a solution you want to share?

**Comment by scorphus** [comment]
I'd say we close this issue. There's no image nor steps to reproduce. Nothing to be done here, really.

Besides, all [Pillow's issues RE ZeroDivisionError](https://github.com/python-pillow/Pillow/search?q=zerodivisionerror&type=issues) are either closed or merged. If this was indeed an issue at some point, it's likely already solved. Otherwise, a new issue can be created.
