### ISSUE TITLE
resize，The picture is blurry

### ISSUE THREAD

**Issue by Espoir999** [thumbor/thumbor#1349]
origin image is 534x924,  300KB, 

resize(186, 294) 

When I resize, the image is very blurry, I just want to resize, but I don't want the image to be blurry

Is there anything I can do? please, thanks.

**Comment by scorphus** [comment]
It would be very helpful if you could provide the actual picture, or — If that's not possible — an example demonstrating the issue you're having.

In the meantime, let me provide some counter examples.

Original 534x924 image:
![image](https://user-images.githubusercontent.com/2112697/111183885-ac83f700-85b0-11eb-9ae6-3903681b9bb6.png)
(https://user-images.githubusercontent.com/2112697/111183885-ac83f700-85b0-11eb-9ae6-3903681b9bb6.png)

Resized by thumbor:
![image](http://thumbor.thumborize.me/unsafe/186x294/https://user-images.githubusercontent.com/2112697/111183885-ac83f700-85b0-11eb-9ae6-3903681b9bb6.png)
(http://thumbor.thumborize.me/unsafe/186x294/https://user-images.githubusercontent.com/2112697/111183885-ac83f700-85b0-11eb-9ae6-3903681b9bb6.png)

Original 534x924 image:
![image](https://user-images.githubusercontent.com/2112697/111185791-a68f1580-85b2-11eb-8263-3cd3ab350aaa.png)
(https://user-images.githubusercontent.com/2112697/111185791-a68f1580-85b2-11eb-8263-3cd3ab350aaa.png)

Resized by thumbor:
![image](http://thumbor.thumborize.me/unsafe/186x294/https://user-images.githubusercontent.com/2112697/111185791-a68f1580-85b2-11eb-8263-3cd3ab350aaa.png)
(http://thumbor.thumborize.me/unsafe/186x294/https://user-images.githubusercontent.com/2112697/111185791-a68f1580-85b2-11eb-8263-3cd3ab350aaa.png)

**Comment by mvhirsch** [comment]
After nearly a year and new releases in meantime, I think this can be closed. @heynemann what do you think?

**Comment by heynemann** [comment]
✔️
