### ISSUE TITLE
Order of execution of crop and filters

### ISSUE THREAD

**Issue by victorjkhalaf** [thumbor/thumbor#1351]
### Thumbor request URL

https://local.thumbor/unsafe/0x0:1000x1000/fit-in/512x512/filters:product(S,8,12,BB,075DW,1):format(png)/https://unsplash.com/photos/_DCkqPaOdTQ/download?force=true

### Expected behaviour

Based on what I've read on Readthedocs, I expected the following image (hacked in something so our filter would perform the crop to demonstrate the intended result we hoped Thumbor's crop would do)
![image](https://user-images.githubusercontent.com/410897/112020048-6c6bc980-8b06-11eb-8c44-1c68e7c73b69.png)

Using this URL 
https://local.thumbor/unsafe/fit-in/512x512/filters:product(S,8,12,BB,075DW,1,0,0,1000,1000):format(png)/https://unsplash.com/photos/_DCkqPaOdTQ/download?force=true

### Actual behaviour

It crops AFTER the filters run (see request URL at the top of this Issue)
![image](https://user-images.githubusercontent.com/410897/112019950-5231eb80-8b06-11eb-814c-2896eb3ab4cc.png)

My question is: Is the crop command supposed to happen AFTER filters have run?

### Operating system
OSx, Ubuntu, etc
Alpine Linux 3.11
Thumbor v6.6.0
Python 2.7

Please let me know if pasting the conf file would be useful

**Comment by mvhirsch** [comment]
Did you find a solution yet?

**Comment by victorjkhalaf** [comment]
No I can't even remember I had posted this truthfully. It is not an issue that we must have needed resolution back then.

**Comment by mvhirsch** [comment]
Okay, so this can be closed for now. If you need any help further, just feel free to reopen or create a new issue.

FYI @heynemann
