### ISSUE TITLE
pip install thumbor fails on Apple M1 Silicon due to Pillow <=7.0 requirement?

### ISSUE THREAD

**Issue by klaumsco** [thumbor/thumbor#1358]
pip install thumbor
Collecting thumbor
  Using cached thumbor-6.7.5-cp39-cp39-macosx_11_0_arm64.whl
Requirement already satisfied: six in /opt/homebrew/lib/python3.9/site-packages (from thumbor) (1.15.0)
Requirement already satisfied: pycurl<7.44.0,>=7.19.0 in /opt/homebrew/lib/python3.9/site-packages (from thumbor) (7.43.0.6)
Requirement already satisfied: webcolors in /opt/homebrew/lib/python3.9/site-packages (from thumbor) (1.11.1)
Collecting libthumbor>=1.3.2
  Using cached libthumbor-2.0.1-py3-none-any.whl (8.7 kB)
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: pytz in /opt/homebrew/lib/python3.9/site-packages (from thumbor) (2021.1)
Collecting Pillow<7,>=4.3.0
  Using cached Pillow-6.2.2.tar.gz (37.8 MB)
Collecting futures
  Using cached futures-3.1.1-py3-none-any.whl (2.8 kB)
Requirement already satisfied: tornado<6.0.0,>=4.1.0 in /opt/homebrew/lib/python3.9/site-packages (from thumbor) (5.1.1)
Collecting derpconf>=0.2.0
  Using cached derpconf-0.8.3-py3-none-any.whl
Requirement already satisfied: statsd>=3.0.1 in /opt/homebrew/lib/python3.9/site-packages (from thumbor) (3.3.0)
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-install-ndee6wwi/pillow_06aef4675a674c04a9209b4239c1f6d9/setup.py'"'"'; __file__='"'"'/private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-install-ndee6wwi/pillow_06aef4675a674c04a9209b4239c1f6d9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-wheel-pzb8_edg
       cwd: /private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-install-ndee6wwi/pillow_06aef4675a674c04a9209b4239c1f6d9/
  Complete output (172 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11-arm64-3.9
  creating build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageMode.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageFile.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/TarIO.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageStat.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageColor.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ContainerIO.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/_version.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageQt.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageMath.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/PaletteFile.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/FontFile.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/PdfParser.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ExifTags.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageCms.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageChops.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/PSDraw.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageFilter.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImagePath.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/__init__.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/JpegPresets.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/features.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageDraw.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageWin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageMorph.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/WalImageFile.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/BlpImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageTk.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageOps.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageShow.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageGrab.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/TiffTags.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/_util.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/GdImageFile.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImagePalette.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageTransform.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageSequence.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/PyAccess.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/_binary.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/Image.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/__main__.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/ImageFont.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
  running egg_info
  writing src/Pillow.egg-info/PKG-INFO
  writing dependency_links to src/Pillow.egg-info/dependency_links.txt
  writing top-level names to src/Pillow.egg-info/top_level.txt
  reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.codecov.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'azure-pipelines.yml'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  no previously-included directories found matching '.azure-pipelines'
  no previously-included directories found matching '.travis'
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "/private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-install-ndee6wwi/pillow_06aef4675a674c04a9209b4239c1f6d9/setup.py", line 852, in <module>
      setup(
    File "/opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/homebrew/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-install-ndee6wwi/pillow_06aef4675a674c04a9209b4239c1f6d9/setup.py", line 687, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: zlib
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-install-ndee6wwi/pillow_06aef4675a674c04a9209b4239c1f6d9/setup.py", line 903, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  ----------------------------------------
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
Installing collected packages: Pillow, libthumbor, futures, derpconf, argparse, thumbor
  Attempting uninstall: Pillow
    Found existing installation: Pillow 8.2.0
    Uninstalling Pillow-8.2.0:
      Successfully uninstalled Pillow-8.2.0
    Running setup.py install for Pillow ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-install-ndee6wwi/pillow_06aef4675a674c04a9209b4239c1f6d9/setup.py'"'"'; __file__='"'"'/private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-install-ndee6wwi/pillow_06aef4675a674c04a9209b4239c1f6d9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-record-4v1wzzwz/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/include/python3.9/Pillow
         cwd: /private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-install-ndee6wwi/pillow_06aef4675a674c04a9209b4239c1f6d9/
    Complete output (174 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-11-arm64-3.9
    creating build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageMode.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageFile.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/TarIO.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageStat.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageColor.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ContainerIO.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/_version.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageQt.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageMath.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/PaletteFile.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/FontFile.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/PdfParser.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ExifTags.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageCms.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageChops.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/PSDraw.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageFilter.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImagePath.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/__init__.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/JpegPresets.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/features.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageDraw.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageWin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageMorph.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/WalImageFile.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageTk.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageOps.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageShow.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageGrab.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/TiffTags.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/_util.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/GdImageFile.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImagePalette.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageTransform.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageSequence.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/PyAccess.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/_binary.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/Image.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/__main__.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/ImageFont.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.macosx-11-arm64-3.9/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.travis'
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-install-ndee6wwi/pillow_06aef4675a674c04a9209b4239c1f6d9/setup.py", line 852, in <module>
        setup(
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-install-ndee6wwi/pillow_06aef4675a674c04a9209b4239c1f6d9/setup.py", line 687, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-install-ndee6wwi/pillow_06aef4675a674c04a9209b4239c1f6d9/setup.py", line 903, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    ----------------------------------------
  Rolling back uninstall of Pillow
  Moving to /opt/homebrew/lib/python3.9/site-packages/PIL/
   from /opt/homebrew/lib/python3.9/site-packages/~IL
  Moving to /opt/homebrew/lib/python3.9/site-packages/Pillow-8.2.0.dist-info/
   from /opt/homebrew/lib/python3.9/site-packages/~illow-8.2.0.dist-info
ERROR: Command errored out with exit status 1: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-install-ndee6wwi/pillow_06aef4675a674c04a9209b4239c1f6d9/setup.py'"'"'; __file__='"'"'/private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-install-ndee6wwi/pillow_06aef4675a674c04a9209b4239c1f6d9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/m1/0rhgw_hx52x9zdmm831vth800000gn/T/pip-record-4v1wzzwz/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/include/python3.9/Pillow Check the logs for full command output.

**Comment by jannejava** [comment]
Thumbor 6.x does not work with Pyton 3.x (which is default in most systems these days). Try Thumbor 7.x-alfa.

**Comment by heynemann** [comment]
Thanks @jannejava for helping other users!!! Appreciate it!
