### ISSUE TITLE
Result files not stored in defined directory

### ISSUE THREAD

**Issue by jake404** [thumbor/thumbor#1362]
### Thumbor request URL
http://192.168.1.252:8579/unsafe/700x0/filters:blur(7)/https%3A%2F%2Fnew.nu%2F78308374

### Expected behaviour
Store the result image in a defined directory.

### Actual behaviour
No result image is stored.

### Operating system
Docker (minimalcompact/thumbor)

### Your thumbor.conf
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = /storage/result

I have also set FILE_STORAGE_ROOT_PATH and it stores the original file correctly in the defined directory. It's just the result files that are not stored.

**Comment by approached** [comment]
...same question/problem

**Comment by mamchyts** [comment]
```RESULT_STORAGE_STORES_UNSAFE=True```

this Environment param was help me


I found info about it in config file:

```
################################ Result Storage ################################

## Expiration in seconds of generated images in the result storage
## Defaults to: 0
#RESULT_STORAGE_EXPIRATION_SECONDS = 0

## Path where the Result storage will store generated images
## Defaults to: '/tmp/thumbor/result_storage'
#RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/tmp/thumbor/result_storage'

## Indicates whether unsafe requests should also be stored in the Result Storage
## Defaults to: False
#RESULT_STORAGE_STORES_UNSAFE = False

```

**Comment by jake404** [comment]
That worked. Thank you @mamchyts.
