### ISSUE TITLE
Support for HDR image formats?  HDR, EXR, HEIF?

### ISSUE THREAD

**Issue by bhouston** [thumbor/thumbor#1363]
### Thumbor request URL
We would like to see support for HDR image formats (float per channel) in thumbor with the ability to convert between them and also to convert to LDR (8bit per channel) image formats like PNG, JPEG.

It isn't clear if this can be done via the PIL framework because I do not know if it supports bitdepth image formats internally -- more than 8bit.  I believe it may not.

The future is HDR image formats everywhere now that smart phone screens and cameras are both HDR capable.  Also all iPhones take their photos and videos in HDR, and soon other Android phones will as well.

Thus I believe Thumbor will need this at some point.  The question is whether now is a good time...

### Expected behaviour
We could fetch a *.hdr or a *.exr file and say that we want it in a png format or jpeg format or resize it or ask to convert .hdr to .exr.

### Actual behaviour
These file formats are not supported.

### Operating system
All

### Your thumbor.conf
Not applicable.

**Comment by scorphus** [comment]
Would you be able to provide some samples? Of both formats, HDR and LDR. Would be great to have a look at some *.hdr and *.exr files and see what can be done about that.

**Comment by bhouston** [comment]
@scorphus I apologize I missed your comment.

Here you go!

Here is an HDR: https://github.com/mrdoob/three.js/blob/dev/examples/textures/memorial.hdr
Here is an equivalent EXR: https://github.com/mrdoob/three.js/blob/dev/examples/textures/memorial.exr
And it should generally look like: https://threejs.org/examples/?q=hdr#webgl_loader_texture_hdr

**Comment by scorphus** [comment]
@bhouston you can use the [wand](https://github.com/scorphus/thumbor-wand-engine/#thumbor-wand-engine) engine which has support to such formats.

**Comment by christaggart** [comment]
Re: https://github.com/thumbor/thumbor/issues/1385  
the specific example was heif related but the question in general still stands:what’s the right place to extend an engine’s built-in support for something where you have to register a new handler with PIL?

**Comment by heynemann** [comment]
I'd say extend PIL engine and do what you need to be done.
