### ISSUE TITLE
Resized pictures appears blurry

### ISSUE THREAD

**Issue by LifestreamVII** [thumbor/thumbor#1367]
### Thumbor request URL
http://xx.xx.xx.xx/unsafe/1200x/image.jpg

### Expected behaviour
Should result in a resized JPEG/WEBP image with minimal quality loss

### Actual behaviour
The output picture has been resized to 1200 pixels (width) but appears slightly blurry (impact varies depending on the image).
This happens both with the JPEG format output (either with AUTO_WEBP off or with format(jpeg) and the WEBP format output.

### Operating system
Thumbor installation on Ubuntu Server
Tests on Windows 10 & macOS Catalina

### Your thumbor.conf
QUALITY=80
AUTO_WEBP=True
MAX_AGE = 10 * 24 * 60 * 60

FILE_LOADER_ROOT_PATH=/home/root/images
LOADER=thumbor.loaders.file_loader

### Examples

Photo 1 - Resized to 1200 with Photoshop :
![aeroplane-air-air-travel-723240_1](https://user-images.githubusercontent.com/36632834/136180774-c091adfb-15e4-4fb3-9a20-6427c0ef46f7.jpg)

Photo 1 - Resized to 1200 with Thumbor :
![aeroplane-air-air-travel-723240_CDNR](https://user-images.githubusercontent.com/36632834/136180772-24c85390-bc78-4e58-b8e7-3941e530e8ae.jpg)

Photo 2 - Resized to 1200 with Photoshop :
![Fotolia_4910750_PhotoshopResized](https://user-images.githubusercontent.com/36632834/136179419-37dcab95-8f5d-493f-99c2-a9b36cc6640d.jpg)

Photo 2 - Resized to 1200 with Thumbor :
![Fotolia_4910750_CDNResized](https://user-images.githubusercontent.com/36632834/136179699-a9045172-ab55-402d-b6c1-6b66fe955baf.jpg)

Photo 3 - Resized to 1200 with Photoshop :
![ff_x_t3_006_PhotoshopResized](https://user-images.githubusercontent.com/36632834/136179430-b15356f5-b5c3-43ba-93f5-cdae7fdacd2f.jpg)

Photo 3 - Resized to 1200 with Thumbor :
![ff_x_t3_006_CDNResized](https://user-images.githubusercontent.com/36632834/136179698-4547d054-9c01-4b9a-9c85-004d8b9f9ade.jpg)

**Comment by melan96** [comment]
can i work on it?

**Comment by DamienPartir** [comment]
do you find a solution ?

**Comment by mvhirsch** [comment]
@LifestreamVII I can see the difference. Would you mind to share the original image, so I can test it with current thumbor version?

**Comment by heynemann** [comment]
One further question. You are using 80 of quality on both thumbor and photoshop, right?

**Comment by LifestreamVII** [comment]
@mvhirsch @heynemann Here's the link to a folder that should contain everything needed to reproduce the issue.
https://drive.google.com/drive/folders/1uBP7yRdd37gvgj668tZOJLUh9rqIXQlE?usp=sharing
Thanks for your help !
