### ISSUE TITLE
High memory usage while using `thumbor.result_storages.no_storage`

### ISSUE THREAD

**Issue by wintercounter** [thumbor/thumbor#1372]
### Expected behaviour
No high memory usage when using `thumbor.result_storages.no_storage`.

### Actual behaviour
My thumbor processes take up 2-3.5GB RAM each. No caching is done anywhere, so there should be no reason for this memory usage. This is achieved by running the processes for a while (days, weeks), so seems like it's probably a memory leak. I'm using `nginx-proxy-cache` in front of it, that's why I don't really need the storage.

### Operating system
Docker, Alpine base

### Your thumbor.conf
I'm using `minimalcompact/thumbor`, pasting my env vars here:

```yaml
environment:
    - VIRTUAL_HOST=0.0.0.0
    - VIRTUAL_PORT=8888
    - THUMBOR_NUM_PROCESSES=4
    - CORS_ALLOW_ORIGIN=*
    - AUTO_WEBP=True
    - RESULT_STORAGE=thumbor.result_storages.no_storage
    - RESULT_STORAGE_STORES_UNSAFE=True
    - LOADER=thumbor.loaders.file_loader_http_fallback
    - FILE_LOADER_ROOT_PATH=/files
    - THUMBOR_PORT=8888
    - SECURITY_KEY=****
    - ALLOW_UNSAFE_URL=False
```

**Comment by kkopachev** [comment]
Thumbor uses ram to unpack image data into uncompressed pixels. Bigger images - more memory used. Normally it would reuse memory.
Do you see this happening with other result storages? That should not be the case.
Do you see memory usage continues to grow over time? I would expect it climb to few GB and sit there forever without much change in long run.

**Comment by wintercounter** [comment]
I think once it reaches ~4GB it's not growing further. Seems like this normal/expected then, I'm closing the thread. I guess my only option on a low RAM machine is to use fewer workers then. Thanks for the info.
