### ISSUE TITLE
Thumbor 7 AWS Loader

### ISSUE THREAD

**Issue by jclimac** [thumbor/thumbor#1381]
Hello!

Is there any AWS loader, like https://github.com/thumbor-community/aws, available for version 7.0.0b1?

Thank you!

**Comment by heynemann** [comment]
I created a very lightweight version here: https://github.com/thumbor/thumbor-aws
It definitely needs some love and if you could help it would be great.

BTW release 7.0.0 is out!

**Comment by mvhirsch** [comment]
I found a bug using storage/result-storage of thumbor-aws. Please take a look: https://github.com/thumbor/thumbor-aws/issues/1

**Comment by heynemann** [comment]
Hey @mvhirsch should we close this?

**Comment by mvhirsch** [comment]
Yes, we can! :-D

I was able to use it with most recent version `thumbor-aws==0.3.1` :tada:
