### ISSUE TITLE
Extending the pil engine for HEIF/HEIC support?

### ISSUE THREAD

**Issue by christaggart** [thumbor/thumbor#1385]
We're able to add heif/heic support by pip installing `pillow_heif` and then calling `register_heif_opener()` inside one of our plugins, but this feels like the wrong place to do it. 

Since this is effectively an engine extension, is there a better place to register this pillow opener? Extend pil.py?

**Comment by scorphus** [comment]
Hi, thanks for reporting. There's already one issue regarding this, and I'll close this one as duplicate. You're more than welcome in discussing your case/needs in #1363 :-)

**Comment by bigcat88** [comment]
@christaggart you can do: `import pillow_heif.HeifImagePlugin` if you do not want to call `register_heif_opener`
