### ISSUE TITLE
Support WebP

### ISSUE THREAD

**Issue by heynemann** [thumbor/thumbor#140]
I was reading this article http://www.igvita.com/2012/12/18/deploying-new-image-formats-on-the-web/ and found myself thinking that it should be fairly easy for us to support webp format (supported currently by chrome and opera).

Do you guys think we should provide some flag that would make thumbor return the smallest possible image? The only downside is that browsers (as is said on the article) do NOT send proper Accept headers.

We could allow the users to specify what formats they want to support. Thumbor would generate the image in all the formats, then pick the smallest one.

What do you guys think?

**Comment by JackHowa** [comment]
has this been updated? struggling to find documentation

**Comment by kkopachev** [comment]
It should just work. At least using default pil engine. You could open new issue if there is something not working.

**Comment by JackHowa** [comment]
working -- my bad, was looking in the wrong place. Thanks
