### ISSUE TITLE
Replaces derpconf with pydantic

### ISSUE THREAD

**Issue by marcelometal** [thumbor/thumbor#1413]
What do you think about replaces [derpconf](https://github.com/globocom/derpconf) with [pydantic](https://pydantic-docs.helpmanual.io/#rationale)?

**Comment by marcelometal** [comment]
> Isn't pydantic for type validation?

Data validation and **settings management** using python type annotations.

https://pydantic-docs.helpmanual.io/usage/settings/

**Comment by heynemann** [comment]
I guess the problem is that we would have to change every thumbor.conf out
there. :( Don't think this is feasible.

**Comment by scorphus** [comment]
True. This ship shas long sailed.
