### ISSUE TITLE
"Smart and None Smart Options"  breaks Metrics

### ISSUE THREAD

**Issue by softberry** [thumbor/thumbor#1417]
### Thumbor request URL
Thumbor can not build

### Expected behaviour
Thumbor should run

### Actual behaviour
Gives following error on build:
```
ValueError: Duplicated timeseries in CollectorRegistry: 
{
        'thumbor_response_none__smart_created', 
        'thumbor_response_none__smart'
}
```

### Operating system
All operationg systems

### Your thumbor.conf
```
....
PROMETHEUS_SCRAPE_PORT = 4001
METRICS = 'tc_prometheus.metrics.prometheus_metrics'
...
```

### Description : 
This change possibly introduces a braking issue for metrics usages :

I could not find the discussions on this issue and documentation about smart & none smart options. Could you please explain what is intended for those smart and none_smart options? Maybe I could implement that usage for my implementation to fix below explained bug.

In my case,
Sample usage of prometheus metrics with thumbor community plugin [tc_prometheus](https://github.com/thumbor-community/prometheus/blob/master/tc_prometheus/metrics/prometheus_metrics.py)

```
self.context.metrics.incr('response.smart')
self.context.metrics.timing('response.smart', total_time)
....
self.context.metrics.incr('response.none_smart')
self.context.metrics.timing('response.none_smart', total_time)
```
as well as : [thumbor/loaders/http_loader.py](https://github.com/thumbor/thumbor/pull/1251/files) 
**PS**: This code is now slightly changed but keeps the same buggy behavior: 
```
    context.metrics.timing(
            f"original_image.fetch.{code}.{netloc}",
            (finish - req_start).total_seconds() * 1000,
        )
        context.metrics.incr(
            f"original_image.fetch.{code}.{netloc}",
        )
```

Above lines from from : [thumbor/handlers/init.py](https://github.com/thumbor/thumbor/pull/1251/files)  are trying to create duplicate entry in CollectorRegistry which resulting following errors:

```
ValueError: Duplicated timeseries in CollectorRegistry: 
{
        'thumbor_response_none__smart_created', 
        'thumbor_response_none__smart'
}
```

In all other implementations of metrics.timing and metrics.incr metric names are always different. For example:

```
        self.context.metrics.timing("response.time.{0}".format(status), total_time)
        self.context.metrics.incr("response.status.{0}".format(status))
```

As seen above, Metric entries must be unique. Above implementations can be done by extending ``BaseMetrics`` for the specific use cases but not within thumbor. Therefore these changes are hidden **breaking issue** since  v7.0.0b1

Currently I am ignoring those calls to create a clean Metrics Collection as work around.

**Comment by heynemann** [comment]
Fix released under thumbor 7.0.8. Thanks for the thorough report!
