### ISSUE TITLE
Ability to launch thumbor with --fd option

### ISSUE THREAD

**Issue by ebilheude** [thumbor/thumbor#1418]
With version 7.0.6 of thumbor, I cannot start the process with an --fd option. I have the following trace : 

`sock = socket_from_fd(  # pylint: disable=too-many-function-args
TypeError: fromfd() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/srv/www/thumbor/bin/thumbor", line 8, in <module>
    sys.exit(main())
  File "/srv/www/thumbor/lib/python3.8/site-packages/thumbor/server.py", line 146, in main
    server = run_server(application, context)
  File "/srv/www/thumbor/lib/python3.8/site-packages/thumbor/server.py", line 109, in run_server
    sock = socket_from_fd(  # pylint: disable=too-many-function-args`

By checking the code in the socketfromfd dependency (v0.2.0) I see there is no additional parameter to the function `fromfd`

It is strange as in the master branch of socketfromfd, there is indeed the possibility to pass 2 parameters (but not in the 0.2.0 version).

**Comment by heynemann** [comment]
Should be working in new release.
