### ISSUE TITLE
Provide an official helm chart

### ISSUE THREAD

**Issue by villesau** [thumbor/thumbor#1425]
[Helm](https://helm.sh/) is a package manager for [Kubernetes](https://kubernetes.io/). I believe that one of the usual places to deploy Thumbor is Kubernetes, so an official helm chart for that purpose would make sense. It could set sensible defaults, and allow configurability as well.

**Comment by heynemann** [comment]
Is that something you can help with @villesau ?

**Comment by villesau** [comment]
Unfortunately I'm not an expert with Helm so cannot pull it off at this point at least. Maybe at some point in the future if we decide to deploy this but there is no timeline.

**Comment by villesau** [comment]
still valid

**Comment by heynemann** [comment]
@villesau I don't think the team will be able to help with this, so if we do not get a contribution we'll likely keep this stale -> comment -> stale cycle. @guilhermef is this something you can help with?

**Comment by guilhermef** [comment]
I'll try to start it this week.

**Comment by guilhermef** [comment]
I was finally able to start creating an official helm chart: https://github.com/thumbor/helm
It's still under development but I'll keep this thread updated in the upcoming weeks.

**Comment by guilhermef** [comment]
This PR is needed for the Helm chart: https://github.com/thumbor/thumbor/pull/1496

**Comment by techytushar** [comment]
Hey @guilhermef ,
Please let me know if you need any help with this

**Comment by guilhermef** [comment]
Thanks, @techytushar. I'll need help with it. Let me just finish the first release.
