### ISSUE TITLE
Is there any documentation on how to use thumbor as a library?

### ISSUE THREAD

**Issue by gcavalcante8808** [thumbor/thumbor#1429]
Hi Folks,

I'd like to know if is there any documentation or source that points how to use thumbor as a library.

Originally I was reading https://github.com/thumbor/thumbor/issues/786 and there is a interesting (but old) comment: https://github.com/thumbor/thumbor/issues/786#issuecomment-520721859

In the example there is a tornado setup, but if its possible to instantiate an engine and then use it to resize some pics directly, it would fit perfectly in my case.

So with that in mind, I ask: Is there any documentation on how to use thumbor as a library?

Thanks in advance.

**Comment by heynemann** [comment]
Not really but would be awesome if you could contribute it :) We can help along the way on how to use it.

Thumbor has docs detailing each of its parts: loaders, storages, engines, filters, detectors...

With that in mind it should be easy to just reuse thumbor's parts (what AWS did in their docs on using thumbor and its filters.
