### ISSUE TITLE
when time to support aarch64?

### ISSUE THREAD

**Issue by kevinsingapore** [thumbor/thumbor#1431]
i hope that offical to support aarch64, binary or docker image.
and thanks!

**Comment by shudack** [comment]
I'm following this topic.

**Comment by shudack** [comment]
@heynemann do you have plans to support aarch64? Thank you

**Comment by guilhermef** [comment]
@kevinsingapore @shudack Thumbor already supports arm64.
You can find the official Docker images here: https://hub.docker.com/r/thumbororg/thumbor/tags

**Comment by shudack** [comment]
> @kevinsingapore @shudack Thumbor already supports arm64. You can find the official Docker images here: https://hub.docker.com/r/thumbororg/thumbor/tags

Hi @guilhermef,

I tried the image you mentioned and got this log:
"No log line matching the '' filter"
![image](https://user-images.githubusercontent.com/17851196/207117350-2971758a-ed85-44f2-924d-d507fc4c7f0e.png)

And in the console with command thumbor-doctor:
![image](https://user-images.githubusercontent.com/17851196/207117295-664d5a97-748b-42ca-ad35-dbf50d56a94d.png)

My docker-compose:
services:
  thumbor:
    image: thumbororg/thumbor:latest
    container_name: thumbor
    restart: unless-stopped
    environment:
      - LOADER=thumbor.loaders.https_loader
      - ALLOWED_SOURCES=['.+.xxxxxxxxx.pt']
      # scale your thumbor instances
      - THUMBOR_NUM_PROCESSES=4
      # returns a webp image if browser Accept headers match
      - AUTO_WEBP=True
      # nginx-proxy does caching automatically, so no need to store the result storage cache
      # (this greatly speeds up and saves on CPU)
      - RESULT_STORAGE=thumbor.result_storages.no_storage
      - RESULT_STORAGE_STORES_UNSAFE=True
      # setting mixed storage, and detector storage using redis
      - STORAGE=thumbor.storages.mixed_storage
      - MIXED_STORAGE_DETECTOR_STORAGE=tc_redis.storages.redis_storage
      # using queued_complete_detector which uses all available detectors
      - DETECTORS=['thumbor.detectors.queued_detector.queued_complete_detector']
      # redis settings for storage and queue
      - REDIS_STORAGE_SERVER_HOST=redis
      - REDIS_STORAGE_SERVER_PORT=6379
      - REDIS_STORAGE_SERVER_DB=0
      - REDIS_QUEUE_SERVER_HOST=redis
      - REDIS_QUEUE_SERVER_PORT=6379
      - REDIS_QUEUE_SERVER_DB=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/thumbor/app:/app
      - /opt/docker/thumbor/data:/data
    links:
      - redis:redis
    ports:
      - 8800:80
    depends_on:
      - redis

Can you help me?
