### ISSUE TITLE
Thumbor doesn't respect order in filters pipeline

### ISSUE THREAD

**Issue by OndrejIT** [thumbor/thumbor#1434]
### Thumbor request URL
http://127.0.0.1:8080/unsafe/500x0/filters:watermark(raw.githubusercontent.com/thumbor/thumbor/master/logo-thumbor.png,-10,-10,50,30):blur(5)/raw.githubusercontent.com/thumbor/thumbor/master/example.jpg
![example](https://user-images.githubusercontent.com/11267809/166238020-f3b80b02-955d-47f7-8c96-f16dd3f38574.jpg)

http://127.0.0.1:8080/unsafe/500x0/filters:blur(5):watermark(raw.githubusercontent.com/thumbor/thumbor/master/logo-thumbor.png,-10,-10,50,30)/raw.githubusercontent.com/thumbor/thumbor/master/example.jpg
![example](https://user-images.githubusercontent.com/11267809/166238069-18b6b50f-f074-4f50-909a-5bda4cb49e5a.jpg)

### Expected behaviour
Thumbor handles filters in a pipeline. This means that they run sequentially in the order they are specified! Given an original image with size 60x40 and the following transformations:

https://thumbor.readthedocs.io/en/latest/filters.html#how-filters-work

### Actual behaviour
Thumbor doesn't respect order in filters pipeline, maybe is reversed?
However in 6.7.5 works fine accordance with the documentation.

### Operating system
docker.io/python:3.10-alpine
thumbor==7.0.9
https://github.com/OndrejIT/thumbor-crypto/archive/devel.tar.gz
pycurl==7.45.1
CairoSVG==2.5.2
sentry-sdk==1.5.10
numpy==1.22.3

+ OpenCV

**Comment by OndrejIT** [comment]
(Virtual env python 10 on my manjaro the same problem.)

**Comment by scorphus** [comment]
Thanks for reporting, @OndrejIT 👍 

I hereby confirm this issue.

## With `watermark` followed by `blur`

> http://127.0.0.1:8888/unsafe/500x0/filters:watermark(raw.githubusercontent.com/thumbor/thumbor/master/logo-thumbor.png,-10,-10,50,30):blur(5)/raw.githubusercontent.com/thumbor/thumbor/master/example.jpg

### Thumbor 6.7.5

![image](https://user-images.githubusercontent.com/2112697/166330819-d40fb853-cf73-48b4-ab72-d979f89642eb.png)

### Thumbor 7.0.9

![image](https://user-images.githubusercontent.com/2112697/166330908-d4a34de4-7f6f-475d-b819-866ee39c9183.png)

## With `blur` followed by `watermark`

### Thumbor 6.7.5

![image](https://user-images.githubusercontent.com/2112697/166331105-55889b32-96fb-4036-919a-301f312b55f8.png)

### Thumbor 7.0.9

![image](https://user-images.githubusercontent.com/2112697/166331137-c4631a18-de5c-49c0-9f95-4a748fb6b510.png)

**Comment by scorphus** [comment]
Introduced in 3d5fbe93aa990ab5e7e8b9724e0fad9d1db60f98. Fix on the way.

**Comment by scorphus** [comment]
Hey, @OndrejIT! Thanks again for reporting. Keep an eye on the upcoming release, it should happen shortly.

**Comment by RaphaelVRossi** [comment]
Hey @OndrejIT we published a new release!
