### ISSUE TITLE
Add stale-while-revalidate to cache-control header

### ISSUE THREAD

**Issue by jaap3** [thumbor/thumbor#1448]
> The stale-while-revalidate response directive indicates that the cache could reuse a stale response while it revalidates it to a cache.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#stale-while-revalidate

**Comment by jaap3** [comment]
I was away during this 5 day period and didn't have a chance to say that this ticket isn't completed :(

**Comment by heynemann** [comment]
Sorry for that :) Just reopened.
