### ISSUE TITLE
Min height and width on a case by case basis

### ISSUE THREAD

**Issue by kippo** [thumbor/thumbor#1451]
I have a use case where I'm trying to use fit in but I also want to ensure both a min height and width.

My understanding is that I could use the following but this appears to be a global configuration whereas I want to be able to specify this per transform. 
https://thumbor.readthedocs.io/en/latest/configuration.html?highlight=MIN_WIDTH#min-width-and-min-height

Is the any way to handle this.

**Comment by mvhirsch** [comment]
Thanks for reaching out. Yes, that configuration is per instance of thumbor, so it will affect all images in the same way.

The only way I could think of is to upscale the image using minimum width/height by thumbor, and resize that image again using thumbor:

1. Original image (200x200): https://placekitten.com/200/200
2. Upscale (300x300): http://thumbor.thumborize.me/unsafe/full-fit-in/300x200/filters:upscale()/https://placekitten.com/200/200
3. Resize (300x200): http://thumbor.thumborize.me/unsafe/300x200/http://thumbor.thumborize.me/unsafe/full-fit-in/300x200/filters:upscale()/https://placekitten.com/200/200

@heynemann any thoughts?

**Comment by mvhirsch** [comment]
You're welcome :+1:
