### ISSUE TITLE
How to serve non-image type files

### ISSUE THREAD

**Issue by jing-nmg** [thumbor/thumbor#1454]
Our attachments are not only in image formats, but also in other non-image formats such as doc, pdf, zip, mp4, etc. I expect thumbor can not only perform some rich operations on image-type files, but also non-image-type files can directly respond and return rather than error.

### Thumbor request URL
`/some-security-string/0x0/filters:water(0,0,0)/1.mp4`

### Expected behaviour
Ignore all command parameters of the URL and directly return the `1.mp4` file from `Loader`

### Actual behaviour
````
2022-06-09 09:55:47 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "path/venv/lib/python3.10/site-packages/thumbor/handlers/__init__.py", line 195, in get_image
    result = await self._fetch(self.context.request.image_url)
  File "path/venv/lib/python3.10/site-packages/thumbor/handlers/__init__.py", line 794, in _fetch
    raise fetch_result.exception
  File "path/venv/lib/python3.10/site-packages/thumbor/handlers/__init__.py", line 763, in _fetch
    self.context.request.engine.load(fetch_result.buffer, extension)
  File "path/venv/lib/python3.10/site-packages/thumbor/engines/__init__.py", line 188, in load
    image_or_frames = self.create_image(buffer)
  File "path/venv/lib/python3.10/site-packages/thumbor/engines/pil.py", line 73, in create_image
    img = Image.open(BytesIO(buffer))
  File "path/venv/lib/python3.10/site-packages/PIL/Image.py", line 3030, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x103ed7c90>
````

### Operating system
OSx

### Your thumbor.conf

IGNORE

May I ask if there is a good solution for this situation just by extending or custom  thumbor?

**Comment by mvhirsch** [comment]
Thanks for reaching out. Thumbor is an imaging service, not a web server in first class. I think what you want to achieve can be done using nginx in a more elegant way: 

1. setup an nginx
2. configure a server to serve all files, except images. 
3. If the mimetype is an image, serve it through an upstream proxy by Thumbor.

```
# pass images to thumbor, add additional file endings in list if needed
location ~ \.(jpg|jpeg|png)$ {
    # keep in mind, that $uri needs to be translated to somewhere 
    # thumbor might be able download that file (or use the Upload Feature)
    proxy_pass http://127.0.0.1:8888/unsafe/100x/$uri;
}

location / {
    root /var/www/html/attachments/
    try_files $uri
}
```

If you need help setting up nginx, try asking for help on https://serverfault.com/

Since this isn't to be solved by Thumbor, I'll close this issue.
