### ISSUE TITLE
Filling image with background color and using nested watermark 

### ISSUE THREAD

**Issue by ajaypande88** [thumbor/thumbor#1456]
### Thumbor request URL
I am trying to fill color to tint the gradient image and watermark my colored gradient image on the black background image.

http://localhost:8888/unsafe/full-fit-in/480x540/
http://localhost:8888/unsafe/960x540/filters:watermark(image_1,0,0,50):watermark(image_2,480,0,60)/blackbackground.png
I want to fill red background for my image_1 and blue in my image_2. Is it possible inside the watermark to apply  background color? 
Is it possible to add a watermark inside the watermark? 
### Expected behaviour
Tell us what should happen
I should get image with red and blue background 
### Actual behaviour
Tell us what happens instead
background-color disappers 
### Operating system
OSx, Ubuntu, etc
osx
### Your thumbor.conf

Your config file (WARNING: replace your SECURITY_KEY key with a dummy key or your key will become public)

**Comment by RaphaelVRossi** [comment]
Hey @ajaypande88,

You can call Thumbor twice inside watermark with background_color filter.

`http://localhost:8888/unsafe/full-fit-in/480x540/
http://localhost:8888/unsafe/960x540/filters:watermark(http://localhost:8888/unsafe/filters:background_image%28red%29/image_1,0,0,50):watermark(http://localhost:8888/unsafe/filters:background_image%28blue%29/image_2,480,0,60)/blackbackground.png`

You need to escape `()` inside watermark filter and add your local domain to `ALLOWED_SOURCES` to make it work.

**Comment by ajaypande88** [comment]
filters:background_color(red) - fills the transparent image? I have also tried filters:fill(red,1) which fills my transparent image but it doesn't work inside watermark

**Comment by RaphaelVRossi** [comment]
You can use background_color to fill a transparent image, for more information read the docs [here](https://thumbor.readthedocs.io/en/latest/background_color.html).

And about fill filter, for some reason, is not working inside watermark filter.
