### ISSUE TITLE
filter `background_color(auto)` not working

### ISSUE THREAD

**Issue by cortopy** [thumbor/thumbor#1469]
### Thumbor request URL
http://localhost:8888/unsafe/100x100/filters:format(jpeg):background_color(auto)/https%3A//my_image.png

### Expected behaviour
According to the [docs](https://thumbor.readthedocs.io/en/latest/background_color.html), `auto` is supported for `background_color` so that "a color will be smartly chosen"

### Actual behaviour
Thumbor returns 500 and in the logs I can see that `ValueError: unknown color specifier: '#auto'`. A real colour passed as argument works

### Operating system
Debian (Docker)

### Your thumbor.conf
Background filter is active as per

```
FILTERS = [
   'thumbor.filters.brightness',
   'thumbor.filters.colorize',
   'thumbor.filters.contrast',
   'thumbor.filters.rgb',
   'thumbor.filters.round_corner',
   'thumbor.filters.quality',
   'thumbor.filters.noise',
   'thumbor.filters.watermark',
   'thumbor.filters.equalize',
   'thumbor.filters.fill',
   'thumbor.filters.sharpen',
   'thumbor.filters.strip_exif',
   'thumbor.filters.strip_icc',
   'thumbor.filters.frame',
   'thumbor.filters.grayscale',
   'thumbor.filters.rotate',
   'thumbor.filters.format',
   'thumbor.filters.max_bytes',
   'thumbor.filters.convolution',
   'thumbor.filters.blur',
   'thumbor.filters.extract_focal',
   'thumbor.filters.focal',
   'thumbor.filters.no_upscale',
   'thumbor.filters.saturation',
   'thumbor.filters.max_age',
   'thumbor.filters.curve',
   'thumbor.filters.background_color',
   'thumbor.filters.upscale',
   'thumbor.filters.proportion',
   'thumbor.filters.stretch',
]
```

**Comment by scorphus** [comment]
Thanks for reporting. It was added by 513db84d9bf3bbe367f046b875487af56f73308d to the docs but not to code. It needs to be implemented, ideally sharing the same logic with the `fill` filter.

A PR with implementation + tests + fixtures is more than appreciated!

**Comment by siqueira-ec** [comment]
@cortopy @RaphaelVRossi @scorphus 

I created a PR fixing that issue. Could you evaluate and, if possible, merge it?
