### ISSUE TITLE
Accepting HEIC/HEIF as image input and output 

### ISSUE THREAD

**Issue by maiagripp** [thumbor/thumbor#1503]
### Thumbor request URL
[HEIC](http://localhost:8888/unsafe/https://github.com/alexcorvi/heic2any/blob/master/demo/1.heic?raw=true)

### Expected behaviour
Thumbor should accept `HEIC` and `HEIF` as image input and output.
Why should this format be used?
```
HEIC/HEIF not only reduces file size by ~50% compared to JPEG, but with iOS 11, it now is also 
the default image format for more than 50% of cell phones in the west
```

### Actual behaviour
Nowadays, Thumbor doesn't accept `HEIC` and `HEIF` as image input or output.

**Comment by RaphaelVRossi** [comment]
I'm working on that!

**Comment by bigcat88** [comment]
I am done with that... will make PR in an hour
