### ISSUE TITLE
When a signature key is invalid Thumbor should return a 401, not a 400 HTTP status

### ISSUE THREAD

**Issue by RaphaelVRossi** [thumbor/thumbor#1514]
### Thumbor request URL
http://domain.org/invalidkey/100x100/http://mydomain.org/image.jpeg

### Expected behaviour
When a signature key is not valid, Thumbor should return a HTTP Status Code 401 - Unauthorized, not a 400 - Bad Request.

This change will help monitoring differents errors code returned by Thumbor, not only one generic error.

### Actual behaviour
When a signature key is not valid, Thumbor returns a 400 - Bad Request

### Operating system
N/A

### Your thumbor.conf
```python
[...]
SECURITY_KEY = "MY_SECURE_KEY"
[...]
```

**Comment by RaphaelVRossi** [comment]
@heynemann @guilhermef @scorphus WDYT?

**Comment by scorphus** [comment]
How is that helpful? Only to a reckless attacker, maybe?
