### ISSUE TITLE
Local Images

### ISSUE THREAD

**Issue by JPH71** [thumbor/thumbor#1525]
I am running Thumbor off the web using a URL starting with 
`http://34.xxx.xxx.xxx:8888/unsafe/url_of_image`

I can grayscale an image by adding filters :  
`http://34.xxx.xxx.xxx:8888/unsafe/filters:grayscale()/url_of_image`

and a watermark by adding an extra filter like:
`http://34.xxx.xxx.xxx:8888/unsafe/filters:grayscale():watermark(url_of_watermark,1,1,15,none,none)/url_of_image`

How can I get the web service to use local images on my hard drive so that I end up with:
`http://34.xxx.xxx.xxx:8888/unsafe/filters:grayscale():watermark(C:\My WaterMarks\Watermark1.png,1,1,15,none,none)/C:\My Images\Image1.jpg`

I tried replacing the spaces with '%20% and also URL Encoding the path to the local images but it it errors out with a timeout.....

**Comment by devppjr** [comment]
@JPH71 you can use py3 to setup a local python server, like:

```
$ python3 -m http.server 8888
Serving HTTP on :: port 8888 (http://[::]:8888/) ...
```

ps: You need to start this python server in your image directory, and access `http://localhost:8888/image.jpeg`

**Comment by guilhermef** [comment]
@JPH71 the default image loader is the HTTP one: https://github.com/thumbor/thumbor/blob/master/thumbor/config.py#L295

To load from your filesystem and HTTP, you would need to switch to this one: https://github.com/thumbor/thumbor/blob/master/thumbor/loaders/file_loader_http_fallback.py

**Comment by JPH71** [comment]
Thanks Guilherm...
I am using it from within Plex.... based on Python 2.7.1

I will try and see if there is a thumbor version for this

Cheers
