### ISSUE TITLE
Malformed URL (signed url) doesn't work version Official Image

### ISSUE THREAD

**Issue by WebLeash** [thumbor/thumbor#1527]
### Thumbor request URL
[The request url for the issue you are having, you can swap the host name with a fake](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/440px-Cat03.jpg)

### Expected behaviour
Should render to to browser

### Actual behaviour
 thumbor:WARNING Malformed URL: /BKVuzv_BjIWOHTc-dgPcxQW2JAg=/800x0/smart/*

### Operating system
[Docker image. ](python:3.9.15-slim-bullseye)
Also Official Image.
[https://hub.docker.com/layers/thumbororg/thumbor/latest/images/sha256-e0df028515a8cf[…]736038ccb878db780632b0d1ef5fe2aac601ea73cae82?context=explore](https://hub.docker.com/layers/thumbororg/thumbor/latest/images/sha256-e0df028515a8cff3f0d736038ccb878db780632b0d1ef5fe2aac601ea73cae82?context=explore)

### Your thumbor.conf
``` 
       SECURITY_KEY="88888888"
        ALLOW_UNSAFE_URL="True"
        AUTO_WEBP="True"
        ALLOW_OLD_URLS="True"
        MAX_WIDTH="1920"
        LOADER = "thumbor.compatibility.loade"
        COMPATIBILITY_LEGACY_LOADER = "tc_aws.loaders.s3_loader"
        PORT             = ""
        QUALITY="70"
        HTTP_LOADER_VALIDATE_CERTS = "False"
        MAX_AGE="360000"
        MAX_AGE_TEMP_IMAGE = "60"
        ENV_NAME              = ""
        DETECTORS="['thumbor.detectors.feature_detector','thumbor.detectors.face_detector']"
        AWS_ACCESS_KEY_ID= *
        AWS_SECRET_ACCESS_KEY=  *
        TC_AWS_REGION="eu-west-2"
        TC_AWS_STORAGE_BUCKET= *
        TC_AWS_STORAGE_ROOT_PATH="storage"
        TC_AWS_RESULT_STORAGE_BUCKET=* 
        TC_AWS_RESULT_STORAGE_ROOT_PATH="result_storage"
        STORAGE="tc_aws.storages.s3_storage"
        UPLOAD_PHOTO_STORAGE="tc_aws.storages.s3_storage"
        RESULT_STORAGE="tc_aws.result_storages.s3_storage"
        
        We tried unsafe mode and this worked. 
        Only when we encrypt URL with signed algorithm fails.
        
        We tried various options, removing the https etc. Still not working.

**Comment by WebLeash** [comment]
We tried all the variants of  LOADER.

**Comment by scorphus** [comment]
Please make sure to use `thumbor-url`. It's part of the Thumbor release.

Please, follow along:

0. Read the manual:
   - https://thumbor.readthedocs.io/en/latest/running.html
   - https://thumbor.readthedocs.io/en/latest/configuration.html?highlight=security_key#security-key
   - https://thumbor.readthedocs.io/en/latest/security.html?highlight=security_key#stopping-tampering
1. Take a look at `thumbor-url` usage:
```
$ docker run -ti --rm --entrypoint thumbor-url thumbororg/thumbor --help
Usage: thumbor-url [options] imageurl or type thumbor-url -h (--help) for help

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -l KEY_FILE, --key_file=KEY_FILE
                        The file to read the security key from [default:
                        none].
  -k KEY, --key=KEY     The security key to encrypt the url with [default:
                        none].
  -w WIDTH, --width=WIDTH
                        The target width for the image [default: 0].
  -e HEIGHT, --height=HEIGHT
                        The target height for the image [default: 0].
  -n, --fitin           Indicates that fit-in resizing should be performed.
  -m, --meta            Indicates that meta information should be retrieved.
  --adaptive            Indicates that adaptive fit-in cropping should be
                        used.
  --full                Indicates that fit-full cropping should be used.
  -s, --smart           Indicates that smart cropping should be used.
  -t, --trim            Indicate that surrounding whitespace should be
                        trimmed.
  -f, --horizontal-flip
                        Indicates that the image should be horizontally
                        flipped.
  -v, --vertical-flip   Indicates that the image should be vertically flipped.
  -a HALIGN, --halign=HALIGN
                        The horizontal alignment to use for cropping [default:
                        center].
  -i VALIGN, --valign=VALIGN
                        The vertical alignment to use for cropping [default:
                        middle].
  --filters=FILTERS     Filters to be applied to the image, e.g.
                        brightness(10).
  -c CROP, --crop=CROP  The coordinates of the points to manual cropping in
                        the format leftxtop:rightxbottom (100x200:400x500)
                        [default: none].
```
3. Generate the signed URL for `https://upload.wikimedia.org/wikipedi a/commons/thumb/3/3a/Cat03.jpg/440px-Cat03.jpg`:
```
$ docker run -ti --rm --entrypoint thumbor-url thumbororg/thumbor -k 88888888 https://upload.wikimedia.org/wikipedi a/commons/thumb/3/3a/Cat03.jpg/440px-Cat03.jpg
URL:
/0bnGh5NuWUoAgpzoJTeExgyR9Ew=/https%3A//upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/440px-Cat03.jpg
```
4. Run Thumbor on exposed port `8888`, in debug mode, with config file being read from a bind mount:
```
$ docker run --mount type=bind,source=(pwd),target=/app -p 8888:8888 -ti --rm thumbororg/thumbor -p 8888 -l DEBUG -d -c /app/thumbor.conf
```
5. Access `http://0.0.0.0:8888/0bnGh5NuWUoAgpzoJTeExgyR9Ew=/https%3A//upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/440px-Cat03.jpg` with no errors.
6. Before you leave, check https://github.com/thumbor/libthumbor

**Comment by VladimirZD** [comment]
It seems we have found the issue. We used [APSL docker image](https://github.com/APSL/docker-thumbor) yesterday and switched to the official Thumbor as that APSL was old.

APSL version has used ENV vars to set params and the official version uses only a config file if I am not mistaken.

**Comment by VladimirZD** [comment]
After bit digging in source code it seems that we need to add one more param to use ENV vars
`docker run --rm --name thumbor -e SECURITY_KEY="Magic" -p 8888:8888 thumbororg/thumbor --use-environment=True`
This works.
