### ISSUE TITLE
"Forbidden" Issue with S3 bucket. 

### ISSUE THREAD

**Issue by WebLeash** [thumbor/thumbor#1528]
### Thumbor request URL
example.com

### Expected behaviour
File uploaded to S3 bucket. 

### Actual behaviour
_RROR ERROR: Traceback (most recent call last):
  File "/home/thumbor/venv/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/thumbor/venv/lib/python3.9/site-packages/thumbor/handlers/imaging.py", line 119, in get
    return await self.check_image(kw)
  File "/home/thumbor/venv/lib/python3.9/site-packages/thumbor/handlers/imaging.py", line 28, in check_image
    exists = await self.context.modules.storage.exists(
  File "/home/thumbor/venv/lib/python3.9/site-packages/tc_aws/storages/s3_storage.py", line 116, in exists
    file_key = self.storage.get_key(file_abspath)
  File "/home/thumbor/venv/lib/python3.9/site-packages/boto/s3/bucket.py", line 193, in get_key
    key, resp = self._get_key_internal(key_name, headers, query_args_l)
  File "/home/thumbor/venv/lib/python3.9/site-packages/boto/s3/bucket.py", line 231, in _get_key_internal
    raise self.connection.provider.storage_response_error(
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden_

### Operating system
Base Image. 
python:3.9.15-slim-bullseye

### Your thumbor.conf
   HTTP_LOADER_VALIDATE_CERTS      = "False"
        ALLOW_OLD_URLS                  = "True"
        ALLOW_UNSAFE_URL                = "True"
        FORWARDED_ALLOWED_IPS           = "0.0.0.0"
        SECURITY_KEY                    = "**********"
        HTTP_ADDRESS                    = "0.0.0.0"
        AUTO_WEBP                       = "True"
        QUALITY                         = "70"
        MAX_AGE_TEMP_IMAGE              = "60"
        AWS_ACCESS_KEY_ID               = "*************"
        AWS_SECRET_ACCESS_KEY           = "************"
        TC_AWS_REGION                   = "******"
        TC_AWS_STORAGE_BUCKET           = "s3-bucket-name"
        TC_AWS_STORAGE_ROOT_PATH        = "storage"
        TC_AWS_RESULT_STORAGE_BUCKET    = "s3-bucket-name"
        TC_AWS_RESULT_STORAGE_ROOT_PATH = "result_storage"
        STORAGE                         = "tc_aws.storages.s3_storage"
        UPLOAD_PHOTO_STORAGE            = "tc_aws.storages.s3_storage"
        COMPATIBILITY_LEGACY_LOADER     = "tc_aws.loaders.s3_loader"
        LOADER                          = "thumbor.compatibility.loader"
        RESULT_STORAGE                  = "tc_aws.result_storages.s3_storage"

**Comment by WebLeash** [comment]
We added **--use-environment=True** parameter as the CMD in dockerfile. 
_CMD thumbor -p $PORT --use-environment=True_

**Comment by WebLeash** [comment]
We also installed installed additional python module. Successfully. 
_`pip install tc-aws==1`_

**Comment by WebLeash** [comment]
Also when "QUALITY = 70" we get "**ValueError: Invalid quality setting**"
Possible issue maybe with env vars being passed.

**Comment by devppjr** [comment]
Hello @WebLeash, env vars are string values. So when you try to apply this config (Quality) with type string the pillow engine will broke. Looking in the [docs](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg-saving) of pillow, the method save just accept quality `0-95` with integer value, or the string `keep`. You can keep this configuration in `thumbor.conf` and use in cmd like `CMD thumbor -p $PORT -c path/to/thumbor.conf --use-environment=True`.

**Comment by VladimirZD** [comment]
@devppjr Shouldn't that work , in docs says ENV vars can be used
https://thumbor.readthedocs.io/en/latest/configuration.html?highlight=ENVIRONMENT#override-config-through-environment-variable

**Comment by guilhermef** [comment]
@devppjr I think there's an issue with derpconf. It might be assigning every value as a string, instead of an integer when it's set via environment variable.

**Comment by VladimirZD** [comment]
Yes that is issue, you can set any string setting via ENV vars, but numeric ones nope..
