### ISSUE TITLE
Thumbor should process gifs in a faster way. 

### ISSUE THREAD

**Issue by maiagripp** [thumbor/thumbor#1539]
### Expected behaviour
Thumbor should process gifs in a faster way. 

### Actual behaviour
Thumbor is taking too long to process some gifs. So we run some tests using gifsicle (our actual process gifs lib) and pil to compare time processing on both.
![image](https://user-images.githubusercontent.com/44818833/209228770-56b17d7f-504a-46e3-b50d-0ccac98bd693.png)

### Conclusion
We thought, although Gifsicle indeed had a better performance in flips, pil had better processing times in all the others. We don't think the flip filter is heavily used, so the trade off pays itself.

**Comment by maiagripp** [comment]
@scorphus @guilhermef @kkopachev thoughts about that?

**Comment by guilhermef** [comment]
I agree with you @maiagripp, using Pil to process GIFs would definitely be an improvement.

**Comment by scorphus** [comment]
I seem to be missing something. Usage of §gifsicle§ is optional and `pil` (or whatever engine is configured) is used whenever `USE_GIFSICLE_ENGINE` is set to `None`:

https://github.com/thumbor/thumbor/blob/c30b20863f516c3414f47826717be7c1c7e065cc/thumbor/handlers/__init__.py#L340

Perhaps we should adapt that line and document the behavior.

**Comment by scorphus** [comment]
Also, this might be a good opportunity to support the `cover` _"filter"_ when `gifsicle` isn't enabled.

**Comment by maiagripp** [comment]
Hey @scorphus,
indeed you are right. 
But we ran some tests comparing how Thumbor process GIFs using PIL and the engine we made and still we got better results.
Here what we got:

```
Processing Time
Crop 
Thumbor                 | Engine
real	0m20.348s         real	0m13.656s

Flips
Thumbor                 | Engine
real	0m22.240s         real	0m11.058s
real	0m20.546s         real	0m12.156s

Resize
Thumbor                 | Engine
real	0m58.331s         real	0m17.397s


Cover
Thumbor                  | Engine
(doesn't work)             real	0m9.699s

Content-Length 
Thumbor                  | Engine
Content-Length: 97324349   Content-Length: 38657490
```

And the visual result is also better.
On the left side is Thumbor and on the right side is the engine
![Visual Results Thumbor X Engine](https://user-images.githubusercontent.com/44818833/210262571-e564851f-9185-4ca9-91c3-85b32152c4e9.png)

**Comment by marcelometal** [comment]
@maiagripp please, share your code changes  =)

**Comment by maiagripp** [comment]
Here it is:
[Code Gist](https://gist.github.com/maiagripp/5f25b0ec28d323cb170279672e29f893)

Could you take a look and share your thoughts? 
@marcelometal @scorphus @guilhermef
