### ISSUE TITLE
Docker image variant with face/feature detection?

### ISSUE THREAD

**Issue by mpdude** [thumbor/thumbor#1561]
It seems that the Docker image provided by/since #1496 does not support feature/face detection, as the necessary libraries (which ones?) are not installed.

Do you think you could provide an image variant supporting this feature?

Or, alternatively, guidance on how to build custom images based on the official one including information how to and which libraries, system packages or wheels need to be installed?

**Comment by gdegoulet** [comment]
[Dockerfile.remotecv.txt](https://github.com/thumbor/thumbor/files/11611140/Dockerfile.remotecv.txt)

```
docker build -t thumbor_with_remotecv -f Dockerfile.remotecv .

echo "
DETECTORS = [ 'thumbor.detectors.face_detector','thumbor.detectors.feature_detector' ]
FACE_DETECTOR_CASCADE_FILE = 'haarcascade_frontalface_alt.xml'
GLASSES_DETECTOR_CASCADE_FILE = 'haarcascade_eye_tree_eyeglasses.xml'
PROFILE_DETECTOR_CASCADE_FILE = 'haarcascade_profileface.xml'
RESULT_STORAGE = 'thumbor.result_storages.file_storage'" > /tmp/thumbor.conf

docker run --rm -it --entrypoint /home/thumbor/venv/bin/thumbor-doctor -v/tmp/thumbor.conf:/tmp/thumbor.conf thumbor_with_remotecv -c /tmp/thumbor.conf
```

...
Verifying extensibility modules found in your thumbor.conf...

✅ thumbor.storages.file_storage
✅ thumbor.loaders.http_loader
✅ thumbor.result_storages.file_storage
✅ thumbor.engines.pil
✅ thumbor.detectors.face_detector
✅ thumbor.detectors.feature_detector
✅ thumbor.filters.background_color
...

**Comment by jaap3** [comment]
I opened a similar issue a while ago https://github.com/thumbor/thumbor/issues/1551, sadly it has gone stale and was auto closed

**Comment by heynemann** [comment]
@guilhermef can you take a look at it?

**Comment by guilhermef** [comment]
I'll have a look this weekend.

**Comment by guilhermef** [comment]
@jaap3 @mpdude The newer images now have support to openCV.

https://hub.docker.com/layers/thumbororg/thumbor/7.5.2-py-3.11/images/sha256-6ba7f8ec037e6b13b50324854181620ade22e0d056cb118651f0596c7ce5d5d4?context=explore
