### ISSUE TITLE
Install Thumbor Error - Python 2.7

### ISSUE THREAD

**Issue by JPH71** [thumbor/thumbor#1570]
I am trying to install thumbor using the following

pip install thumbor

but I get the following error:
![InstallThumbor](https://github.com/thumbor/thumbor/assets/43102249/5a1b5d7b-3969-4ffc-bf08-cd9d9c266e65)

What is the latest version of Thumbor that works with Python 2.7 - would this be the reason....

**Comment by marcelometal** [comment]
Hi @JPH71,

try to use 6.7.6

https://github.com/thumbor/thumbor/releases/tag/6.7.6

**Comment by JPH71** [comment]
Many Thanks!!!

**Comment by JPH71** [comment]
Hi there

I have just tried to install version 6.7.6: No difference:
![image](https://github.com/thumbor/thumbor/assets/43102249/e28061ce-be99-44f7-9ae1-848ab8896642)

still failing on pyCurl

**Comment by scorphus** [comment]
Hey, @JPH71, Python 2 is long discontinued (3+ years ago) and we unfortunately do not offer support for it anymore. I'm sorry to let you know that we have no bandwidth to do so.
