### ISSUE TITLE
Thumbor filters not working on pictures from website

### ISSUE THREAD

**Issue by JPH71** [thumbor/thumbor#1571]
I do not have thumbor installed on my system, but use its cloud based service which is renewed every 90 days or so...

I can open this image:
https://gayeroticvideoindex.com/episode/184348

But when I try to rotate it or change it to grayscale
http://34.150.135.138:8888/unsafe/filters:rotate(270)/https://gayeroticvideoindex.com/episode/184348

I get the following:
![image](https://github.com/thumbor/thumbor/assets/43102249/5f68306c-83aa-4b88-a1ff-7a4a2e867383)

However, for the following it works???
http://34.150.135.138:8888/unsafe/filters:rotate(270)/https://www.iafd.com/graphics/headshots/shawnreeves_m_shawn%20reeve.jpg
![image](https://github.com/thumbor/thumbor/assets/43102249/feeff7b9-35fb-4b52-bf18-027069e91c81)

What am I doing wrong: what would prevent thumbor working on one website and not the other?

**Comment by gdegoulet** [comment]
http status code : 403 + it 's not an "image" url ...

**Comment by JPH71** [comment]
my mistake it should have been

http://34.150.135.138:8888/unsafe/filters:rotate(270)/https://gayeroticvideoindex.com/images/Episodes/episode184348b.jpg

Many thanks for taking the time...

**Comment by gdegoulet** [comment]
ok, https://gayeroticvideoindex.com/images/Episodes/episode184348b.jpg is now an image url but thumbor can't access to it because the url is protected by a "cloudflare  challenge" ( https://developers.cloudflare.com/fundamentals/get-started/concepts/cloudflare-challenges/ )

**Comment by JPH71** [comment]
Thank you for your help on this...

Cheers
