### ISSUE TITLE
Local Images

### ISSUE THREAD

**Issue by JPH71** [thumbor/thumbor#1573]
I previously had an issue whereby Thumbor could not access the image because of Cloudflare.

Is there a way I can use Thumbor to perform the same procedure on a local image:

For example I download this image : https://gayeroticvideoindex.com/images/Episodes/episode184348b.jpg and store it in C:\Temp

How would I correctly do this?
http://34.150.135.138:8888/unsafe/filters:rotate(270)/C:\Temp\episode184348b.jpg

**Comment by scorphus** [comment]
As documented in https://thumbor.readthedocs.io/en/latest/image_loader.html#file-loader, you can set `LOADER` and `FILE_LOADER_ROOT_PATH` on your `thumbor.conf` accordingly.

For example:

```python
# ...
LOADER = "thumbor.loaders.file_loader"
FILE_LOADER_ROOT_PATH = "C:\Temp"
# ...
```
