### ISSUE TITLE
Can't use https loader on domain with self signed certificate

### ISSUE THREAD

**Issue by sebastienroux** [thumbor/thumbor#1574]
### Thumbor request URL
/unsafe/0x0/filters:format(webp)/https://mydomain.fr/media/catalog/photo.png 

### Expected behaviour
I can't get thumbor to work with the https loader and a self-signed certificate.

Here is the call log: 

```
2023-06-21 15:24:06 thumbor:ERROR [BaseHandler] get_image failed for url `https%3A//mydomain.fr/media/catalog/photo.png`. error: `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)`
2023-06-21 15:24:06 tornado.access:ERROR 500 GET /unsafe/0x0/filters:format(webp)/https://mydomain.fr/media/catalog/photo.png (X.X.X.X) 485.67ms
```

I tried to set HTTP_LOADER_VALIDATE_CERTS=false, add the certificate in the thumbor docker image ( by retrieving it with echo -n | openssl s_client -connect mydomain.fr/:443 -servername mydomain.fr/ | openssl x509 > cert.crt

Create my docker image with the certificate : 
FROM thumbororg/thumbor:7.5.1-py-3.9
COPY cert.pem /etc/ssl/certs/certif.pem

And use conf:
HTTP_LOADER_CA_CERTS: "/etc/ssl/certs/certif.pem"

But nothing changes, I can't use the https loader on a domain with a self-signed certificate.

### Operating system
Thumbor Docker image

### Your thumbor.conf
ALLOWED_SOURCES =  ['.*']
    ALLOW_UNSAFE_URL = "True"
    RESULT_STORAGE_STORES_UNSAFE = "True"
    RESULT_STORAGE = 'thumbor.result_storages.file_storage'
    FILE_STORAGE_ROOT_PATH = '/data/storage/source'
    RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/data/storage/result'
    CORS_ALLOW_ORIGIN: "*"
    HEALTHCHECK_ROUTE: "/healthcheck"
    THUMBOR_LOG_CONFIG: "JSON"
    HTTP_LOADER_CA_CERTS: "/etc/ssl/certs/certif.pem"
    LOADER: "thumbor.loaders.https_loader"

**Comment by scorphus** [comment]
It should work with `HTTP_LOADER_VALIDATE_CERTS = False` — which, I must add, should not be used in production, although I'm confident you know that 😊

Please, make sure you have the following entry in your `thumbor.conf`:

```python
HTTP_LOADER_VALIDATE_CERTS = False  # attention: no single nor double quotes here
```

Also make sure you're setting other boolean variables accordingly (with no quotes), such as:

```python
RESULT_STORAGE_STORES_UNSAFE = True
```
