### ISSUE TITLE
i want the filenames and paths of the results storage to be unhashed.

### ISSUE THREAD

**Issue by SeonJae83** [thumbor/thumbor#1576]
hi. I'm not a developer

I'm trying to use thumbor's attractive features.

After saving the resized image as a result, I am trying to use the file in another program.

please help me

### Thumbor request URL
http://192.168.1.50:6081/unsafe/250x250/https://www.sample.com/wp-content/uploads/2023/04/logo.png

### Expected behaviour
Result storage is enabled.
Save as the unencrypted image file name and use the path or
I want to know the means to see the matching result.

### Actual behaviour
hash? sha1? It is displayed as an encrypted file name and path.

### Operating system
CentOS 7.10, Python3.9, thumbor 7.5.1

## Defaults to: None
#THUMBOR_LOG_CONFIG = None

## Defaults to: '%(asctime)s %(name)s:%(levelname)s %(message)s'
#THUMBOR_LOG_FORMAT = '%(asctime)s %(name)s:%(levelname)s %(message)s'

## Defaults to: '%Y-%m-%d %H:%M:%S'
#THUMBOR_LOG_DATE_FORMAT = '%Y-%m-%d %H:%M:%S'

################################################################################

## Defaults to: 0
#MAX_WIDTH = 0

## Defaults to: 0
#MAX_HEIGHT = 0

## Defaults to: 75000000.0
#MAX_PIXELS = 75000000.0

## Defaults to: 1
#MIN_WIDTH = 1

## Defaults to: 1
#MIN_HEIGHT = 1

## Defaults to: [
#]

#ALLOWED_SOURCES = [
#]

## Defaults to: 80
QUALITY = 95

## Defaults to: True
#PROGRESSIVE_JPEG = True

## Defaults to: None
#PILLOW_JPEG_SUBSAMPLING = None

## Defaults to: None
#PILLOW_JPEG_QTABLES = None

## Defaults to: 'LANCZOS'
#PILLOW_RESAMPLING_FILTER = 'LANCZOS'

## Defaults to: None
#WEBP_QUALITY = None

## Defaults to: None
#AVIF_QUALITY = None

## Defaults to: None
#AVIF_SPEED = None

## Defaults to: 'auto'
#AVIF_CODEC = 'auto'

## Defaults to: 'auto'
#AVIF_CODEC_FALLBACK = 'auto'

## Defaults to: None
#HEIF_QUALITY = None

## Defaults to: None
#SRGB_PROFILE = None

## Defaults to: 6
#PNG_COMPRESSION_LEVEL = 6

## Defaults to: True
#PILLOW_PRESERVE_INDEXED_MODE = True

## Defaults to: False
#AUTO_WEBP = False

## Defaults to: False
#AUTO_AVIF = False

## Defaults to: False
#AUTO_JPG = False

## Defaults to: False
#AUTO_HEIF = False

## Defaults to: False
#AUTO_PNG_TO_JPG = False

## Defaults to: 150
#SVG_DPI = 150

## Defaults to: 86400
#MAX_AGE = 86400

## Defaults to: 0
#MAX_AGE_TEMP_IMAGE = 0

## Defaults to: False
#RESPECT_ORIENTATION = False

## Defaults to: False
#IGNORE_SMART_ERRORS = False

## Defaults to: False
#SEND_IF_MODIFIED_LAST_MODIFIED_HEADERS = False

## Defaults to: False
PRESERVE_EXIF_INFO = True

## Defaults to: False
#PRESERVE_EXIF_COPYRIGHT_INFO = False

## Defaults to: False
#PRESERVE_IPTC_INFO = False

## Defaults to: True
#ALLOW_ANIMATED_GIFS = True

## Defaults to: False
#USE_GIFSICLE_ENGINE = False

## Defaults to: False
#USE_BLACKLIST = False

## Defaults to: 0
#ENGINE_THREADPOOL_SIZE = 0

################################################################################

## Defaults to: 'thumbor.metrics.logger_metrics'
#METRICS = 'thumbor.metrics.logger_metrics'

## Defaults to: 'thumbor.loaders.http_loader'
#LOADER = 'thumbor.loaders.http_loader'

## Defaults to: 'thumbor.storages.file_storage'
STORAGE = 'thumbor.storages.file_storage'

## Defaults to: None
#RESULT_STORAGE = None
RESULT_STORAGE = 'thumbor.result_storages.file_storage'

## Defaults to: 'thumbor.engines.pil'
#ENGINE = 'thumbor.engines.pil'

## Defaults to: 'thumbor.engines.gif'
#GIF_ENGINE = 'thumbor.engines.gif'

## Defaults to: 'libthumbor.url_signers.base64_hmac_sha1'
#URL_SIGNER = 'libthumbor.url_signers.base64_hmac_sha1'

################################################################################

## Defaults to: True
#ALLOW_UNSAFE_URL = True

################################################################################

## Defaults to: True
ENABLE_ETAGS = False

################################################################################

## Defaults to: 32
#MAX_ID_LENGTH = 32

################################################################################

## Defaults to: None
#GC_INTERVAL = None

################################################################################

## Defaults to: '/healthcheck/?'
#HEALTHCHECK_ROUTE = '/healthcheck/?'

################################################################################

## Defaults to: None
#STATSD_HOST = None

## Defaults to: 8125
#STATSD_PORT = 8125

## Defaults to: None
#STATSD_PREFIX = None

################################################################################

## Defaults to: '/root'
#FILE_LOADER_ROOT_PATH = '/root'

################################################################################

## Defaults to: 5
#HTTP_LOADER_CONNECT_TIMEOUT = 5

## Defaults to: 20
#HTTP_LOADER_REQUEST_TIMEOUT = 20

## Defaults to: True
#HTTP_LOADER_FOLLOW_REDIRECTS = True

## Defaults to: 5
#HTTP_LOADER_MAX_REDIRECTS = 5

## Defaults to: 10
#HTTP_LOADER_MAX_CLIENTS = 10

## Defaults to: False
#HTTP_LOADER_FORWARD_USER_AGENT = False

## Defaults to: False
#HTTP_LOADER_FORWARD_ALL_HEADERS = False

## Defaults to: [
#]

#HTTP_LOADER_FORWARD_HEADERS_WHITELIST = [
#]

## Defaults to: 'Thumbor/7.5.0'
#HTTP_LOADER_DEFAULT_USER_AGENT = 'Thumbor/7.5.0'

## Defaults to: None
#HTTP_LOADER_PROXY_HOST = None

## Defaults to: None
#HTTP_LOADER_PROXY_PORT = None

## Defaults to: None
#HTTP_LOADER_PROXY_USERNAME = None

## Defaults to: None
#HTTP_LOADER_PROXY_PASSWORD = None

## Defaults to: None
#HTTP_LOADER_CA_CERTS = None

## Defaults to: None
#HTTP_LOADER_VALIDATE_CERTS = None

## Defaults to: None
#HTTP_LOADER_CLIENT_KEY = None

## Defaults to: None
#HTTP_LOADER_CLIENT_CERT = None

## Defaults to: False
#HTTP_LOADER_CURL_ASYNC_HTTP_CLIENT = False

################################################################################

## Defaults to: 0
#HTTP_LOADER_CURL_LOW_SPEED_TIME = 0

## Defaults to: 0
#HTTP_LOADER_CURL_LOW_SPEED_LIMIT = 0

## Defaults to: False
#NON_BLOCKING_SOCKETS = False

## Defaults to: 'thumbor.app.ThumborServiceApp'
#APP_CLASS = 'thumbor.app.ThumborServiceApp'

## Defaults to: False
#ACCESS_CONTROL_ALLOW_ORIGIN_HEADER = False

################################################################################

## Defaults to: 2592000
STORAGE_EXPIRATION_SECONDS = 0

## Defaults to: False
STORAES_CRYPTO_KEY_FOR_EACH_IMAGE = True

## Defaults to: '/tmp/thumbor/storage'
#FILE_STORAGE_ROOT_PATH = '/tmp/thumbor/storage'

################################################################################

## Defaults to: 0
#UPLOAD_MAX_SIZE = 0

## Defaults to: False
#UPLOAD_ENABLED = False

## Defaults to: 'thumbor.storages.file_storage'
#UPLOAD_PHOTO_STORAGE = 'thumbor.storages.file_storage'

## Defaults to: False
#UPLOAD_DELETE_ALLOWED = False

## Defaults to: False
#UPLOAD_PUT_ALLOWED = False

## Defaults to: 'image'
#UPLOAD_DEFAULT_FILENAME = 'image'

################################################################################

## Defaults to: 'thumbor.storages.no_storage'
#MIXED_STORAGE_FILE_STORAGE = 'thumbor.storages.no_storage'

## Defaults to: 'thumbor.storages.no_storage'
#MIXED_STORAGE_CRYPTO_STORAGE = 'thumbor.storages.no_storage'

## Defaults to: 'thumbor.storages.no_storage'
#MIXED_STORAGE_DETECTOR_STORAGE = 'thumbor.storages.no_storage'

################################################################################

## Defaults to: None
#META_CALLBACK_NAME = None

################################################################################

## Defaults to: [
#]

#DETECTORS = [
#]

## Defaults to: 'haarcascade_frontalface_alt.xml'
#FACE_DETECTOR_CASCADE_FILE = 'haarcascade_frontalface_alt.xml'

## Defaults to: 'haarcascade_eye_tree_eyeglasses.xml'
#GLASSES_DETECTOR_CASCADE_FILE = 'haarcascade_eye_tree_eyeglasses.xml'

## Defaults to: 'haarcascade_profileface.xml'
#PROFILE_DETECTOR_CASCADE_FILE = 'haarcascade_profileface.xml'

################################################################################

## Defaults to: [
#]

#OPTIMIZERS = [
#]

## Defaults to: '/usr/bin/jpegtran'
#JPEGTRAN_PATH = '/usr/bin/jpegtran'

## Defaults to: ''
#JPEGTRAN_SCANS_FILE = ''

## Defaults to: '/usr/local/bin/ffmpeg'
#FFMPEG_PATH = '/usr/local/bin/ffmpeg'

################################################################################

## Defaults to: [
#    'thumbor.filters.brightness',
#    'thumbor.filters.colorize',
#    'thumbor.filters.contrast',
#    'thumbor.filters.rgb',
#    'thumbor.filters.round_corner',
#    'thumbor.filters.quality',
#    'thumbor.filters.noise',
#    'thumbor.filters.watermark',
#    'thumbor.filters.equalize',
#    'thumbor.filters.fill',
#    'thumbor.filters.sharpen',
#    'thumbor.filters.strip_exif',
#    'thumbor.filters.strip_icc',
#    'thumbor.filters.frame',
#    'thumbor.filters.grayscale',
#    'thumbor.filters.rotate',
#    'thumbor.filters.format',
#    'thumbor.filters.max_bytes',
#    'thumbor.filters.convolution',
#    'thumbor.filters.blur',
#    'thumbor.filters.extract_focal',
#    'thumbor.filters.focal',
#    'thumbor.filters.no_upscale',
#    'thumbor.filters.saturation',
#    'thumbor.filters.max_age',
#    'thumbor.filters.curve',
#    'thumbor.filters.background_color',
#    'thumbor.filters.upscale',
#    'thumbor.filters.proportion',
#    'thumbor.filters.stretch',
#]

#FILTERS = [
#    'thumbor.filters.brightness',
#    'thumbor.filters.colorize',
#    'thumbor.filters.contrast',
#    'thumbor.filters.rgb',
#    'thumbor.filters.round_corner',
#    'thumbor.filters.quality',
#    'thumbor.filters.noise',
#    'thumbor.filters.watermark',
#    'thumbor.filters.equalize',
#    'thumbor.filters.fill',
#    'thumbor.filters.sharpen',
#    'thumbor.filters.strip_exif',
#    'thumbor.filters.strip_icc',
#    'thumbor.filters.frame',
#    'thumbor.filters.grayscale',
#    'thumbor.filters.rotate',
#    'thumbor.filters.format',
#    'thumbor.filters.max_bytes',
#    'thumbor.filters.convolution',
#    'thumbor.filters.blur',
#    'thumbor.filters.extract_focal',
#    'thumbor.filters.focal',
#    'thumbor.filters.no_upscale',
#    'thumbor.filters.saturation',
#    'thumbor.filters.max_age',
#    'thumbor.filters.curve',
#    'thumbor.filters.background_color',
#    'thumbor.filters.upscale',
#    'thumbor.filters.proportion',
#    'thumbor.filters.stretch',
#]

################################################################################

## Defaults to: 0
RESULT_STORAGE_EXPIRATION_SECONDS = 0

## Defaults to: '/tmp/thumbor/result_storage'
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/tmp/thumbor/result_storage'

## Defaults to: False
RESULT_STORAGE_STORES_UNSAFE = True

################################################################################

## Defaults to: 'localhost'
#REDIS_QUEUE_SERVER_HOST = 'localhost'

## Defaults to: 6379
#REDIS_QUEUE_SERVER_PORT = 6379

## Defaults to: 0
#REDIS_QUEUE_SERVER_DB = 0

## Defaults to: None
#REDIS_QUEUE_SERVER_PASSWORD = None

## Defaults to: 'single_node'
#REDIS_QUEUE_MODE = 'single_node'

## Defaults to: 'localhost:26379'
#REDIS_QUEUE_SENTINEL_INSTANCES = 'localhost:26379'

## Defaults to: None
#REDIS_QUEUE_SENTINEL_PASSWORD = None

## Defaults to: 'master'
#REDIS_QUEUE_SENTINEL_MASTER_INSTANCE = 'master'

## Defaults to: None
#REDIS_QUEUE_SENTINEL_MASTER_PASSWORD = None

## Defaults to: 0
#REDIS_QUEUE_SENTINEL_MASTER_DB = 0

## Defaults to: 10.0
#REDIS_QUEUE_SENTINEL_SOCKET_TIMEOUT = 10.0

################################################################################

## Defaults to: None
#SQS_QUEUE_KEY_ID = None

## Defaults to: None
#SQS_QUEUE_KEY_SECRET = None

## Defaults to: 'us-east-1'
#SQS_QUEUE_REGION = 'us-east-1'

################################################################################

## Defaults to: False
#USE_CUSTOM_ERROR_HANDLING = False

## Defaults to: 'thumbor.error_handlers.sentry'
#ERROR_HANDLER_MODULE = 'thumbor.error_handlers.sentry'

## Defaults to: None
#ERROR_FILE_LOGGER = None

## Defaults to: False
#ERROR_FILE_NAME_USE_CONTEXT = False

################################################################################

## Defaults to: ''
#SENTRY_DSN_URL = ''

## Defaults to: None
#SENTRY_ENVIRONMENT = None

################################################################################

## Defaults to: 0
#MAX_WAIT_SECONDS_BEFORE_SERVER_SHUTDOWN = 0

## Defaults to: 0
#MAX_WAIT_SECONDS_BEFORE_IO_SHUTDOWN = 0

################################################################################

## Defaults to: [
#    'thumbor.handler_lists.healthcheck',
#    'thumbor.handler_lists.upload',
#    'thumbor.handler_lists.blacklist',
#]

#HANDLER_LISTS = [
#    'thumbor.handler_lists.healthcheck',
#    'thumbor.handler_lists.upload',
#    'thumbor.handler_lists.blacklist',
#]

################################################################################

## Defaults to: None
#COMPATIBILITY_LEGACY_LOADER = None

## Defaults to: None
#COMPATIBILITY_LEGACY_STORAGE = None

## Defaults to: None
#COMPATIBILITY_LEGACY_RESULT_STORAGE = None

################################################################################

**Comment by scorphus** [comment]
Here's where you want to look into:

https://github.com/thumbor/thumbor/blob/46964e7abd6604cac3179728d0115330c496d8eb/thumbor/result_storages/file_storage.py#L117-L126

Specifically, lines 118 and 126.

In other words:

```python
path = "/unsafe/250x250/https://www.sample.com/wp-content/uploads/2023/04/logo.png"
digest = hashlib.sha1(unquote(path).encode("utf-8")).hexdigest()
print(f"/.../{digest[:2]}/{digest[2:4]}/{digest[4:]}")  # /.../44/34/155a5d5134f4f6c7de2b9fd6c7bcbc93503c
```

**Comment by SeonJae83** [comment]
> 살펴보고 싶은 곳은 다음과 같습니다.
> 
> https://github.com/thumbor/thumbor/blob/46964e7abd6604cac3179728d0115330c496d8eb/thumbor/result_storages/file_storage.py#L117-L126
> 
> 특히 118행과 126행입니다.
> 
> 다시 말해서:
> 
> ```python
> path = "/unsafe/250x250/https://www.sample.com/wp-content/uploads/2023/04/logo.png"
> digest = hashlib.sha1(unquote(path).encode("utf-8")).hexdigest()
> print(f"/.../{digest[:2]}/{digest[2:4]}/{digest[4:]}")  # /.../44/34/155a5d5134f4f6c7de2b9fd6c7bcbc93503c
> ```

Thanks scorphus.
I found the syntax in file_storyge.py.

But I don't know how to fix it.... T.T
can you give me an example?

**Comment by SeonJae83** [comment]
> > 살펴보고 싶은 곳은 다음과 같습니다.
> > https://github.com/thumbor/thumbor/blob/46964e7abd6604cac3179728d0115330c496d8eb/thumbor/result_storages/file_storage.py#L117-L126
> > 
> > 특히 118행과 126행입니다.
> > 다시 말해서:
> > ```python
> > path = "/unsafe/250x250/https://www.sample.com/wp-content/uploads/2023/04/logo.png"
> > digest = hashlib.sha1(unquote(path).encode("utf-8")).hexdigest()
> > print(f"/.../{digest[:2]}/{digest[2:4]}/{digest[4:]}")  # /.../44/34/155a5d5134f4f6c7de2b9fd6c7bcbc93503c
> > ```
> 
> Thanks scorphus. I found the syntax in file_storyge.py.
> 
> But I don't know how to fix it.... T.T can you give me an example?
 
I decided to code and use it to produce the same result in JAVA, and the test was completed! Thank you for your help!
