### ISSUE TITLE
Why is a file generated every time a meta url is refreshed?

### ISSUE THREAD

**Issue by jinmarcus** [thumbor/thumbor#1577]
Why is a file generated every time a meta url is refreshed?

url：
http://127.0.0.1:8888/unsafe/meta/http://127.0.0.1:9999/test/5d8cce994c0190cbdb2f1e0914286c0a

These files are all from the same meta url.

Shouldn't only one file be correct?

![example](https://github.com/thumbor/thumbor/assets/17996289/a4da8be6-59d6-48bc-9987-e43af76ab883)

**Comment by scorphus** [comment]
That happens because of a bug for which a fix is already on its way. Thank you for reporting, @jinmarcus.
