### ISSUE TITLE
Compression Order in Docs not followed?

### ISSUE THREAD

**Issue by rhurling** [thumbor/thumbor#1584]
### Thumbor request URL
`curl -I -H 'Accept: image/avif,image/webp' "https://localhost:8888/image.jpg"`

### Expected behaviour
According to the docs Thumbor should return a file with the content-type `image/avif`, see [AUTO_*](https://thumbor.readthedocs.io/en/latest/configuration.html?highlight=avif#auto)

### Actual behaviour
Thumbor returns an image with content-type `image/webp`.
When I'm using `curl -I -H 'Accept: image/avif' "https://localhost:8888/image.jpg"`Thumbor correctly returns an image with `image/avif`

### Possible Error
I think the if/elseif/else in the [\_\_init\_\_.py](https://github.com/thumbor/thumbor/blob/master/thumbor/handlers/__init__.py#L485-L518) is in the wrong order which results in only checking if webp is possible and skipping everything else.
If I'm reading the docs correctly it should be in reverse order and first check for HEIF, then JPG, then AVIF and finally WEBP.

Or am I reading the docs incorrectly?

### Operating system
Debian 10, Thumbor 

### Your thumbor.conf
I'm using Thumbor behind an nginx proxy and without allowing filters and the more advanced processing.

```
AUTO_WEBP = True

AUTO_AVIF = True

MAX_AGE = 0

USE_GIFSICLE_ENGINE = True

LOADER = 'thumbor.loaders.file_loader'

ALLOW_UNSAFE_URL = True

FILE_LOADER_ROOT_PATH = '/web/cdn'

OPTIMIZERS = ['thumbor.optimizers.jpegtran']

JPEGTRAN_PATH = '/usr/bin/jpegtran'

ERROR_HANDLER_MODULE = None

STORAGE = 'thumbor.storages.no_storage'

QUALITY = 85
```

**Comment by rhurling** [comment]
As far as I can tell this is still an issue.

**Comment by scorphus** [comment]
> [snip]
> ### Actual behaviour
> 
> Thumbor returns an image with content-type `image/webp`. When I'm using `curl -I -H 'Accept: image/avif' "https://localhost:8888/image.jpg"`Thumbor correctly returns an image with `image/avif`
> [snip]

Isn't that the expected behavior? The docs state the precedence being [**_WEBP -> AVIF -> JPG -> HEIF_**](https://thumbor.readthedocs.io/en/latest/configuration.html?highlight=avif#auto), which matches the order of if statements. Perhaps that sentence should be further clarified in the docs?

cc/ @devppjr

**Comment by rhurling** [comment]
I read the docs as "WEBP to AVIF (if enabled) to JPG (if enabled and possible) to HEIF (if enabled)".  
In my opinion the arrows seem counterintuitive without any further information, since they suggest the conversion of WEBP to AVIF and further.
A better option would probably be additional text that specifies the order, something similar to this (don't quite know the appropriate wording) :

> These configurations indicates that thumbor will try to automatically convert the image format to a lighter image format, following a better compression order. The order in which formats will be tried (if enabled and possible): WEBP, AVIF, JPG, HEIF.

**Comment by devppjr** [comment]
@scorphus @rhurling Thank you for your contributions. I created [this pull request](https://github.com/thumbor/thumbor/pull/1599) to improve the documentation, what did you think? Accepting ideas 😄
