### ISSUE TITLE
Documentation update: quick start with docker

### ISSUE THREAD

**Issue by keul** [thumbor/thumbor#1589]
To quickstart with docker, the documentation suggest to use the MinimalCompact/thumbor image: https://github.com/thumbor/thumbor/blob/82309288806bfa63d7be446ccad1f028ff470b0f/docs/getting_started.rst?plain=1#L34:L39

But it seems that repo has stopped using docker.io, so just following the readme you are going to use a very old image.

I would suggest to highlight this in the documentation.

Another question: I also see this https://hub.docker.com/r/thumbororg/thumbor/tags which is unclear if is the new way to go, or a totally different image.

**Comment by mamchyts** [comment]
Fixed in https://github.com/thumbor/thumbor/pull/1620

**Comment by RaphaelVRossi** [comment]
I'm closing this! Thanks again @mamchyts
