### ISSUE TITLE
Documentation / Installation

### ISSUE THREAD

**Issue by Bro3x** [thumbor/thumbor#1630]
### Thumbor request URL
Option 2: Binary
sudo add-apt-repository ppa:thumbor/ppa
sudo aptitude update
sudo aptitude install thumbor

### Expected behaviour
Install thumbor

### Actual behaviour
# add-apt-repository ppa:thumbor/ppa
Repository: 'deb https://ppa.launchpadcontent.net/thumbor/ppa/ubuntu/ bookworm main'
More info: https://launchpad.net/~thumbor/+archive/ubuntu/ppa
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/thumbor-ubuntu-ppa-bookworm.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/thumbor-ubuntu-ppa-bookworm.list
Adding key to /etc/apt/trusted.gpg.d/thumbor-ubuntu-ppa.gpg with fingerprint 4655F10A58E74C6B923ED28468DFB11CCBEC8F27
...
Hit:7 http://deb.debian.org/debian bookworm-updates InRelease
Ign:8 https://ppa.launchpadcontent.net/thumbor/ppa/ubuntu bookworm InRelease
Err:9 https://ppa.launchpadcontent.net/thumbor/ppa/ubuntu bookworm Release
  404  Not Found [IP: 2620:2d:4000:1::81 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/thumbor/ppa/ubuntu bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### Operating system
Debain 12

**Comment by marcelometal** [comment]
Hi @Bro3x ,

I'm sorry about it, this PPA has ~10 years old. I will fix the docs.

Try to use via `pip`:
https://github.com/thumbor/thumbor?tab=readme-ov-file#option-1-pip

**Comment by Bro3x** [comment]
```
# pip install thumbor[all]
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

I managed it with pipx but had to install a lot of dependencies manually.

**Comment by lostfocus** [comment]
Hm, the stalebot closed this but I'm running into the same issues
