### ISSUE TITLE
Security - Eval Injection

### ISSUE THREAD

**Issue by dpramani** [thumbor/thumbor#1642]
Hi

I am using the 7.7.1th version of minimalcompact/thumbor in one of my apps.

Current version of pillow seems to be vulnerable to [Eval Injection](https://security.snyk.io/vuln/SNYK-PYTHON-PILLOW-6182918).

Are there releases that handles this ?

Thanks

**Comment by scorphus** [comment]
Thumbor makes no use of `ImageMath.eval`. Therefore it's not affected by vulnerability. Thanks for reporting, @dpramani

**Comment by dpramani** [comment]
Thanks @scorphus.

**Comment by dpramani** [comment]
@scorphus What's the current version of pillow being used ? Is it 10.0.1?

**Comment by marcelometal** [comment]
https://github.com/thumbor/thumbor/blob/master/setup.py#L154
