### ISSUE TITLE
Asynchronous file operations - os library

### ISSUE THREAD

**Issue by OndrejIT** [thumbor/thumbor#1650]
Hello,
While tuning thumbor for the company I work for, which handles a lot of traffic, I noticed that all the work with the files is not asynchronous (https://github.com/thumbor/thumbor/blob/master/thumbor/loaders/file_loader.py#L41 atc..). Thumbor uses the standard os library, which itself is blocking. Or am I mistaken?
If I'm right, I'd like to fix this with, for example, the aiofiles library that wraps the standard os, but I'd hate to do something unnecessary.

**Comment by RaphaelVRossi** [comment]
Hey @OndrejIT, thanks for reaching out.

Yes, in this case Thumbor is using the standard os library.

Thanks again for your time and consideration!
