### ISSUE TITLE
Can we add a text to the return images from thumbor

### ISSUE THREAD

**Issue by nhha1602** [thumbor/thumbor#1653]
Hi,

Due to the security, I want to add a text (for example, username) to the picture that returns from thumbor?
If yes, please advise the solution for this?

Thank you a lot.

**Comment by OndrejIT** [comment]
Hello, it is not possible to add text to images currently.
Actually, Thumbor only has a [watermark](https://thumbor.readthedocs.io/en/latest/watermark.html) filter.
By the way, this is a great idea for a new text filter.
If there is interest, I could create this filter.

**Comment by nhha1602** [comment]
Hi,
Yeah, please. Thank you a lot.

**Comment by marcelometal** [comment]
Hi,
This plugins provide a way to generate text via Thumbor filter:

https://github.com/wongnai/thumbor-text-filter
