### ISSUE TITLE
Endpoint Security.

### ISSUE THREAD

**Issue by christos-marres** [thumbor/thumbor#1680]
What is the proposed way of handling the endpoint security?

The issues that i am facing are the following:

### POST PUT DELETE Endpoints
From what i've seen in the documentation there is no security on those endpoints. So anyone could use them.

### GET Endpoint
Even though the hmac signature, protects from url tampering, it also completely discards thumbor's dynamic filtering capabilities. Say I already have signed urls for images served from our backend. And then we update our frontend and we need a slight change in the image filtering. Frontend can not sign the urls, because then the key would be exposed. So we would need to resign every image url on our database with the new filters. Am I missing something?

**Comment by heynemann** [comment]
You are not missing. But you can proxy the unsafe endpoint if you want to do so. That way your thumbor instance is not exposed and you get the dynamic capabilities.
