### ISSUE TITLE
Thumbor not delete the cache files in /data/storage/ directory

### ISSUE THREAD

**Issue by TheNha** [thumbor/thumbor#1682]
### Expected behaviour
Cache files should be deleted after 1 minute, in /data/storage/ directory.

### Actual behaviour
The files and directories are not deleted, example of files left in place, older than 5 minutes:
![image](https://github.com/user-attachments/assets/3743af4c-3509-4367-863a-64b9f0842144)

### Operating system
Debian GNU/Linux 10 (buster)

### Your thumbor.conf
STORAGE_EXPIRATION_SECONDS = 60
FILE_STORAGE_ROOT_PATH = '/data/storage'

**Comment by ook** [comment]
Even I’m not a specialist nor a maintener of Thumbor, I’m pretty sure there’s a misunderstanding here: `STORAGE_EXPIRATION_SECONDS` is about the time Thumbor will consider the source file in its cache as fresh enough for not checking again it didn’t change: for a given file, you won’t hit the loader more than once per minute. That doesn’t mean that thumbor will clean its cache, even it could be a nice iteration (see https://github.com/thumbor/thumbor/blob/252c5b10ff4766b8a09e0a017a11cb9912bf557a/thumbor/storages/file_storage.py#L134 ).

**Comment by vitorhugomattos** [comment]
that's it, @ook

**Comment by TheNha** [comment]
How can I clear cache in data/storage folder? @ook @vitorhugomattos . It's too full and the disk is overflowing.
