### ISSUE TITLE
Command to clean specific image cache

### ISSUE THREAD

**Issue by gsalvati** [thumbor/thumbor#186]
When it's used to cache profile's photo on websites, and the users change its profile's photo, the thumbor-server  cannot reload that image until the cache expires.

Command example:

http://thumbor-server/unsafe/smart/refresh-cache/http://myserver/images/myImage.png

**Comment by guilhermebr** [comment]
I had this problem, default profile image has a clean name, when changed thumbor keep showing the older =[

But I use docker than I removed the container and created again... =]
