### ISSUE TITLE
Add 2x retina image support

### ISSUE THREAD

**Issue by dangayle** [thumbor/thumbor#223]
Would you be able to add support for new retina-quality images? Simply adding a `/2x` flag to the request url would work perfectly.

**Comment by johjacb** [comment]
Is retina support still under consideration?

**Comment by heynemann** [comment]
It is... We just didn't have time to do it... ;(

**Comment by chrisiona** [comment]
::nudge::

**Comment by adelaineho** [comment]
+1

**Comment by rosscdh** [comment]
+1

**Comment by masom** [comment]
@chrisiona @adelaineho @rosscdh @e-jameson Please submit a PR implementing this filter. Commenting with +1 won't make things happen faster.

**Comment by dangayle** [comment]
@masom Where's the place to start? Suggestions on how you would go about doing this if you had the time?

**Comment by masom** [comment]
It could be a new filter, based on https://github.com/thumbor/thumbor/blob/master/thumbor/filters/upscale.py

Parameter example: https://github.com/thumbor/thumbor/blob/master/thumbor/filters/background_color.py

You would basically want to a url component like this: `retina(2x)`, the arguments for resize  could be a hash lookup (`retina_sizes = { '2x': [200, 200], '3x': [300, 300]}`)

**Comment by kkopachev** [comment]
why not use picture tag and/or srcset to achieve this?

**Comment by heynemann** [comment]
I'm closing this, since I don't think we got where we wanted with this feature.

If you have any further questions on this issue, please reopen it.
