### ISSUE TITLE
Installation via Thumbor PPA does not work

### ISSUE THREAD

**Issue by neovatar** [thumbor/thumbor#231]
Hello,

we are about deploying thumbor. I noticed that the PPA seems outdated/unsupported:
- https://launchpad.net/~thumbor/+archive/ppa shows an error page
- the thumbor version I get when using the PPA to install is 3.7.1
- the stable thumbor version I get via pip is 3.15.0

If the PPA is still a valid installation source, it probably should be updated and the error with the launchpad pages should be fixed. If not, it should be removed from documentation / flagged as deprecated.

Or am I am doing something wrong here?

Thanks!
Tom

**Comment by mpdude** [comment]
@morpheu The PPA is outdated. Do you have any plans for fixing this?
