### ISSUE TITLE
Add python 3.x support

### ISSUE THREAD

**Issue by frankdu** [thumbor/thumbor#241]
Please please consider supporting python 3.x. This website could be helpful: http://python3porting.com/. I used it to convert my codes.

**Comment by j127** [comment]
Does thumbor work with Python 3? It installs under Python 3 without errors using `pip install thumbor`, but then it gives this error when I type `thumbor` in a terminal: `SyntaxError: Missing parentheses in call to 'print'`. I didn't see any mention about its not working in Python 3 on the install page.

**Comment by stevelacey** [comment]
Agreed, whist I can come to terms with Thumbor not supporting Python 3 yet – at this point given distros are now being released with Python 3 installed by default – you really should write this... in big letters... for those that have no idea that `print` was something that changed in 2>3
