### ISSUE TITLE
Wrong EXIF orientation

### ISSUE THREAD

**Issue by robolson** [thumbor/thumbor#245]
Source image with exif orientation of 6 is rotated correctly when view in a browser:
https://raw.github.com/recurser/exif-orientation-examples/master/Portrait_6.jpg

If I filter the image through Thumbor without applying any filters the image is now shown rotated 90 degrees clockwise: 
http://thumbor.theia.local/unsafe/https://raw.github.com/recurser/exif-orientation-examples/master/Portrait_6.jpg

Inspecting the exif info shows that the image still has an EXIF orientation of 6 which means that the raw image is oriented correctly but when the 90 degree clockwise rotation is applied the rotation goes from correct to wrong.

```
exiftool Portrait_6\ bad.jpg
ExifTool Version Number         : 9.45
File Name                       : Portrait_6 bad.jpg
Directory                       : .
File Size                       : 105 kB
File Modification Date/Time     : 2014:01:15 11:01:52-08:00
File Access Date/Time           : 2014:01:15 11:02:08-08:00
File Inode Change Date/Time     : 2014:01:15 11:01:52-08:00
File Permissions                : rw-r--r--
File Type                       : JPEG
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Exif Byte Order                 : Big-endian (Motorola, MM)
Orientation                     : Rotate 90 CW
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Exif Image Width                : 600
Exif Image Height               : 450
Profile CMM Type                : appl
Profile Version                 : 2.2.0
Profile Class                   : Display Device Profile
Color Space Data                : RGB
Profile Connection Space        : XYZ
Profile Date Time               : 2009:02:25 11:26:11
Profile File Signature          : acsp
Primary Platform                : Apple Computer Inc.
CMM Flags                       : Not Embedded, Independent
Device Manufacturer             : appl
Device Model                    :
Device Attributes               : Reflective, Glossy, Positive, Color
Rendering Intent                : Perceptual
Connection Space Illuminant     : 0.9642 1 0.82491
Profile Creator                 : appl
Profile ID                      : 0
Image Width                     : 450
Image Height                    : 600
Encoding Process                : Progressive DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 450x600
```

I have `PRESERVE_EXIF_INFO` and `RESPECT_ORIENTATION` both set to `True` in my config. I am using the PIL engine with Redis storage.

**Comment by AizazAZ** [comment]
I want to force portrait for all images, Please guide me how to do that ?

**Comment by heynemann** [comment]
Not sure what you are trying to achieve here. If you want portrait images, just pass to thumbor the size as portrait (600x300) and thumbor will crop the images to that size.

**Comment by AizazAZ** [comment]
![screenshot_2015-05-14-10-13-12](https://cloud.githubusercontent.com/assets/1931778/7624870/3d2cd626-fa22-11e4-9b44-b80b8509aeff.png)
These pictures are cropped though thumbor but I want them to ignore EXIF and give me all photos in portrait. How to do that? @heynemann  Thanking in anticipation.

**Comment by AizazAZ** [comment]
Image loading...
![screenshot_2015-05-14-11-16-00](https://cloud.githubusercontent.com/assets/1931778/7625538/64ef5d60-fa2b-11e4-909b-4f655e6188b6.png)

Some of the image looks good in landscape but some images I need in portrait, all those are re sized with Thumbor. How to do that, I hope you'll understand my concern. @heynemann
