### ISSUE TITLE
Amazon's S3 based storage?

### ISSUE THREAD

**Issue by gcobr** [thumbor/thumbor#261]
Hi,

I'd like to know if there's any known storage implementation for Thumbor that uses Amazon's S3 service to store image files.

Thank you,

**Comment by RKushnir** [comment]
@heynemann thank you, I implemented the solution you are suggesting and it (almost) works. The only problem is `thumbor_aws` uses sha1 hash for filenames and nginx is having a hard time guessing the mime type, so in the browser I just get `application/octet-stream` followed by download prompt.
Do you have any ideas how to fix this?

**Comment by willtrking** [comment]
@RKushnir 

In NGINX you can use the following config directive to specify that all files from a certain location will be of a certain mime type

```
location /my/image/location {
      default_type image/jpeg;
}
```

To my knowledge most browsers don't care if the image is, for example, a PNG but is served as a jpeg (please correct me on this!).

If this doesn't work for you, I wouldn't mind extending thumbor_aws with a config option to allow preserving the file extension.

**Comment by RKushnir** [comment]
@willtrking Thank you for response. I tried the following without success
```
types {}
default_type image/jpeg;
```
Maybe it doesn't work together with `proxy_pass`.

**Comment by willtrking** [comment]
@RKushnir Glad you got it working, you're right about adding the file extension being the more elegant solution.

**Comment by gansbrest** [comment]
@heynemann @willtrking I know this thread is a bit old, but I wonder if u guys could share your config related to s3 storage for originals as well as generated presets. We are using imgix at the moment, but it becomes prohibitively expensive, so we would like to run thumbor with nginx proxy and s3 storage. Kind of lost with config part, would appreciate the help.

**Comment by masom** [comment]
@gansbrest There's an updated AWS plugin, based on @willtrking  at https://github.com/thumbor-community/aws
