### ISSUE TITLE
Why do you recommend using Redis as a storage?

### ISSUE THREAD

**Issue by goosechaser** [thumbor/thumbor#265]
> The thumbor team strongly advises the usage of Redis (http://redis.io/) as a storage, since it is REALLY fast and has built-in features that help us invalidate old image originals.

512 images x 1MB = 100% memory usage by Redis on a 512MB machine. I have thousands of images. Not sure this is the best advice, unless I am misunderstanding something.

**Comment by syntonyze** [comment]
Hi guys,
apologies for commenting on such an old post, but I am looking at using the redis adapter as a result storage in production and I was wondering if any of you have done it and whether you think [tc_redis](https://github.com/thumbor-community/redis) is production ready.

Some initial testing shows good results, but I noticed the [repo](https://github.com/thumbor-community/redis) has not been updated in years. Do you know if still maintained? what's your experience with it?

**Comment by heynemann** [comment]
I haven't used it personally as a result storage, but I think it is a great solution. Not sure on tc_redis, but our Result Storage contract is quite stable, thus it might explain why the library has not changed in a couple years.

**Comment by syntonyze** [comment]
Thanks @heynemann,
Yep you're right, this is exactly what I thought too, the code itself looks quite straightforward.
Hopefully someone will share their experience with the redis adapter in production.
(I should probably raise that question elsewhere too)
