### ISSUE TITLE
Making thumbor work with PM2 app manager

### ISSUE THREAD

**Issue by majimboo** [thumbor/thumbor#291]
I have been using PM2 @ https://github.com/Unitech/pm2 and it is pretty neat. I was trying to use PM2 with thumbor, it does run, it does work. But I realized it was the cause of Thumbor crashing when loading huge images.

**Comment by masom** [comment]
Thumbor will use a lot of memory if needed by the image opeartion. PM2 seems to enforce memory usage and has other settings to trigger an application server restart.

I'm not quite sure what can be done on our end, thumbor works fine with supervisord, init.d, rc.d, and many other application process managers.
