### ISSUE TITLE
Using --fd option for thumbor to listen on a socket 

### ISSUE THREAD

**Issue by chemouna** [thumbor/thumbor#300]
Thanks a lot for your work on thumbor,  
I have a socket file for example in /tmp/nginx.socket , how can i say to thumbor to listen on it , i tried : thumbor -c ./thumbor.conf --fd /tmp/nginx.socket
and  thumbor -c ./thumbor.conf --fd unix:/tmp/nginx.socket  but it seems to require an integer value.
 is it a misunderstanding on my part , any suggestions ?

**Comment by Bertg** [comment]
Bit old ticket, but would indeed be nice if thumbor would just create the descriptor if it's not present.
