### ISSUE TITLE
Provide metrics exposition

### ISSUE THREAD

**Issue by dhardy92** [thumbor/thumbor#302]
Thumbor should provide some way to expose metrics on some /metrics endpoint for example

I don't know if tornado can handle this feature natively but something like  https://github.com/Cue/scales would help ?

**Comment by phoet** [comment]
would be really cool to get more metrics out of thumbor. we experimented with NewRelic to gain more insight, but it looks like tornado is not supported any longer. if you have any pointers for how we could easily get more data into our librato setup or any other helpful service, please let me know. we are especially interested in the time it takes to fetch the original images from the web. i guess that would be `Original Image Cache Miss`.

**Comment by heynemann** [comment]
It seems incredibly useful @phoet do you think you can help with a Pull Request to add it?

**Comment by heynemann** [comment]
Any news here?

**Comment by phoet** [comment]
Please have a look at this, its not battle tested though https://github.com/thumbor-community/librato

**Comment by masom** [comment]
Thumbor now supports pluggable metrics which allows anyone to supply an implementation for their favourite data collection system.
