### ISSUE TITLE
Invalid Webp format

### ISSUE THREAD

**Issue by niqo01** [thumbor/thumbor#304]
We just setup Thumbor in version 4.1.2 and we are having an issue with Webp images.
When the client request a webp format via `filters:format(webp)`, we receive the following valid HTTP Response:
```
HTTP/1.1 200 OK
Server: nginx/1.2.1
Date: Wed, 23 Apr 2014 21:50:42 GMT
Content-Type: image/webp
Content-Length: 7791
Connection: keep-alive
Expires: Thu, 24 Apr 2014 21:50:42 GMT
Vary: Accept
```

However the returned binary is not a valid webp format. [showriff](http://manpages.ubuntu.com/manpages/hardy/man1/showriff.1.html) print the following:
```
 *** Error: Expected chunk 'RIFF', found '����'
```

You can find here the generated invalid image:
https://drive.google.com/file/d/0B0GUnzoAotiFUGFYTGlLRG1CTFE/edit?usp=sharing

Note that the image is viewable...

**Comment by heynemann** [comment]
Any news?
