### ISSUE TITLE
Failed Installing from source and via pip

### ISSUE THREAD

**Issue by andremaha** [thumbor/thumbor#307]
With Python 3.3.5 install I get following error message:

```
# python3.3 setup.py install
  File "setup.py", line 121
    print "\n\n*******************************************************************"
                                                                                  ^
SyntaxError: invalid syntax
```

**Comment by sunnytambi** [comment]
Is it still the same case ... Thumbor still doesn't support Python 3.4?

**Comment by heynemann** [comment]
We didn't put any effort in supporting python 3.4. Sorry.

**Comment by Arthien** [comment]
@heynemann If  may ask, what needs to be updated for 3.x support?

**Comment by heynemann** [comment]
I'm not sure @Arthien. I believe one has to run it under python 3.x and see what breaks.
