### ISSUE TITLE
Has support for memcached been dropped?

### ISSUE THREAD

**Issue by patoarvizu** [thumbor/thumbor#309]
When I enable memcached storage, I get this error:

2014-05-13 15:59:59 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1244, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1427, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/thumbor/handlers/imaging.py", line 25, in get
    if self.context.modules.storage.exists(kw['image'][:32]):
  File "/usr/lib/python2.7/dist-packages/thumbor/storages/memcache_storage.py", line 77, in exists
    return self.storage.get(path) is not None
TypeError: key must be an instance of str

Reading the [requirements](https://github.com/thumbor/thumbor/wiki/Requirements), I see that you don't explicitly mention memcached as a currently supported storage, but I do see the memcache_storage.py module under [thumbor/storages](https://github.com/thumbor/thumbor/blob/master/thumbor/storages/memcache_storage.py) and I also see the option commented out on [thumbor.conf](https://github.com/thumbor/thumbor/blob/master/thumbor/thumbor.conf).

Can you help clarify this and/or troubleshoot the issue above?

Thanks!

Python 2.7.3
Thumbor 3.15.0
Tornado 3.2.1
Pillow 2.4.0
Ubuntu 12.04

**Comment by heynemann** [comment]
I'm fixing memcached storage right now. Any idea what the URL was that you were getting the error with? Did it involve unicode characters? If you don't know it's ok. I'm aware it's been a long time and I'm sorry for it.

**Comment by patoarvizu** [comment]
No, I can't really remember what the URL was. Sorry about that.
