### ISSUE TITLE
Using aptitude with Ubuntu 14.04 LTS (Trusty Tahr)

### ISSUE THREAD

**Issue by ppatriotis** [thumbor/thumbor#311]
It seems that when using apt-get to install thumbor, there wasn't a package built for Ubuntu 14.04 LTS (Trusty Tahr), which is what Amazon is offering now by default from it's launch wizard.

I found this because I got the error:
```
W: Failed to fetch http://ppa.launchpad.net/thumbor/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages: 404  Not Found
```
when I ran `sudo aptitude update`.

The fix I found was to edit `vi /etc/apt/sources.list.d/thumbor-ppa-trusty.list` and changing `trusty` to `saucy`, which should be compatible, and all is working well.

Is this the proper way to fix this and will you be uploading a package for trusty as well?

**Comment by okor** [comment]
+1 this, would love to have 14.04 support

**Comment by eksoverzero** [comment]
If you're not completely set on installing using aptitude, I have it working on 14.04, as part of a docker image with OpenCV using:

```
sudo apt-get update
sudo apt-get install -y build-essential python-dev curl python-pycurl python-pip
sudo apt-get install -y python-numpy python-opencv webp libpng-dev libtiff-dev libjasper-dev libjpeg-dev
sudo apt-get install -y libdc1394-22-dev libdc1394-22 libdc1394-utils

sudo pip install thumbor
```

I have no idea if all these packages are required but, it's working.
