### ISSUE TITLE
ext3 max subdirectories

### ISSUE THREAD

**Issue by mightydes** [thumbor/thumbor#316]
For now, when I use`'RESULT_STORAGE_FILE_STORAGE_ROOT_PATH` option, I am limited for 32000 subdirectories on ext3 file system.
It is not very much, so I think It is handier to use wiki style storage algorithm.
For example, sha 1 checksum of file `Gendalf.jpg` is `4D1FF89B608E0D9FE5`. We use first, second and third letters to create folders:
```
4
    D1
```
Which results in structure:
```
4
    D1
        80x80
            Gendalf.jpg
```

**Comment by heynemann** [comment]
Our storage does that now. Hope it helps.

**Comment by mightydes** [comment]
@heynemann thanks for your job!
