### ISSUE TITLE
Segmentation fault when using graphicsmagick_engine

### ISSUE THREAD

**Issue by florentvaldelievre** [thumbor/thumbor#329]
Hello,

I am having an issue when using graphicsmagick_engine.<strong> It works fine using PIL engine.</strong> Please find below the stacktrace:
Please note that the problem occurs with any image format(well at least jpg and bmp), AUTO_WEBP = False in conf. Tried with Chrome and Firefox
My thumbor configuration: http://pastebin.com/zc28xBmx

```
gdb python
(gdb) run server.py -l debug
```
Starting program: /usr/bin/python server.py -l debug
[Thread debugging using libthread_db enabled]
Detaching after fork from child process 25909.
Detaching after fork from child process 25911.
2014-07-29 11:29:11 root:DEBUG thumbor running at 0.0.0.0:8888
2014-07-29 11:29:22 thumbor:DEBUG [RESULT_STORAGE] getting from /tmp/thumbor/result_storage/v2/un/sa/unsafe/200x200/smart/pcvaldelif.mtl.shopmedia.com:8080/images/upload/2014/7/aaa/aaa/cDg0NTQ5MF85OTg4NzZfMTI=.jpg
2014-07-29 11:29:22 thumbor:DEBUG [RESULT_STORAGE] image not found at /tmp/thumbor/result_storage/v2/un/sa/unsafe/200x200/smart/pcvaldelif.mtl.shopmedia.com:8080/images/upload/2014/7/aaa/aaa/cDg0NTQ5MF85OTg4NzZfMTI=.jpg

<b>Program received signal SIGSEGV, Segmentation fault.</b>
0x00007fffec0e1852 in ?? () from /lib64/libuuid.so.1
(gdb) backtrace
#0  0x00007fffec0e1852 in ?? () from /lib64/libuuid.so.1
#1  0x00007fffec0e197a in ?? () from /lib64/libuuid.so.1
#2  0x00007fffec0e1b40 in __uuid_generate_random () from /lib64/libuuid.so.1
#3  0x00007fffec0e1bc6 in uuid_generate_random () from /lib64/libuuid.so.1
#4  0x00007fffebabbdac in ffi_call_unix64 () from /usr/lib64/libffi.so.5
#5  0x00007fffebabbb34 in ffi_call () from /usr/lib64/libffi.so.5
#6  0x00007fffebccf074 in _CallProc () from /usr/lib64/python2.6/lib-dynload/_ctypes.so
#7  0x00007fffebcc83a2 in ?? () from /usr/lib64/python2.6/lib-dynload/_ctypes.so
#8  0x00000037d3043c63 in PyObject_Call () from /usr/lib64/libpython2.6.so.1.0
#9  0x00000037d30d4f74 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#10 0x00000037d30d6b8f in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#11 0x00000037d30d6b8f in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#12 0x00000037d30d7657 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#13 0x00000037d30d5aa4 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#14 0x00000037d30d7657 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#15 0x00000037d306adad in ?? () from /usr/lib64/libpython2.6.so.1.0
#16 0x00000037d3043c63 in PyObject_Call () from /usr/lib64/libpython2.6.so.1.0
#17 0x00007ffff0afe5d4 in ?? () from /usr/lib64/python2.6/lib-dynload/_functoolsmodule.so
#18 0x00000037d3043c63 in PyObject_Call () from /usr/lib64/libpython2.6.so.1.0
#19 0x00000037d30d4470 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#20 0x00000037d30d7657 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#21 0x00000037d306adad in ?? () from /usr/lib64/libpython2.6.so.1.0
#22 0x00000037d3043c63 in PyObject_Call () from /usr/lib64/libpython2.6.so.1.0
#23 0x00007ffff0afe5d4 in ?? () from /usr/lib64/python2.6/lib-dynload/_functoolsmodule.so
#24 0x00000037d3043c63 in PyObject_Call () from /usr/lib64/libpython2.6.so.1.0
#25 0x00000037d30d4f74 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#26 0x00000037d30d7657 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#27 0x00000037d30d5aa4 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#28 0x00000037d30d7657 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#29 0x00000037d30d5aa4 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#30 0x00000037d30d7657 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#31 0x00000037d30d5aa4 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#32 0x00000037d30d7657 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#33 0x00000037d30d7732 in PyEval_EvalCode () from /usr/lib64/libpython2.6.so.1.0
#34 0x00000037d30f1bac in ?? () from /usr/lib64/libpython2.6.so.1.0
#35 0x00000037d30f1c80 in PyRun_FileExFlags () from /usr/lib64/libpython2.6.so.1.0
#36 0x00000037d30f316c in PyRun_SimpleFileExFlags () from /usr/lib64/libpython2.6.so.1.0
#37 0x00000037d30ff8a2 in Py_Main () from /usr/lib64/libpython2.6.so.1.0
#38 0x00007ffff71bfd1d in __libc_start_main () from /lib64/libc.so.6
#39 0x0000000000400649 in _start ()

### I am using the following packages / distrib:
```
- CentOS release 6.5 (Final)
- Python 2.6.6
- Thumbor 4.2.1
```
 
### This is how i have installed thumbor :+1: 
```
yum install GraphicsMagick-c++-devel
yum install boost-devel
yum -y install python-pip
pip install thumbor
pip install pgmagick
pip install graphicsmagick_engine
```
### This is the list of my pip packages
```
root@pcguerinc:/usr/lib64/python2.6/site-packages/thumbor #pip freeze
Beaker==1.3.1
Magic-file-extensions==0.1
Mako==0.3.4
MarkupSafe==0.9.2
MySQL-python==1.2.3c1
PIL==1.1.6
Pillow==2.3.1
PyXML==0.8.4
SSSDConfig==1.9.2
backports.ssl-match-hostname==3.4.0.2
cas==0.15
cups==1.0
cupshelpers==1.0
decorator==3.0.1
derpconf==0.6.0
distribute==0.6.10
ethtool==0.6
firstboot==1.110
freeipa==2.0.0.alpha.0
graphicsmagick-engine==0.1.1
gyp==0.1
iniparse==0.3.1
ipapython==3.0.0
iwlib==1.0
kerberos==1.0
lxml==2.2.3
netaddr==0.7.5
paramiko==1.7.5
pexpect==2.3
pgmagick==0.5.7
pyOpenSSL==0.10
pycrypto==2.6.1
pycurl==7.19.0
pygpgme==0.1
python-default-encoding==0.1
python-ldap==2.3.10
python-magic==0.4.6
python-meh==0.11
python-nss==0.13
pyxdg==0.18
qpid-python==0.14
qpid-tools==0.14
reportlab==2.3
scdate==1.9.60
sckdump==2.0.5
scservices==0.99.45
scservices.dbus==0.99.45
six==1.7.3
slip==0.2.20
slip.dbus==0.2.20
slip.gtk==0.2.20
smbc==1.0
thumbor==4.2.1
thumbor-pexif==0.14
tornado==3.2.2
urlgrabber==3.9.1
wxPython==2.8.12.0
wxPython-common==2.8.12.0
yum-metadata-parser==1.1.2
```

Any idea ?

**Comment by heynemann** [comment]
Any news here?
