### ISSUE TITLE
Create a Vagrant box or virtual appliance to help new contributors get started.

### ISSUE THREAD

**Issue by stackstack** [thumbor/thumbor#333]
I was looking into issue 331, but I was unable to get a development installation working. 

It would be very nice if perspective contributors had access to a Vagrant box for development.

For example, the [hacking](https://github.com/thumbor/thumbor/wiki/Hacking-on-thumbor) doc doesn't specify that Redis needs to be started on a specific port. 

Here's how far I got:

`make test` failed due to a relative import error by vows.

`pip install .` and running the `thumbor` command caused this error:

`'thumbor.server' from '...' has no 'main' attribute`

**Comment by estahn** [comment]
@heynemann I tried to get thumbor up and running in a vagrantbox so that i would be able to add a new optimiser. However i receive the following error:

```
(ENV)root@vagrant-ubuntu-trusty-64:/vagrant# python -m thumbor.server
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/vagrant/thumbor/server.py", line 112, in <module>
    main(sys.argv[1:])
  File "/vagrant/thumbor/server.py", line 58, in main
    importer.import_modules()
  File "thumbor/importer.py", line 44, in import_modules
    self.import_item('ENGINE', 'Engine')
  File "thumbor/importer.py", line 86, in import_item
    module = self.import_class('%s.%s' % (conf_value, class_name))
  File "thumbor/importer.py", line 33, in import_class
    module = get_module and __import__(name) or __import__(module_name)
  File "thumbor/engines/pil.py", line 16, in <module>
    from PIL import Image, ImageFile, ImageDraw, ImageSequence
  File "thumbor/engines/PIL.py", line 16, in <module>
    from PIL import Image, ImageFile, ImageDraw, ImageSequence
ImportError: cannot import name Image
```

Any idea on how to solve it?

**Comment by heynemann** [comment]
Apparently pillow is not installed in the virtualenv in your Vagrant box.

**Comment by scorphus** [comment]
@estahn: Please take a look at https://github.com/scorphus/thumbor-bootstrap for it may be helpful, although I haven't touched it for a little while.

**Comment by gi11es** [comment]
Gives a lot more than just Thumbor, but I've written a pretty extensive Thumbor role included in the Mediawiki Vagrant VM: https://www.mediawiki.org/wiki/MediaWiki-Vagrant

It sets up a bit of a stack around Thumbor (Varnish for caching and Swift to store originals), but it's possible to hit Thumbor directly on the default port (8888).

FYI it pulls my fork at the moment, and not the latest copy of Thumbor.

As I keep working towards our production deployment of Thumbor, the Vagrant role will be kept up to date to match the production setup as much as possible. Which should be an interesting large scale deployment example setup for people to peek at.

**Comment by homm** [comment]
@estahn Look at https://github.com/thumbor/thumbor/pull/1074, I believe this helps.
