### ISSUE TITLE
image optimization

### ISSUE THREAD

**Issue by zkourouma** [thumbor/thumbor#346]
I see there are plenty of sizing options for the dimensions of images, but I was wondering if there is/will be support for image optimization? Google provides site feedback via [PageSpeed](https://developers.google.com/speed/pagespeed/) and recommended [losslessly compressing some pictures](https://developers.google.com/speed/docs/insights/OptimizeImages).

**Comment by rafaelalbsantiago** [comment]
what do you think about this service?

https://kraken.io

**Comment by xethorn** [comment]
I'd rather go with http://www.imgix.com/, they are much cheaper and offer more features.
