### ISSUE TITLE
No free disk space checking in (result) file storage ?

### ISSUE THREAD

**Issue by renaudguerin** [thumbor/thumbor#352]
Hi,

Looking at the source, there doesn't seem to be any free disk space checking (or any write error checking for that matter) in the file storage (+ result storage) classes.

Does anyone use them in production ? I understand it may complicate the module significantly to keep track of files and do LRU expiration for example, but do you all just run a cron job to remove older files ?

**Comment by heynemann** [comment]
Closing as this is not thumbor's responsibility.

**Comment by renaudguerin** [comment]
Not Thumbor's responsibility to ensure there is free disk space, for sure, but checking for write errors would be good practice.

**Comment by heynemann** [comment]
Sorry I didn't mean it as disrespectful. Just meaning there are more capable solutions for doing this sort of validation. But I do agree with you. Catching write errors in our storages is the way to go.

**Comment by luisdavim** [comment]
At least the healthcheck URL should check for write errors.

**Comment by bf** [comment]
This is a real issue that keeps creeping up every year or so. Can we configure `TC_AWS_RESULT_STORAGE_BUCKET` in a way so it writes to /dev/null? Would that fuck stuff up?
