### ISSUE TITLE
Convert animated GIF to non-animated (with an image-format filter)

### ISSUE THREAD

**Issue by illarionov** [thumbor/thumbor#357]
Now the image-format filter can not be applied to animated GIFs. The output image remains in a gif format.
[gif](http://thumbor0.tasty0.ru/unsafe/0x0/filters:format(jpg)/att/be/5b/16143410_39649_19345266_9e00cdc9d718dd1648ce70dc)
It would be great if the image will be converted to the non-animated (using the first frame).
Or maybe add a filter to cut a specified frame.

**Comment by guilhermef** [comment]
After experimental gifv(), I think it's time to deal with this issue.
@kplaube

**Comment by guilhermef** [comment]
Done on https://github.com/thumbor/thumbor/wiki/Extract-Cover
