### ISSUE TITLE
Optional syslog logging

### ISSUE THREAD

**Issue by wking** [thumbor/thumbor#377]
I'm not sure that this has been submitted upstream (i.e. here), but @miracle2k has a [patch][1] by @elprans that swaps in Python's `SysLogHandler` based on a `THUMBOR_USE_SYSLOG` environment variable.  The patch seems like it's [also under the MIT license][2], so we should be able to include it without trouble.  It would be nice to get something like that incuded by default, although I'd probably treat the environment variable as a string which would be:

* empty if you don't want syslog handling
* `tcp://HOST:PORT` or `udp://HOST:PORT` if you want to talk to the syslog daemon over the network
* anything else would be interpreted as the absolute path to the syslog Unix socket.

[1]: https://github.com/miracle2k/dockerfiles/blob/master/thumbor/setup/patches/thumbor/0001-Add-syslog-support.patch
[2]: https://github.com/thumbor/thumbor/blob/master/LICENSE

**Comment by heynemann** [comment]
@wking any news on this?

**Comment by wking** [comment]
On Mon, Jan 12, 2015 at 04:20:18AM -0800, Bernardo Heynemann wrote:
> @wking any news on this?

Ah, sorry, it had slipped off my radar.  I'll queue it for the
upcoming weekend.

**Comment by guilhermef** [comment]
I've released the 4.9.0 with @dhardy92 pull request.

**Comment by wking** [comment]
On Thu, Feb 19, 2015 at 10:09:10AM -0800, Guilherme Souza, A.k.a.: Galinho wrote:
> Closed #377.

Thanks :).
