### ISSUE TITLE
Deploy on heroku fails.

### ISSUE THREAD

**Issue by PanManAms** [thumbor/thumbor#381]
I followed the directions for deploying on Heroku.
However, the deploy fails. After lots of other output, this is where it seems to go wrong. Could it be that CURL is missing? I deployed lots of things to heroku, but never python sofar...

       src/easy.c: In function ‘do_curl_getinfo’:

       src/easy.c:1985: warning: call to ‘_curl_easy_getinfo_err_curl_slist’ declared with attribute warning: curl_easy_getinfo expects a pointer to struct curl_slist * for this info

       gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPYCURL_VERSION="7.19.5" -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/app/.heroku/python/include/python2.7 -c src/module.c -o build/temp.linux-x86_64-2.7/src/module.o

       src/module.c: In function ‘initpycurl’:

       src/module.c:723: error: ‘CURLPROTO_IMAP’ undeclared (first use in this function)

       src/module.c:723: error: (Each undeclared identifier is reported only once

       src/module.c:723: error: for each function it appears in.)

       src/module.c:724: error: ‘CURLPROTO_IMAPS’ undeclared (first use in this function)

       src/module.c:725: error: ‘CURLPROTO_POP3’ undeclared (first use in this function)

       src/module.c:726: error: ‘CURLPROTO_POP3S’ undeclared (first use in this function)

       src/module.c:727: error: ‘CURLPROTO_SMTP’ undeclared (first use in this function)

       src/module.c:728: error: ‘CURLPROTO_SMTPS’ undeclared (first use in this function)

       src/module.c:729: error: ‘CURLPROTO_RTSP’ undeclared (first use in this function)

       src/module.c:730: error: ‘CURLPROTO_RTMP’ undeclared (first use in this function)

       src/module.c:731: error: ‘CURLPROTO_RTMPT’ undeclared (first use in this function)

       src/module.c:732: error: ‘CURLPROTO_RTMPE’ undeclared (first use in this function)

       src/module.c:733: error: ‘CURLPROTO_RTMPTE’ undeclared (first use in this function)

       src/module.c:734: error: ‘CURLPROTO_RTMPS’ undeclared (first use in this function)

       src/module.c:735: error: ‘CURLPROTO_RTMPTS’ undeclared (first use in this function)

       src/module.c:736: error: ‘CURLPROTO_GOPHER’ undeclared (first use in this function)

       error: command 'gcc' failed with exit status 1

       ----------------------------------------
       Cleaning up...
       Command /app/.heroku/python/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_u27466/pycurl/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-fMs7Cm-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_u27466/pycurl
Traceback (most recent call last):
  File "/app/.heroku/python/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 60: ordinal not in range(128)

 !     Push rejected, failed to compile Python app

**Comment by heynemann** [comment]
Closing this. Hope it does solve things with heroku.
