### ISSUE TITLE
Support for PDF

### ISSUE THREAD

**Issue by cblock** [thumbor/thumbor#383]
Hi!

Just a short question: Are there any plans or is there any work in progress towards supporting PDF as raw file format, i.e. generating thumbnail previews of PDF files? Thanks in advance for any pointers and hints.

**Comment by hamishcampbell** [comment]
This is closed, however would people be interested in support for this? Thumbs of PDF pages are useful in a lot of contexts and are supported by (for example) ImageMagick. This might not be appropriate as core functionality, but an extension that handles them would be very useful.

**Comment by mpdude** [comment]
Interested in it :-)

Imagemagick can do this.

**Comment by intellisense** [comment]
Hi,

I have created a package [tc_pdf](https://github.com/intellisense/tc_pdf) (on [pypi](https://pypi.python.org/pypi/tc-pdf) as well) to support PDF preview image of first page. Any contribution is welcome! Check it out :)

Thanks!
