### ISSUE TITLE
thumbor:WARNING Unsupported Media Type

### ISSUE THREAD

**Issue by erinthon** [thumbor/thumbor#384]
Hello,

I'm trying to upload image using the API of thumbor /image, but I not understand how it works correctly.

I have a thumbor server and a application running in another server with PHP, i do a form whith PHP and send a request to thumbor server, but everytime I have this error: 

thumbor:WARNING Unsupported Media Type
tornado.access:WARNING 415 POST /image

Anyone have a example how I can do this with PHP ?

I try using a simple HTML form with method="post" enctype="multipart/form-data"

And:

$ch = curl_init();

	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type:  image/jpeg"));	
	curl_setopt($ch, CURLOPT_HEADER, 1);
	
	//set the url, number of POST vars, POST data
	curl_setopt($ch, CURLOPT_URL, 'http://my.thumborserver/image');
	curl_setopt($ch, CURLOPT_POST, count($fields));
	curl_setopt($ch, CURLOPT_POSTFIELDS, $fields_string);
	
	//execute post
	$result = curl_exec($ch);
	
	print_r($result);
	
	//close connection
	curl_close($ch); 

I tried too using REST Console on Google Chrome estension, but I have the same error too.

**Comment by marcguevremont** [comment]
same issue

**Comment by vishaalgc** [comment]
Im trying the same thing and have this same issue .. Did any one find any fix for this ?

**Comment by guilhermef** [comment]
That's still a problem ?

**Comment by RuslanZavacky** [comment]
@guilhermef can you #696 as I think it might be related.
