### ISSUE TITLE
Use gifsicle only on non-animated gifs

### ISSUE THREAD

**Issue by patoarvizu** [thumbor/thumbor#385]
I would like to be able to use both ALLOW_ANIMATED_GIFS = False and USE_GIFSICLE_ENGINE = True, so thumbor only runs gifsicle on non-animated gifs.

It seems like right now using USE_GIFSICLE_ENGINE = True overrides ALLOW_ANIMATED_GIFS.

**Comment by heynemann** [comment]
That would be a pure performance optimization, right? It does not hurt the images to go through gifsicle, or does it?
