### ISSUE TITLE
Error when going on a media file with "http://"

### ISSUE THREAD

**Issue by avelino** [thumbor/thumbor#392]
thumbor==4.7.1

error: `http://127.0.0.1:8888/unsafe/800x600/http://media.jovempanfm.uol.com.br/archives/2014/12/01/1488020994-esportesrss-webber-diz-nao-lembrar-de-acidente-em-interlagos-99074.jpg`

OK: `http://127.0.0.1:8888/unsafe/800x600/media.jovempanfm.uol.com.br/archives/2014/12/01/1488020994-esportesrss-webber-diz-nao-lembrar-de-acidente-em-interlagos-99074.jpg`

**Comment by heynemann** [comment]
I'm guessing it 's not happening anymore.
