### ISSUE TITLE
Support max-width & max-height

### ISSUE THREAD

**Issue by adambutler** [thumbor/thumbor#394]
This is a request to support requesting an image with a maximum width and a maximum height without the image aspect ratio being known before hand.

For example an image that is 800x600 could be requested with a max-width and max-height of 400px this would result in the rendered image being 400x300. The same request applied to an image that is 600x800 would result in the rendered image being 400x533

**Comment by heynemann** [comment]
We do support it. It's called full-fit-in:

http://localhost:8888/unsafe/full-fit-in/400x300/s.glbimg.com/es/ge/f/original/2015/01/11/pico2---gilvan-de-souza---flamengo.jpg

I've updated the [docs](https://github.com/thumbor/thumbor/wiki/Usage) to reflect this.

**Comment by adambutler** [comment]
@tholder :eyes:
