### ISSUE TITLE
wrong background color used with fill(auto)

### ISSUE THREAD

**Issue by virtuman** [thumbor/thumbor#405]
Background fill doesn't ever seem to match with the actual background color, even if it's white, am i not doing something right? :

ORIGINAL IMAGE:
![image_original](https://cloud.githubusercontent.com/assets/1087996/5701599/5f641946-9a02-11e4-965d-3be6874afb83.jpg)

Applying TRIM and FIT-IN with fill(auto)
http://localhost:8888/unsafe/trim/fit-in/300x300/smart/filters:format(webp)brightness(10):fill(auto)/http://thestore.com/media/catalog/product/b/r/brown_lace_top-ts448pzsyj_1n.jpg

![image_resized_with_fill_auto_and_trim](https://cloud.githubusercontent.com/assets/1087996/5701614/97eb7c5a-9a02-11e4-833b-68e52e0d099d.jpg)

same effect if not using trim or any other param:
http://localhost:8888/unsafe/fit-in/300x300/smart/filters:format(webp)brightness(10):fill(auto)/http://thestore.com/media/catalog/product/b/r/brown_lace_top-ts448pzsyj_1n.jpg

![image_resized_with_fill_auto](https://cloud.githubusercontent.com/assets/1087996/5701615/97f0aebe-9a02-11e4-8f03-12ba2edbd584.jpg)

**Comment by heynemann** [comment]
The automatic fill get the average color from the picture (in your case a brownish hue). If you want fill with white, you have to pass white.

**Comment by virtuman** [comment]
is there a way to identify actual background color, to fill empty space, or is it impossible with the current thumbor version ?
