### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by ustun** [thumbor/thumbor#406]
Are there any plans to support SVG's? (Conversion to png would be nice.) The reason is I'm having problems with SVG's in IE (broken aspect ratio for some svgs where the width and height is specified)

Ustun

**Comment by heynemann** [comment]
It seems like a sensible feature. Not sure if it thumbor's responsibility, though. I think this should be implemented in the imaging engines (PIL, GraphicsMagick, etc).

What do you think?

**Comment by sunil05** [comment]
I needed SVG support as well. Then for my purpose I thought I would atleast return the original image on first request as response if not resize it. But while constructing the header we set Conten-Type as returned by method get_mimetype which is not having the catch for SVG format. 

I think supporting here will leave the rest job only for PIL guys. what say?

**Comment by heynemann** [comment]
Closing this as we need PIL support. As soon as it lands on PIL we can reopen it.
