### ISSUE TITLE
SNI support for default Http loader 

### ISSUE THREAD

**Issue by stetelepta** [thumbor/thumbor#409]
Since a few months, guess just after [Poodle](http://en.wikipedia.org/wiki/POODLE), some websites that use https seem to require [SNI](http://en.wikipedia.org/wiki/Server_Name_Indication). 
Now I find these errors in the log:
```
2015-01-17 07:57:37 tornado.general:WARNING uncaught exception
Traceback (most recent call last):
  File "/path/to/virtualenvs/my_virtualenv/local/lib/python2.7/site-packages/tornado/stack_context.py", line 239, in wrapped
    callback(*args, **kwargs)
  File "/path/to/virtualenvs/my_virtualenv/local/lib/python2.7/site-packages/tornado/simple_httpclient.py", line 315, in _on_close
    raise HTTPError(599, message)
HTTPError: HTTP 599: [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

I tried to upgrade python to 2.7.9, that includes SNI support, but I guess the loader (or tornado) must be support it too. [this articles addresses the issue more deeply](https://www.mnot.net/blog/2014/05/09/if_you_can_read_this_youre_sniing)

**Comment by heynemann** [comment]
Our HTTP Loader uses libcurl's one. If your libcurl version supports it, I'm guessing it should be supported.

**Comment by stetelepta** [comment]
Thanks, I'll check.

**Comment by stetelepta** [comment]
It appears that Tornado 4.0.2 does not pass the parameter "server_hostname" to ssl_wrap_socket. Servers that are very strict on using SNI will now raise the handshake error.

It's already fixed but not yet released: https://github.com/tornadoweb/tornado/commit/ab706d692e83d146b2b8ecfc502414bc49cbdd01

**Comment by satyadeepk** [comment]
This is what worked for me on Ubuntu 14.04 LTS to make thumbor http loader work for SNI based SSL urls.
`HTTP_LOADER_CURL_ASYNC_HTTP_CLIENT = True`

Make sure your `curl` and `pycurl` libraries are up to date.
`sudo apt-get upgrade curl`
`sudo pip install --upgrade pycurl`
