### ISSUE TITLE
Support for thumbnails of videos?

### ISSUE THREAD

**Issue by asmaier** [thumbor/thumbor#411]
Just a quick question: Is it possible or do you plan to support the generation of thumbnails from video urls, e.g. like 
http://nimbb.com/Doc/Dev/Service/Video/Thumbnail.aspx  ?

**Comment by guilhermef** [comment]
It would be easy to implement, but right now it won't work.

**Comment by ishirav** [comment]
I was faced with the same requirement, and managed to solve it by creating a custom loader. It's almost identical to the regular file loader, but when asked to load a file it first checks whether it's a video. If so, it uses ffmpeg to extract a single frame from the video and then loads the extracted frame (instead of the original file). Works like a charm, and pretty quickly too.

The complete code is below; in order to use it you need to:
- install ffmpeg
- configure thumbor's FFMPEG_PATH
- configure thumbor's LOADER to use the custom loader

```python
from thumbor.loaders import LoaderResult
from datetime import datetime
from os import fstat
from os.path import join, exists, abspath
from urllib import unquote
from tornado.concurrent import return_future
import mimetypes

mimetypes.init()


@return_future
def load(context, path, callback):
    file_path = join(context.config.FILE_LOADER_ROOT_PATH.rstrip('/'), unquote(path).lstrip('/'))
    file_path = abspath(file_path)
    inside_root_path = file_path.startswith(context.config.FILE_LOADER_ROOT_PATH)

    result = LoaderResult()

    if inside_root_path and exists(file_path):

        if is_video(file_path):
            file_path = get_video_frame(context, file_path)

        with open(file_path, 'r') as f:
            stats = fstat(f.fileno())

            result.successful = True
            result.buffer = f.read()

            result.metadata.update(
                size=stats.st_size,
                updated_at=datetime.utcfromtimestamp(stats.st_mtime)
            )
    else:
        result.error = LoaderResult.ERROR_NOT_FOUND
        result.successful = False

    callback(result)


def is_video(file_path):
    type = mimetypes.guess_type(file_path)[0]
    return type and type.startswith('video')


def get_video_frame(context, file_path):
    import subprocess, tempfile, os
    f, outfile = tempfile.mkstemp('.jpg')
    os.close(f)
    cmd = [
        context.config.FFMPEG_PATH,
        '-i', file_path,
        '-ss', '00:00:01.000',
        '-vframes', '1',
        '-y',
        outfile
    ]
    subprocess.call(cmd)
    return outfile
```

**Comment by heynemann** [comment]
Would you guys be willing to have a project under thumbor-community with this extension? I'm sure @masom can help you get it off the ground and add some tests for good measure.

**Comment by ishirav** [comment]
Sure, I'm willing to help. Although it seems to me that the "correct" way to achieve video thumbnailing should be similar to the way thumbor extracts a cover photo from animated gifs (it's conceptually the same operation, extended to additional file types beyond gif).

**Comment by masom** [comment]
Yep, it is failry similar.

We've had discussions about dynamically calling engines and/or chaining them.

Right now the way you proposed the change is the cleanest way to do it within the current thumbor architecture.

Ideally we'd have a video engine that executes ffmpeg and transfers the image to Pillow for further processing.

If you want I can create a `video` repo under https://github.com/thumbor-community and assign you as repo owner.

**Comment by ishirav** [comment]
Great, I'll put the custom loader there. Since I've never contributed to thumbor before, what else should be in that repo other than a README? What do you use for writing and running tests?

**Comment by masom** [comment]
community projects follow this:

- MIT License
- Python unittest ( see thumbor tests, we are moving away from PyVows.)
- The package itself is named `tc_<name>`. Versions follow this: `<thumbor_major>.<package_major>.<package_minor>`. This allows releasing versions that match thumbor.
- Code of conduct: https://github.com/thumbor-community/code-of-conduct

**Comment by masom** [comment]
Repo created at https://github.com/thumbor-community/video

**Comment by heynemann** [comment]
Can we close this issue?

**Comment by ishirav** [comment]
I suppose you can close this issue. I've put everything in https://github.com/thumbor-community/video - please take a look and tell me if something's missing or not working. Thanks!

**Comment by masom** [comment]
Thanks @ishirav . I'll close this issue and will review on tc_video.

**Comment by imoyaes** [comment]
Is this video work around compatible with thumbor_aws? I see that thumbor_aws uses s3_loader.py and in the end returns the result of file_key.read(). I'm not even sure if file_key.read() is a kind of LoaderResult

**Comment by masom** [comment]
@imoyaes Thumbor supports old-style results ( just plain media buffers ) and the new `LoaderResult` class.

**Comment by trungkhong** [comment]
I change my http_loader like your code but it got error in Pillow:
`IOError: cannot identify image file <_io.BytesIO object at 0x3a4b350>`
