### ISSUE TITLE
round_corner with transparent background

### ISSUE THREAD

**Issue by pgherveou** [thumbor/thumbor#412]
Hi there, first of all congrat for the project this is awseome!
One question is it possible to use the round_corner filter to create transparent circle image

```
http://localhost:8888/unsafe/200x200/filters:round_corner(100,255,255,255)/...
```

will create white non transparent borders

**Comment by heynemann** [comment]
It is possible. We haven't done it that way, though... Do you think you can contribute with the solution?

**Comment by pgherveou** [comment]
unfortunately I have 0 python skills and too little time right now :(
I found a way to do it in node using imagemagick though if it can help anyone
https://gist.github.com/pgherveou/2440e4209098700961ac

**Comment by mcoenca** [comment]
Hey ! Is it possible to reopen this issue ? It was closed but i don't know why, as it is not fixed ATM and seems to quite a useful feature to have. 
Actually as it will really improve my thumbor use, if i have some time i think i will take a look at it.
If you can give me somes pointers to where the difficulty lies or if you have similar issues looked at, will glady accept them ! Thanks

**Comment by timic** [comment]
+1

**Comment by heynemann** [comment]
I don't think it's a problem of being difficult. It's just something we don't need right now, thus we can't take time from more important things to work on this.

As said before, if anyone can provide a PR, we'd be happy to evaluate it.

If you have any further questions on this issue, please reopen it.

**Comment by Salcave** [comment]
Is this not going to be implemented at all?

**Comment by kkopachev** [comment]
@Salcave see #1163
