### ISSUE TITLE
ubuntu 14 / can't install correctly with aptitute

### ISSUE THREAD

**Issue by bbnnt** [thumbor/thumbor#413]
sudo aptitude install thumbor
does not install any service, then everything gets pretty difficult to handle or get started with
Not to mention that package for trusty are available (compatible with saucy though)

Anyway, my point right is to understand how things can be done correctly with the latest linux version. Many pieces can be found about it on the web; but is there a reliable reference about ?

**Comment by RKushnir** [comment]
I followed [this tutorial](http://www.dadoune.com/blog/best-thumbnailing-solution-set-up-thumbor-on-aws/) and got it installed without any problems. Just skip the AWS part. It can be summarized in the following commands:
```bash
apt-get install python-devel gcc libjpeg-dev libtiff-dev libpng-dev libjasper-dev libwebp-dev libcurl4-openssl-dev python-pip
pip install pycurl numpy thumbor
thumbor-config > /etc/thumbor.conf
```
Then just run `thumbor`.

**Comment by okor** [comment]
+1 this issue, there is a duplicate case over here too: https://github.com/thumbor/thumbor/issues/311

**Comment by bbnnt** [comment]
Yep saw that one; but felt like it was lost so I wanted to put up this issue
@RKushnir installing via pip did not make it for me and I guess everyone would appreciate a service installed by default that would make a better starting point for everyone

**Comment by okor** [comment]
For anyone that's interested, I created a Gist for getting Thumbor setup on a fresh Ubuntu 14.04 box: https://gist.github.com/okor/79c38cfb03b153bd4eb2

**Comment by masom** [comment]
Shouldn't `thumbor-config` be called in the `.deb` post-install script ?

**Comment by heynemann** [comment]
Maybe @marcelometal can help shed some light here...

**Comment by BradWhittington** [comment]
:+1:

**Comment by marcelometal** [comment]
Hi! I am reviewing thumbor package... I have already sent some build-depends (pyvows, preggy, derpconf, yanc, etc) to the Debian unstable repository, but there are others (libthumbor, tornado_pyvows, etc). 

WIP:
https://github.com/marcelometal/thumbor/commits/debian

**Comment by bbnnt** [comment]
I have to say that @okor works okay, or at least would put you on the way
