### ISSUE TITLE
Allowed sources only matches domain

### ISSUE THREAD

**Issue by mcfedr** [thumbor/thumbor#416]
The [wiki](https://github.com/thumbor/thumbor/wiki/Configuration#allowed_sources) suggests that one can match the whole url of source images, when it says

    i.e.: ALLOWED_SOURCES=['http://s.glbimg.com']

But actually it seems to only match the domain, it does work when i leave `http://` at the beginning.

This feature would of course be far more helpful if it did work like this, so i could match a folder on a server such as `https://s3-eu-west-1.amazonaws.com/ucm-media/.+`

Its also not clear if its a regex, as suggested by the comments in the file, or just a search string. If its a regex then the example should surely have `\` before the `.` in the domain.

**Comment by mcfedr** [comment]
@guilhermef is that closed because its fixed or because won't fix?

**Comment by guilhermef** [comment]
@mcfedr I was just closing old issues, since we've changed a lot of things since this issue was open.
We can change the current implementation to support a regex on ALLOWED_SOURCES.

**Comment by guilhermef** [comment]
@mcfedr This commit(https://github.com/thumbor/thumbor/commit/8d983205bf24b787b2f42cff2932838cb74f7ff6) allows regex patterns to be matched against the url.

i.e.:  ALLOWED_SOURCES=[re.compile(r'^https:\/\/www\.google\.com/img/.*')]

@masom @heynemann what do you guys think ?

**Comment by mcfedr** [comment]
That looks great to me

**Comment by masom** [comment]
Great!

**Comment by isTravis** [comment]
Has anyone had success with that? I have the following:

```
ALLOWED_SOURCES=[re.compile(r'^https://www.mysite.org/.*')]
```
which throws:
```
NameError: name 're' is not defined 
```

**Comment by mcfedr** [comment]
Try adding `import re` at the top of the conf file

**Comment by isTravis** [comment]
Durp... Thank you! 

I didn't realize thumbor.conf was just a regular python file. I assumed the values in the conf file were executed elsewhere (where re would be imported). 

Thanks again for the very speedy reply.
