### ISSUE TITLE
extend transparent background

### ISSUE THREAD

**Issue by evanmo** [thumbor/thumbor#419]
Hi all,

I want to resize my image without crop it, and extend with transparent background if the ratio not match.
My thumbor path like ```fit-in/320x240/filters:fill(white)/image.png```
But ```filter:fill``` seems not support transparent parameter.
Can anyone help me. Thanks.

**Comment by scorphus** [comment]
Hi, @evanmo. Try `fit-in/320x240/filters:fill(white,true)/image.png` or `fit-in/320x240/filters:fill(white,1)/image.png`. It should work.

**Comment by scorphus** [comment]
Thanks to you, I've updated the docs: https://github.com/thumbor/thumbor/wiki/Filling :smiley:

**Comment by evanmo** [comment]
@scorphus,  Thank you for your reply.
Maybe I make an wrong expression because i am not a native English speaker.
My purpose is resizing image and keeping the transparent background. (no image cropping)
Can thumbor do that?

**Comment by scorphus** [comment]
I'm sorry, @evanmo, rereading your first message now I see I misunderstood it. Thumbor can't do that. Not yet, at least.

**Comment by scorphus** [comment]
Hello again, @evanmo. Can you please let us know what your needs are? And why would you need the image to be extended and filled with transparency? Thanks.

**Comment by evanmo** [comment]
Hello, @scorphus 

What I need are resizing transparent image without cropping.
For example:
I have a png image 320x240
![github1](https://cloud.githubusercontent.com/assets/270899/6436006/69ff9cce-c0e3-11e4-8a60-237eebdb4404.png) 

I need to resize it to 320x250 and keep the extend background transparent, not black.
thumbor path ```/fit-in/320x250/filters:fill(black)/image.png```

![github2](https://cloud.githubusercontent.com/assets/270899/6436197/6da548ee-c0e6-11e4-9483-eaf5c3a0d298.png)

Thanks for your help.

**Comment by heynemann** [comment]
Makes sense. Right now we don't have this capability. Do you have the means to implement this with a Pull Request? If so that would be awesome. 

If not, one way that has worked in the past is to finance this development with bounty source: https://www.bountysource.com/issues/8855459-extend-transparent-background

That might help get the development you need done fast and would benefit the whole community! :)

**Comment by scorphus** [comment]
@evanmo: https://github.com/thumbor/thumbor/wiki/Filling :smiley:

**Comment by heynemann** [comment]
We need this implemented in MagickEngine as well @scorphus Nice job, though! Very nice job!

**Comment by scorphus** [comment]
MagickEngine just supports it out of the box. How cool is that! Not a single line of code change needed :trophy:

**Comment by heynemann** [comment]
Awesome!!!

**Comment by evanmo** [comment]
Awesome! @scorphus , many thanks!
