### ISSUE TITLE
Signed urls with + are malformed

### ISSUE THREAD

**Issue by kartikluke** [thumbor/thumbor#420]
```
2015-02-26 15:53:49 tornado.access:WARNING 404 GET /ucjdhSH9IP3mZJwAz4PHhhBylKI=/100x100/https://jobspireproduction.s3.amazonaws.com/uploads/1424965974657-thubiuaa9p8-15476f062670b360b184c563e51c4acb/logo+copy.jpg (127.0.0.1) 1.54ms
```

I'm getting errors for URLs with spaces in them.

**Comment by kartikluke** [comment]
Trying the other character for space %20. Still gives the same error 2015-02-26 17:36:57 
```
thumbor:WARNING Malformed URL: /dYNUNBBMHpjr0wCW_6r66Y8bLgw=/200x200/https://jobspiredevelopment.s3.amazonaws.com/uploads/1424971984330-lzcvfxwxwoo-8276aa983150de2409dc4d584d5ff214/grey%20face.png
```

**Comment by kartikluke** [comment]
Alright changing + to %20 before signing allows this to work. But I don't see the harm in adding + to the allowed characters as S3 accepts it as blank space.

**Comment by heynemann** [comment]
S3 does allow it, but thumbor is not meant to support only S3 as storage. :(

We do not make any assumptions about URLs. Either the URL is correct or we can't find it. Sorry.

**Comment by kartikluke** [comment]
Alright so + is incorrect usage? Or I guess not the standard?

**Comment by heynemann** [comment]
Yep... When URL encoding an URL the character that corresponds to a space is %20, not +.

You could write your own loader for thumbor to account for that. I don't think it's worthy, though. I'd just encode the URL before appending to thumbor's URL.

**Comment by kartikluke** [comment]
Yeah I've already implemented it. Thank you I thought + was a valid
character as s3 accepted it. Thanks for your time. Love the project. :)

**Comment by kartikluke** [comment]
Hello!
Your friend Kartik S. recently e-filed taxes on ClearTax -- and wants to recommend ClearTax to you for your tax return filing.

I'll give you a little bit of context on ClearTax: India's largest tax platform with over a million Indian tax payers and 20,000 businesses. E-Filing is secure and free on our platform.

    - If you receive a Form-16, just upload it here - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcd4I-2BBn3xohJ9LxX-2B0LmjnB6TLj-2FWQdfNzgfLYzg8A51TRvlaw-2F5siwCtsDS5-2BHsU1jPcMyiqZAaLDpXCC-2FKdlpY0QZoVHX65-2F99g0jcW05RYk50d745zZ5BgyPxcfbPoj9XJC5QLIa4bwHO1KHn2DOl6Z0hle2oVl8CBVerPiN6PSnNx3wSU8jFChezGIf5yBbOeNK0sqN2e-2B-2BF9-2Fw5RTGXceYAB4wtH-2FHrAUSx5MrxV82toXusmVcW1OPcI0AOofcvP9vlEcczBn-2BQ-2FUq3EAlct-2Bm2mD0CozQ63Qju2JoA-2BdKCJzr-2FX5rDIo4elejVsktIyvDNzUGyIZMrUbKteJ6u656r0NCQb1x-2FBWKXT8rP and automatically all details will be filled for you.
    - We support all income types from Indian residents, NRIs, Freelancers and Businesses.
    - We partner with large corporations, public banks and state Governments for customers and employees.

We would love to help you with your e-Filing. Here's the invitation referral link - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcd4I-2BBn3xohJ9LxX-2B0LmjnB6TLj-2FWQdfNzgfLYzg8A51TRvlaw-2F5siwCtsDS5-2BHsU1jPcMyiqZAaLDpXCC-2FKdlpY0QZoVHX65-2F99g0jcW05RYk50d745zZ5BgyPxcfbPoj9XJC5QLIa4bwHO1KHn2DOl6Z0hle2oVl8CBVerPiN6eoy1TajE-2FBh3Px-2Fkb93ME32JoyaIIgS3HR6-2FKCizv1clfuWjBnHpN6KTPjnhNbt0-2Fx9supYaXuxfuw6PC7U6qE14PFQW-2BypJBv1Il5-2BWyBb0-2BnIkj6iOdDXoQkK7zReD6vBZOruKZsHUVRcmdlIeYs1WKCg-2F4y3QTb95isCc-2FPrVTpm5QYlG40xJnldK1W-2FG

Best,
Neha, Head Customer support, ClearTax

PS: Economic Times and NDTV ranked ClearTax as the best tax platform in India.

**Comment by kartikluke** [comment]
Hello!
Your friend Kartik S. recently e-filed taxes on ClearTax -- and wants to recommend ClearTax to you for your tax return filing.

I'll give you a little bit of context on ClearTax: India's largest tax platform with over a million Indian tax payers and 20,000 businesses. E-Filing is secure and free on our platform.

    - If you receive a Form-16, just upload it here - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcd4I-2BBn3xohJ9LxX-2B0LmjnB6TLj-2FWQdfNzgfLYzg8A51TRvlaw-2F5siwCtsDS5-2BHsU1jPcMyiqZAaLDpXCC-2FKdlpY0QZoVHX65-2F99g0jcW05RYk50d745zZ5BgyPxcfbPojRYAESI3Az82d83i1iLn8wUOlcxKVyXNcElad5dIAsfuhXnnpaSBdlAGllQ70811jpf05zgjrvn0IV6nFIFNmBedtaokZNyIhHt2vIIdyYWWbF4lzbuew5Gd2IH9vdAtrdR4CD-2F-2Fv4IS27FhEJt839Zwrrl0Xl-2BB5ihB88BYL8GLaWbHm5qhrpFOylaGVKneKwlmOxaPRpNZKR-2FoZ9shpZ4qJvcgmYMqMPHiTFosfpN and automatically all details will be filled for you.
    - We support all income types from Indian residents, NRIs, Freelancers and Businesses.
    - We partner with large corporations, public banks and state Governments for customers and employees.

We would love to help you with your e-Filing. Here's the invitation referral link - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcd4I-2BBn3xohJ9LxX-2B0LmjnB6TLj-2FWQdfNzgfLYzg8A51TRvlaw-2F5siwCtsDS5-2BHsU1jPcMyiqZAaLDpXCC-2FKdlpY0QZoVHX65-2F99g0jcW05RYk50d745zZ5BgyPxcfbPojRYAESI3Az82d83i1iLn8wUOlcxKVyXNcElad5dIAsfnCZQBrw-2BJsAmG3uovCjbJQYtiX7STUeWNaKSTXk0tOb9kEydrPYbmwCtEpm2MRZlEEmPpeANtRtIddRPjOWmzJi2e9mY2mu00Ru8nx-2BdYJrFqIADQnrOK4LhulcHyccucIgZrH9D1B4D1p-2FUXEs4EVyQjB-2F-2FuzL2n1YGFm5McAq-2BLmu7Ad6zaMcL5iHwczCQ

Best,
Neha, Head Customer support, ClearTax

PS: Economic Times and NDTV ranked ClearTax as the best tax platform in India.
