### ISSUE TITLE
Optimizers are not asynchronous

### ISSUE THREAD

**Issue by masom** [thumbor/thumbor#434]
We're hitting some concurrency issues when using optimizers.

Upon investigation, it was discovered optimizers are not asynchronous ( also mentioned by @kevin1024, https://github.com/thumbor/thumbor/pull/429 )

**Comment by masom** [comment]
@kevin1024 are you working on making the optimizers be asynchronous? If not it is something I can start.

**Comment by kevin1024** [comment]
Yeah, it's on my to-do list.  I think I will just execute them in a threadpool like I'm doing with the transformers.

**Comment by masom** [comment]
Cool. If you need help with anything let me know. I'll be happy to help.

**Comment by masom** [comment]
Fixed by https://github.com/thumbor/thumbor/pull/429
