### ISSUE TITLE
thumborize.me seems broken?

### ISSUE THREAD

**Issue by msumme** [thumbor/thumbor#440]
Not sure where to report this issue - but nothing happens on thumborize.me, which is linked from thumbor.org.

I've waited over 10 minutes for a single image.  That's on Chrome.

On Firefox, it looks like this:
![image](https://cloud.githubusercontent.com/assets/462931/6678117/63606bd8-cc04-11e4-9430-0b0a307b0a6d.png)

I guess the CSS or JS isn't properly loading there?

**Comment by heynemann** [comment]
Should be working properly now. Can you test it?

**Comment by msumme** [comment]
Not quite: 
![image](https://cloud.githubusercontent.com/assets/462931/6691537/3022b140-cc95-11e4-9845-68b1289d0140.png)


That's on Chrome.  

What's it supposed to do?

**Comment by heynemann** [comment]
You are not supposed to add an image, you are supposed to add your website,
like this:

http://thumborize.me/?url=http://dreamatico.com

Hope it helps!

**Comment by msumme** [comment]
Makes sense.  I was expecting a "demo" when I clicked the link from the
docs - where I expected to put an image in and see it cropped.  So - my bad
not reading the page.

So there's nowhere you can go to see the abilities of thumbor without
installing it?

**Comment by heynemann** [comment]
http://plouc.github.io/thumbor-toy/

Hope it helps! :)

**Comment by msumme** [comment]
Awesome! Thanks.
