### ISSUE TITLE
Use static pre-compiled ffmpeg

### ISSUE THREAD

**Issue by masom** [thumbor/thumbor#441]
Half the CI time seems to be spent compiling ffmpeg.

http://johnvansickle.com/ffmpeg/ has statically compiled binaries.

**Comment by heynemann** [comment]
Nice! :)

**Comment by masom** [comment]
@heynemann I'll submit a PR with a working travis.yml

**Comment by masom** [comment]
PR has been rebased. Unless Mongo fails again this should be good to go.
