### ISSUE TITLE
Who's using it?

### ISSUE THREAD

**Issue by falschparker82** [thumbor/thumbor#446]
Hi there,

At JustWatch, we're big fans of Thumbor as well:

https://www.justwatch.com/us/

We're serving it behind a CloudFront custom origin like many others, and features like WebP and smart cropping saved us huge amounts of time and bandwidth.

What we did on top was write a custom proxy server in Go, so we could use shorter, SEO-optimized and more speaking URLs like 

https://images.justwatch.com/poster/297896/s718/Guardians-of-the-Galaxy 

instead of something like

https://images.justwatch.com/unsafe/300x0/smart/http:/i.imgur.com/MwZwcOY.jpg 

That way we are still able to use the great features of Thumbor while we can very quickly iterate through different variations in our staging system.

We're currently thinking of open sourcing this component as well, but it's still tightly coupled with our API.

Here's our logo, would be great if you could mention us on your "Who's using it?" page:

https://lh4.googleusercontent.com/gHam5ielak_FmlYLnl9ONZSD_LXyp8SLS1LbU9xt7WedO3BiX8KVGGUmcYXEX7UB__14GA=w1883-h1153

**Comment by heynemann** [comment]
When opening your logo image I get 403... ;(

> 403 That’s an error.

> Your client does not have permission to get URL /gHam5ielak_FmlYLnl9ONZSD_LXyp8SLS1LbU9xt7WedO3BiX8KVGGUmcYXEX7UB__14GA=w1883-h1153 from this server. (Client IP address: 186.192.87.77)

> Forbidden That’s all we know.

**Comment by webffo** [comment]
Hi @falschparker82 , is there any news regarding the proxy? I would love to test it.

**Comment by SergioJorge** [comment]
Hi @falschparker82 

Your logo image return 403.
You can send your testimonial at [testimonials](http://thumbor.org/testimonials).
