### ISSUE TITLE
jpeg compression not lossless

### ISSUE THREAD

**Issue by rcrowe** [thumbor/thumbor#456]
I've recently setup a new Thumbor instance of Centos & haven't seen this issue before when running under Ubuntu.

I can see that Ubuntu and CentOS are using different jpeg libraries, libjpeg8 in Ubuntu and libjpeg-turbo in CentOS.

Original: https://files-crowdcube-com.s3.amazonaws.com/files/pitch_pics/original/201503/213cfa94f1f60f106226b29144694b26_2880.jpg

Resized: https://d2fhjrohvhnm6j.cloudfront.net/unsafe/fit-in/200x150/https://files-crowdcube-com.s3.amazonaws.com/files/pitch_pics/original/201503/213cfa94f1f60f106226b29144694b26_2880.jpg

I'm not saying this is a Thumbor issue, more likely its dependencies. But any idea where to start on this?

**Comment by rcrowe** [comment]
Hmm, just tried it out with the Ubuntu version & seeing the same issue.

https://46.101.62.157/unsafe/fit-in/200x150/https://files-crowdcube-com.s3.amazonaws.com/files/pitch_pics/original/201503/213cfa94f1f60f106226b29144694b26_2880.jpg

Both servers are running with QUALITY = 80 so wouldn't expect to see such impact on the resized image.

**Comment by guilhermef** [comment]
For this case, I think it would behave better as a PNG,
so you can try: https://46.101.62.157/unsafe/fit-in/200x150/filters:format(png)/https://files-crowdcube-com.s3.amazonaws.com/files/pitch_pics/original/201503/213cfa94f1f60f106226b29144694b26_2880.jpg

or force the quality up: https://46.101.62.157/unsafe/fit-in/200x150/filters:quality(100)/https://files-crowdcube-com.s3.amazonaws.com/files/pitch_pics/original/201503/213cfa94f1f60f106226b29144694b26_2880.jpg

**Comment by rcrowe** [comment]
Thanks for the update. `filters:format(png)` does bring back the crispness, but unfortunately takes a ~144kb JPG to over a 1mb png file.

Changing the quality to 100 does improve the image, but has still lost the sharpness of the image.

**Comment by guilhermef** [comment]
Are you sure ?
Because I was seeing a 22.3kb png.

**Comment by rcrowe** [comment]
Sorry was testing a different image; 2secs I'll get those links.

**Comment by rcrowe** [comment]
Original (602kb): https://files-crowdcube-com.s3.amazonaws.com/banners/bigeasy-banner5.jpg

Resized (1013kb): https://46.101.62.157/unsafe/fit-in/1200x400/filters:format(png)/https://files-crowdcube-com.s3.amazonaws.com/banners/bigeasy-banner5.jpg

**Comment by rcrowe** [comment]
So is the issue with the underlying jpeg library? Seems that quality is heavily effected on jpegs with each jpeg behaving differently.

**Comment by guilhermef** [comment]
@rcrowe can you enable the jpegtran optimizer on your environment ?

**Comment by rcrowe** [comment]
I've enabled it on the staging server where the quality is set at 95%:

https://images-staging.crowdcube.com/unsafe/fit-in/1200x400/https://files-crowdcube-com.s3.amazonaws.com/banners/bigeasy-banner5.jpg

Couldn't see a change in filesize for the when converting to png or jpegtran turned on or off.

**Comment by rcrowe** [comment]
Presuming the `pngquant` optimizer is ready yet & how much of an impact that would make.

**Comment by rcrowe** [comment]
Feels like JPEG just can't be used without a loss of quality?

**Comment by guilhermef** [comment]
Since we use it more for non vetorial like images, we didn't notices this.

**Comment by rcrowe** [comment]
What do you want me to do with this ticket? Not sure it's an issue with Thumbor.

Going to change quality to 95 in production to get over really bad images for the time being.

**Comment by guilhermef** [comment]
I'll just close it.
