### ISSUE TITLE
Which Python version it supports? Cannot install on CentOS 6

### ISSUE THREAD

**Issue by AizazAZ** [thumbor/thumbor#460]
pip install git+git://github.com/globocom/thumbor.git
Downloading/unpacking git+git://github.com/globocom/thumbor.git
  Cloning git://github.com/globocom/thumbor.git to /tmp/pip-EJ2zq5-build
  Running setup.py egg_info for package from git+git://github.com/globocom/thumbor.git
    no previously-included directories found matching 'dist'
    no previously-included directories found matching 'build'
Requirement already satisfied (use --upgrade to upgrade): tornado>2.3.0,<4.0.0 in /usr/lib64/python2.6/site-packages (from thumbor==4.12.2)
Downloading/unpacking pyCrypto>=2.1.0 (from thumbor==4.12.2)
  Running setup.py egg_info for package pyCrypto
Requirement already satisfied (use --upgrade to upgrade): pycurl>=7.19.0,<7.20.0 in /usr/lib64/python2.6/site-packages (from thumbor==4.12.2)
Downloading/unpacking Pillow>=2.3.0,<3.0.0 (from thumbor==4.12.2)
  Running setup.py egg_info for package Pillow
    Single threaded build, not installing mp_compile: 1 processes
Downloading/unpacking derpconf>=0.2.0 (from thumbor==4.12.2)
  Running setup.py egg_info for package derpconf
Downloading/unpacking python-magic>=0.4.3 (from thumbor==4.12.2)
  Running setup.py egg_info for package python-magic
Downloading/unpacking pexif>=0.15,<1.0 (from thumbor==4.12.2)
  Running setup.py egg_info for package pexif
Downloading/unpacking statsd>=3.0.1 (from thumbor==4.12.2)
  Running setup.py egg_info for package statsd
Downloading/unpacking libthumbor (from thumbor==4.12.2)
  Running setup.py egg_info for package libthumbor
    no previously-included directories found matching 'dist'
    no previously-included directories found matching 'build'
Downloading/unpacking futures (from thumbor==4.12.2)
  Running setup.py egg_info for package futures
Downloading/unpacking backports.ssl-match-hostname (from tornado>2.3.0,<4.0.0->thumbor==4.12.2)
  Running setup.py egg_info for package backports.ssl-match-hostname
Downloading/unpacking six (from derpconf>=0.2.0->thumbor==4.12.2)
  Running setup.py egg_info for package six
    no previously-included directories found matching 'documentation/_build'
Installing collected packages: pyCrypto, Pillow, derpconf, python-magic, pexif, statsd, libthumbor, futures, backports.ssl-match-hostname, six
  Running setup.py install for pyCrypto
    warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
    building 'Crypto.Hash._MD2' extension
    gcc -pthread -fno-strict-aliasing -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.6 -c src/MD2.c -o build/temp.linux-x86_64-2.6/src/MD2.o
    src/MD2.c:31:20: error: Python.h: No such file or directory
    src/MD2.c:131: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
    In file included from src/MD2.c:147:
    src/hash_template.c:48: error: expected specifier-qualifier-list before 'PyObject_HEAD'
    src/hash_template.c:59: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'PyTypeObject'
    src/hash_template.c: In function 'newALGobject':
    src/hash_template.c:69: warning: implicit declaration of function 'PyObject_New'
    src/hash_template.c:69: error: expected expression before 'ALGobject'
    src/hash_template.c: At top level:
    src/hash_template.c:76: error: expected ')' before '*' token
    src/hash_template.c:91: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
    src/hash_template.c:110: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
    src/hash_template.c:122: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
    src/hash_template.c:162: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
    src/hash_template.c:188: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
    src/hash_template.c:190: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'ALG_methods'
    src/hash_template.c:199: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
    src/hash_template.c:225: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'ALGtype'
    src/hash_template.c:271: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
    src/hash_template.c:304: error: array type has incomplete element type
    src/hash_template.c:305: error: 'PyCFunction' undeclared here (not in a function)
    src/hash_template.c:305: error: expected '}' before 'ALG_new'
    src/hash_template.c: In function 'init_MD2':
    src/hash_template.c:339: error: 'PyObject' undeclared (first use in this function)
    src/hash_template.c:339: error: (Each undeclared identifier is reported only once
    src/hash_template.c:339: error: for each function it appears in.)
    src/hash_template.c:339: error: 'm' undeclared (first use in this function)
    src/hash_template.c:351: error: 'ALGtype' undeclared (first use in this function)
    src/hash_template.c:351: error: 'PyType_Type' undeclared (first use in this function)
    src/hash_template.c:352: warning: implicit declaration of function 'Py_InitModule'
    src/hash_template.c:356: error: 'o' undeclared (first use in this function)
    src/hash_template.c:356: warning: implicit declaration of function 'PyInt_FromLong'
    src/hash_template.c:356: warning: implicit declaration of function 'PyDict_SetItemString'
    src/hash_template.c:356: warning: implicit declaration of function 'PyModule_GetDict'
    src/hash_template.c:356: warning: implicit declaration of function 'Py_DECREF'
    src/hash_template.c:360: warning: implicit declaration of function 'PyErr_Occurred'
    src/hash_template.c:361: warning: implicit declaration of function 'Py_FatalError'
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-root/pyCrypto/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kSWrB_-record/install-record.txt --single-version-externally-managed:
    running install

running build

running build_py

running build_ext

running build_configure

warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.

building 'Crypto.Hash._MD2' extension

gcc -pthread -fno-strict-aliasing -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.6 -c src/MD2.c -o build/temp.linux-x86_64-2.6/src/MD2.o

src/MD2.c:31:20: error: Python.h: No such file or directory

src/MD2.c:131: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token

In file included from src/MD2.c:147:

src/hash_template.c:48: error: expected specifier-qualifier-list before 'PyObject_HEAD'

src/hash_template.c:59: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'PyTypeObject'

src/hash_template.c: In function 'newALGobject':

src/hash_template.c:69: warning: implicit declaration of function 'PyObject_New'

src/hash_template.c:69: error: expected expression before 'ALGobject'

src/hash_template.c: At top level:

src/hash_template.c:76: error: expected ')' before '*' token

src/hash_template.c:91: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token

src/hash_template.c:110: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token

src/hash_template.c:122: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token

src/hash_template.c:162: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token

src/hash_template.c:188: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token

src/hash_template.c:190: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'ALG_methods'

src/hash_template.c:199: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token

src/hash_template.c:225: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'ALGtype'

src/hash_template.c:271: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token

src/hash_template.c:304: error: array type has incomplete element type

src/hash_template.c:305: error: 'PyCFunction' undeclared here (not in a function)

src/hash_template.c:305: error: expected '}' before 'ALG_new'

src/hash_template.c: In function 'init_MD2':

src/hash_template.c:339: error: 'PyObject' undeclared (first use in this function)

src/hash_template.c:339: error: (Each undeclared identifier is reported only once

src/hash_template.c:339: error: for each function it appears in.)

src/hash_template.c:339: error: 'm' undeclared (first use in this function)

src/hash_template.c:351: error: 'ALGtype' undeclared (first use in this function)

src/hash_template.c:351: error: 'PyType_Type' undeclared (first use in this function)

src/hash_template.c:352: warning: implicit declaration of function 'Py_InitModule'

src/hash_template.c:356: error: 'o' undeclared (first use in this function)

src/hash_template.c:356: warning: implicit declaration of function 'PyInt_FromLong'

src/hash_template.c:356: warning: implicit declaration of function 'PyDict_SetItemString'

src/hash_template.c:356: warning: implicit declaration of function 'PyModule_GetDict'

src/hash_template.c:356: warning: implicit declaration of function 'Py_DECREF'

src/hash_template.c:360: warning: implicit declaration of function 'PyErr_Occurred'

src/hash_template.c:361: warning: implicit declaration of function 'Py_FatalError'

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-root/pyCrypto/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kSWrB_-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip-build-root/pyCrypto
Storing complete log in /root/.pip/pip.log

**Comment by AizazAZ** [comment]
[root@ip-172-31-2-176 tmp]# easy_install thumbor
Searching for thumbor
Best match: thumbor 4.12.2
Adding thumbor 4.12.2 to easy-install.pth file
Installing thumbor script to /usr/bin
Installing thumbor-url script to /usr/bin
Installing thumbor-config script to /usr/bin

Using /usr/lib/python2.6/site-packages
Processing dependencies for thumbor
Searching for futures
Reading http://pypi.python.org/simple/futures/
Best match: futures 2.2.0
Downloading https://pypi.python.org/packages/source/f/futures/futures-2.2.0.tar.gz#md5=310e446de8609ddb59d0886e35edb534
Processing futures-2.2.0.tar.gz
Running futures-2.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-8rNnUl/futures-2.2.0/egg-dist-tmp-Ig_vcO
Adding futures 2.2.0 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/futures-2.2.0-py2.6.egg
Searching for libthumbor
Reading http://pypi.python.org/simple/libthumbor/
Best match: libthumbor 1.0.1
Downloading https://pypi.python.org/packages/source/l/libthumbor/libthumbor-1.0.1.tar.gz#md5=4e7b6c6137fe8686cf48283780989749
Processing libthumbor-1.0.1.tar.gz
Running libthumbor-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-DOswtV/libthumbor-1.0.1/egg-dist-tmp-DY9Wke
no previously-included directories found matching 'dist'
no previously-included directories found matching 'build'
zip_safe flag not set; analyzing archive contents...
Adding libthumbor 1.0.1 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/libthumbor-1.0.1-py2.6.egg
Searching for statsd>=3.0.1
Reading http://pypi.python.org/simple/statsd/
Best match: statsd 3.1
Downloading https://pypi.python.org/packages/source/s/statsd/statsd-3.1.tar.gz#md5=8f7b49412b09b2fedb2c8c70f0f10192
Processing statsd-3.1.tar.gz
Running statsd-3.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-R6R0fV/statsd-3.1/egg-dist-tmp-NF9ZM3
zip_safe flag not set; analyzing archive contents...
Adding statsd 3.1 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/statsd-3.1-py2.6.egg
Searching for pexif>=0.15,<1.0
Reading http://pypi.python.org/simple/pexif/
Best match: pexif 0.15
Downloading http://www.benno.id.au/code/pexif/pexif-0.15.tar.gz
error: Can't download http://www.benno.id.au/code/pexif/pexif-0.15.tar.gz: 404 Not Found

**Comment by AizazAZ** [comment]
Step 1 : sudo yum install python-devel
Step 2: pip install thumbor and done :+1:

**Comment by AizazAZ** [comment]
[root@ip-172-31-2-176 bin]# thumbor --ip 54.255.183.121
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.brightness could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.colorize could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.contrast could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.rgb could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.round_corner could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.noise could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.watermark could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.equalize could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.fill could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.sharpen could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.frame could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.convolution could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.blur could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.saturation could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.curve could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Error importing bounding_box filter, trimming won't work
Traceback (most recent call last):
  File "/usr/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==4.12.2', 'console_scripts', 'thumbor')()
  File "/usr/lib/python2.6/site-packages/thumbor/server.py", line 95, in main
    server.bind(context.server.port, context.server.ip)
  File "/usr/lib64/python2.6/site-packages/tornado/tcpserver.py", line 162, in bind
    backlog=backlog)
  File "/usr/lib64/python2.6/site-packages/tornado/netutil.py", line 104, in bind_sockets
    sock.bind(sockaddr)
  File "<string>", line 1, in bind
socket.error: [Errno 99] Cannot assign requested address

**Comment by dhardy92** [comment]
again 54.255.183.121 is not the local ip on host

due to recent changes (logging feature at least), Python2.6 support is not any more. only Python2.7.

**Comment by heynemann** [comment]
We dropped support to Python 2.6. Sorry.

**Comment by vanjulchrist** [comment]
> Step 1 : sudo yum install python-devel
Step 2: pip install thumbor and done 👍

It works for me, thanks !!
