### ISSUE TITLE
Better debugging message for signed URLs

### ISSUE THREAD

**Issue by bfischer1121** [thumbor/thumbor#462]
I think it'd be helpful if the malformed url error mentions that the security key may be wrong.

It took me a day or two to figure that out when all that was in the error log was:
thumbor:WARNING Malformed URL: ...
tornado.access:WARNING 404 GET ...

**Comment by heynemann** [comment]
What do you think the message should say?

**Comment by bfischer1121** [comment]
I'd actually split it into 2 error messages depending on the path. If url validation fails, something like "thumbor:ERROR Could not validate signed URL: ...", and the existing message for other errors
