### ISSUE TITLE
just rotate

### ISSUE THREAD

**Issue by whiskeykontequila** [thumbor/thumbor#466]
Is there any way to just rotate image according to exif tag, and do not affect quality of the image. I was trying different settings / url parameters but I could not get thumbor to just rotate image, update orientation exif tag to normal and output same size/quality image.

**Comment by metalcro** [comment]
If something like

`http://localhost:8888/unsafe/filters:rotate(90)/https://raw.githubusercontent.com/wiki/thumbor/thumbor/tom_before_rotate.jpg`

is giving you issues, you could always perform whatever other manipulations you're using thumbor for  and then set a class to rotate the image with css. I realize that doesn't solve your issue with thumbor's rotate, but it's a workaround.

**Comment by heynemann** [comment]
There's a config flag for automatically rotating according to exif - https://github.com/thumbor/thumbor/wiki/Configuration#respect_orientation

Hope it helps!

**Comment by whiskeykontequila** [comment]
@metalcro @heynemann Thanks - I'm using respect_orientation =True and preserve_exif = False (to avid image being rotated from thumbor and then rotate by browser again). My question was how to *just* rotate according to that tag and do not touch quality and other image properties.

**Comment by bborn** [comment]
+1 also would like to be able to *just* resize an image without affecting quality. Right now it seems thumbor always optimizes the image (correct me if I'm wrong), which gives me poorer quality when scaling an image (and, weirdly, also larger file sizes sometimes)

**Comment by heynemann** [comment]
You can just resize... Just use filter:quality(90) if  your global quality
is lower than that.

Thumbor does not optimize the image any further than:

* Remove metadata;
* Use the imaging engine compression (depends on the image type and engine).

Cheers,

Bernardo Heynemann
Developer @ globo.com

**Comment by kshipp** [comment]
RESPECT_ORIENTATION = True --> isn't working.

**Comment by sbaechler** [comment]
@whiskeykontequila When you rotate an image you are creating a new generation and the quality will degrade. Since most browsers ignore the embedded Exif Orientation value, there is no way around that.
