### ISSUE TITLE
Predefined sizes

### ISSUE THREAD

**Issue by diequeiroz** [thumbor/thumbor#467]
Is there a way to create "aliases" to sizes or filters?

For example, something like this:

http://thumbor-server/**thumb**/s.glbimg.com/et/bb/f/original/2011/03/24/VN0JiwzmOw0b0lg.jpg
http://thumbor-server/**large**/s.glbimg.com/et/bb/f/original/2011/03/24/VN0JiwzmOw0b0lg.jpg

would correspond to 

http://thumbor-server/**60x40/smart**/s.glbimg.com/et/bb/f/original/2011/03/24/VN0JiwzmOw0b0lg.jpg
http://thumbor-server/**1024x768/smart**/s.glbimg.com/et/bb/f/original/2011/03/24/VN0JiwzmOw0b0lg.jpg

**Comment by heynemann** [comment]
Why do you need this?

**Comment by diequeiroz** [comment]
To control what sizes can be served

**Comment by heynemann** [comment]
Then you can do it in something like NGinx or you can build a layer before thumbor itself.

**Comment by diequeiroz** [comment]
Thanks!!
