### ISSUE TITLE
Make HTTPS default configurable? HTTPS by default?

### ISSUE THREAD

**Issue by lukaselmer** [thumbor/thumbor#470]
Hi,

We use thumbor for our image resizing service, and it's great, thanks! We now would like that thumbor fetches the images using HTTPS by default. I know that we could configure it (e.g. change the image url by adding https:// in front of the url, or specify a custom loader in the config), but I'd like to ask what you think about

* Changing the default to HTTPS here: https://github.com/thumbor/thumbor/blob/master/thumbor/loaders/http_loader.py#L22
* Adding an option so the https://github.com/thumbor/thumbor/blob/master/thumbor/loaders/http_loader.py
 * uses HTTPS by default,
 * or even restricts to HTTPS only

Of course I would implement any of these options and make a pull request.

**Comment by masom** [comment]
We had to move away from HTTPS on high-load thumbor instances due to the time it takes to do SSL negotiation.

**Comment by lukaselmer** [comment]
Good to know, but how is that related to this issue? Sure you need more server performance when using SSL, but you can just add more servers if HTTPS is worth it for you and your users / customers.

**Comment by heynemann** [comment]
What do you think of a third option:

Creating a https_loader that inherits from http_loader but favors HTTPS first? That way we are backwards-compatible AND support more use cases.

**Comment by lukaselmer** [comment]
:+1: I actually considered that too, but then I thought that the code can be maintained easier if it's kept in one loader. And it would take away the opportunity to supply http:// image urls.

**Comment by lukaselmer** [comment]
But for us an https_loader would be the right solution since we want to use https only.

**Comment by lukaselmer** [comment]
Basic implementation for a strict https loader (no tests yet): https://github.com/lukaselmer/thumbor/commit/854dc538df897abc2fcb87737c1ddbe0fb614e47

**Comment by lukaselmer** [comment]
If you ack that this is the right approach I'll write tests and make a PR :wink:

**Comment by lukaselmer** [comment]
Basic implementation for a strict and a non-strict https loader (no tests yet): https://github.com/lukaselmer/thumbor/compare/master...https-loader

**Comment by heynemann** [comment]
Looks good! :)

**Comment by lukaselmer** [comment]
Continuing in #471, closing this issue
