### ISSUE TITLE
Autorotation and scaling problems

### ISSUE THREAD

**Issue by onyxmaster** [thumbor/thumbor#472]
We have RESPECT_ORIENTATION = True and orientation preservation works great, but when resizing the images exhibit strange problems.
Consider the Portrait_5.jpg from https://github.com/recurser/exif-orientation-examples as a source image. While the original is 600x450, after orientation transform it should become 450x600. Unfortunately, while thumboring it handles the pixel data correctly, "resizing" it to 450x600 leads to it being cropped to 450x450:
http://images.d3-x.net/lxGvawLcvpDF48Eb8cvWoIF0b0c=/450x600/filters:no_upscale()/post/FNMqBmgNOTlFWd1hEJCDp8ID2AQB.jpg
I believe this is not a result most would expect from automatic orientation handling.

**Comment by guilhermef** [comment]
@onyxmaster It was really a bug, we weren't considering reorientation when we limited the image with the no_upscale filter.
This https://github.com/thumbor/thumbor/commit/0fc258aa92432ce0f99e5a228c9a591be2600423 should solve it.
Do you mind testing ?

**Comment by onyxmaster** [comment]
Will do next week, thanks for the fix.

**Comment by onyxmaster** [comment]
Works for us, thank you again.
