### ISSUE TITLE
Forward request headers to target server

### ISSUE THREAD

**Issue by mariotaku** [thumbor/thumbor#473]
Some server (e.g. ton.twitter.com) requires authorization header for getting image, seems thumbor does not forward some request headers.

Is it already an option I haven't found or feature not yet implemented?

**Comment by guilhermef** [comment]
We create a new request object every time, without using the current request parameters.
https://github.com/thumbor/thumbor/blob/master/thumbor/loaders/http_loader.py#L73

**Comment by mariotaku** [comment]
Can I write some plugin to modify request?

**Comment by guilhermef** [comment]
You can write a loader that uses the current request headers.

**Comment by heynemann** [comment]
I'm going to close this as creating a loader should solve the issue. @mariotaku if you need more info on loaders, please check the docs https://github.com/thumbor/thumbor/wiki/Image-loader#custom-loaders
