### ISSUE TITLE
Webm to gif 

### ISSUE THREAD

**Issue by Juanchimienti** [thumbor/thumbor#474]
I see that gifv() optimizer gives the ability to transform gifs to webm and mpeg. I was wondering if there is a way to make webms back to gifs. 
In case the feature does not exists, do you plan to add it ?

**Comment by guilhermef** [comment]
I doesn't exist now, since we only deal with images. 
You would have to implement a engine that supports videos.
It's not impossible, but I don't see thumbor supporting vides anytime soon.
