### ISSUE TITLE
thumbor-url --fitin --full does not work

### ISSUE THREAD

**Issue by yteraoka** [thumbor/thumbor#476]
`--full` option of thumbor-url does not work with thumbor 5.0 and libthumbor 1.0.1.

When these changes will be released?
https://github.com/thumbor/libthumbor/commit/9101ee406340b11be481dd6d2b5c1209838d8af7
https://github.com/thumbor/libthumbor/commit/edbe702a878f287915680a1e8b12d1c39820aef9

**Comment by heynemann** [comment]
@guilhermef can you tackle this?

**Comment by guilhermef** [comment]
@yteraoka I'll release a new version of libthumbor

**Comment by guilhermef** [comment]
@yteraoka do you mind testing ? https://pypi.python.org/pypi/libthumbor
And sorry for that ;)

**Comment by guilhermef** [comment]
@yteraoka There were still some params missing on thumbor-url.
It's nox fixed on thumbor 5.0.1 and libthumbor 1.1.0

**Comment by yteraoka** [comment]
I tested libthumbor 1.1.0 and thumbor 5.0.0 + https://github.com/thumbor/thumbor/commit/499636708c87c55fb3f6fd1635b88035e664d55b patch.
thumbor-url `fitin` combination worked fine. thanks.

But, `--filters` option does not work, too. (sorry, i have not mentioned)

```
# /opt/thumbor/bin/thumbor-url --filters='blur(6)' http://example.com/
{'trim': False, 'old': False, 'crop_top': 0, 'halign': 'center', 'vertical_flip': False, 'crop_left': 0, 'height': 0, 'width': 0, 'meta': False, 'image_url': 'http://example.com/', 'horizontal_flip': False, 'filters': 'blur(6)', 'valign': 'middle', 'crop_right': 0, 'crop_bottom': 0, 'smart': False}
URL:
/cKRLx6Xc2sMrSuEPUozWLjrySas=/filters:b:l:u:r:(:6:)/http://example.com/
/cKRLx6Xc2sMrSuEPUozWLjrySas=/filters:b:l:u:r:(:6:)/http://example.com/
```

**Comment by guilhermef** [comment]
@yteraoka It should be working now on thumbor 5.0.2

**Comment by yteraoka** [comment]
@guilhermef I tested 5.0.2. Yes, It worked :+1:  :smile:

**Comment by guilhermef** [comment]
\o/
