### ISSUE TITLE
% in image url

### ISSUE THREAD

**Issue by vinczente** [thumbor/thumbor#484]
If a image url contains a % (%25 escaped) thumbor fail to generate a thumbnail

example url : "http://domain.com/100%25BigC.jpg"

Also not sure how to replicate but it can also makes the server hang forever and then all subsequent images resizing fail.

**Comment by guilhermef** [comment]
@vinczente I can't replicate this behavior.
Which Thumbor version are you on ?

**Comment by vinczente** [comment]
I think I have 4.7.1

**Comment by guilhermef** [comment]
Do you have an image example that causes this ?

**Comment by vinczente** [comment]
The image that made me raise the issue is this one:
http://i.digiguide.tv/up/1406/974526-100%25BigC-14035365930.jpg 
Sorry I haven't tried the new Thumbor version

**Comment by guilhermef** [comment]
@vinczente You should always quote the url's.
```
>>> from urllib import quote
>>> quote('http://i.digiguide.tv/up/1406/974526-100%25BigC-14035365930.jpg')
'http%3A//i.digiguide.tv/up/1406/974526-100%2525BigC-14035365930.jpg'
>>>
```

I've tested and the quoted url works.

**Comment by vinczente** [comment]
Oh, right !

Thanks !
