### ISSUE TITLE
[RFC] URL shortening feature

### ISSUE THREAD

**Issue by Bladrak** [thumbor/thumbor#485]
Hello,

I'd like to suggest a URL shortening feature for thumbor, and I'd like the community opinion on that.

# What we need
When you add several filters to your image through thumbor, with resize and long image names, at some point, you may find yourself with very long URLs. Maximum length of an URL is 2,083 characters, and it might be reachable with long parameters in filters.

Moreover, you may want to obfuscate the data present in the URL to your end-users.

This is not the same need as preventing URL tampering through the security key (https://github.com/thumbor/thumbor/wiki/Security).

# Proposed solution
I'd like to suggest the integration of a URL shortening feature in thumbor. This would work as a classic URL shortener, storing into a database each URL to shorten and matching them thereafter.

## REST API
There would be a simple API to handle the shortening, offering a single endpoint:

**GET** /short/{my_thumbor_url}
*Return*:
```json
{"url": "/{my_short_url}"}
```
This API would validate the URL to avoid URL tampering as well, and once validated, store the key/value pair into the database.

## Storage
We would need to edit some of the storage possibilities to handle the shortening storage; we could begin with mongo, redis & memcached.

## Routing
When thumbor receives a shortened URL, it decodes it, and then passes it on to classic thumbor routing.

## Entry points
In order to offer the user the ability to customize the look & feel of the shortened URL, we would implement a generic module to generate short urls that can be overridden.

I'd be able to manage some available time to develop this feature in the coming weeks if this seems appropriate.

Thanks for your feedback.

**Comment by masom** [comment]
This would be kinda cool. Right now we implemented our own obfuscator by overloading a few classes and loading a different tornado app.

**Comment by masom** [comment]
The API should probably use `POST /short/{my_thumbor_url}` as it creates a resources.

**Comment by Bladrak** [comment]
@masom regarding the API I agree we could have a POST, I was thinking of it in the way that you want to GET the short url for this thumbor URL, but both would work I guess :)

If you already have some code, would you be ok to share it? Maybe we can work on that together?

**Comment by guilhermef** [comment]
Why don't you use the old URL generation to avoid the URL size limit ?

**Comment by Bladrak** [comment]
@guilhermef the old URL generation requires to use URL signing. If thumbor is within a closed network, we don't need signing as it adds complexity for thumbor's clients. However we may still need to shorten URLs.

**Comment by masom** [comment]
@Bladrak  I'm open to contribute new code/extensions to thumbor but our thumbor extensions are currently closed and non-distributable.

Short url should probably be a third-party extension.

#### Expanding on the API
`POST /short/[:url]` could work although the URL length limit could be hit again.
`POST /short` with post data could also be used.
`GET /short/[:code]` could return the actual image

#### Custom thumbor app with new handlers
We use something like this to load a different thumbor app:

```
class ImageServiceApp(tornado.web.Application):
    def __init__(self, context):
        self.context = context
        super(ImageServiceApp, self).__init__(self.get_handlers())

    def get_handlers(self):
        handlers = [
            (r'/healthcheck', HealthcheckHandler),
            (r'/robots.txt', RobotsHandler),
        ]

        handlers.append(
            # Imaging handler (GET)
            (
                ObfuscatedUrl.regex(),
                ImagingHandler,
                {'context': self.context}
            )
        )

        return handlers
```

To launch:
```bash
thumbor -a imaging.app.image_service_app ...
```

**Comment by guilhermef** [comment]
I'm not sure that a shortener belongs to thumbor,  since a 2083 characters
limit is enough for most cases.

**Comment by masom** [comment]
This is actually a very good case for unofficial extensions. Thumbor could probably support that without loading a new app with a simple refactor to allow loading tornado handlers like it does with filters.

**Comment by Bladrak** [comment]
@guilhermef @masom I agree, this should be handled outside of thumbor. I could work on a PR to allow appending handlers without overriding the application if you'd like.

**Comment by guilhermef** [comment]
Following your example, you would still need to sign the requests sent to
the shortener, at least to create the short URL.
Why don't you just sign using the old generation method ?

**Comment by heynemann** [comment]
Why not use an URL shortener?

My point here is twofold:

a) You probably won't have the /short endpoint available to the end-user (the whole internet) for security reasons. That would be exposing your database to anyone that wants to create a new shortened URL. Even if you always return the same one, people can easily abuse this by making you query your database in each request. We could work around this issue, but it would increase thumbor's complexity by at least one order of magnitude.

b) If the /short endpoint is private and thus will only generate a redirect endpoint to thumbor, why use this capability at all? Why not use a tool that was specifically designed for this purpose (https://github.com/sanshi0518/shorturl-nginx as an example)? I'd rather keep thumbor simple than adding capabilities that can be easily accomplished with other tools.

**Comment by Bladrak** [comment]
@guilhermef this is to cover the case where the signing is required; if you don't need it, you wouldn't need to sign the encoded URL either.

@heynemann it would indeed be another way to use an URL shortener. I was proposing this for thumbor as this is something that could be of use to several users, even though it's partially out of the scope of the application. That's why an external extension would maybe be the way to do it, as it would give us access to the way thumbor works internally, without adding a feature different than image processing directly in the repository.

**Comment by masom** [comment]
@Bladrak I created a new org to allow incubating ideas for Thumbor before submitting them to the official repo.

The idea is to allow experimenting with ideas while keeping the thumbor core lean and clean.

https://github.com/thumbor-community

**Comment by Bladrak** [comment]
Thanks @masom that's a great idea! :)

**Comment by muratcorlu** [comment]
Just using SECURITY_KEY as full path of request would be a good option I think. For example if we can use security keys that reversible by a salt for urls, our urls may look like `/<authentication code with 28 characters>.jpg` instead of `/<authentication code with 28 characters>/300x200/smart/path/to/image.jpg`. Then, Thumbor gets security key only, and parses it with salt and returns the requested image.

Is it a bad idea?

**Comment by masom** [comment]
It depends on the generated length. Encoding all the options + source image url can still produce a long url.

**Comment by muratcorlu** [comment]
Oh, you're right. I think it's impossible to produce a security_key that encoded by a salt, reversible and shorter from it's source content. :)

**Comment by masom** [comment]
There is a WIP at https://github.com/thumbor-community/shortener

- Clone `https://github.com/thumbor-community/core` and do a `pip install -e .` inside the core folder.
- Clone `https://github.com/thumbor-community/shortener` and do a `pip install -e .` inside the core folder.

- Setup the following config keys:
```
COMMUNITY_EXTENSIONS = [
    'thumbor_shortener'
]

SHORTENER_STORAGE='thumbor_shortener.storages.redis_storage'
SHORTENER_GENERATOR='thumbor_shortener.generators.sha256_generator'
SHORTENER_REDIS_STORAGE_SERVER_PASSWORD=None
SHORTENER_REDIS_STORAGE_SERVER_PORT=None
SHORTENER_REDIS_STORAGE_SERVER_HOST='localhost'
SHORTENER_REDIS_STORAGE_SERVER_DB=0
```
- Start thumbor with:
```
thumbor --conf=conf -a thumbor_community.app.App -l debug
```

- Start redis with `redis-server`
- Set a key with `redis-cli`
```
SET google http://localhost/unsafe/www.google.ca/images/srpr/logo11w.png
```

- Access `http://localhost:8888/shortener/google` and you should see the Google logo.

**Comment by heynemann** [comment]
Closing this as it should be discussed in the TC Repo.
