### ISSUE TITLE
Automagical support for JPEG XR / 2000

### ISSUE THREAD

**Issue by okor** [thumbor/thumbor#486]
Webp is great but not supported everywhere. The unfortunate state of things is that there are several image formats that would be helpful to automagically support, ala current auto webp support depending on the browser. See browser support: http://caniuse.com/#search=image%20format

I'm hoping to get a conversation started about potential support for these alternative formats. Please leave comments and thoughts.

**Comment by guilhermef** [comment]
I'm not sure we should support other formats, the reason we do automagical WEBP is because it represents 61.67% of browsers share.
We would add more complexity for 10.61% on JPEG 2000 or 11.08% on JPEG XR.

**Comment by okor** [comment]
@guilhermef In our case (Vox Media) JPEG 2000 support would affect something like 40% of page views, so definitely a non-trivial percentage. And a large percentage of those views are on mobile devices where we really want to reduce network weight as much as possible. I imagine that many other websites have similar traffic trends. I am much less concerned with JPEG XR (< 10%), but it would still be great to support it. I really wish we had Webp support everywhere but that's just not the case. 

Are there any specific areas of concern you have?

**Comment by guilhermef** [comment]
We're currently using Chrome's header: 
Accept:image/webp
To define webp's support.
We still need a way to define if the browser supports JPEG XR or JPEG 2000.
Any ideas on how to do this ?

**Comment by okor** [comment]
I will investigate possible methodologies and report on what I find.

**Comment by okor** [comment]
So after some investigation and thinking about this problem I think that Thumbor probably should *not* try to "automagically" return jpeg 2000 encoded images. In both Safari on Yosemite and Safari on iOS 8.3 (the two primary benefactors of real world jpeg 2000 compression) do not put anything in the request headers that I think we could use to reliably return an alternate format ... unlike Chrome which adds webp to the accepts headers. I used Safari's dev tools and Wireshark to inspect requests from both safari desktop and emulated iOS. No dice. Lame.

We could alternatively use some kind of User Agent switch but that is brittle so I can't recommend it.

I think the best way to handle format detection is on the client. Probably be by putting a 1x1 jpeg 2000 & base64 encoded string into a javascript image object and see if it successfully loads or not. There are several scripts out there to do this and writing a custom one is trivial. It's not ideal but probably the most reliable methodology in this case. Then populate image/background urls using the desired image format url.

So, given that Safari isn't doing us any favors, I'd say we should close this ticket and file under "tears".

One issue that seems outstanding however, is supporting jpeg 2000 encoding at all. I don't see anything in the docs or the source that indicates Thumbor supports jpeg 2000 as a format() option at all. Is this the case? If so, we should probably tackle that problem first. But I do think it's a huge value add. Should I file a separate issue for the jpeg 2000 format filter?
 
**Note: I haven't heard about anybody talking to Safari devs teams and getting stuff done. But I have (somewhat surprisingly) heard pretty great things about the Microsoft IE dev team. I'll see if I can reach out to them and see if they would be willing to do the cool thing ... and just support Webp. The license is great and the tools are good for Webp. Not so much for MS's jpeg xr format. It's a very long shot but given the ever smaller traffic numbers from IE clients it might not be worth it to do a bunch of work to support jpeg xr.

**Comment by heynemann** [comment]
If they could at least provide the accept header for their format, it would be a little helpful. Thanks for all the effort @okor!

I would create separate issues for each format. I'm closing this issue.
