### ISSUE TITLE
Thumbor seems to optimize on each request instead of serving cached image

### ISSUE THREAD

**Issue by ekoka** [thumbor/thumbor#487]
After I enable optimizers (jpegtran, pngquant) thumbor seems to call upon them on each request, instead of just serving the previously optimized version from the first request. Is there a configuration to control this?

**Comment by ekoka** [comment]
After digging a bit more I found out that caching is affected by the RESULT_STORAGE config. It needs to be enabled explicitly (it defaults to `None`). Even though thumbor stores a copy of the generated image on the file system, it doesn't imply that caching is in effect.

So far thumbor only includes the 'thumbor.result_storages.file_storage'.

`RESULT_STORAGE = 'thumbor.result_storages.file_storage'`

**Comment by heynemann** [comment]
Yep. You have to explicitly enable result storage. Thumbor won't store it unless you enable it. It will store the original, though.
