### ISSUE TITLE
Gif images aren't transparant

### ISSUE THREAD

**Issue by jordi12100** [thumbor/thumbor#488]
When optimising a GIF using Gifsicle, the image loses it's transparency. Am I missing a setting, or is this a bug?

Original:
http://f.jwwb.nl/public/v/e/q/vliegvissentjechie/B4productionsdoorschijnend-4.gif

Thumbor:
http://t.jwwb.nl/KITlIrWJmcqJEiG_-FyOS93fGtY=/72x0/http://f.jwwb.nl/public/v/e/q/vliegvissentjechie/B4productionsdoorschijnend-4.gif

**Comment by guilhermef** [comment]
@jordi12100 ,
you're probably not using gifsicle,
and should be getting this warning from Pil.

UserWarning: Couldn't allocate palette entry for transparency

Make sure you've enabled USE_GIFSICLE_ENGINE on your conf.

**Comment by jordi12100** [comment]
Hmm.. The setting was set to false indeed. Setting it to True didn't helped. I've tried loading a new image so that it won't load from Cache. 


    gifsicle: warning: too many colors, using local colormaps
      (You may want to try ‘--colors 256’.)
    gifsicle: warning: too many colors, using local colormaps
      (You may want to try ‘--colors 256’.)

**Comment by guilhermef** [comment]
It should work, I've tested with your gif.
I'm running LCDF Gifsicle 1.87

**Comment by guilhermef** [comment]
@jordi12100 Any news about the problem ?

**Comment by jordi12100** [comment]
Hey @guilhermef, sorry for the small delay.

When enabled that setting, thumbor crashes without any error in the logs. Do you have any idea why it does crash? 

I can confirm that Gifsicle is installed and that the paths are correct.

**Comment by guilhermef** [comment]
It should work, can you inspect what Gifsicle is running on https://github.com/thumbor/thumbor/blob/master/thumbor/engines/gif.py#L29

**Comment by guilhermef** [comment]
@jordi12100 Any news about this issue ?
