### ISSUE TITLE
Thumbor crashes in production under unknown circumstances with KeyError in ioloop

### ISSUE THREAD

**Issue by banks** [thumbor/thumbor#490]
We have been running thumbor in production at full scale for a while now at DeviantArt. We've had our cluster scale up automatically to handle initial switchover traffic ( > 3k req/second peak) from our CDN and in general it's working really well for us.

We are now finding thought that occasionally one thumbor process (we run one per core on each instance) will start crashing and being restarted with this in logs:

```
2015-06-08_05:53:24.63121 thumbor-2: KeyError: 3
2015-06-08_05:53:24.63123 thumbor-2: 2015-06-08 05:53:24 tornado.application:ERROR Exception in callback None
2015-06-08_05:53:24.63126 thumbor-2: Traceback (most recent call last):
2015-06-08_05:53:24.63129 thumbor-2:   File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 688, in start
2015-06-08_05:53:24.63134 thumbor-2:     self._handlers[fd](fd, events)
```

Unfortunately, it takes down the whole instance when it does so because runit continues to restart and it appears to immediately crash again which causes svlogd to consume 100% CPU just pumping this error out repeatedly until we terminate the instance.

We've also only ever seen it happen when we are not immediately present so we are somewhat limited in our insight as to what happens to cause this so far. We have other thoughts to investigate but it seems likely to be a bug whatever the root cause.

My very preliminary analysis shows that the line in question is inside the main event loop and the error indicates that for some reason the file descriptor `fd` does not exist in the handlers dictionary. I can only conjecture with my current level of understanding of tornado/thumbor that this might be due to some external cause such as OS destroying file descriptor due to resource constraint or something. But if that were the case it's odd that it seems a stable failure and not a temporary one - even when machines have failed and been removed from load balancer they appear stuck in this error loop until they terminate.

I searched these issues and tornado project issues for similar things or possible fixes in more recent versions but found nothing directly relevant. We are currently running Thumbor 4.5.4 it seems which is some way behind stable release.

If you have any insight into the issue please let us know - we'll update with any more info we get from further investigation and try upgrading to see if it's fixed in a more recent version - we still are not sure how to reproduce outside of production.

Thanks

Paul

**Comment by guilhermef** [comment]
@banks, can you test with the 5.0.3 release and see if it still happens ?

**Comment by banks** [comment]
We will try - as we are discussed elsewhere it's not very clear from your change log how much work upgrading past 5.0.0 is given our use of custom engines. It now seems no effort (untested) but your changelog explicitly says the opposite! We'll figure it out.

**Comment by guilhermef** [comment]
@banks you're right, the engine part was misleading, since it now runs inside a threadpool.
The part that changed was the loaders.

**Comment by xgt001** [comment]
I face this issue even now occasionally. Will get back with the details to reproduce this.
