### ISSUE TITLE
Can local Thumbor instances share the same disk cache?

### ISSUE THREAD

**Issue by aorra** [thumbor/thumbor#492]
I am new to Thumbor and considering it for on-demand image delivery. I am planning to setup a server instance with one Nginx and e.g. 4 Thumbor instances connected to it. In this kind of cluster setup can the file storage (thumbor.storages.file_storage) and the result storage (thumbor.result_storages.file_storage) be setup to use the same path for all the Thumbor instances? Or do I need to setup a dedicated cache path for each Thumbor instance?

**Comment by guilhermef** [comment]
It would be better to have different paths to the file_storage and result storage, but the instances can share these same paths.

**Comment by aorra** [comment]
Just to make sure I understood you correctly... If I set e.g. the file_storage path to be the same for multiple Thumbor instances, are they able to successfully utilize the same file cache? I could see some performance benefits here.

**Comment by guilhermef** [comment]
Yes, that's correct.
