### ISSUE TITLE
Result storage breaks on Windows when special characters in parameters

### ISSUE THREAD

**Issue by martinpengellyphillips** [thumbor/thumbor#494]
Thumbor 5.0.3 on Windows.

Thumbor fails trying to store files to cache when the resulting directory name contains characters that are invalid in directory names on Windows (E.g. ':')

Error is:
```
WindowsError: [Error 267] The directory name is invalid: 'c:\\users\\martin\\appdata\\local\\temp\\thumbor\\result_storage\\v2\\gF\\Zk\\gFZkswl6NEC8Jnq0xnXREZ03y7U=/fit-in/300x300/127.0.0.1:8090'
```

Tried to work around by url quoting the parameters before passing to thumbor, but that then results in a malformed url warning.

Is this expected behaviour or a bug? Is there a workaround?

**Comment by guilhermef** [comment]
I think we've never tested thumbor on windows.
It's probably a bug.

**Comment by martinpengellyphillips** [comment]
Thanks for the quick response. New to thumbor, but happy to test on Windows. Can try and work up a pull request if that helps?

**Comment by guilhermef** [comment]
sure.
