### ISSUE TITLE
Support for jpeg xr

### ISSUE THREAD

**Issue by okor** [thumbor/thumbor#496]
According to Abe Bateman, IE on Windows 10 sends some kind of jpeg xr note in image request headers - see convo https://twitter.com/adrianba/status/611222598135877632

I haven't personally confirmed it yet but will work on getting a copy of Win 10 to do so. But this would be in the same vein as webp automagic support. So we need to two things.
1. Support for the jpeg xr format.
2. Automagic support via accepts heads

IMO, step 1 is pretty great. step 2 is awesome bonus.

**Comment by heynemann** [comment]
When we are able to confirm IE header, we can definitely implement this.

I think it's a point where we should refactor the whole multiple image formats support. It's kind of hard coded for webp. We should have something more extensible that allows thumbor users to implement it on their own.

Want to support JPEG XR? Go for it. Implement a "driver" for it and thumbor will support it.

That would be the way to go IMHO. And the code that does WebP nowadays would be ported to be the reference implementation of this approach.

**Comment by heynemann** [comment]
Apparently Jpeg-XR is now advertised in Edge... ;)

**Comment by sbaechler** [comment]
I would definitely refactor the output format support fist. Currently Webp support is in core and Jpeg2000 and Mozjpeg are available as optimizers. This is not very consistent. 
It would need a top down approach for this. Like the output size, the output format now might depend on multiple factors like request headers and network speed. Depending on the format chosen, Cache headers need to be set correctly.

Jpeg XR is a proprietary Microsoft technology and is only supported by their browsers. It's not as efficient as Jpeg 2000, which is supported by Safari only. 
It would be interesting to see how it compares against the 'better' Jpeg encoders like Mozjpeg. 

There are also two other formats on the horizon: [FLIF](http://flif.info) and [BPG](http://bellard.org/bpg/). Both surpass WebP, Jpeg, PNG and Jpeg2000 in quality and efficiency.

**Comment by guilhermef** [comment]
@sbaechler The problem with Flif is browser support and BPG the [patents](http://www.philipstorry.net/thoughts/bpg-vs-jpeg-vs-webp-vs-jpeg-xr).
Until Edge we didn't had a way to detect Jpeg-xr support, parsing the User-agent string would probably be a mess.
That's why they're filters, so a client side script can decide and change the url, this way avoiding collision with another browser image.

**Comment by ahmed-sigmalux** [comment]
Any progress on this request?

**Comment by heynemann** [comment]
I don't think we are implementing this. If anyone wants to provide a PR, we can work on it.

If you have any further questions on this issue, please reopen it.
