### ISSUE TITLE
Support for jpeg 2000

### ISSUE THREAD

**Issue by okor** [thumbor/thumbor#497]
As mentioned in https://github.com/thumbor/thumbor/issues/486 and similar to https://github.com/thumbor/thumbor/issues/496, I am lobbying for jpeg 2000 support. It's supported in most versions of Safari on OSx and iOS. This request is purely for explicit conversion to jpeg 2000 via the format() filter. I think jpeg 2000 support is significantly more important than jpeg xr given global browser trends and that's certainly the case for the websites I work with.

* I have filed a bug with Webkit and asked for jpeg 2000 indicator in accepts header. Feels like a long shot but here it is: https://bugs.webkit.org/show_bug.cgi?id=146071 I also submitted feedback via Apple's Safari feedback form (no public link) making the same request. If they ever add it to accepts, that would be rad. Until then, we can leave support detection up to the front end devs which will have to use javascript methods to handle things.

**Comment by okor** [comment]
@guilhermef @heynemann Ok, so I'm going to start working on jpeg2000 stuff for thumbor.

My plan:
1) using a local CLI based jp2 encoder, assert that compression results are significant enough (>= 15%  source png/jpg file size avg, over test image set) to justify all Thumbor work required to support the format (maybe a lot?)
2) understand Thumbor's use of various encoder libraries/bindings and what the expectation is for each encoder is
3) identify the preferred encoder based on the opinions of current Thumbor developers
4) myself or maybe somebody (at Vox) more familiar with the Python ecosystem, will create a minimal implementation for jp2 support.
5) iterate between Thumbor devs until jp2 encoding is awesome & get into master
6) win internet

So, how does that sound?

**Comment by heynemann** [comment]
Sounds awesome... :) Go for it. Any help we can provide, we are here for it!

**Comment by okor** [comment]
So, I did some research. Over a sample size of 10k (out of a total of several million), j2k performed similarly to webp, so big wins could be achieved. Additionally, mozjpeg performed quite well. In last place was pngquant2 but still pretty good.

Here is an example data set (very small sample, but results nearly the same as 10k set): https://limitless-sands-3072.herokuapp.com/

Test server thing here if you want to take a peak: https://github.com/voxmedia/image_compression_experiments

Conclusion: definitely need to implement j2k in Thumbor

**Comment by heynemann** [comment]
I think implementing it as an optimizer would be awesome. Optimizers are the way thumbor post-processes images. What that means is that we can run J2K on top of our current JPG processing (PIL, GraphicsMagick, etc.). If you'd like to see how to implement an optimizer: https://github.com/thumbor/thumbor/blob/master/thumbor/optimizers/jpegtran.py

It should be fairly simple to build one for j2k. If you'd like to use the command line application it's straightforward. If you'd rather use a python library, just use StringIO (file-like object).

Does that make sense?

**Comment by okor** [comment]
Absolutely, it's clearly documented over here too: https://github.com/thumbor/thumbor/wiki/Optimizers

The gifv optimizer is similar, in that we don't want to do any "auto" j2k. We unfortunately need to explicitly ask for a j2k image via the filters. So plenty of docs and examples.

I should have a PR soon.

**Comment by heynemann** [comment]
why not an auto j2k optimizer? It seems to make sense to me.​

**Comment by okor** [comment]
j2k is only supported on Safari. And Safari doesn't send an accepts header indicating the client supports j2k. So I don't think we could use it in an automagic way. The only other way I could think to detect support is UA sniffing which is not reliable / hard / would add bloat. The way I will be using it is detecting it on the client by loading a small j2k image and seeing if the browser handles it correctly.

mozjpeg on the other hand, could totally be an automatic optimizer as a drop in alternative/replacement to jpegtran, though I have not compared the two so I can't really say which is better. I've read about some other folks testing mozjpeg against jpegturbo and it averaged a bit better overall.

**Comment by okor** [comment]
I'm closing this issues as JPEG2000 has now been implimented as a plugin optimizer. 

See https://github.com/thumbor/thumbor-plugins/wiki/JPEG2000 and https://github.com/thumbor/thumbor-plugins/pull/11 for more info.
