### ISSUE TITLE
Delays between frames are deleted in animated GIFs

### ISSUE THREAD

**Issue by neonal** [thumbor/thumbor#498]
Hello,

When I try to resize an animated GIF using thumbor, delay information in animated GIFs are deleted.

Example:
Original image: http://img-9gag-fun.9cache.com/photo/aDmwdrx_460sa.gif
Thumborized: http://thumbor.thumborize.me/unsafe/500x330/filters:strip_icc()/http://img-9gag-fun.9cache.com/photo/aDmwdrx_460sa.gif

**Comment by guilhermef** [comment]
That's a problem related to Pil, when you use gifsicle it doesn't happen.

**Comment by guilhermef** [comment]
It should be working now, we've updated thumborize.me to use gifscicle.
