### ISSUE TITLE
Webp image with alpha/transparency filled with black

### ISSUE THREAD

**Issue by okor** [thumbor/thumbor#501]
We just turned on automagic webp for all of our sites and noticed that images that had transparency in the source (just png sources tested) the resulting webp image has filled the alpha channel with black : (

Top image is Firefox (png) lower image is Chrome (webp). Any ideas what might be causing this?

![screen shot 2015-06-29 at 16 21 21](https://cloud.githubusercontent.com/assets/142910/8417504/204fff42-1e7b-11e5-8b9d-bc80be9dca4d.png)

**Comment by okor** [comment]
For reference, here is the source image:

![centralline 0](https://cloud.githubusercontent.com/assets/142910/8418074/ae9c9b4a-1e7e-11e5-8abc-8dccd0d351eb.png)

**Comment by guilhermef** [comment]
I've tried on Thumborize.me with PIL: http://thumbor.thumborize.me/unsafe/400x0/filters:no_upscale()/https://cloud.githubusercontent.com/assets/142910/8418074/ae9c9b4a-1e7e-11e5-8abc-8dccd0d351eb.png
It didn't happened, which engine are you using ?

**Comment by okor** [comment]
We are using pillow. It's thumbor version 4.12.2 on Ubuntu 12.04.

I think that we have figured out the issue. Our version of libwebp-dev is too old ( 0.1.3-2.1ubuntu1 ) from a time when libwebp did not support alpha. I've installed libwebp-dev version ~ 0.4 and seems to have fixed the problem. Conducting further testing but I think we can close this issue.

**Comment by okor** [comment]
For anyone reading this, I confirmed that libwebp was the cause and the solution was to upgrade to ~ 0.4

This may be an issue for you if you are running thumbor on Ubuntu 12.04. You may be able to find a ppa (if you trust it) otherwise build from source.
