### ISSUE TITLE
Docker thumbor

### ISSUE THREAD

**Issue by eduherraiz** [thumbor/thumbor#503]
I've been working on a complete docker image for thumbor.
Take a look in [github](https://github.com/APSL/docker-thumbor) or in the [docker hub](https://registry.hub.docker.com/u/apsl/thumbor/).

Features:

* All configuration via environment variables
* Opencv detectors included
* Optimizer JPEG included
* Nginx cache to optimize the server of result images
* Separated remotecv docker image (necessary for lazy detection)
* A lot of docker-compose examples with tipical uses cases

I think is the best way to start with thumbor and test all the functionality.  
 Could be interesting include a section in the Thumbor Wiki.

**Comment by eduherraiz** [comment]
I found the related issues #205 and #206. 
I could be work in include the docker images code in thumbor. 
What do you think?

**Comment by guilhermef** [comment]
@eduherraiz It looks amazing, I'll add to the Docs.
Thanks ;)

**Comment by guilhermef** [comment]
I've added to the Getting started section: https://github.com/thumbor/thumbor/wiki/Getting-started#running-on-docker

**Comment by eduherraiz** [comment]
Great! @guilhermef
