### ISSUE TITLE
Malformed URL for any images from media.nbcdfw.com

### ISSUE THREAD

**Issue by sgavade** [thumbor/thumbor#504]
Hi Any image URL that I try to thumborize from media.nbcdfw.com ends up giving malformed url. I have tried urlencode as well without much success. Here is a sample url http://media.nbcdfw.com/images/1200*675/shutterstock_413603_metro_train_double.jpg

This is my thumborized url

http://thumborserver/LvYwUb3DtlbCzMfotyAHSKwDKgI=/fit-in/236x0/http%3A%2F%2Fmedia.nbcdfw.com%2Fimages%2F1200*675%2Fshutterstock_413603_metro_train_double.jpg

Any insights?

Thanks,
Sameer

**Comment by guilhermef** [comment]
That happens on the unsafe url too ?

**Comment by sgavade** [comment]
I have not tested with unsafe url but will try it and get back to you.

**Comment by lfalcao** [comment]
@sgavade, using 5.0.4 and unsafe works.

200 GET /unsafe/fit-in/236x0/http://media.nbcdfw.com/images/1200*675/shutterstock_413603_metro_train_double.jpg (127.0.0.1) 99.24ms

**Comment by heynemann** [comment]
I think we need to specify it somewhere in the Docs that makes sure that people encode the URL before generating the signed URL.

If you do encode the URL it works like a charm.

/J7yz2TKQQxrq_9zc7mlVnRThBaU=/fit-in/236x0/http%3A//media.nbcdfw.com/images/1200%2A675/shutterstock_413603_metro_train_double.jpg

With security key of MY_SECURE_KEY works like a charm.

**Comment by sgavade** [comment]
Thanks. In my case I encoded the URL as well but it did not help. The  url
that you tired are little different from mine. Let me send you the urls
that fail for me.

Regards.
Sameer

**Comment by heynemann** [comment]
I used:

    from urllib2 import quote
    url = quote("http://media.nbcdfw.com/images/1200*675/shutterstock_413603_metro_train_double.jpg")

If you are using a different language I advise you to look at how python does url encoding.
