### ISSUE TITLE
Sample NGINX config including WEBP

### ISSUE THREAD

**Issue by runa** [thumbor/thumbor#505]
I've found [several NGINX sample configs](https://gist.github.com/heynemann/3341234) to serve the results generated by thumbor directly from NGINX (by having a `location` config block with the `RESULT_PATH` as `root`). 

If I understand correctly, when `AUTO_WEBP` is enabled, the `RESULT_PATH` tree structure is prefixed by a `webp` directory.

I would love to see a sample NGINX config supporting `AUTO_WEBP`.

Thanks

**Comment by lfalcao** [comment]
@runa,

You can also use proxy cache... https://gist.github.com/lfalcao/d1e0ae9ac267605967ff

**Comment by heynemann** [comment]
@runa are you satisfied? Can I close this issue?

**Comment by runa** [comment]
well, I liked the RESULT_PATH serving better; but it's fine

**Comment by runa** [comment]
@heynemann we've tested this but the storage needed grows *a lot*; 
I think we could do something sniffing the `Accept` header in the request?

I'm suprised noone found this before? Or everyone else does this at CDN level?

Our CDN (edgecast) only respects `Vary` in some specific cases :(

**Comment by heynemann** [comment]
Yep, the storage does grow. What people have suggested works better is using a fixed-size storage like Redis. You allocate some amount of memory to it (8gb or something like it) and let it expire results. This way you'll always know what your limit to result storage is. Does that make sense in your scenario?

**Comment by runa** [comment]
meh...  I liked nginx serving from the result storage.
I'll hack something, sniffing the accept req header.  if I come up with
something interesting I'll let you know
