### ISSUE TITLE
New optimizer jpeg-archive / recompress

### ISSUE THREAD

**Issue by estahn** [thumbor/thumbor#512]
It would be great if someone could help providing an optimiser integration for [jpeg-archive](https://github.com/danielgtaylor/jpeg-archive). I had great success reducing images without visible effects, e.g. similar to [jpegmini](http://www.jpegmini.com/). 

If you want to give it  a shot just clone and run it on a couple of images:
```
./jpeg-recompress --no-copy -s -a --loops 10 <source image> <target image>
```

Unfortunately I was unable to get thumbor running so that i could contribute code, e.g. PILEngine was missing even though it was in the path.

Enrico

**Comment by heynemann** [comment]
That's odd, did you try our [Hacking on Thumbor](https://github.com/thumbor/thumbor/wiki/Hacking-on-thumbor) page?

Other than that, we have a project dedicated to plugins: [thumbor-plugins](https://github.com/thumbor/thumbor-plugins). Do you mind creating this issue there?

thanks!

**Comment by estahn** [comment]
@heynemann I think i did check this page without success. I'll give it another try this afternoon.

I move the issue to plugins.

Thanks :)
