### ISSUE TITLE
Dynamic script Image URLs 

### ISSUE THREAD

**Issue by virtuman** [thumbor/thumbor#513]
I see that a lot of work in the last commits went towards filtering query params, but this introduces a very much unwanted behavior. Here's an example of reallife issue:

URL format (not when widht, height, quality are not specified, then default thumbnail size is served (100x100, quality 60):
www.site.com/Assets/Images/Default.aspx?productID=44444&Image=1
www.site.com/Assets/Images/Default.aspx?productID=44444&Image=2
www.site.com/Assets/Images/Default.aspx?productID=44444&Image=5
www.site.com/Assets/Images/Default.aspx?productID=44444&Image=7
www.site.com/Assets/Images/Default.aspx?productID=44444&Image=7&size=1000x1000&quality=95

all these images are obviously different. Product param &productID= and image param &image= define what image number is served for that particular product. I agree that this is not a good practice for serving images, but unfortunately some websites that we use as a content source use this particular technique for serving images.

The main problem here, is that in the newly added logic for filtering query params, takes this URL:
www.site.com/Assets/Images/Default.aspx?productID=44444&Image=1
and it becomes this:
www.site.com/Assets/Images/Default.aspx  << and this URL won't actually serve anything, since all important params had been stripped off.

And same goes for all types of links:
www.site.com/Assets/Images/Default.aspx?productID=44444&Image=2
www.site.com/Assets/Images/Default.aspx?productID=44444&Image=5
www.site.com/Assets/Images/Default.aspx?productID=44444&Image=7
www.site.com/Assets/Images/Default.aspx?productID=44444&Image=7&size=1000x1000&quality=95
*they will all become:*
www.site.com/Assets/Images/Default.aspx

But just to outline second problem, i included example with image=7 - where additional problem describes that some other parameters maybe even more geared towards getting a better image.
www.site.com/Assets/Images/Default.aspx?productID=44444&Image=7
www.site.com/Assets/Images/Default.aspx?productID=44444&Image=7&size=1000x1000&quality=95

in this particular example that I outlined here, I used one of our content providers real use case, however the more complex ones (also real life examples) - they do not use easily filterable extension such as .aspx .. but instead they add query params to image URLs to optimize product size, quality, etc based on the additional parameters, and without size and quality being specificed it serves small thumbnail (200x150, quality 70) ... so urls such as:
www.site2.com/Assets/Images/Default.jpg?size=1000x1000&quality=95
*will also become:*
www.site2.com/Assets/Images/Default.jpg  and it will serve a small thumbnail instead of a full size image

**SOLUTION:**
what we did with the previous version to support query params was simply to try wrap around the method that detects meta type in the try catch and default to image/jpeg  and .jpg extension for further processing in cases when meta couldn't be determined based on file extension), everything seems to be working nicely that was and we never lose opportunity to render real image. This would seem to be a more complete and real solution instead of filtering off query params (which may be useful in many cases for optimization and to prevent loading multiple copies of same image, but it is very hurtful in many other cases)

**Comment by guilhermef** [comment]
The query params were stripped to read the image format, and we've actually abandoned this solution in favor of a mimetype reader.
If you quote the url like this: http://thumbor.thumborize.me/pqXNEcUYZtuMCY2DCPmfZjWVg3Q=/https%3A//alecs1.files.wordpress.com/2009/05/18-jos2.jpg%3Fw%3D300
It will work.
