### ISSUE TITLE
How to config for libcurl in thumbor.conf can be download an image with multi connection ?

### ISSUE THREAD

**Issue by nguyennhatkhang92** [thumbor/thumbor#515]
Hi.
I'm using thumbor recently and I have been read thumbor-config on https://github.com/thumbor/thumbor/wiki/Configuration. I don't know "how to config for libcurl in thumbor can be download an image with multi connection ?".
I using Nginx proxy_pass to thumbor service then I see two case:
1.
"- thumbor:WARNING ERROR retrieving image http://192.168.1.1:89/private/20/FshareFS/mega/201507/20/afe5fdffae59d6ef7f8bd63c07c0da9948326bd4_img_8804.jpg: HTTP 599: Timeout
- tornado.access:WARNING 404 GET /unsafe/64x64/filters:no_upscale()/http://192.168.1.1:89/private/20/FshareFS/mega/201507/20/afe5fdffae59d6ef7f8bd63c07c0da9948326bd4_img_8804.jpg (127.0.0.1) 5006.71ms"

2.
"- thumbor:WARNING ERROR retrieving image http://192.168.1.2:89/private/3/FshareFS/mega/201507/20/f422943d489e5fe70d2484e47038be5b76b681d3_img_8719-12.jpg: HTTP 599: Timeout
- tornado.access:WARNING 404 GET /unsafe/64x64/filters:no_upscale()/http://192.168.1.2:89/private/3/FshareFS/mega/201507/20/f422943d489e5fe70d2484e47038be5b76b681d3_img_8719-12.jpg (127.0.0.1) 20847.26ms"

afe5fdffae59d6ef7f8bd63c07c0da9948326bd4_img_8804.jpg is a jpg file, size 8.8M.
f422943d489e5fe70d2484e47038be5b76b681d3_img_8719-12.jpg is a jpg file, size 50M. 
I'm checked network, it very well. I having using Lua to save connection to URI and I see image size 50M have 2 connection, image 8.8M have 1 connection. I think reason caused by libcurl download file very slow.
Someone can help me, Thank!

**Comment by masom** [comment]
We've seen this happen in production with several hundred images being loaded at the same time. It usually boils down to the upstream server limiting the number of concurrent requests from a single host or the thumbor instance being overloaded.

Some work was done on thumbor 4.x to "throttle" thumbor using a threadpool.

Can you try `ENGINE_THREADPOOL_SIZE=n` where n is your number of cpu?

Docs on the threadpool option: https://github.com/thumbor/thumbor/blob/master/thumbor/config.py#L77

**Comment by nguyennhatkhang92** [comment]
Thank you for your help, masom.
I was update thumbor and use ENGINE_THREADPOOL_SIZE. It's very well but I tried use MAX_SOURCE_SIZE in thumbor.conf for limit image size and I saw it didn't work. Can you explain yourself? masom, Thank.
