### ISSUE TITLE
FEAT: Configurable url signing strategy

### ISSUE THREAD

**Issue by masom** [thumbor/thumbor#522]
Thumbor url signing is awesome but produces "long" urls.

Signer should be configurable like the storages and loaders.

The interface is already defined and the request contains the hash. The only change would happen on line https://github.com/thumbor/thumbor/blob/master/thumbor/handlers/imaging.py#L65 and context code to load a signer.

The required  changes will not break backward compatibility and a new configuration option will contain the default Signer.

**Comment by masom** [comment]
I'll open a PR tomorrow for this feature.

**Comment by heynemann** [comment]
@masom Did you include this in the docs?

**Comment by masom** [comment]
Forgot, will update now.
