### ISSUE TITLE
Make focal point settable via web url

### ISSUE THREAD

**Issue by roelvanduijnhoven** [thumbor/thumbor#525]
The users of our application can set the focal point of images themeselves in our CMS. In the frontend we use Thumbor to serve the images efficient.

We do this using the `Manual Crop` option. This forces us to do some math ourselves. It would have been easier if we could use the resize option and simply pass along a focal point ourselves.

Did I simply overlooked this or isn't this possible? In the later case I think it would be a helpfull addition to Thumbor!

**Comment by roelvanduijnhoven** [comment]
A solution that comes to mind is to be able to add custom focal points via a filter. An URL call could look like this the one below.

`http://172.17.0.8:8888/unsafe/800x280/filters:add_focal(100,100):extract_focal()/https://url.jpg`

**Comment by heynemann** [comment]
It should be fairly simple to implement this filter. Do you think you can do it? The focal points are in the context object available to all filters (the extract focal filter adds to them as well).

**Comment by roelvanduijnhoven** [comment]
In the end I implemented the math to crop around a point myself and pass the crop and resize coordinates to Thumbor.

I did hack around a little. I had no clue however where to add those Python files and how to make sure they got loaded. No reference to be found around that! So some help and guidance on how to do so would be helpful.

**Comment by Perni1984** [comment]
Hi @roelvanduijnhoven, I have the same use case here - but no clue on python either ;-), and not to much time to dig into this. Could you shed some light on the math and the hack that you did?

Thanks.

**Comment by roelvanduijnhoven** [comment]
The PHP library I wrote to do this can be found at https://github.com/roelvanduijnhoven/reverse-image-cover.

**Comment by okor** [comment]
Hey. Having done some work with the `extract_focal()` filter recently, the "dual url" syntax is making CDN routing weird. I think we should create a `focal_point()` filter - roughly similar to what has been described here. The use case for this is growing, as more and more people move away from fixed crops and do more focal point style, on the fly image creation. We are starting to do this at Vox Media right now. If no one else does, I'll start hacking on this pretty soon.

**Comment by renet** [comment]
I'm a little confused. It seems to me that this solution doesn't require a focal *point*, but rather a focal *rectangle* to make this filter work properly. But what, If I have only percentages as a focal point (lets say I don't know the original size of the image to be cropped)? How can I simply say a focal point positioned at "80% from the left" and "20% from the top" focuses an object based near the upper right corner of my image? Is there a way to set these 80% + 20% via url?

**Comment by lboaretto** [comment]
I would also like to have the focal point based on the top/left coordinates in %.
