### ISSUE TITLE
Can you access the URL string from a Filter?

### ISSUE THREAD

**Issue by nickponline** [thumbor/thumbor#526]
I'm trying to access some parameters from the URL from a filter but can't find a way to get access to it. Is it possible?

**Comment by dhardy92** [comment]
it would be available in ```self.context.request``` object (inherited from BaseFilter)
There is already many things in it (heigth, width, parameters...) that could be much accurate for your needs than URL

**Comment by heynemann** [comment]
@nickponline what kind of filter are you doing? Is it something the whole community can benefit from? If it is, would you like to put it in thumbor community org? /cc @masom
