### ISSUE TITLE
thumbor Truck Factor

### ISSUE THREAD

**Issue by gavelino** [thumbor/thumbor#527]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **thumbor** and obtained a value of **2**.

The developers responsible for this TF are:

Bernardo Heynemann - author of 66% of the files
Cezar Sa Espinola - author of 29% of the files

To validate our results, we would like to ask **thumbor** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **thumbor**?

(b) Do you agree that **thumbor** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **thumbor** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by heynemann** [comment]
a) We were. I think to have a better understanding of participation, you must track recent activity, not overall activity.

b) No (look answer a).

c) We have an awesome community. This makes up for the fact we have some key developers.
