### ISSUE TITLE
Thumbor returns a 404 when it has a timeout retrieving the original image, should be a 504

### ISSUE THREAD

**Issue by bgentry** [thumbor/thumbor#529]
I'm experiencing an issue similar to #208 in the same circumstances: Thumbor, under high load, is logging error messages about 599 timeouts when trying to fetch original source images so that it can create thumbnails of them.

Here's a log from one time that happened:

```
2015-08-12T00:52:20.488677+00:00 app[web.2]: 2015-08-12 00:52:20 thumbor:WARNING ERROR retrieving image https://example-s3-bucket.s3.amazonaws.com/uploads/listing-55/747.jpg: HTTP 599: Timeout
2015-08-12T00:52:20.786979+00:00 app[web.2]: 2015-08-12 00:52:20 tornado.access:WARNING 404 HEAD /THUMBOR_SECRET_REDACTED=/1800x1200/https://example-s3-bucket.s3.amazonaws.com/uploads/listing-55/747.jpg (10.169.215.33) 7136.35ms
```

When Thumbor experiences a timeout in this situation, it's returning a 404 status code. That's definitely not the right status code for this behavior, as it authoritatively means that file does not exist and tells upstream proxies to cache the result.

The correct status code in this scenario is a 5XX. In particular the 504 description perfectly summarizes this scenario:
 
> ## 10.5.5 504 Gateway Timeout
> The server, while acting as a gateway or proxy, did not receive a timely response from the upstream server specified by the URI (e.g. HTTP, FTP, LDAP) or some other auxiliary server (e.g. DNS) it needed to access in attempting to complete the request.

Is it possible to change Thumbor so it returns the correct HTTP status code when it experiences a timeout or other internal error?

**Comment by heynemann** [comment]
We definitely need to fix this. Sorry for that. Will try to work on it this week. Maybe @guilhermef will beat me to it.

**Comment by heynemann** [comment]
One question, though. Are you using libcurl?

**Comment by bgentry** [comment]
@heynemann nope, no libcurl. We do use https://github.com/thumbor-community/aws for result storage though

**Comment by heynemann** [comment]
I think you'd see a lot less timeouts if you were using libcurl:

https://github.com/thumbor/thumbor/blob/9119e2b3882bc2605d256b4d2ff5de8d79887fd0/thumbor/config.py#L156

**Comment by heynemann** [comment]
BTW: the reason for not having the curl client as default is because it's a hard dependency and would make thumbor unusable for people installing using pip ;(

**Comment by seichner** [comment]
This change fixes the Timeout-Status-Code, but introduces a strange behavior: now if the HTTP-Loader receives a 404, Thumbor sends a "504 Gateway Timeout", which in turn leads CDNs to **not** cache responses for non-existing images. I was wondering where all the timeouts come from after our last deploy... ;-)

The [handler_image_vows.py](https://github.com/thumbor/thumbor/blob/b2154f988de5aeb31bb6eb6c2a9b46b12729996c/vows/handler_images_vows.py#L76) test makes this explicit. As far as i can see the http_loader does not have an interface to return information about why retrieval failed. It just uses [_callback(None)_](https://github.com/thumbor/thumbor/blob/b2154f988de5aeb31bb6eb6c2a9b46b12729996c/thumbor/loaders/http_loader.py#L46) no matter wether it was a 404 or 5x response. Sadly I don't know enough about Python design to make a decent suggestion for the fix...

**Comment by masom** [comment]
We'd probably have to introduce a return object to handle various error scenarios with different loaders.

```python
class LoaderResult(object):
    ERROR_NOT_FOUND = 'not_found'
    ERROR_UPSTREAM_ERROR = 'upstream_error'

    def __init__(self, buffer, successful=True, error=None):
        self.buffer = buffer
        self.successful = successful
        self.error = error
```

or something similar.

Using a value object would allow a bit more flexibility than returning `None.`

We could probably support backward compatibility by checking the type when the loader returns:

```
result = yield ...

successful = False
error = None

if isinstance(result, LoaderResult):
    # Support for > 6.0 loaders
    successful = result.successful
    error = result.error
else:
    # Support > 5.0 < 6.0 loaders
    successful = result is None
    if not successful:
        error = LoaderResult.ERROR_NOT_FOUND
```

**Comment by heynemann** [comment]
That does make sense. I really like the approach of a return object. The context is one such construct that allowed us a LOT of flexibility over the years.

We should keep the current behavior for previous loaders, though. Meaning returning timeout is better then authoritatively saying it was not found.

**Comment by heynemann** [comment]
I'm keeping this issue open until we fix it properly.

**Comment by masom** [comment]
@heynemann definitely. The error happened between thumbor and the upstream image storage and we should generate a 5xx response code if we can't determine the reason (ex: `None` being returned)

**Comment by phoet** [comment]
@heynemann a value object for return types would be nice. it would allow us to consume meta information later on. for example, [this PR about modified-since headers](https://github.com/thumbor/thumbor/pull/439) could be implemented by passing this information along from the loader.

**Comment by masom** [comment]
@phoet @heynemann I'll open a PR with a minimal implementation. We'll be able to discuss what the return object should contain for a "sane" API that will work with most loaders.

Things it should probably contain:
- buffer
- successful
- error code
- metadata:
    - created_at / some date data about the buffer. Would be used for `modified-since`
    - size

**Comment by masom** [comment]
https://github.com/thumbor/thumbor/pull/554 implements the concept on the file_loader.

**Comment by twelvelabs** [comment]
I would like to cache 404s on the CDN side, but don't want to do so until this gets fixed. Can you please point me to what specifically needs to be changed and I'll see if we can make progress on it?

**Comment by masom** [comment]
@twelvelabs the core now supports errors from the loader.

The loader must return a `thumbor.loaders.LoaderResult` instance with the error set to `LoaderResult.ERROR_NOT_FOUND` or `LoaderResult.ERROR_UPSTREAM`.

Thumbor will react to the loader error and handle it with a 404 or 502 response code. See https://github.com/thumbor/thumbor/blob/be007874fbf3d41fa44f182612972223782141f9/thumbor/handlers/__init__.py#L105

See https://github.com/thumbor/thumbor/blob/master/thumbor/loaders/file_loader.py#L25 and https://github.com/thumbor/thumbor/blob/master/thumbor/loaders/http_loader.py#L44 for the implementation detail on the loader.
