### ISSUE TITLE
Problem wih STORAGE_EXPIRATION_SECONDS

### ISSUE THREAD

**Issue by erinthon** [thumbor/thumbor#530]
Hi, 

I have some trouble with the parameter STORAGE_EXPIRATION_SECONDS, I define for 1 second, but the images still in storage.

The thumbor only keeps the images on storage for a determined time, right?

If the image is no more used, the image will be deleted of storage? I'm wrong about that?

I have to change anyone other parameter?

**Comment by masom** [comment]
Which storage are you using?

**Comment by erinthon** [comment]
I m using storage default of thumbor.

How I can find an example to use other type of storage, one storage to remove the files generated after the expiration time? Any suggestion?

**Comment by masom** [comment]
Thumbor has a few storages: https://github.com/thumbor/thumbor/tree/master/thumbor/storages

In the config file you can specify which one you would like to use:
```
## The file storage thumbor should use to store original images. This must be the
## full name of a python module (python must be able to import it)
## Defaults to: thumbor.storages.file_storage
#STORAGE = 'thumbor.storages.file_storage'

## The result storage thumbor should use to store generated images. This must be
## the full name of a python module (python must be able to import it)
## Defaults to: None
#RESULT_STORAGE = None
```

`thumbor-config` will generate a blank configuration file with all available configuration keys.

**Comment by heynemann** [comment]
Wow, @masom is a much better support than we are! Thanks for the help man. @erinthon do you think we can close this issue?

**Comment by erinthon** [comment]
Yes @heynemann.
