### ISSUE TITLE
is it possible to add a cache-buster to the url?

### ISSUE THREAD

**Issue by phoet** [thumbor/thumbor#532]
we would like to pass an explicit cache-buster query string, say `?v=some_timestamp` to the thumbor urls to fix some caching issues within our setup, but [as it looks](https://github.com/thumbor/thumbor/blob/9119e2b3882bc2605d256b4d2ff5de8d79887fd0/thumbor/handlers/imaging.py#L36) thumbor uses the whole URI not just the path to determine what is part of the image filename.

so when appending something like `?v=123` the http loader and the s3 loader append them to the file-name resulting in a 404 not found:

```
2015-08-14 16:00:28 thumbor:WARNING ERROR retrieving image https://....amazonaws.com/17731/image/30191402?...Expires=1443607200&Signature=Yc5nPKcfp1qN44HsfoRtxMS1Bes%3D?v=123: HTTP 403: Forbidden
...
2015-08-14 15:46:32 boto:DEBUG path=/17731/image/30191402/%3Fv%3D123
```

as you can see the http loader generates a request-url with two `?`.

is there anything else we could use as a cache-buster?

**Comment by masom** [comment]
@phoet correct me if this is wrong but I think thumbor should parse the following url like this:

`http://localhost:8888/unsafe/http%3A%2F%2Fsome-image-server.com%2Fimage.jpg%3Fhello%3D1?v=123`
as:
```
parsed = urlparse.urlparse('http://localhost:8888/unsafe/http%3A%2F%2Fsome-image-server.com%2Fimage.jpg%3Fhello%3D1?v=123')

ParseResult(scheme='http', netloc='localhost:8888', path='/unsafe/http%3A%2F%2Fsome-image-server.com%2Fimage.jpg%3Fhello%3D1', params='', query='v=123', fragment='')
```

And use the `path` to build the proper url for the source:

```http://some-image-server.com/image.jpg?hello=1```

This would allow passing query parameters to the original source server and also pass query parameters to thumbor.

Which library are you using to generate the thumbor urls?

**Comment by masom** [comment]
`url = self.request.uri` would become

```
parsed_url = urlparse.urlparse(self.request.uri)
url = parsed_url.path
````

**Comment by masom** [comment]
It seems like the current behaviour has been coded to pass the url parameters to the original url: https://github.com/thumbor/thumbor/blob/eaa46421597804414f4a5318f12a731d104c3103/thumbor/context.py#L209

This seems like a bug, the thumbor url query parameters should be handled by thumbor and query parameters added to the source image should be encoded and used as part of the signature, allowing:

`http://localhost:8888/unsafe/http%3A%2F%2Fsome-image-server.com%2Fimage.jpg%3Fhello%3D1?v=123`

The url contains an encoded `?hello=1` and the thumbor request includes a `?v=123`. They should be treated separately ( outer for thumbor/cache busting/etc and the inner for the original source server )

**Comment by heynemann** [comment]
We should fix this. There's no need to pass the query_string arguments to the image url. The image should be encoded properly. You are absolutely right @masom. This is a backwards-incompatible change, though. :(

**Comment by phoet** [comment]
i'm glad we all agree :) i don't know if we could use a configuration flag to enable backwardcompatible behavior until the next mayor version?

**Comment by phoet** [comment]
btw, right now, we use a psudo-filter to achive the same behavior `.../format(jpg):cachebuster(123)/...`
