### ISSUE TITLE
Converting PDF's to PNG's and/or splitting PDF's?

### ISSUE THREAD

**Issue by gotjosh** [thumbor/thumbor#534]
After reading the Wiki/Documentation around, I didn't found any information regarding two things I'd like to accomplish:

1. Have a PDF splitted into several images.
2. Convert a PDF page to a PNG (or be able to serve PDF image files to thumbor).

I know these are things that can be done via ImageMagick but a couple of months ago, we replaced all our resizing/converting from ImageMagick to Thumbor so I'm trying to avoid bringing the dependency back into my project.

Any information regarding what I'd like to accomplish would be helpful and/or a pointer in the right direction would be greatly appreciated.

Thank you!

**Comment by heynemann** [comment]
Right now we do not support loading PDFs. Not sure if we will, though. For now I'm closing this issue if there is not anything else we can help to accomplish here.
