### ISSUE TITLE
Error 500 on demo

### ISSUE THREAD

**Issue by LC43** [thumbor/thumbor#535]
hi, trying the demo throws a  500 

http://thumborize.me/report?url=http://www.joaocajuda.com/
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

but it works ( on the same server )
http://thumborize.me/report?url=http://www.thewanderlust.pt/

on different server, also Error 500
http://thumborize.me/?url=http://www.viajecomigo.com/

**Comment by heynemann** [comment]
Not sure why that is. As soon as I get some time I'll check the logs to find out. Sorry for that.
