### ISSUE TITLE
Urls with SECURITY_KEY don't work with Heroku ?

### ISSUE THREAD

**Issue by LeFredd** [thumbor/thumbor#536]
Hi,

I installed on thumbor heroku like this : 
https://github.com/TwidereProject/Twidere-Thumbor-Heroku

I only change the SECURITY_KEY like this : 

in my conf : 

    import os

    STORAGE = "thumbor.storages.mixed_storage"

    MIXED_STORAGE_FILE_STORAGE = "thumbor.storages.no_storage"
    MIXED_STORAGE_CRYPTO_STORAGE = "thumbor.storages.no_storage"
    MIXED_STORAGE_DETECTOR_STORAGE = "thumbor.storages.no_storage"

    DETECTORS = []

    FILTERS = [
    'thumbor.filters.brightness',
    'thumbor.filters.contrast',
    'thumbor.filters.rgb',
    'thumbor.filters.round_corner',
    'thumbor.filters.quality',
    'thumbor.filters.noise',
    'thumbor.filters.watermark',
    ]

    OPTIMIZERS = [
    'thumbor.optimizers.jpegtran'
    ]

    SECURITY_KEY = 'MySecurityKey'
    ALLOW_OLD_URLS = False
    ALLOW_UNSAFE_URL = False

    HTTP_LOADER_FORWARD_USER_AGENT = True

    AUTO_WEBP = True

    JPEGTRAN_PATH = 'jpegtran' 

And just add the config variables in heroku like this : 
BUILDPACK_URL https://github.com/heroku/heroku-buildpack-multi

I did not add THUMBOR_SECURITY_KEY variable as in the project
Twidere-Thumbor-Heroku

When I try with ALLOW_UNSAFE_URL = True with the the url : 
http://my-project-thumbor.herokuapp.com/unsafe/700x600/http://images.midilibre.fr/images/2015/08/14/1201990_355_000-hkg10202204_1200x800.jpg?v=1

it works 

But when I try with ALLOW_UNSAFE_URL = False with the url : 
http://my-project-thumbor.herokuapp.com/unsafe/700x600/smart/http://images.midilibre.fr/images/2015/08/14/1201990_355_000-hkg10202204_1200x800.jpg?v=1

it does not work

with : 
http://my-project-thumbor.herokuapp.com/MySecurityKey/700x600/smart/http://images.midilibre.fr/images/2015/08/14/1201990_355_000-hkg10202204_1200x800.jpg?v=1

it does not work

What is the problem ? Thanks :)

**Comment by masom** [comment]
The security key itself is used to sign the url and should not be used directly in the URL.

You can use a cli application `thumbor-url` ( try `thumbor-url -h` for all options) to generate urls.

Many languages have url builders:
Python: https://github.com/thumbor/thumbor/blob/master/thumbor/url_composer.py
Ruby: https://github.com/thumbor/ruby-thumbor
PHP: https://github.com/99designs/phumbor

**Comment by LeFredd** [comment]
Ok, I had not seen this part in the doc where my incomprehension. My choice to go npm thumbor because the use will be for angularjs.
Thanks
