### ISSUE TITLE
Composing text on an image

### ISSUE THREAD

**Issue by gabek** [thumbor/thumbor#539]
I'm looking to replace a few homemade ImageMagick solutions with Thumbor.  One of the things that Thumbor doesn't natively do is text, nor should it.  But has anybody written a custom filter or solution that utilizes Thumbor and text composition?

Feel free to close if this is just too out of scope of a question.

**Comment by heynemann** [comment]
Would you like to write a filter for it and put it in the thumbor-community org? /cc @masom

**Comment by gabek** [comment]
Is there any documentation about writing custom filters anywhere?  I'd take a stab at it!

**Comment by heynemann** [comment]
I don't think we have, but have a look at the many filters bundled with thumbor: https://github.com/thumbor/thumbor/tree/master/thumbor/filters

**Comment by gabek** [comment]
Awesome.  I'll take a look and report in if I have any questions!

**Comment by heynemann** [comment]
Btw @masom you are now a full committer for thumbor org ;) Congratulations!
