### ISSUE TITLE
Using If-Modified-Since and e-tag to revalidate 

### ISSUE THREAD

**Issue by ribeirofelix** [thumbor/thumbor#540]
Does Thumbor uses If-Modified-Since or e-tag to re-validate with original image?

If the requested URI responses 304, will Thumbor re-validate the image?

**Comment by heynemann** [comment]
We don't in our default http loader. You could easily implement your own loader that does it, though.

**Comment by heynemann** [comment]
Does this respond your question? Can I close this?

**Comment by ribeirofelix** [comment]
Oh yes! Sorry!
