### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by SebastienPi** [thumbor/thumbor#543]
Hi,

About https://github.com/thumbor/thumbor/issues/509 and the new value “None”, could you add it to the documentation https://github.com/thumbor/thumbor/wiki/Configuration?

Before I found this issue, I tried “0” to ignore the parameter. But thumbor understand 0 second and we can not get with this value…
It would be helpful if this value has in the conf comments.

Thanks

**Comment by heynemann** [comment]
@guilhermef you did change this, right?

**Comment by guilhermef** [comment]
yep. https://github.com/thumbor/thumbor/wiki/Configuration#storage_expiration_seconds
