### ISSUE TITLE
Filters: Center aligning watermarks?

### ISSUE THREAD

**Issue by MarcFowler** [thumbor/thumbor#545]
I read over in an old message #18 that a watermark can be added to the center of an image.

Is that still possible?

I'd love to be able to place the watermark in the center (vertically and horizontally) without having to calculate it myself beforehand, because that's something of a pain.

I've tried without providing `x`, `y` and `alpha` params to the filter (i.e. just `filters:watermark(whateverimage.jpg)`) but it just doesn't place it anywhere. To confirm, if I provide `filters:watermark(whateverimage.jpg,20,20,1)` everything works as expected so it's not an issue of the image not being read or anything.

If this isn't possible with the built-in watermark filter specifically, I'm sure it can be done via a new one. However, I'm not 100% sure how I would go about creating one. I don't know Python, though could probably figure this out!, so what's my best way of doing that? Do I just duplicate the `watermark.py` script, rename it and make my changes, and then add the new filter to the list of available ones in the config and away I go or is there more to it?

Also do I literally do that inside `/usr/local/lib64/python2.7/site-packages/thumbor/filters` or is there some other place I'd place them? I wouldn't want to lose it during updates etc.

**Comment by MarcFowler** [comment]
Sorry to bump this but I'm going to be needing this for my project soon and hoping I can work on it soon. Maybe @masom could you give us a hand? It seems to me like I'll need to adjust the existing filter to position the watermark in the centre - is there a way to get the watermark's dimensions in the filter and those of the base image that I'm applying it to? Then I can specify the `x` and `y` coordinates for the watermark like:

```
x = (base image width * 0.5) - (watermark width * 0.5)
y = (base image height * 0.5) - (watermark height * 0.5)
```

Alternatively I could always provide the watermark's dimensions into the filter - as I said, this probably best belongs in a new filter rather than the current watermark one but I'm not 100% on where I'd place things etc. Any advice would be really appreciated!

**Comment by adeboisanger** [comment]
Hi,

For my project, I have added the possibility to specify 'center' as x or/and y to center the filigrane.
ex:
filters:watermark(whateverimage.jpg,center,20,1) 
or filters:watermark(whateverimage.jpg,center,center,1) .
I have made the modification on thumbor/filters/watermark.py

On which branch do I have to do my pull request ?

Thank you

**Comment by heynemann** [comment]
It should be synced with our master branch and passing all tests. Thanks for your contribution.

**Comment by LeonB** [comment]
Would be nice to have this merged!
