### ISSUE TITLE
Installation steps for windows 7 for beginners

### ISSUE THREAD

**Issue by dsinghr** [thumbor/thumbor#546]
Requirements:
1. Python 2.7.x
2. Microsoft Visual C++ Compiler for Python 2.7 (For non Visual Studio users)
3. modified `pycurl` for windows

Steps:
1. Download python from https://www.python.org/downloads/ and download specifically 2.7.x latest version and NOT 3.x.x and install it.
2. Skip this step if MS VIsual Studio is already installed (required to compile c++ files) or go to the link http://www.microsoft.com/en-in/download/details.aspx?id=44266 to download Microsoft Visual C++ Compiler for Python 2.7 and install it.
3. Download modified `pycurl` for windows from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pycurl and choose according to windows (x86/64) pycurl-7.19.5.1-cp27-none-xxxxx.whl
4. Install the wheel file by using following command in command propmt:
pip install pycurl-7.19.5.1-cp27-none-xxxxx.whl
5. Finally install thumbor:
pip install thumbor

It took me 5 hours to figure it out all these steps as I am not familiar with python at all. I hope this can help non-python + non-linux developers who want to try it before actual implementation.

Thanks,
Dev

**Comment by heynemann** [comment]
Thank you @dsinghr and good job getting it done and sharing it with us.

**Comment by dsinghr** [comment]
Welcome @heynemann.

**Comment by dsinghr** [comment]
@heynemann It would be helpful for others if you can add this windows 7 installation guide in the installation wiki with my profile link. By the way, I tried to edit installation wiki but was unable to match the github fancy formatting, as I am new user.

**Comment by schwarzeszeux** [comment]
None of the filters worked for me when installing thumbor with pip,

I had to resort to building it myself. However, that does come with its own set of problems.
But I'm finally running a thumbor instance with filters intact :)

I really hope this helps someone else in the future and I personally think it'd be a good idea to either put this in the wiki in one way or antoher.
Or at least have it linked with a big warning on top.

# Building on Windows

## Requirements

If you need help installing any of the requirements, follow @dsinghr 's instructions
 * Python 2.7.x

    https://www.python.org/downloads/
 * Microsoft Visual C++ Compiler for Python 2.7

    Download from https://aka.ms/vcpython27
 * pycurl

    http://www.lfd.uci.edu/~gohlke/pythonlibs/#pycurl
 * latest or stable source

## Changes to the source
The filter wont compile out of the box, you'll need to modify setup.py
 * **Line 39**:

    *From*: ['thumbor/ext/filters/%s.c' % name] + lib_objs,
    *To*: ['thumbor/ext/filters/%s.cpp' % name] + lib_objs,
 * **Line 40**:
    
    *From*: libraries=['m'],
    *To*: libraries=[]
    *because msvc includes the math library already*
 * **Line 47/48**:

    Change the globs from *.c to *.cpp
 * **Line 51**: 

    *From*: return [filter_extension_module(f[0:-2].split('/')[-1], lib_objs, lib_headers) for f in files]
    *To*: return [filter_extension_module(f[0:-2].split('\\\\')[-1], lib_objs, lib_headers) for f in files]

    *The difference is the path separator, which is \ on windows*
 * Rename all *.c files in thumbor/ext/filters to *.cpp

    Here are three options of doing that
   * Use the poweshell command from your thumbor source root

        ls .\thumbor\ext\filters *.c | Rename-Item -NewName { $_.name -replace '\.c$', '.cpp' }
   * Navigate in a cmd prompt to ./thumbor/ext/filters and run "ren *.c *.cpp"
   * Do it manually

    Why? Because msvc compiles with C89 and wont allow you to declare variables in the middle of a code block. I found it easiest to just rename the files to c++ and have them compiled as such.
Actually, I changed the flags in setuptools to force c++ compilation and skipped the renaming part, but don't do that.
 * Delete the sharpen filter

    Why? Because I grew tired of fixing stupid errors and I don't need it anyway. If someone has a solution to the external link problem, I'd be happy to extend this guide.

## Debug build process
If the build process is still failing you, I recommend adding
print(traceback.format_exc())
after line 126 and importing traceback to see what all the fuss is about

## Final words
![Image of Yaktocat](http://www.ademiller.com/blogs/tech_pictures/2008/06/it-works-award1.png)
