### ISSUE TITLE
Applying watermark filter changes image mode and type and returns wrong Content-Type

### ISSUE THREAD

**Issue by optroodt** [thumbor/thumbor#547]
I'm using Thumbor 4.12.2 and have AUTO_WEBP enabled for clients that support it, so there are two distinct cases (images linked at bottom):

** In FireFox (no WEBP support) the error appears**
The image without without a watermark gets served properly as a JPEG with the correct Content-Type.
The image with a watermark becomes a PNG (download it and run identify, it shows up as PNG, but you can already tell by the file size) but Thumbor sets the Content-Type to image/jpeg.

** In Chrome (WEBP support) all goes well**
The image without the watermark is served as a WEBP image with the correct image/webp Content-Type.
The image with the watermark is served as a WEBP image with the correct image/webp Content-Type.

I would expect that Thumbor respects the image format of the image the watermark gets applied to. If it would be PNG, stay PNG, if it's JPEG, stay JPEG. In my case I want JPEG because the PNG's are just too large.
I'm assuming the the image gets converted to RGBA in order to apply the watermark (with transparency) but doesn't get converted back to RGB. This is not a problem for WEBP as it supports transparency, but JPEG doesn't.

The images (same source, original is a JPEG):

** Without watermark **
http://c.looklive.com/v32_sW-rRhIzsgrFafTzMzvKN-E=/600x0/b80ecf5b-59a1-4de1-8493-f698b22a849a

** With watermark **
http://c.looklive.com/L5VBnUKg0NVWP8McDrZnTesDla8=/600x0/filters:watermark(8a0668b9-cc65-4646-94f1-fb62da2dcb58,60,124,97)/b80ecf5b-59a1-4de1-8493-f698b22a849a

Any help is greatly appreciated!
Thanks!

**Comment by optroodt** [comment]
I had an old version (4.4.1) running somehwere that worked correctly so I did a git bisect and found the 'bad' commit: 0bb44efd51fc93df4452eeba4aba642115ec6227

I'm using a custom loader (S3) and result storage, just going to figure out exactly why this is happening.

**Comment by optroodt** [comment]
I ended up always setting the extension to .jpg in our custom engine. We want to send out jpg as a default any way.

**Comment by heynemann** [comment]
Sorry for that, we should fix this. Maybe @guilhermef can take a look at adding a test for this regression?
