### ISSUE TITLE
pil-engine loses jpeg metadata on transformations (quantization, subsampling)

### ISSUE THREAD

**Issue by seichner** [thumbor/thumbor#548]
Hi!

We investigated a problem where using *quality='keep'* does not keep the information it is supposed to (use same subsampling, quantization like the original image). These settings **are kept when 
not doing any transformations, but are lost as soon as we eg. resize the image**.

Debugging showed that in [pil.py](https://github.com/thumbor/thumbor/blob/master/thumbor/engines/pil.py#L81) the *self.image reference* (which was a [PIL.JpegImagePlugin.JpegImageFile](https://github.com/python-pillow/Pillow/blob/master/PIL/JpegImagePlugin.py#L282)) is replaced with a new one (which is a [PIL.Image.Image](https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py). The Pillow-Sourcecode [confirms this](https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L1563), the jpeg specific file is replaced with a generic one. 

When saving the info on subsampling and quantization therefore is missing.

Can anybody give me a hint how this is supposed to work?

Thanks a lot!

**Comment by seichner** [comment]
cc @phoet

**Comment by masom** [comment]
Good catch. Thanks for the initial research @seichner 

I'll try to take a look at this today.

**Comment by seichner** [comment]
actually, i guess the 'solution' would be similiar to how the icc_profile and exif-info is handled right now: first [copied when the image is loaded](https://github.com/thumbor/thumbor/blob/master/thumbor/engines/pil.py#L53) and later [re-injected when it's saved](https://github.com/thumbor/thumbor/blob/master/thumbor/engines/pil.py#L139)...

**Comment by masom** [comment]
@seichner yep

**Comment by masom** [comment]
@seichner Would you mind posting a relatively small jpeg with quantization + subsampling? I'll use the image in tests to ensure this does not happen again in the future.

**Comment by phoet** [comment]
i think @seichner was looking at this image here ![quantization test](http://f.cl.ly/items/0n3A2a3i0z2w0G3g2b0T/ImageTransformationTestQuantization.jpg)

**Comment by seichner** [comment]
@masom Yes, the picture @phoet posted is a good example. It has 4:4:4 Subsampling (exiftool can show you this), and for any conversion with a lower subsampling the text will look fuzzy and its color will change. 
You can check the quantization by outputting the attribute 'quantization' for the JpegImageFile.

**Comment by seichner** [comment]
@masom  i added a failing test as demonstration of the problem in a pull request: https://github.com/thumbor/thumbor/pull/562

I also wrote up a first attempt on solving the problem as discussed above: https://github.com/thumbor/thumbor/pull/563
I simply extract the relevant fields and put them back when the image is written. This is still WIP as the setting is not in thumbor.conf yet. I'd love to hear some feedback, if that's the way to go.

**Comment by masom** [comment]
@seichner Thanks for adding the tests. I am currently overwhelmed with work on a new project and sadly cannot currently look into this issue.

I think the tests + PR you have opened are spot-on and the issue should be solved shortly.

**Comment by seichner** [comment]
@masom ok, thanks! I will see if we can test out the PR above in our system here.

**Comment by seichner** [comment]
if somebody else wants to review it, i'm happy about feedback!

**Comment by seichner** [comment]
FYI: i will close this ticket as my PR from above was already merged and solves this problem.
For completeness: i cleaned the solution up, this is now here: https://github.com/thumbor/thumbor/pull/578
