### ISSUE TITLE
Thumbor not respecting EXIF Orientation while resizing and stripping off EXIF metadata

### ISSUE THREAD

**Issue by AizazAZ** [thumbor/thumbor#550]
Please wait for images to load below

I have enabled flag in Thumbor to respect EXIF orientation.

Original Image with EXIF information: Orientation	Rotate 90 CW

This image is shown to me correctly rotated at 90 CW because I have turned on EXIF flag, so just image it's rotated and correctly displayed :)

![1](https://cloud.githubusercontent.com/assets/1931778/9625366/26aee520-5188-11e5-844e-824dad2402fb.jpg)

Re sized stripped off EXIF metadata 

Re sizing options 

http://SomeThumborServer.com/unsafe/fit-in/300x200/smart/http://someImagePath/images/1.jpg

![2](https://cloud.githubusercontent.com/assets/1931778/9625389/51c06cc0-5188-11e5-827f-4ca503779234.jpg)

Question:
How to force Thumbor not to remove EXIF data or give correctly rotated re sized image?

Here's the full data:

EXIF — this group of metadata is encoded in 4,225 bytes (4.1k)
Exif Image Size	3,920 × 2,204
Make	Sony
Camera Model Name	LT29i
Software	9.2.A.1.215_58_f100
Modify Date	2015:09:01 12:05:52
12 hours, 19 minutes, 38 seconds ago
Y Cb Cr Positioning	Centered
Exposure Time	1/40
F Number	2.40
ISO	320
Exif Version	0220
Date/Time Original	2015:09:01 12:05:52
12 hours, 19 minutes, 38 seconds ago
Create Date	2015:09:01 12:05:52
12 hours, 19 minutes, 38 seconds ago
Components Configuration	Y, Cb, Cr, -
Shutter Speed Value	1/40
Exposure Compensation	0
Metering Mode	Center-weighted average
Light Source	Unknown
Flash	Off, Did not fire
Focal Length	4.5 mm
Flashpix Version	0100
Color Space	sRGB
Interoperability Index	R98 - DCF basic file (sRGB)
Interoperability Version	0100
Custom Rendered	Normal
Exposure Mode	Auto
White Balance	Auto
Digital Zoom Ratio	1
Scene Capture Type	Standard
Subject Distance Range	Unknown
Compression	JPEG (old-style)
Orientation	Rotate 90 CW
Resolution	72 pixels/inch
Thumbnail Length	3,487
File — basic information derived from the file.
File Type	JPEG
MIME Type	image/jpeg
Exif Byte Order	Big-endian (Motorola, MM)
Encoding Process	Baseline DCT, Huffman coding
Bits Per Sample	8
Color Components	3
File Size	942 kB
Image Size	3,920 × 2,204
Y Cb Cr Sub Sampling	YCbCr4:2:0 (2 2)
Composite
This block of data is computed based upon other items. Some of it may be wildly incorrect, especially if the image has been resized.
Aperture	2.40
Megapixels	8.6
Shutter Speed	1/40
Thumbnail Image	(3,487 bytes binary data)
Focal Length	4.5 mm
Light Value	6.2

**Comment by heynemann** [comment]
This is a bug. Thumbor should strip exif metadata to save bytes, but the stored image should be properly rotated. Sorry for that.

**Comment by AizazAZ** [comment]
Please let me know when it is fixed @heynemann

**Comment by guilhermef** [comment]
@AizazAZ It should be fixed now.
