### ISSUE TITLE
Multiple watermarks

### ISSUE THREAD

**Issue by dubaksk** [thumbor/thumbor#551]
Is it possible to apply two or more watermarks over photo? I have read [docs] (https://github.com/thumbor/thumbor/blob/9119e2b3882bc2605d256b4d2ff5de8d79887fd0/docs/watermark.rst), but nothing like that was mentioned.

For example calling: **Usage: watermarks ( [imageUrl1,x,y,alpha], [imageUrl2,x,y,alpha] )** would place two watermarks. So we could send array of watermarks into function with desired positions and opacities.

If it's not possible, are you planning something similar?
Thank you for answer.

**Comment by heynemann** [comment]
We are not planning it, no. If you are willing to specify x and y for both images, can't you just merge them before using it as a watermark?

**Comment by dubaksk** [comment]
I am doing merge of two watermarks into one picture and then sending it into function as one. I was just curious if there is this possibility. 
Thank you for answer.
