### ISSUE TITLE
No module named pngcrush, gifsicle

### ISSUE THREAD

**Issue by onerandomgig** [thumbor/thumbor#552]
Hello,
I have been using thumbor for the last few months and its amazing how awesome it is. Thank you.
I am currently facing an issue related to gifs. When i submit a gif for resizing, it becomes a static image. 

I am not sure if it is related to the below error.

I have installed both the gifsicle and pngcrush packages. But after installing the optimizer plugins, when i run thumbor, i get a No module found error. I get the same error for gifsicle as well.

This is the error i m getting.

Traceback (most recent call last):
File "/usr/local/bin/thumbor", line 9, in
load_entry_point('thumbor==5.0.6', 'console_scripts', 'thumbor')()
File "/usr/local/lib/python2.7/dist-packages/thumbor/server.py", line 58, in main
importer.import_modules()
File "/usr/local/lib/python2.7/dist-packages/thumbor/importer.py", line 50, in import_modules
self.import_item('OPTIMIZERS', 'Optimizer', is_multiple=True)
File "/usr/local/lib/python2.7/dist-packages/thumbor/importer.py", line 74, in import_item
module = self.import_class('%s.%s' % (module_name, class_name))
File "/usr/local/lib/python2.7/dist-packages/thumbor/importer.py", line 33, in import_class
module = get_module and import(name) or import(module_name)
ImportError: No module named pngcrush

In the configuration file, under optimizers, I have this configuration - OPTIMIZERS = ['thumbor.optimizers.jpegtran','thumbor.optimizers.pngcrush','thumbor.optimizers.gifsicle']

I would greatly appreciate any help I can get towards resolving this.

**Comment by guilhermef** [comment]
pngcrush is on a different module,
It should be 'thumbor_plugins.optimizers.pngcrush'

**Comment by onerandomgig** [comment]
Thank you so much @guilhermef. This worked :+1:

**Comment by yanndc** [comment]
same issue here, renaming won't make it work.

**Comment by planetahuevo** [comment]
Getting: 
No module named thumbor_plugins.optimizers.pngcrush
