### ISSUE TITLE
Funky test results on master branch

### ISSUE THREAD

**Issue by okor** [thumbor/thumbor#555]
I'm working on a few PR's for Thumbor right now. But I'm not sure what the test results to should look like. On master, the last couple of lines says:

```
make: nosetests: No such file or directory
make: *** [test] Error 1
```

See https://gist.github.com/okor/e60fcace3aea9ef4c1fc for full test log

No problems with too many files. OpenCV is installed with bindings, no problem. Thumbor anecdotally works just fine locally, both on master and my yet to be submitted PR's. Just want to get a sense for what the test output should look like.

**Comment by masom** [comment]
High chance you need to install the `nose` package.

**Comment by okor** [comment]
@masom To give some context, I'm not that familiar with the Python ecosystem and this is my first real Python work. I normally work with Ruby/Rails/Node/browser js. So I may need a little more help than some other contribs.

I didn't see anything on the docs about this package. But it appears to already be installed.

```
 ~/Projects/voxmedia/thumbor $ pip install nose
Requirement already satisfied (use --upgrade to upgrade): nose in /usr/local/Cellar/numpy/1.9.2/libexec/nose/lib/python2.7/site-packages
```

Appears to be version 1.3.4
```
 ~/Projects/voxmedia/thumbor $ python
Python 2.7.9 (default, May  1 2015, 19:04:44)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nose
>>> print nose.__version__
1.3.4
>>>
```

Any insight into what the `No such file or directory` error means? In the mean time I'll be googling around.

Thanks!

**Comment by okor** [comment]
Ok, I got it working. I'm on OSx Yosemite. Previously installed nose with `pip install nose`.

I had to uninstall nose then reinstall as root. Issue seems that the CLI was not in the path. Fixed. 

Thanks!
