### ISSUE TITLE
artefacts in scaled png image with pil engine

### ISSUE THREAD

**Issue by phoet** [thumbor/thumbor#564]
we are seeing some edge-cases where scaled pngs are rendered with artefacts. i'm not sure how i could properly debug this or if i should actually open an issue on the pillow repository. anyhow, maybe someone here can give me a hint on how to proceed.

_those images are white and transparent, you should see nothing on a white background_

this is the original image:

![original](http://image.jimcdn.com/app/cms/image/transf/none/path/s07f3459425dd27f2/image/i23aaf7ddb2a0e16d/version/1443516467/image.png)
http://image.jimcdn.com/app/cms/image/transf/none/path/s07f3459425dd27f2/image/i23aaf7ddb2a0e16d/version/1443516467/image.png

this is what thumbor renderes scaled:

![thumbor scaled](http://image.jimcdn.com/app/cms/image/transf/dimension=259x10000:mode=fitin:format=png/path/s07f3459425dd27f2/image/i23aaf7ddb2a0e16d/version/1443516467/image.png)
http://image.jimcdn.com/app/cms/image/transf/dimension=259x10000:mode=fitin:format=png/path/s07f3459425dd27f2/image/i23aaf7ddb2a0e16d/version/1443516467/image.png

this is what we had before using imagemagic:

![imagemagic scaled](http://u.jimdo.com/www400/o/s07f3459425dd27f2/img/i23aaf7ddb2a0e16d/1443516467/std/image.png)
http://u.jimdo.com/www400/o/s07f3459425dd27f2/img/i23aaf7ddb2a0e16d/1443516467/std/image.png

feedback appreciated

/cc @seichner

**Comment by heynemann** [comment]
It looks like compression artifacts. Are you using any optimizers?

**Comment by phoet** [comment]
@heynemann no, we are not using any optimizers.

**Comment by phoet** [comment]
the image is also rendered correctly when it's delivered through thumbor in the original resolution:

![original resolution](http://image.jimcdn.com/app/cms/image/transf/dimension=1820x672:mode=fitin:format=png/path/s07f3459425dd27f2/image/i23aaf7ddb2a0e16d/version/1443516467/image.png)
http://image.jimcdn.com/app/cms/image/transf/dimension=1820x672:mode=fitin:format=png/path/s07f3459425dd27f2/image/i23aaf7ddb2a0e16d/version/1443516467/image.png

and with a rotation:
![original resolution but rotated](http://image.jimcdn.com/app/cms/image/transf/dimension=1820x672:mode=fitin:format=png:rotate=90/path/s07f3459425dd27f2/image/i23aaf7ddb2a0e16d/version/1443516467/image.png)
http://image.jimcdn.com/app/cms/image/transf/dimension=1820x672:mode=fitin:format=png:rotate=90/path/s07f3459425dd27f2/image/i23aaf7ddb2a0e16d/version/1443516467/image.png

**Comment by heynemann** [comment]
It looks like an issue with PIL. I created a script that resizes the image using PIL only and the artifacts appear, meaning it's not an issue with how thumbor handles images.

You can see the script and try it for yourself [here](https://gist.github.com/heynemann/fc59ebdcfe77ca4e81a2).

It would be awesome if you could create an issue in [pillow](https://github.com/python-pillow/Pillow/issues) and link this issue there.

Sorry for this inconvenience.

**Comment by phoet** [comment]
@heynemann thx for looking into it, i will cross-link it

**Comment by homm** [comment]
Fixed in https://github.com/python-pillow/Pillow/pull/1912 as part of 3.3.0 release.
