### ISSUE TITLE
Thumbor reporting wrong version

### ISSUE THREAD

**Issue by okor** [thumbor/thumbor#565]
I've checked out version 4.12.2 locally to investigate and issue and possibly patch. We will be upgrading in the near future but due to the change in async/sync in 5.0 we need to stick with 4.12.2 for a bit.

So, the problem I am having is two fold. Our production version of Thumbor is not setting the correct `Content-Type` for webp images (just reported to me yesterday) - we think. Wanted to confirm it was Thumbor and not something in our production stack, caching layer, etc. Most browsers don't care but Chrome on iOS which supports webp does care and will simply not render the image if the Content-Type is not `image/webp`. 

Here is one such example sitting behind our CDN: https://cdn2.vox-cdn.com/thumbor/OMEoUhCUd5LTrAoYyp00QvAPBjs=/64x0:1437x772/800x450/filters:format(webp)/cdn0.vox-cdn.com/uploads/chorus_image/image/47292802/Screen_Shot_2015-09-29_at_4.58.08_PM.0.0.png

And a direct link to Thumbor: http://thumbor.voxmedia.com/thumbor/OMEoUhCUd5LTrAoYyp00QvAPBjs=/64x0:1437x772/800x450/filters:format(webp)/cdn0.vox-cdn.com/uploads/chorus_image/image/47292802/Screen_Shot_2015-09-29_at_4.58.08_PM.0.0.png

Both with the incorrect Content-Type

A colleague pointed out this PR: https://github.com/thumbor/thumbor/pull/425/files

Which appears to be in version 4.12.2: https://github.com/thumbor/thumbor/blob/b12e623a0d1f318abd265f2d6927d01af2bfc71e/thumbor/handlers/__init__.py#L218

We thought that maybe the "auto webp" and the filters may be setting the Content-Type in a different way. So I set out to investigate, checkout out the last commit on 4.12.2:

```
commit b12e623a0d1f318abd265f2d6927d01af2bfc71e
Author: Guilherme Souza <guivideojob@gmail.com>
Date:   Wed Mar 18 15:27:21 2015 -0300

    Bump to 4.12.2
````

^ last commit on this local 4.12.2 branch

But if I curl a test url:
```
 ~/Projects/voxmedia/thumbor $ curl -I "http://localhost:8888/unsafe/0x401/filters:format(webp)/cdn0.vox-cdn.com/uploads/chorus_image/image/47283870/verge-2015-06-14_13-32-08.0.0.0.jpg"
HTTP/1.1 200 OK
Content-Length: 7634
Expires: Thu, 01 Oct 2015 14:17:25 GMT
Server: Thumbor/5.1.0
Etag: "a5cc42c60657a38ba85943ab621870d3342e611e"
Cache-Control: max-age=86400,public
Date: Wed, 30 Sep 2015 14:17:24 GMT
Content-Type: image/webp
```

^ 5.1.0 version is reported. I also did extensive search replace of all assignments to Content-Type and content_type variables to "icecold/beer", just to see if I could see which call was actually setting the Content-Type since it didn't change when I updated the value in the change from the previously mentioned PR.

So, I probably have something funky going on with my dev setup but I don't know what it is. I did do a fresh clone and checkout but that didn't have any affect on the version of Thumbor reported. I'm sure this is something stupid I am doing but would appreciate any help you could provide.

p.s. I also tried running `python -m compileall .` after reading about pyc, thinking maybe there was a code cache issue. But no dice. That was before the fresh clone.

![i-have-no-idea-what-im-doing-dog](https://cloud.githubusercontent.com/assets/142910/10195820/92bc3ade-675d-11e5-99df-66366bd2737b.jpg)

**Comment by okor** [comment]
So, I figured it out kind of but still not sure why this is the case. But I had version 5.1.0 installed with pip locally and it was using that code. I uninstalled with pip and then reran `make setup` which installed 4.12.2

I am still super confused why I would need to install thumbor as a pip package when I have the source code locally and I'm executing the server directly with `python thumbor/server.py`. But if I don't have the thumbor package installed the server will not start.

**Comment by masom** [comment]
@okor Are you using virtualenv ?

Python somewhat always had an awkward relationship with local files and packages installed in `site-packages`. It is often better to start a fresh virtualenv per-project otherwise "contamination" happens.

Another way to test a local version of a package is to do a `pip install -e .`

`  -e, --editable <path/url>   Install a project in editable mode (i.e. setuptools "develop mode") from a local project path or a VCS url.`

**Comment by guilhermef** [comment]
@okor did you put the header "Accept" in the white-list on Cloudfront ?
You don't need to force the format webp, it will detect based on the Accept header.

**Comment by okor** [comment]
@guilhermef The "Accept" is forwarded, yes. But I don't think that's the issue. It's the response `Content-Type` which I didn't think had anything to do with the Accepts. And in this case, we are asking for webp explicitly via the format filter, so I didn't think that's really relevant here. 

Colleague strongly recommends using virtualenv, I am not currently. He thinks that's why trying to run thumbor is using lib version instead of local repo. I had issues getting virtualenv setup a while back and decided to roll without it ..... which I now believe was a blunder. I'll take the time to get a proper Python env setup. That's what I get for rushing!

**Comment by masom** [comment]
@okor Rushing is fun :)

Once familiar with virtualenv ( it's akin to Ruby's rvm/rbenv ) you'll probably never install packages at the system level. It's really awesome at isolating dependencies, allowing you to run multiple version of the same software / packages.

**Comment by okor** [comment]
@masom @guilhermef I read a couple of tutorials and docs, I think I grok everything. I purged all the global pip packages. Started over. And now I have successfully setup virtualenv (and wrapper). I'm good to go!

Also worth noting, unaltered 4.12.2 version of thumbor seems to be setting the `Content-Type` correctly. So, I'll mess with the source to make sure it's doing what I think it's doing. But I bet this is an issue with our stack/caching layers in prod. My guess is something is passing the `Content-Type` header from cloudfront but somehow when Thumbor rewrites the header, it's not propagating up through all the layers .... and there are several "fun" layers of custom caching we are doing ... one of which I bet is messing up the `Content-Type`

Thanks again for the help! I'm closing this since it's probably our fault : )

**Comment by okor** [comment]
Just as an update for any Googler's or curious, Thumbor is definitely setting the `Content-Type` correctly when using the format filter and that is happening here: https://github.com/thumbor/thumbor/blob/b12e623a0d1f318abd265f2d6927d01af2bfc71e/thumbor/handlers/__init__.py#L218 as suspected. I'm off to have a chat with the Ops team : )

**Comment by heynemann** [comment]
Good to know @okor!
