### ISSUE TITLE
thumbor slack channel

### ISSUE THREAD

**Issue by heynemann** [thumbor/thumbor#567]
I created thumbor's slack channel and would like to add everyone to it. It would be great if you guys could help invite people.

/cc @masom @robolson @rfloriano @cezarsa @okor @dhardy92 @guilhermebruzzi @guilhermef 

I definitely forgot people, so please start cc'ing people in this issue.

Anyone that does not feel safe putting their e-mail here in this issue, please e-mail me at heynemann at gmail.com with your e-mail so I can invite you to thumbor's slack.

**Comment by masom** [comment]
martin@doorbot.co

**Comment by eduherraiz** [comment]
gshark@gmail.com

**Comment by okor** [comment]
jason.ormand1@gmail.com

**Comment by rcrowe** [comment]
hello@vivalacrowe.com

**Comment by varshithr** [comment]
Hey, Is the channel still active?
If yes sign me up

varshith@scriptbees.com
