### ISSUE TITLE
Proposal: Media object

### ISSUE THREAD

**Issue by masom** [thumbor/thumbor#577]
Right now thumbor passes around the image/video buffer. Some work has begun to allow storages to return a "LoaderResult" or "ResultStorageResult" objects that contains metadata and allows for better error handling.

This gives thumbor a lot more flexbility in error handling and allows it to leverage backend specifics ( ex: TTL in redis, ContentType / LastModified in AWS ).

Going through the current modifications it would make things a little bit easier if thumbor moved the buffer and associated data into a `Media` object that would abstract out how it got into the pipeline.

`file_loader` or the `http_loader` would return a `Media` object that contains the buffer and some metadata.

`*_storage` and `*_result_storage` would also return this `Media` object.

This would allow thumbor to provide a uniform object to engines, filters, optimizers, etc. Many methods would also be greatly simplified.

Backward compatibility can probably be maintained like it is currently done with loaders. If a loader does not return a `Media` instance we just create it.
##### Example implementation

``` python
class Media(object):
    def __init__(self, buffer, is_valid=True, metadata = {}, errors = []):
        self.buffer = buffer
        self.metadata = metadata
        self.errors = errors
        self.is_valid = True // or some other boolean to indicate everything is fine.

     @property
     def content_type(self):
         return self.metadata.get('ContentType', None)

      // Other utility methods
```

`metadata` would contain things like:
- `ContentType` or `MIME`
- `Source` ex: `http://bucket.s3.amazonaws.com/image.jpg`, `redis://some-key`
- `Size` file size in bytes
- `Frames` # of frames in the video/gif
- `Length` ( for video types )
- `Width` pixels
- `Height` pixels
- `ColorSpace` RGB / CYMK
- `EXIF` Exif data

As engines / optimizers / filters operate on the Media object those values would be changed.

**Comment by heynemann** [comment]
Sounds like a good abstraction to me.

**Comment by masom** [comment]
Added example metadata fields.

**Comment by Bladrak** [comment]
:+1:

**Comment by masom** [comment]
@guilhermef thoughts?

**Comment by guilhermef** [comment]
It's a great idea

**Comment by sbaechler** [comment]
@masom Have you started work on this feature yet? I plan to start with the metadata extraction soon and would like it to be based on your branch.

I would make `is_valid` a method instead of a property.

**Comment by masom** [comment]
@sbaechler I had planned on working on this tomorrow morning.

The heavylifting already happend with `LoaderResult`, supporting a `Media` object would work for 6.x series.

**Comment by masom** [comment]
@sbaechler https://github.com/thumbor/thumbor/pull/633

Currently broken but the core of the changes have been implemented.

**Comment by sbaechler** [comment]
@masom If I understand this correctly, `LoaderResult` and `ResultStorageResult` are deprecated in favor of `Media`.

**Comment by heynemann** [comment]
How is this as of today?

**Comment by heynemann** [comment]
We are working in another branch to get rid of all the Result objects. Closing this as this is very old. If someone feels like we should reopen, feel free to do it.
