### ISSUE TITLE
Outdated haarcascade detector files?

### ISSUE THREAD

**Issue by Bertg** [thumbor/thumbor#581]
We are getting close to rolling out Thumbor on our service and have started some user testing. One of the remarks we collected is that not "all" faces are detected. I tried to understand a bit better how this works. 

This stuff if way out of my league, but I did notice that the [files in the opencv project](https://github.com/Itseez/opencv/tree/master/data/) are more recent. This led me to these questions:

* Where do the current haarcascade files come from, and does that source have an update?
* Can we use the files provided by opencv?
* Would it make sense to create a script that can bring the scripts up-to-date on the regular?

**Comment by heynemann** [comment]
I think @guilhermef is the best person to answer this since he's been doing some work on updating OpenCV on thumbor (non-trivial task).

**Comment by guilhermef** [comment]
@Bertg I'm updating the haarcascade files on the branch https://github.com/thumbor/thumbor/tree/feature/nosetests
this commit https://github.com/thumbor/thumbor/commit/d00a212a4063472659618c10fce838c20e8eb051 updates the files, but I had to change the way we use OpenCv, so right now I'm trying to integrate with the other engines before releasing it.

**Comment by guilhermef** [comment]
About keeping the haarcascade files updates, I think after releasing this new version, we could point to the OpenCV folder and use the ones bundled with it, instead of copying them to Thumbor's folder.

**Comment by Bertg** [comment]
Cool, I've looked at the branch and seems quite interesting. Is there an ETA for the changes? 

Just so I could move further along, the sales added in your commit, will these also work with the current thumbor version?

**Comment by guilhermef** [comment]
We're still trying to cover some test scenarios, but It's close, something like 2 weeks.
We will generate a new version, since the new haarcascade files don't work on the old OpenCV api.

**Comment by guilhermef** [comment]
@Bertg Right now Thumbor's master has the updated haarcascade files
