### ISSUE TITLE
Allow chaining engines

### ISSUE THREAD

**Issue by masom** [thumbor/thumbor#585]
Quick terrible brainstorm:

It would be awesome if engines could be chained given certain conditions are met.

Something like creating document (pdf, docx, etc.) thumbnails would then be possible.

Input: `my_document.pdf` executes on an engine, producing an image buffer. Pillow is the executed to alter the preview.

https://github.com/btimby/thumbnailer implements most of the required functionality to generate document thumbnails ( requires open office / libre office ). That thumbor engine should probably not reside in the thumbor repo but there should be an infrastructure in place that allows this.

**Comment by heynemann** [comment]
I'm not sure this should be chainable engines. The engine in thumbor is responsible for generating the most optimized image possible.

I've given this idea some thought for a while now and I think this should come down to loaders. The loader should be the one to actually grab whatever resource you need and make sure thumbor gets an image. The following are ideas:

* Loader gets video/mp4 as content-type and grabs a video and returns a specific frame to thumbor engine;
* Loader gets application/pdf and grabs a specific frame to send to thumbor engine;
* Loader gets application/zip, decompress it and retrieves an image from inside the zip file;
* Loader gets image/svg+xml and grabs an SVG and transforms it to an image to thumbor.

You get the general idea. The main thing here is that this GREATLY simplifies thumbor as in it only needs to deal with images, no matter where they come from. 

The only issue we have right now, IMHO, to start using this approach is that engines would need access to request parameters that are not there yet (if it's via filters, filters have not been executed yet in the loading phase).

What do you think?

**Comment by masom** [comment]
The loader approach does make things a lot more simpler for most use cases.

This probably means loaders would get a new "step" since downloading from HTTP/FTP/AWS/file is not directly related to manipulating a pdf / zip / gif / etc. to produce an acceptable media.

A good example of this is the gif thumbnail filter.

Satisfying where these operations happen or how is going to be interestingly complex. Hopefully a simple approach can be figured out.

A good test would be loading a gif and extracting a thumbnail to apply a black/white filter on the thumbnail.

Loading a PDF amounts to the "exact" same work, a page screenshot needs to be extracted and filters ( ex: resizing/cropping) applied.


Also maybe this shouldn't be part of thumbor, limiting scope is nice as it reduces complexity. Example: handling GIF is awesome although it feels a little bit hacky when trying to generate thumbnails and apply filters on the resulting image.

**Comment by masom** [comment]
Related: https://github.com/thumbor/thumbor/issues/586

The OpenCV engine image manipulation is different from Pillow. It would be great to issue the shape detection to OpenCV and then operate on the image using Pillow.

**Comment by gi11es** [comment]
I've worked around the problem by writing a proxy engine to achieve just that: https://phabricator.wikimedia.org/diffusion/THMBREXT/browse/master/wikimedia_thumbor/engine/proxy/proxy.py

Note that this code wasn't written with any guarantee that this would work beyond simple resizing, which is all we're planning on using in the short term.

To go along that proxy engine, I've written several minimal (equally not feature-complete) engines for a bunch of formats, and through the proxy engine a single Thumbor instance can process all these file formats: https://phabricator.wikimedia.org/diffusion/THMBREXT/browse/master/wikimedia_thumbor/engine/
