### ISSUE TITLE
convert CMYK to sRGB filter

### ISSUE THREAD

**Issue by Perni1984** [thumbor/thumbor#586]
I have several original .jpgs from our photographer saved with ICC profile Coated Fogra27 (ISO 12647-2:2004), which should be CMYK if I understood well.

Is there a filter or another way in thumbor that I can use to deliver "web-safe" sRGB pictures out of those CMYK pictures. Unfortunately I didn't find anything on the filters wiki page or here in the issues.

**Comment by masom** [comment]
Hi @Perni1984 

This is an interesting problem we faced on crated.com

Artists would upload their originals in CMYK + embedded ICC profile. Browser support for CMYK is kinda clunky and as you discovered, the file displays fine on a computer but not on the web.

We discovered in some case a simple convert from CMYK to RGB worked. One issue we faced with the conversion is the loss of colours / parity on some art pieces.

You could use ImageMagick `identify` to determine if you have a CMYK image:
```
identify -verbose something.jpg
...
Colorspace: CMYK
...
```

You can convert a CMYK to RGB using the `convert` command using the original profile:
```
convert original.jpg -negate -profile <original_profile>.icc -profile <adobe rgb profile>.icc output.jpg
```


In thumbor it would be possible to write a filter that will apply the Adobe RGB profile.

From Pillow docs:
```
icc-profile
If present, the image is stored with the provided ICC profile. If this parameter is not provided, the image will be saved with no profile attached. To preserve the existing profile:

im.save(filename, 'jpeg', icc_profile=im.info.get('icc_profile'))
```

Welcome to image correction and colour space hell :)

Let me know if you need help writing the filter althoug if the amount of picture is small it might be faster / better if you let the artist know. Converting from CMYK to RGB usually changes the image.

**Comment by Perni1984** [comment]
Hi @masom, thanks for pointing out the options.

As I am not really python savvy (unfortnately) I will probably use Imagemagick or Graphicsmagick to modify the file after the upload and before serving it o thumbor. 

I was just wondering if I have overseen a filter or something to directly throw a CMYK jpeg onto thumbor and have it being automatically converted to a web safe .jpg without ICC profile.

Thanks. Best.

**Comment by masom** [comment]
@Perni1984 if you really need it "on-the-fly" within thumbor I could probably contribute the filter although there's several small issues.

ICC profiles usually cannot be re-distributed and to do a proper conversion the original profile needs to be available.

**Comment by Perni1984** [comment]
@masom really thanks for your help. 

If I understood it correctly the .jpg files I have already contain the icc profiles in them. What do you mean that they cannot be re-distributed?

**Comment by guilhermef** [comment]
@masom @Perni1984 We convert every jpg to rgb: https://github.com/thumbor/thumbor/blob/master/thumbor/engines/pil.py#L136

but we keep the icc_profile: https://github.com/thumbor/thumbor/blob/master/thumbor/engines/pil.py#L154

**Comment by masom** [comment]
Damn, thanks @guilhermef I completely forgot about that step.

@Perni1984 some profiles we had to work with had a "do not distribute" clause ( which is kinda silly when they get embedded in the file ).

**Comment by Perni1984** [comment]
hmm, strange, then the conversion is not working as expected, eventually it is related to thumbor/opencv-engine#16. 

I am attaching the file that I would like to send to thumbor to crop and resize.

Adobe Photoshop shows me that it has the following profile embedded:
ICC profile Coated Fogra27 (ISO 12647-2:2004)

When I am sending the following picture to thumbor
![dominator 800-272](https://cloud.githubusercontent.com/assets/9039956/10730146/75a2f384-7bee-11e5-939f-65a8a8102589.jpg)

this is what I get:
![converted by thumbor](https://cloud.githubusercontent.com/assets/9039956/10730270/382d7848-7bef-11e5-82ed-e382da074b66.jpg)


this is what it should look like (after photoshop conversion to sRGB):
![converted by photoshop](https://cloud.githubusercontent.com/assets/9039956/10730266/33c04b28-7bef-11e5-8fa9-2e60a8e72220.jpg)

**Comment by guilhermef** [comment]
@Perni1984 Are you using the opencv-engine ?

**Comment by Perni1984** [comment]
For the above pictures I was using the standard pillow engine with opencv for face/feature detection. 

I now dowloaded the opencv-engine and changed the pillow engine in the configuration to opencv, but the result was the same. 

Interestingly photoshop is showing me that the color profile after the conversion is RGB, so it seems like the ICC-profile is stripped during conversion. But I guess for the color conversion to RGB the ICC-profile is not taken into account and this generates the wrong colors.

**Comment by Perni1984** [comment]
one thing to add. I was using the the mozjpeg optimizer to generate the above images. I also tried disabling it, but nothing changed.

**Comment by sbaechler** [comment]
This looks like the color profiles are ignored. Have you built Pillow with support for [littlecms](http://www.littlecms.com/) for the color management?

**Comment by okor** [comment]
Hey, I just wanted to necromance this issue back to life. @sbaechler Are you saying that CMYK to (s)RGB should be more predictable if littlecms support is built into Pillow? If so, are there any docs on that? I don't see anything ~ /cmyk|littlecms/

@guilhermef Should we only expect predictable CMYK to (s)RGB conversion if we are using pillow?

**Comment by sbaechler** [comment]
@okor You can compile Pillow with Littlecms support if the library is installed on your system. Only then PIL can interpret ICC profiles. However, you still need the right color profile files for CMYK. I have tried getting this to work a few years ago but didn't succeed. Color management is not just an issue for CMYK. An image can also have AdobeRGB embedded. If the ICC profile is stripped during processing the colors will be off.

What we ended up doing in FeinCMS is refuse an uploaded image if the color space is CMYK.

**Comment by okor** [comment]
Pillow has since rewritten CMYK to RGB color conversion https://github.com/python-pillow/Pillow/pull/2699 and this issue has been inactive for quite a while, so I'm closing.
