### ISSUE TITLE
Utilising different storage backends for uploads and loaded images

### ISSUE THREAD

**Issue by lextoumbourou** [thumbor/thumbor#589]
Hi all,

Firstly, thanks a lot for Thumbor, it's awesome! :smile:

Regarding Thumbor's upload functionality, it seems like you can set the `UPLOAD_PHOTO_STORAGE` and `STORAGE` params to use different storage backends, but then when actually requesting the image, it appears to always use the `STORAGE` backend.

Is there a way to support complete separate backends for uploaded images and stuff loaded from the `LOADER`? For example, I'd like to store and load user uploaded images from S3 and everything else on the disk.

Thanks!

**Comment by heynemann** [comment]
You can implement your own loader. That's the easiest way to achieve it.
