### ISSUE TITLE
 If using USE_GIFSICLE_ENGINE configuration to True, the `gifsicle` binary must be in the PATH 

### ISSUE THREAD

**Issue by ahmadimt** [thumbor/thumbor#596]
I am using the latest version of Thumbor with Gifsicle.. While Starting the server, I am getting the below error, Although gifsicle is present in /usr/local/bin

RuntimeError: If using USE_GIFSICLE_ENGINE configuration to True, the `gifsicle` binary must be in the PATH and must be an executable.
Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==5.2.1', 'console_scripts', 'thumbor')()
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.2.1-py2.7-linux-x86_64.egg/thumbor/server.py", line 126, in main
    validate_config(config, server_parameters)
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.2.1-py2.7-linux-x86_64.egg/thumbor/server.py", line 79, in validate_config
    'If using USE_GIFSICLE_ENGINE configuration to True, the `gifsicle` binary must be in the PATH '
RuntimeError: If using USE_GIFSICLE_ENGINE configuration to True, the `gifsicle` binary must be in the PATH and must be an executable.
Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==5.2.1', 'console_scripts', 'thumbor')()
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.2.1-py2.7-linux-x86_64.egg/thumbor/server.py", line 126, in main
    validate_config(config, server_parameters)
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.2.1-py2.7-linux-x86_64.egg/thumbor/server.py", line 79, in validate_config
    'If using USE_GIFSICLE_ENGINE configuration to True, the `gifsicle` binary must be in the PATH '
RuntimeError: If using USE_GIFSICLE_ENGINE configuration to True, the `gifsicle` binary must be in the PATH and must be an executable.

**Comment by masom** [comment]
Getting this error means Thumbor was unable to locate `gifsicle`.

Is `gifsicle` executable?

**Comment by ahmadimt** [comment]
yes it is...here is the screenshot for that

![image](https://cloud.githubusercontent.com/assets/10077189/11039281/e53446d2-872c-11e5-894e-5559f365c1a4.png)

**Comment by masom** [comment]
What's the `PATH` environment value for the user `thumbor` executes under?

Does that user have access to the `gifsicle` executable?

**Comment by ahmadimt** [comment]
here is the value of PATH
root@TH01:/etc# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

Also, the user has the access to the gifsicle...

**Comment by ahmadimt** [comment]
Hi Martin,

I found a workaround for this....instead of building gifsicle from source...I just installed it directly from Ubuntu repo...Now it's working...

Thank you for your time..Martin....appreciate your help.. :+1:

**Comment by dhardy92** [comment]
actually this is current root shell $PATH ...
to really know what PATH thumbor is using prefer /proc filesystem information
```
 #get PID of first occurrence of thumbor process
THUMBORPID=$( ps -edf | awk '/\/usr\/bin\/thumbor/{print $2; exit}' )
sudo cat /proc/$THUMBORPID/environ | tr '\0' '\n' | grep PATH
```
