### ISSUE TITLE
Malformed URL for some secure URLs

### ISSUE THREAD

**Issue by hawkett** [thumbor/thumbor#597]
I'm getting the following error for some URLs, while others work fine. I _am_ encoding the url before hash generation. The SECURITY_KEY I used for everything in this issue was ```BOTEZu^p_EH+(G5hf5in```.

```WARNING Malformed URL: /THpDlimZIwCIdMql0gXf2MYn6Lg=/0x200/smart/https%3A%2F%2Fcdn-images-1.medium.com%2Fmax%2F800%2F1*tR_m1tLvYS8VXX1w5mHz5A.png```

Original URL (from medium.com): https://cdn-images-1.medium.com/max/800/1*tR_m1tLvYS8VXX1w5mHz5A.png

----
An example of a working URL:

```
/HnsCJyyQQ_87UM3FkbJZaztRkcM=/0x200/smart/https%3A%2F%2Fi.guim.co.uk%2Fimg%2Fmedia%2Fe2e8604b4eb0026afa7f2962375e650838a5db9f%2F0_0_2000_1199%2Fmaster%2F2000.jpg%3Fw%3D1200%26q%3D85%26auto%3Dformat%26sharp%3D10%26s%3D83ad33fb1fb9be7cbae1cf7d25ddd427
```

Original URL (from theguardian.com): https://i.guim.co.uk/img/media/e2e8604b4eb0026afa7f2962375e650838a5db9f/0_0_2000_1199/master/2000.jpg?w=1200&q=85&auto=format&sharp=10&s=83ad33fb1fb9be7cbae1cf7d25ddd427

----
Here's the code I'm using to generate the hash:

```
var crypto = require('crypto');

function getImageKey(url) {
  var key = crypto
        .createHmac('sha1', THUMBOR_SECURITY_KEY)
        .update(url)
        .digest('base64');
  return key.replace(/\+/g, '-').replace(/\//g, '_');
}

var imageUrl = '0x200/smart/' + encodeURIComponent(originalUrl);
var secureUrl = 'https://thumbor.myserver.com/' + getImageKey(imageUrl) + '/' + imageUrl;
```

The encryption approach came from [here](https://github.com/PolicyMic/thumbor/blob/master/index.js#L254). But I also tried [this approach](https://github.com/dcaramelo/ThumborUrlBuilder/blob/master/index.js#L258) with the same results.

Do both those images work correctly in other's implementations? Any obvious issues with my approach?

**Comment by hawkett** [comment]
It looks like this problem is caused by javascript's ```encodeURIComponent()``` method not encoding some characters (in this case ```*```) as thumbor expects. I modified my code to the use the ```fixedEncodeURIComponent()``` method documented [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent), and the broken URL is now working.

The documentation on the Security wiki doesn't mention encoding the URL (always refers to ```path/to/image.jpg```). Does thumbor have an explicit encoding requirement for the URL - e.g. RFC 3986)? Currently I'm assuming my new implementation is correct, but the reality may be that I just haven't found any URLs that fail.

**Comment by masom** [comment]
Since the image URL itself is part of the HTTP path it is better to always encode it using RFC 3986
