### ISSUE TITLE
URL escaping parens in filter string not supported

### ISSUE THREAD

**Issue by banks** [thumbor/thumbor#598]
Hi we are using thumbor 5.2.1 (current stable version I think).

We have an issue which has been partially reported before e.g. #344 but the "fix" in that case was to go fix the other system that was adding additoinal escaping to the URL.

We've been running fine with thumbor in production for a while.

Problem is we now have requirement to send HTML emails and many mail clients (including Outlook.com (used to be called hotmail) appear to add the same additional escaping to URLs that the ticket above complained about.

Specifically in many languages all special chars are encoded not just those required to make the URL RFC compliant.

For example when we send an email with a thumb URL:

http://t01.deviantart.net/6ER_tA9w-k8lfWg4f-fB3h-Neh8=/300x200/filters:fixed_height(100,100):origin()/pre10/05c2/th/pre/i/2015/300/9/6/testing_by_petralfire-d9el86h.jpg

outlook.com adds additional escaping (presumably as part of a bad link filtering process that decodes and re-encodes the URLs):

http://t01.deviantart.net/6ER_tA9w-k8lfWg4f-fB3h-Neh8=/300x200/filters:fixed_height%28100%2c100%29:origin%28%29/pre10/05c2/th/pre/i/2015/300/9/6/testing_by_petralfire-d9el86h.jpg

The result is that obviously the HMAC security key doesn't validate and they get a 404.

If we proactively encode our URLs so the are already like the outlook mangled one, the hmac key is valid but thumbor doesn't decode them again and so fails not being able to parse the filter string (presumably).

http://t01.deviantart.net/wYl5ECvmlOIkCC88Kwk_mOJo5eQ=/300x200/filters:fixed_height%28100%2c100%29:origin%28%29/pre10/05c2/th/pre/i/2015/300/9/6/testing_by_petralfire-d9el86h.jpg

In that case we see messages in thumbor log like:

```
2015-11-11_17:46:46.91013 thumbor-1: 2015-11-11 09:46:46 thumbor:WARNING ERROR retrieving image http://filters:fixed_height(100,100):origin()/pre10/05c2/th/pre/i/2015/300/9/6/testing_by_petralfire-d9el86h.jpg: [Errno -2] Name or service not known
```

So thumbor is obviously not recognising the percent encoded filter string as a filter string at all.

This is quite an urgent issue for us so we will likely be patching thumbor to fix it. I'll add a PR when/if we do.

If you have any input on this issue - like rationale for cases that break if you "fix" this one or similar, then I'd love to hear your thoughts.

**Comment by heynemann** [comment]
The issue here is these "smart" encoders. Outlook automatically encodes stuff. Tornado automatically decodes stuff. This leaves us in the middle. What do we do? Automatically decode? Then we have issues with people who didn't encode it in the first place. Do not automatically decode? Issues with clients like Outlook that automatically encode.

If you manage to find a way to work this out, it would be a GREAT contribution to thumbor. We also have issues with unicode and not decoding.

God I hate encoding...

**Comment by heynemann** [comment]
Btw, sorry for this issue affecting you guys. Really sorry for the poor service it's providing...

**Comment by banks** [comment]
So a trivial fix that solves this issue as stated is:

```
diff --git a/thumbor/url.py b/thumbor/url.py
index 6dbe010..9e4e88d 100644
--- a/thumbor/url.py
+++ b/thumbor/url.py
@@ -24,7 +24,10 @@ class Url(object):
     halign = r'(?:(?P<halign>left|right|center)/)?'
     valign = r'(?:(?P<valign>top|bottom|middle)/)?'
     smart = r'(?:(?P<smart>smart)/)?'
-    filters = r'(?:filters:(?P<filters>.+?\))/)?'
+    filters = r'(?:filters:(?P<filters>.+?(?:\)|%29))/)?'
     image = r'(?P<image>.+)'

     compiled_regex = None
```

See the problem appears to be that Tornado has NOT unescaped the parens by the time regex matching on URL happens, so the filter string is treated as part of the source file explaining the log output I posted originally. Oddly it just works with this one change, which implies tornado (or thumbor) IS magically unescaping the filter string by the time you come to actually use the value. I didn't see anything obvious in tornado docs about that and didn't have time to dig deeper.

The fix above does indeed "fix" this for us insofar as it would allow us to generate URLs with filter string already url encoded when we make our HMAC and hence would work fine in outlook and other misbehaving clients.

The reason I didn't make this a PR yet is it's an ugly and incomplete solution - the URL generator shipping with thumbor would still generate URLs that break in outlook for example, but if you change it, everyone's URLs in the next release will suddenly change causing cache invalidations which is a nasty side-effect of an upgrade even if it's a major version.

That is probably the reason is that we probably _won't_ use this patch either. Although it makes it possible to encode URL and get around outlook issue, it will invalidate every URL in 2 different layers of CDN caching we have in front of thumbor which will either be a huge performance/cost issue and require us to scale up to many hundreds of thumbor nodes to handle the traffic for a while, or we'll have to have some complicated gradual roll out where we only switch a few percent of thumb urls we serve to use new encoding each day for a few weeks. That is time consuming and means we still can't launch this feature until it's totally done.

Instead what we will probably do is add rules to our loadbalancer/caching tier in front of thumbor to automatically decode % encoded chars. For us, we know for sure there are never % encoded chars in the source URL for our source files, nor % encoded `/` in filter string etc. so we could do it blindly, but in general it would have to be smarter and only apply that decoding to parts of the URL before the actual source (i.e. before the final `/`) and possibly to subset of chars we know to expect encoded in a valid thumbor URL.

You might want to consider finding a way to do that in thumbor in general - intercepting the request before the regex matching and manually converting those escaped parens. That way only requests from encoding-munging clients would invalidate normal cached results in CDNs etc. Alternatively, you could possibly validate the hmac both with and without % encoded filter string and allow either, then this patch would be a reasonable solution.

Let me know your thoughts.

**Comment by heynemann** [comment]
My initial reaction to this was to try to validate both the encoded and unencoded version against the hmac to make sure either work. I think the issue here is the storage bit. If we allow for both formats you would end up with two different items in storage (possibly). Any ideas @masom @okor @guilhermef?

**Comment by banks** [comment]
I have a working patch that makes the above less unpleasant.

I'll submit a PR for you to look at although I doubt it's acceptable as-is because I've run out of time and still not managed to get your test suite to run on OS X...

It uses the last idea to combine permitting encoded closing paren in the URL regex with re-encoding the URL before we validate HMAC so that it passes.

It's not a fully general solution though - if original image source URL also has chars like parentheses in, those would also have been mangled but the bad client but it's not safe for us to assume any encoded chars there were not in original so we don't decode those and HMAC validation would still fail.

I didn't look into what point the result storage comes in so yeah you may need to normalise earlier to avoid storing multiple copies.

If you don't there is a slight risk of DOS attack because malicious user can submit same URL with each char (including alphanumeric ones) percent encoded in turn and my patch would make those work and process the image bypassing result cache.

So I'll submit PR for sake of sharing - it's good enough for us and we have a few custom patches already, but probably needs more work (and at least some tests) before it's merged upstream I'd guess.

**Comment by banks** [comment]
FWIW I couldn't get `make test` to run due to many dependency issues. Even using virtualenv I was unable after 30 mins or so of googling to get past `ImportError: cannot import name wraps` despite having manually installed latest versions of `mocks` and `six`...

If there is some trivial thing I can do to make that work please let me know :) I guess I'll see now if travis fails the PR at least...

**Comment by guilhermef** [comment]
@banks are you using python 2.7 ?

**Comment by banks** [comment]
Yep

**Comment by banks** [comment]
Turns out we probably won't even use this patch for now. In production we have a caching proxy cluster in front of our thumbor cluster since our CDN does not have it's own origin shielding function. Thumbor result storage is not really possible for us because our thumbor cluster is auto-scaling and it result storage makes each instance stateful so cache coherency becomes very hard to manage. 

This patch would essentially open up the same DOS vector we were discussing above for us since it would allow attacker to take one valid URl and turn it into trillions of distinct URIs* that would bypass both CDN and our cache cluster and cause work in thumbor even though it would be producing same output each time.

So for us, it's more pragmatic to decode URLs in our caching cluster before we proxy them. That means that we both fix HMAC validation issue, and that we still have cache hits if same url gets encoded different ways.

I'm happy to continue the conversation if you want to figure out the best general solution for other thumbor users though.

---
* every char in `300x200/filters:fixed_height(100,100):origin()` replaced with encoded one is 2^47 possible URIs (~140 trillion)

**Comment by okor** [comment]
Just brainstorming here. But it seems like a url shortener would be a simple solution that would not cause massive cache invalidations or code smell (in thumbor) for funky client issues.

**Comment by banks** [comment]
Yep that could work, but it's a bunch of overhead - when sending out millions of dynamically generated emails, having to create new shortened URL is not practical, not to mention that if you used these in other places bad clients might lurk you'd need to make calls/db updates to url shortening service every time you serve an image...

A more realist alternative is to define a new URL syntax that encodes all the features of thumbor we need but avoids using any special chars at all, and then build a scalable proxy that translates those into actual thumbor URLs... But this has same downsides as my original patch - all cached URLs in CDN's etc are invalidated, plus there is an extra piece of infrastructure up maintain...

**Comment by masom** [comment]
@banks PopKey is doing that: `https://m.popkey.co/197808/k00vK_f-thumbnail-100-0_s-600x0.jpg`

- The url signer has been modified to produce shorter signatures
- A custom url parser has been built to parse `{:slug}_{:options}.{:format}`.
- options:
 - filter: `f-{:name}-{:params}`

Url generation / parsing is a little bit tricky as you need your own url generators. PopKey supports vanilla + custom urls.

**Comment by banks** [comment]
@masom interesting thanks. That would probably be our next solution if it weren't for the fact that we can just have our caching proxy decode urls safely anyway without an extra layer of processing. It works for us as we know we never have encoded chars in our source image URL. You might have noticed we have a few custom filters already for "knowing" where the origin is - it's not explicitly encoded in our URL.

I guess the only clean long-term solution for thumbor generally might require changing URL format and would be a big migration for existing users when it's released.

**Comment by masom** [comment]
> I guess the only clean long-term solution for thumbor generally might require changing URL format and would be a big migration for existing users when it's released.

Yep. One way to approach this would be to support both formats in a `mixed_url_parser` and to also let people chose the format generated by the different libraries.

**Comment by okor** [comment]
Between having two ways of doing things and a single way to doing things, I'd say choose the single way. If we invalidate a bunch of cache to fix a real issue - then we can put sirens around the release notes. Folks who are running small setups probably won't notice (or read the changelog). Folks running huge clusters know the deal - massive cache invalidation is possible with a major version upgrade. And that's how I'd brand it - a major upgrade. I'm not super familiar with PIP but if someone was just doing a command line upgrade perhaps we could add some sort of a red all caps warning about the change.

That said, we should be *rock solid* in our confidence that all target clients will support the new encoding. Browser, email clients, rss feeds, wall gardens (facebook instant articles, whatever apple calls it, the new google thing). All the things. It seems possible that any change to encoding could result in weird gotchas.

**Comment by masom** [comment]
Yep, this is why I'm proposing to use a format with no special chars and also support old urls.

**Comment by okor** [comment]
I hate the idea of supporting two different formats but I have to admit it's a practical alternative to a global change. Any breaking changes could be brutal. If we could do it with minimal code stink then maybe we should give it a shot.

**Comment by banks** [comment]
FYI the "broken" link in the original post now works just fine. This was not a thumbor fix but we fixed out caching proxy in front of thumbor to normalise (decode) URLs before cache lookup as discussed.

**Comment by guilhermef** [comment]
@banks We've changed the way Thumbor deal with quoted url's, do you mind testing your scenario with the current master ?

**Comment by banks** [comment]
@guilhermef not sure when I will be able to get around to it, but it should be trivial for you to recreate with HMAC security on and at least one filter that uses parentheses enabled - just try encoding the url with python lib as normal, and then transform:  `'(' => '%28', ) =>  '%29', ',' => '%2c'`.

**Comment by guilhermef** [comment]
Thanks @banks, I'll create a test to validate this scenario.
