### ISSUE TITLE
Subtle issue with accented characters during encryption/decryption of url keys

### ISSUE THREAD

**Issue by ekoka** [thumbor/thumbor#602]
## Summary

 I have a file named with an accent (e.g. alizée.jpg). I url-encode the name with `urllib.quote()`. The url-encoded name now includes a code to represent the accented character (e.g. aliz%C3%A9e.jpg). Note that the code is in uppercase. I then generate a secure url from that quoted name with `CryptoURL.generate()`. When requesting the file from the browser however, Thumbor receives the name with the quoted character in lowercase (aliz%c3%a9e.jpg) and tries to calculate the key based on that, which results in an error 400.
## More details

``` python
from libthumbor import CryptoURL
import urllib

crypto = CryptoURL('my_secure_key')

# the file we want to serve
url = u"alizée.jpg"
utf8_encoded = url.encode('utf8')
url_encoded = urllib.quote(utf8_encoded)
# note the uppercase url-encoded character
print(url_encoded) # aliz%C3%A9e.jpg
# the key is calculated based on the url_encoded string
secure_url = crypto.generate(image_url=url_encoded, old=False)
print(secure_url) # /iXTJF_L7QewKS3PgWEKcYeTFAUg=/aliz%C3%A9e.jpg
```

That `secure_url` is what is provided to the browser and looking at the Firefox console it seems to be what is also sent back to the server. However, there seems to be an issue somewhere between Tornado or possibly a proxy, where upon reception of the request by Thumbor, that url has become this:

`/iXTJF_L7QewKS3PgWEKcYeTFAUg=/aliz%c3%a9e.jpg`

Note the now lowercased url-encoded characters. 

This results in the calculation of the key not matching the original key.

I propose as an improvement that the decryption step be done after url-decoding the path (i.e. after the conversion from '%c3%a9' to the more friendly utf8 '\xc3\xa9'). It removes the ambiguity between the url format originally provided to `CryptoURL` when generating the key, and the one later received by Thumbor when decrypting it.

I'm not sure if the culprit in my case is Tornado or the library it uses to parse the request, but in different scenarios it could be anything that can write to the request before it reaches Thumbor. For instance some browser that, after a quick copy-paste of http://myserver.xyz/alizée.jpg in the address bar, decides to request it as http://myserver.xyz/aliz%c3%a9e.jpg, instead of the expected http://myserver.xyz/aliz%C3%A9e.jpg. 

I think a further improvement would be to internally work with UTF-8, but simply ask for unicode at the API level (e.g. `crypto.generate(u'alizée.jpg')`).

``` python
crypto.generate(u'alizée.jpg')
# (1) encodes in utf8
# (2) then generates the key and secure url
# (3) then url-encodes and returns
```

When receiving the request from the browser

``` python
'/<KEY>/aliz%C3%A9e.jpg'
# (1) url-decode the path 
# (2) calculate key from decoded string and compare with provided <KEY>
```

**Comment by ishirav** [comment]
I have similar problems with image paths containing Hebrew Unicode characters, and even blank characters.

**Comment by heynemann** [comment]
Is this still an issue (hope not since this is from 2015)?

If you have any further questions on this issue, please reopen it.

**Comment by LuigiCNM** [comment]
Still not working with accents, for example if I try to get /imagem/579x387/100/public/blog/2018/11/Patrick-Blanc-Green-Wall-Muse**é**-Du-Quai-Branly-Paris-1.jpg, i got 404 error.
