### ISSUE TITLE
PNG bomb vulnerability

### ISSUE THREAD

**Issue by gi11es** [thumbor/thumbor#604]
![PNG bomb file](https://cloud.githubusercontent.com/assets/487183/11267360/394eb86c-8eab-11e5-922b-f8e779607f15.png)

PIL actually detects the bomb, but Thumbor crashes anyway:

```
vagrant@mediawiki-vagrant:~$ sudo /srv/thumbor/bin/python /srv/thumbor/bin/thumbor -c /etc/thumbor.conf
/srv/thumbor/local/lib/python2.7/site-packages/PIL/Image.py:2261: DecompressionBombWarning: Image size (50625000000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  DecompressionBombWarning)
vagrant@mediawiki-vagrant:~$ 
```
Having a configurable source megapixel limit would work around that problem.

**Comment by gi11es** [comment]
FYI I'm working on an attempt to fix this, I'm just fighting my way through tests setup, as my other issue reports would have hinted by now :)

**Comment by masom** [comment]
`sudo /srv/thumbor/bin/python` might also be a good idea to not run thumbor as root.
