### ISSUE TITLE
"make test" dependencies

### ISSUE THREAD

**Issue by gi11es** [thumbor/thumbor#607]
When running "make test", the following dependencies are required and only manifest themselves through errors mid-test:

- pyvows
- a running redis instance
- tornado-pyvows
- gifsicle
- coverage

It's not very graceful to discover those dependencies that way, having to decipher errors.

As an aside, I find the need for a running redis instance a bit questionable. What are the tests doing with it? Are they writing to it?

**Comment by banks** [comment]
Presumably for testing [Queued detectors](https://github.com/thumbor/thumbor/blob/08ac6fb07c2b7a20e12e3f4814777c9c372dfb0e/thumbor/detectors/queued_detector/__init__.py)

**Comment by guilhermef** [comment]
@gi11es `make setup` should install all the python test dependencies.
The only ones that will be missing are: redis and gifsicle

**Comment by gi11es** [comment]
Thanks, I did miss the "make setup" step, the message it displays at the end:

```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
>>>>>>>>>>>>>>> MAKE SURE GIFSICLE IS INSTALLED IF RUNNING TESTS <<<<<<<<<<<<<<
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

Should probably also mention the need to have a redis instance running (and not just having redis installed).

**Comment by guilhermef** [comment]
`make test` starts a Redis instance: https://github.com/thumbor/thumbor/blob/master/Makefile#L19

**Comment by gi11es** [comment]
Ah, I stand corrected, sorry for the noise!

**Comment by guilhermef** [comment]
No problem man ;)

**Comment by masom** [comment]
> As an aside, I find the need for a running redis instance a bit questionable.

The redis instances is used for the redis_storage tests. That storage is being moved out of the main thumbor repo. Same thing used to happen for MongoDB.
