### ISSUE TITLE
Several copyrighted images in source code

### ISSUE THREAD

**Issue by gi11es** [thumbor/thumbor#610]
I've spotted a logo, celebrities portraits, a gif from a movie, etc. used for the tests. All of which are certainly copyrighted and shouldn't be part of thumbor's source code.

I suggest switching all of those copyrighted images to openly licensed ones, with proper attribution.

**Comment by guilhermef** [comment]
I agree, but most of them are used to test image detection, so we should be careful

**Comment by sbaechler** [comment]
There is also an animated gif in the root folder: https://github.com/thumbor/thumbor/blob/master/60a48000-0198-11e4-978c-f1a9f360fa11.gif. I believe this got there accidentally.

**Comment by gi11es** [comment]
I'm going to have to tackle this soon, because the thumbor source code won't get accepted into debian with non-free images. Which test images are openly licensed, and who's the copyright owner for them? So that I don't re-create all test images if some are fine licensing-wise.

**Comment by guilhermef** [comment]
I'm not sure most times we've just copied without searching for it's license

**Comment by gi11es** [comment]
Alright, then, I'll just recreate them all from scratch.
