### ISSUE TITLE
404 Error When retrieving images with %20 in URL

### ISSUE THREAD

**Issue by ahmadimt** [thumbor/thumbor#617]
I am getting below error while access urls with %20

2015-11-26 06:11:34 tornado.access:WARNING 404 GET /unsafe/http://res.cloudinary.com/culture-machine/image/upload/v1445935626/alif%20laila/alif8.jpg (127.0.0.1) 446.84ms

**Comment by guilhermef** [comment]
@ahmadimt It should be working on master now: https://github.com/thumbor/thumbor/commit/1feff2a733e0a863584b483e9261c4aaa1929b25

**Comment by ahmadimt** [comment]
@guilhermef Thanks for the update.However, for getting these changes I need to build it from source and my current installation is from Ubuntu ppa. Is there anyway to incorporate it in my current installation.

**Comment by guilhermef** [comment]
@ahmadimt Which version are you using ?

**Comment by ahmadimt** [comment]
@guilhermef It is working from master... Also, Thanks a lot for fixing it in such short period of time. :+1:  
I am using Thumbor v5.2.1.

**Comment by gabn88** [comment]
I think I have a similar question but then with %3A, see https://github.com/thumbor/thumbor/issues/637. Would this also be solved by this fix? I am already using 5.2.1, so I guess not?

**Comment by guilhermef** [comment]
@gabn88 Are you quoting the url before generating the signed url ?

**Comment by gabn88** [comment]
My urls are unquoted.

However if I try quoting, the last ' is transformed to %27 because it is inside the get query paramaters of the Amazon key.

A.k. thumborurl.com/fit-in/150x150/'myfile.png?Signature=06...q%3D&Expires=17...21&AWSAccessKeyId=H...JQ%27
is what it becomes then.

**Comment by guilhermef** [comment]
Sorry, by quote, I mean:
```
import urllib2
urllib2.quote('https://domain.com/my-image.jpeg')
'https%3A//domain.com/my-image.jpeg'

**Comment by gabn88** [comment]
Wow, it works!
Took me hours and I still couldn't find the issue! Thank you so much!

Just for anyone else struggling with this, the url looked like this in the end:

mythumbor.com/bX..secret..Sg=/fit-in/192x192/https%3A//myfile-withtime%252018%253A18%253A29.png%3FSignature%3Did..thesig..Ozo%253D%26Expires%3D14..theexp..21%26AWSAccessKeyId%3DA..theAccessKeyJQ
