### ISSUE TITLE
Smart mode and watermark not handling URL without extension

### ISSUE THREAD

**Issue by TwanoO67** [thumbor/thumbor#619]
Hello guys,

Our website is using Images which are hidden behind ID and so our URLs doesn't provide the extensions of the file (but the mime-type is well formed) because we don't know it at that moment (and don't want to serve an "image/png" with a .jpg extension...).

For exemple "mysite.dn/images/getImage/IDSTRING"
would respond a correct image, with the correct mime-type.

But if i try to pass it to Thumbor some filters doesn't work.

For example, this would work:
http://myThumbor.dn/unsafe/300x300/smart/mysite.dn/url-with-extension.jpg

But this, would give me a cropped image, without smart detect
http://myThumbor.dn/unsafe/300x300/smart/mysite.dn/url-without-extension

And if I'm using those type of URL in a watermark filter, It would event get me an error 500:
http://myThumbor.dn/unsafe/300x300/smart/filters:watermark(mysite.dn/url-without-extension,0,0,50)/mysite.dn/url-with-extension.jpg

I think it's something related to OpenCV... But it could also be related to the url parsing who need a "point" or else...

**Comment by masom** [comment]
Hi @TwanoO67 

The url shortener capabilities override the thumbor url in a similar fashion. The request url is overwritten with the database value and thumbor keeps operating as normal.

Take a look at: https://github.com/thumbor-community/shortener/blob/master/tc_shortener/handlers/shortener.py

**Comment by TwanoO67** [comment]
Hi @masom 

Thank you for your answer.

It seems that the issue was coming from my test image, and not related to the url:

So for the smart mode, this image is not working
http://images.charentelibre.fr/26/11/2015/565723c97971bb8469064a0f/a.jpg

And this image is:
http://images.charentelibre.fr/26/11/2015/565723c97971bb8469064a0f/default/b.jpg

Both are the same size, and image data, but the second one is passed through Imagick ( setBlob, getBlob) without modification.

So I think that the original image as some kind of problem that crash the smart mode, and that Imagick do a sort of cleaning.

So maybe it could be related to IPTC/EXIF or other metadata?
( My image knowledge doesn't help me to investigate more than that...)

**Comment by TwanoO67** [comment]
Furthermore,

The Watermark part is a real "extension" issue.
If I use "filter:watermark(url-without-extension,0,0,100)" I'm always getting an 500 error

**Comment by heynemann** [comment]
Any progress here?

Since this has been open since 2015, I'm closing it.

If you have any further questions on this issue, please reopen it.
