### ISSUE TITLE
make thumbor server listen on next available port if already binded

### ISSUE THREAD

**Issue by dhardy92** [thumbor/thumbor#623]
if port specified or default (8888) is already bind, try 8889 (then 8890, ...)
This can make thumbor runing several instance with the same configuration.
Limit it with a range size ?

Use case : Using http://supervisord.org/ I now defined 4 configurations one for each port of my 4 running instances. I may set only one config file and set ```numprocs: 4```

my load balancer is configured to manage the range of port.

**Comment by gi11es** [comment]
You can already do that by starting thumbor on different ports, pointing to the same configuration. Use the -p option, like so:

`thumbor -p 8889`

Imho this sounds like something that can be created around thumbor, given that the -p option already exists.

**Comment by dhardy92** [comment]
yes this is my point I need to change a switch to do this. 
I would like to run the same command with the same config as many time as I want and this make a range of port available for thumbnailing with a loadbalancer

**Comment by ad-m** [comment]
''''
[program:thumbor]
command=thumbor --port=800%(process_num)s --conf=/etc/thumbor800%(process_num)s.conf
process_name=thumbor800%(process_num)s
numprocs=4
'''
is enough, so :-1: won't fix

**Comment by dhardy92** [comment]
nice, like it ☺

**Comment by ad-m** [comment]
Read docs please https://github.com/thumbor/thumbor/wiki/Hosting

**Comment by dhardy92** [comment]
actually did it a long time ago, even wrote an other part, and forgot this trick. sorry for disturb.
