### ISSUE TITLE
file changed on fresh checkout

### ISSUE THREAD

**Issue by phoet** [thumbor/thumbor#624]
when forking the repo on OSX 10.10.5 with git 2.6.3

i'm getting a changed file:

```
± |master ✗| → git st
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	"tests/fixtures/images/alabama1_ap620\303\251.jpg"
```

i assume it's because of the accent in the filename, but i could not find a matching git issue. anyone else experiencing this?

**Comment by masom** [comment]
Experiencing the same issue. Tests are also failing because the file doesn't seem to resolve on OS X

**Comment by heynemann** [comment]
The issue here is that we need a file with an unicode char and linux and mac treat it differently... Any ideas?

**Comment by phoet** [comment]
the filename of a none unicode named file could be modified in the test?
