### ISSUE TITLE
Quality filter not working with Thumbor engine

### ISSUE THREAD

**Issue by TwanoO67** [thumbor/thumbor#628]
Hello Team,

When installing thumbor with this conf:
ENGINE = 'thumbor.engines.pil'

the filters "quality" doesn't change the size of the produced file.

Using this engine, the filter work as expected
ENGINE = 'opencv_engine'

(tested on several Thumbor instance in version 5.0.0, 5.0.6, 5.1.0 and 5.2.1 ) 

Regards,
Antoine

**Comment by guilhermef** [comment]
@TwanoO67 Did you enable the quality filter on you thumbor.conf ?
Because it seems to work: http://thumbor.thumborize.me/unsafe/filters:quality(2)/http://img-9gag-fun.9cache.com/photo/am9qL7j_700b.jpg

**Comment by TwanoO67** [comment]
Hello @guilhermef 

In my config file, the FILTERS tab is always commented, so in default, all filters seems activated.
The only difference in my installation, is using the thumbor engine or the opencv engine.
