### ISSUE TITLE
Image optimization

### ISSUE THREAD

**Issue by dkhabarov** [thumbor/thumbor#631]
Hi.
![google page speed](http://storage2.static.itmages.ru/i/15/1224/h_1450945013_4378390_cb30a255da.png)

Tell me please how to make optimization of pictures on thumbor? I tried to connect thumbor.optimizers.jpegtran but that does not give effect it.

**Comment by masom** [comment]
You could use the quality filter: `quality(80)` would probably be a good start. Changing the quality value will compress the image.

**Comment by heynemann** [comment]
Jpegtran itself (as @masom pointed out) won't do any magic (or at least not a lot of it) by itself.

Closing this as I think it has been properly adressed.
