### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by sbaechler** [thumbor/thumbor#642]
Please start documenting the source code with PyDoc.
It would really help other developers working on the project.  The first priority should be the `handlers.__init__.py` and `handlers.imaging.py` modules. Most of the code is async and the callbacks are all over the place.

Some of the code is documented using the markdown syntax so it would make sense to keep that.

**Comment by heynemann** [comment]
Sure, whenever I touch the code I`ll try to add docs to it.
