### ISSUE TITLE
Thumbor breaks on latest master for signed urls.

### ISSUE THREAD

**Issue by gabn88** [thumbor/thumbor#644]
Today I tried to upgrade thumbor to the latest git master (pip install git+git://github.com/thumbor/thumbor.git) and then the thumbnail creation breaks completely for signed urls.

It probably has to do with the fact that I have urls like:

https://xxxxxx.s3.amazonaws.com/xxxxxxx.png?Signature=testestset%3D&Expires=1453753437&AWSAccessKeyId=testestest

which are broken in the latest git version with the default http_loader and pre-signed urls.

The urls are called like:

https://mythumborinstance/makeitsafe=/fit-in/192x192/https%3A//xxxxxxxx.s3.amazonaws.com%3A443/xxxxxxx.png%3FSignature%3Dtestestest%253D%26Expires%3D1453753437%26AWSAccessKeyId%3Dtestestest.

In the latest pypi release those urls are working fine, but when upgrading to the latest git master it breaks and the amazon url gives back forbidden.

Although I understand that it is not the most elegant way of displaying protected thumbnails this way has some advantages, such as not requiring another call the the authentication backend. I really like to keep using this, but I also need the latest reorientation fix on the master ;)

**Comment by guilhermef** [comment]
@gabn88 we had the same issue at Globo, I'm trying to fix this right now.

**Comment by guilhermef** [comment]
@gabn88 This https://github.com/thumbor/thumbor/commit/2c280ae09a3816a5d68bce92805672f6c3e4efa3 should fix this problem.

**Comment by gabn88** [comment]
thanks!
