### ISSUE TITLE
Clean custom urls and caching

### ISSUE THREAD

**Issue by webffo** [thumbor/thumbor#651]
Hi,
my current setup requires me to load the images from a web server using http. I have tried it with the default http loader and it works, but I see some problems with that.

1) The url structure 
The current schema includes , besides thumbor stuff, the protocol+domain+uri, which is pretty clear, because it needs to fetch the image somehow. For me the protocol and domain does not change so it would be great to predefine that in the loader.

I've seen somebody else posting that he solved the problem with base64 encoding, but that would create unnecessary long urls. 

2) Size Alias
It would be great to have an alias for the sizes, like xxl, xl, etc and map that to a widthxheight, like openross does. You have thought about signing the url in order to avoid dos attacks. Additionaly it would be great to have /xl/ in the url than 1920x1280 etc.

3) Is there an execution plan somewhere available (like for varnish: http://blog.zeit.de/dev/files/2015/02/vcl.png ), I'm interested in how the caching works and if there is an automatic invalidation or I need to remove old versions myself. 

What did you do for scaling your image deliver? Is there a way to put cloudfront or any other cdn upfront and does it (theoretically) make sense? 

By the way, I should mention that I have never written a line of python, although I am educated in cs.

**Comment by guilhermef** [comment]
@webffo you can create a custom http loader that uses your domain, and right now you don't need to set the protocol, you can just use domain+uri.

There's already a discussion on size alias: #467 

We highly recommend you to use a CDN in front of your service,
just remember to whitelist the Accept header if you're planning o use the AUTO_WEBP feature.

**Comment by webffo** [comment]
Hi, thank you for your answer.
I will try to create a custom http loader, but as I am completely unfamiliar with python and python syntax, I wanted to avoid that. Someone here (in another issue I can't find anymore) stated that he has created a proxy written in go which does that url rewriting and he may publish it, what obviously did not happen (yet) so I thought maybe someone else is using such a setup.  From another perspective I don't want to have one more component which could fail, thus it's probably better with thumbor loader.

Does the required size come from the loader or is the loader invoked only if a cache hit misses? If the loader parses the size, #467 could be done there.

Thank you for the hint regarding CDN, I will try it as setting it up is probably easier than creating some custom load balancing and ensuring high availability.

**Comment by guilhermef** [comment]
You don't need to rewrite the entire http_loader, you just need to append your domain before the request.
the required size is parsed before hitting the loader, and the size is used on the signer.
The loader is just called if there's no cache on the result_storage.

**Comment by masom** [comment]
To prevent ddos thumbor uses signed urls. You application uses a shared secret with thumbor to generate a valid url to an image. Sizes, filters, etc are part of that signature, preventing malicious users from requesting many different options.

The loader itself is acollection of stateless methods used to load an image from given source when there is a cache miss on the storage.

In your case, a simple line of code can add the domain+path prefix to your images. This can be done by using the http loader methods as a base.

Your app would sign urls without the prefix, allowing thumbor to validate them at the front controller (tornado handler).

**Comment by webffo** [comment]
Thank you for the details, I'll try it and maybe we also get some more info in the other issues.
