### ISSUE TITLE
Installed thumbor not working

### ISSUE THREAD

**Issue by asolenzal** [thumbor/thumbor#654]
Hi I have installed thumbor correctly with no errors or warnings.

Now after install I i try to exec thumbor from the console I get the following error:

Traceback (most recent call last):
  File "/bin/thumbor", line 7, in <module>
    from thumbor.server import main
  File "/usr/lib/python2.7/site-packages/thumbor/server.py", line 22, in <module>
    from thumbor.console import get_server_parameters
  File "/usr/lib/python2.7/site-packages/thumbor/thumbor/console.py", line 14, in <module>
    from thumbor import __version__, __release_date__
ImportError: cannot import name __release_date__

**Comment by masom** [comment]
Are did you install thumbor and how are you trying to launch it?

**Comment by asolenzal** [comment]
I have installed it using pip, my python version is 2.7.5 and the OS is CentOS 7. 

After install I just wrote "thumbor" on a ssh console. The same process that I made on my Mac. In CentOS the error, on the Mac works as expected.

**Comment by masom** [comment]
Something weird happened while installing thumbor.

`"/usr/lib/python2.7/site-packages/thumbor/thumbor/console.py"` should not be two levels deep within the thumbor structure.

**Comment by asolenzal** [comment]
I will reinstall it and post the full output of the installation process.

**Comment by asolenzal** [comment]
[root@mail tmp]# pip install thumbor
Collecting thumbor
Requirement already satisfied (use --upgrade to upgrade): pexif<1.0,>=0.15 in /usr/lib/python2.7/site-packages/pexif-0.15-py2.7.egg (from thumbor)
Requirement already satisfied (use --upgrade to upgrade): derpconf>=0.2.0 in /usr/lib/python2.7/site-packages/derpconf-0.7.3-py2.7.egg (from thumbor)
Requirement already satisfied (use --upgrade to upgrade): Pillow<3.0.0,>=2.7.0 in /usr/lib64/python2.7/site-packages (from thumbor)
Requirement already satisfied (use --upgrade to upgrade): pycurl<7.20.0,>=7.19.0 in /usr/lib64/python2.7/site-packages (from thumbor)
Requirement already satisfied (use --upgrade to upgrade): libthumbor in /usr/lib/python2.7/site-packages/libthumbor-1.3.1-py2.7.egg (from thumbor)
Requirement already satisfied (use --upgrade to upgrade): futures in /usr/lib/python2.7/site-packages/futures-3.0.4-py2.7.egg (from thumbor)
Requirement already satisfied (use --upgrade to upgrade): tornado<5.0.0,>=4.1.0 in /usr/lib64/python2.7/site-packages (from thumbor)
Requirement already satisfied (use --upgrade to upgrade): statsd>=3.0.1 in /usr/lib/python2.7/site-packages/statsd-3.2.1-py2.7.egg (from thumbor)
Requirement already satisfied (use --upgrade to upgrade): python-magic>=0.4.3 in /usr/lib/python2.7/site-packages/python_magic-0.4.10-py2.7.egg (from thumbor)
Requirement already satisfied (use --upgrade to upgrade): pyCrypto>=2.1.0 in /usr/lib64/python2.7/site-packages (from thumbor)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/site-packages (from derpconf>=0.2.0->thumbor)
Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/lib/python2.7/site-packages (from tornado<5.0.0,>=4.1.0->thumbor)
Requirement already satisfied (use --upgrade to upgrade): backports-abc>=0.4 in /usr/lib/python2.7/site-packages (from tornado<5.0.0,>=4.1.0->thumbor)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /usr/lib/python2.7/site-packages (from tornado<5.0.0,>=4.1.0->thumbor)
Requirement already satisfied (use --upgrade to upgrade): singledispatch in /usr/lib/python2.7/site-packages (from tornado<5.0.0,>=4.1.0->thumbor)
Installing collected packages: thumbor
Successfully installed thumbor-5.2.1
[root@mail tmp]# thumbor
Traceback (most recent call last):
  File "/bin/thumbor", line 7, in <module>
    from thumbor.server import main
  File "/usr/lib/python2.7/site-packages/thumbor/server.py", line 22, in <module>
    from thumbor.console import get_server_parameters
  File "/usr/lib/python2.7/site-packages/thumbor/thumbor/console.py", line 14, in <module>
    from thumbor import __version__, __release_date__
ImportError: cannot import name __release_date__

**Comment by masom** [comment]
It would be a good idea to attempt the installation within a python virtualenv to prevent conflicts with system packages.

**Comment by asolenzal** [comment]
Installing thumbor on a virtualenv inside my server bypasses the previous error, I get new errors that I can solve, errors related to filter importing.
Thanks for the virtualenv suggestion. I will close now
