### ISSUE TITLE
Steps to produce `AttributeError: 'module' object has no attribute 'CV_P2GRAY'`

### ISSUE THREAD

**Issue by hus787** [thumbor/thumbor#657]
`DETECTORS=['thumbor.detectors.feature_detector','thumbor.detectors.face_detector']`

1.This request just won't return `curl http://192.168.99.100:28765/unsafe/512x512/smart/www.opteam.fi/wp-content/themes/brbr/img/logo_fb.png > /dev/null`
2. Make more than one simultaneous/quick requests with `curl http://192.168.99.100:28765/unsafe/512x512/smart/http://img.vandaag.be/tmp/450/350/r/articles/201101131006-1_europese-commissie-lidstaten-moeten-meer-bezuinigen.jpg > /dev/null`. Thumbor will throw:

```
2016-02-08 17:07:39 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/src/app/src/thumbor/thumbor/transformer.py", line 166, in do_smart_detection
    detectors[0](self.context, index=0, detectors=detectors).detect(self.after_smart_detect)
  File "/usr/src/app/src/thumbor/thumbor/detectors/feature_detector/__init__.py", line 31, in detect
    convert_mode = getattr(cv, 'CV_%s2GRAY' % image_mode)
AttributeError: 'module' object has no attribute 'CV_P2GRAY'
```
PS: When the container/thumbor starts the following gets printed:

```
libdc1394 error: Failed to initialize libdc1394
```

**Comment by sbaechler** [comment]
This looks like a bug. The png image has indexed colors. OpenCV as the color transform matrices RGB2GRAY and RGBA2GRAY. 

This has been fixed already in a current version of Thumbor which uses the image engine (and therefore Pillow) to do the conversion.

For your issue, just convert the image to 24 bit or 32 (with alpha) and the error should go away.

**Comment by guilhermef** [comment]
This won't happen on 6.0.
