### ISSUE TITLE
[GIF] Thumbor spawning computer-crashing gifsicle processes

### ISSUE THREAD

**Issue by mcoenca** [thumbor/thumbor#658]
Under certain conditions I am currently investigating, thumbor spawns gifsicle processes that steal all my CPU and memory, most of the time never timeout, and spawn back again when they do (Who said zombies ?). 

This lock send all subsequent Thumbor requests to "Python: Cannot Allocate Memory" black hole, and i need to manually kill gifsicle zombies and restart everything to go back to normal.

Here is a look at /top when this happens

![2 gifsicle from httploader taking 50% CPU each](http://i.imgur.com/xBZhqXF.png)

My setup: 4 thumbor processes behind nginx, 2 http loader, 2 aws loader.

Right now, I have been able to reproduce the bug when I use httploader on this gif with any kind of resizing (origxorig works).
 It's a very simple gif with only one frame from http://www.lalouver.com/html/gallery-history-images/logo.gif 

![Buggy gif when loaded through httploader](http://www.lalouver.com/html/gallery-history-images/logo.gif)

Sometimes I get an according message error in thumbor error log. It ends like this
`....
packages/thumbor/transformer.py", line$
    self.auto_crop()
  File "/usr/local/lib64/python2.7/site-packages/thumbor/transformer.py", line$
    self.engine.crop(crop_left, crop_top, crop_right, crop_bottom)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/engines/gif.py", line$
    self.update_image_info()
  File "/usr/local/lib64/python2.7/site-packages/thumbor/engines/gif.py", line$
    self.image_size = size.groups()[0].split('x')
AttributeError: 'NoneType' object has no attribute 'groups'`

I've checked the source code, this is where you use a regex search on `gifsicle --info` to extract the gif size. The python error comes whenever the regex has not found anything. 

It's weird because when I download directly the gif on my server with `curl --output buggy.gif http://www.lalouver.com/html/gallery-history-images/logo.gif` and analyze it with `gifsicle --info buggy.gif` 

I get the following answer, which should go perfectly fine in the python regex search : 

`* buggy.gif 1 image
  logical screen 230x116 \b global color table [8] \b background 6 \b extensions1 \b + image #0 230x116 transparent 6`

I am setting up a local thumbor environnement from the source to be able to debug further python and see if I can reproduce. 
If somebody has encountered something similar or have some tips about why gifsicle doesn't stop, LMK.

**Comment by guilhermef** [comment]
@mcoenca This error still happens ?

**Comment by mcoenca** [comment]
I havent taken the time to build a local debugging environment, and just changed the gif image to be displayed in order to make my app work again fast... It's bad I know. 

@guilhermef is there a new thumbor version for me to test this bug again ?

**Comment by guilhermef** [comment]
We've released the version 6.0.
It should fix this error.

**Comment by rmens** [comment]
Having this issue too. Thumbor 6.2.0 on Debian 8 and Gifsicle 1.86.
![schermafbeelding 2016-12-21 om 23 14 10](https://cloud.githubusercontent.com/assets/6742496/21408110/73b20452-c7d3-11e6-8faf-72d2fbe5bf0e.png)

**Comment by masom** [comment]
@rmens Do you know which files causes Thumbor or some other lib to crash? Without that we can't really help you.

Thumbor builds upon many, many, other packages such as libjpeg, gifsicle, Pillow, etc.

**Comment by rmens** [comment]
@masom If i'm using this image ```https://cdn.onemorething.nl/uploads/2016/12/deejaygif.gif``` and set use gifsicle to false, thumbor starts using massive amounts of RAM. With gifsicle is true this doesn't occur.

**Comment by heynemann** [comment]
Is this still a problem?
