### ISSUE TITLE
Thumbor crashes when it encounters a corrupted JPG (segfault in libc-2.19.so)

### ISSUE THREAD

**Issue by aorra** [thumbor/thumbor#659]
We are running Thumbor 5.2.1. When we encounter a corrupted image (like the one attached at https://cloud.githubusercontent.com/assets/5318545/12918103/f28ae8fc-cf45-11e5-9240-46c593ef7c17.jpg), all the Thumbor processes running on the server crash. There is no error message in the log file of Thumbor. However, in the syslog I can see the following error.
`Feb  9 13:30:40 ip-10-165-67-165 kernel: [ 2076.179691] thumbor[14274]: segfault at 18 ip 00007fe1903aa845 sp 00007ffc6ebfe4a0 error 4 in libc-2.19.so[7fe19032c000+1bb000]
Feb  9 13:30:40 ip-10-165-67-165 kernel: [ 2076.357889] traps: thumbor[14250] general protection ip:7fd3329ae845 sp:7ffc05a0b600 error:0 in libc-2.19.so[7fd332930000+1bb000]`

The OS in question is Ubuntu 14.04.3 LTS.

Any ideas what could be causing this? We shouldn't of course have corrupted images in the first place. However, I do not think that the whole Thumbor process should crash because of this.

![e15e6fba0cbe4142ae2f65aa011a3af1](https://cloud.githubusercontent.com/assets/5318545/12918103/f28ae8fc-cf45-11e5-9240-46c593ef7c17.jpg)

**Comment by masom** [comment]
Hi @aorra 

I've tried loading the image on my machine ( OS X Yosemite ) and seems to work although the image itself is corrupted:

```
http://localhost:8888/unsafe/200x200/https://cloud.githubusercontent.com/assets/5318545/12918103/f28ae8fc-cf45-11e5-9240-46c593ef7c17.jpg
```
```
2016-02-09 09:26:07 thumbor:DEBUG Content Type of image/jpeg detected.
2016-02-09 09:26:07 tornado.access:INFO 200 GET /unsafe/200x200/https://cloud.githubusercontent.com/assets/5318545/12918103/f28ae8fc-cf45-11e5-9240-46c593ef7c17.jpg (127.0.0.1) 6.69ms
```

Since you are running a LTS version of ubuntu chances are the libraries shipped with it are ok.

Which engine are you using ( OpenCV / Pillow ) ?

I would attempt at re-installing Pillow from pypi after updating the system to use the latest packages `apt-get update && apt-get upgrade` and `pip install --upgrade pillow`.

**Comment by aorra** [comment]
Thanks @masom for the quick reply. We are using Pillow version 2.7.0. As you suggested I tried installing all the latest packages, and upgraded Pillow to 3.1.1. However, the error still persists.

I debugged the situation a bit more and detected that the Thumbor will crash only when we try to apply the sharpen filter (e.g. sharpen(0.2,0.5,true)) to the corrupted image. Any ideas how this crash could be avoided?

**Comment by masom** [comment]
Thanks for trying to upgrade Pillow and specifying the invalid filter.

@heynemann there is a good chance it's something in https://github.com/thumbor/thumbor/blob/9817a6ee7f44d594e58b54e11c10fac41564f390/thumbor/ext/filters/lib/wavelet_sharpen.c#L84

**Comment by guilhermef** [comment]
It seems to work on 6.0.

**Comment by aorra** [comment]
I actually tested this with Thumbor 6.0 and the issue still persists. The Thumbor process crashes when it tries to run the sharpen filter. Any chance of getting this fixed?

**Comment by xgt001** [comment]
➕ 1.
I still face this issue with 6.2.0. A process restart resolves this issue until it crashes again.
