### ISSUE TITLE
Just optimizing

### ISSUE THREAD

**Issue by khelll** [thumbor/thumbor#660]
Is there a way where we can do just a lossless compression? I have tried to set the QUALITY config to 100, but that resulted in 30% increase of the original file size.

**Comment by guilhermef** [comment]
@khelll you can set the quality to `'keep'`, and use the filter strip_icc().
example:
`http://localhost:8888/unsafe/filters:strip_icc()/s.glbimg.com/jo/g1/f/original/2016/02/15/20160215150949.jpg`

**Comment by khelll** [comment]
I tried `QUALITY = 'keep'`, and still the output image size is becoming bigger.

Here is the image for the reference:

https://khamsat-production.s3-eu-west-1.amazonaws.com/images/services/14094/0caca134da501b4508e0036fef812943.jpg

**Comment by guilhermef** [comment]
I've tried here, It went from 76.3KB to 68.8KB using QUALITY='keep'.

**Comment by khelll** [comment]
Worked, Thanks! 

I was looking at [stripping ICC](https://github.com/thumbor/thumbor/wiki/Strip-icc) info, and it mentions that there might be a loss of quality. I'm no expert here, but how much is saving from stripping it out?

**Comment by heynemann** [comment]
The [ICC Profile](https://en.wikipedia.org/wiki/ICC_profile) characterizes the colors of   the image. If you remove the reference profile, the colors will change (usually slightly).

That's what we refer to when saying quality will decrease. It's not compression related, but color related.

**Comment by sbaechler** [comment]
All browsers interpret images without an ICC profile as sRGB. Not all browsers have color management and support ICC profiles. The best thing therefore to do is to convert your image to sRGB when exporting them for the web. Then you can safely strip the ICC profile.

The quality and size of the jpeg output is determined by the libjpeg version that Pillow is compiled against.

**Comment by khelll** [comment]
Great it's clear now.

However I got this error when trying to optimize a jpeg image file that doesn't have the jpeg file extension:

```
"Cannot use 'keep' when original image is not a JPEG"
ValueError: Cannot use 'keep' when original image is not a JPEG
```

**Comment by heynemann** [comment]
That's definitely a bug... Sorry for that... We need to improve the checks for file types...

**Comment by guilhermef** [comment]
@khelll I'm trying to fix this error on thumbor, but I wasn't able to get this on master.
Can you post the image and the url you're trying to load ?

**Comment by khelll** [comment]
@guilhermef  

/unsafe/fit-in/800x800/http://suar-staging.s3.amazonaws.com/uploads/upload/RRy/o

**Comment by guilhermef** [comment]
@khelll That should be fixed on master.
https://github.com/thumbor/thumbor/commit/f8fa60c29033be1fddbc28980e897b1ca67a0e2b
