### ISSUE TITLE
RESULT_STORAGE = 'thumbor.storages.no_storage' does not work

### ISSUE THREAD

**Issue by cerber717** [thumbor/thumbor#663]
Trying to avoid storing the result at all. 
using this :
`RESULT_STORAGE = 'thumbor.storages.no_storage'`
Getting this error message :
`2016-02-12 23:47:14 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)

  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 63, in execute_image_operations
    result = yield gen.maybe_future(self.context.modules.result_storage.get())

  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 473, in wrapper
    future.result()

  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)

  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 461, in wrapper
    result = f(*args, **kwargs)

TypeError: get() takes exactly 3 arguments (2 given)`

**Comment by cerber717** [comment]
DISCLAIMER, I have zero python experience. not But I am trying to help.

I think the issue is that result_storage needs its own `no_storage` module because `storage` get function is using 3 arguments, and `result_storage` is using 2 arguments.

**Comment by heynemann** [comment]
Yep, this is a bug with thumbor. Mainly due to the fact that almost every single thumbor user uses result storage. I would advice you to use it as well. Even if you limit the amount of storage you want (i.e.: use RedisStorage and give redis a max memory of 2gb or something like that).

That does not excuse us from fixing it, though. Thanks a lot for your report and sorry for the issue.

**Comment by cartrdgeproduct** [comment]
> There's also a nostorage storage for debugging or benchmarking purposes.

I think it's important to preserve the 'nostorage' functionality for benchmarking purposes and debugging, as stated in the documentation. This is very helpful for instance, in evaluating the performance of the host hardware and degradation from virtualization layers. Like shopping for the right VM type at your vendor of choice.

**Comment by guilhermef** [comment]
@cerber717 You can create a PR with a no_storage for the result_storage.
Thumbor has 2 types of storage, the `thumbor.storage` that caches the result from the file before transformations and the `thumbor.result_storage` that caches the image after transformations.
The one you're using was not intended to be a result_storage.
To avoid storing, you should set 
```
RESULT_STORAGE = 'thumbor.result_storages.file_storage'
RESULT_STORAGE_EXPIRATION_SECONDS = 0
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH='/tmp'

```

**Comment by cerber717** [comment]
I have been fighting this for a number of hours now and it drives me crazy. no matter what I do it keeps trying to store that result on S3. for example if the image is in BUCKET/images/test.jpg, and this is the url - 'https://BUCKET/HASH/fit-in/218x218/smart/test.jpg` it would save the result photo in S3 with this path = BUCKET/images/https://BUCKET/HASH/fit-in/218x218/smart/test.jpg. 

if I use what @guilhermef suggested it does not store in /tmp (which is good !  ) but it still stores it in S3.

this is my thumbor config (I cut the non important stuff) : 
`

################################ Extensibility #################################

## The loader thumbor should use to load the original image. This must be the
## full name of a python module (python must be able to import it)
## Defaults to: thumbor.loaders.http_loader
LOADER = 'thumbor.loaders.http_loader'

## The file storage thumbor should use to store original images. This must be the
## full name of a python module (python must be able to import it)
## Defaults to: thumbor.storages.file_storage
STORAGE = 'tc_aws.storages.s3_storage'
STORAGE_BUCKET = ''
RESULT_STORAGE_BUCKET = ''


## The result storage thumbor should use to store generated images. This must be
## the full name of a python module (python must be able to import it)
## Defaults to: None

RESULT_STORAGE = 'thumbor.result_storages.file_storage'


## The imaging engine thumbor should use to perform image operations. This must
## be the full name of a python module (python must be able to import it)
## Defaults to: thumbor.engines.pil
ENGINE = 'thumbor.engines.pil'

################################################################################


################################# File Loader ##################################

## The root path where the File Loader will try to find images
## Defaults to: /tmp
FILE_LOADER_ROOT_PATH = '/data/loader'

################################################################################


################################# HTTP Loader ##################################

## The maximum number of seconds libcurl can take to connect to an image being
## loaded
## Defaults to: 5
HTTP_LOADER_CONNECT_TIMEOUT = 5

## The maximum number of seconds libcurl can take to download an image
## Defaults to: 20
HTTP_LOADER_REQUEST_TIMEOUT = 20

## Indicates whether libcurl should follow redirects when downloading an image
## Defaults to: True
HTTP_LOADER_FOLLOW_REDIRECTS = True

## Indicates the number of redirects libcurl should follow when downloading an
## image
## Defaults to: 5
HTTP_LOADER_MAX_REDIRECTS = 5

## Indicates whether thumbor should forward the user agent of the requesting user
## Defaults to: False
HTTP_LOADER_FORWARD_USER_AGENT = False

## Default user agent for thumbor http loader requests
## Defaults to: Thumbor/5.0.3
HTTP_LOADER_DEFAULT_USER_AGENT = 'Thumbor/5.0.3'

## The proxy host needed to load images through
## Defaults to: None
HTTP_LOADER_PROXY_HOST = None

## The proxy port for the proxy host
## Defaults to: None
HTTP_LOADER_PROXY_PORT = None

## The proxy username for the proxy host
## Defaults to: None
HTTP_LOADER_PROXY_USERNAME = None

## The proxy password for the proxy host
## Defaults to: None
HTTP_LOADER_PROXY_PASSWORD = None

################################################################################


################################# File Storage #################################

## Expiration in seconds for the images in the File Storage. Defaults to one
## month
## Defaults to: 2592000
STORAGE_EXPIRATION_SECONDS = 2592000

## Indicates whether thumbor should store the signing key for each image in the
## file storage. This allows the key to be changed and old images to still be
## properly found
## Defaults to: False
STORES_CRYPTO_KEY_FOR_EACH_IMAGE = False

## The root path where the File Storage will try to find images
## Defaults to: /tmp/thumbor/storage
FILE_STORAGE_ROOT_PATH = '/data/storage'

################################################################################


#################################### Upload ####################################

## Max size in Kb for images uploaded to thumbor
## Aliases: MAX_SIZE
## Defaults to: 0
UPLOAD_MAX_SIZE = 0

## Indicates whether thumbor should enable File uploads
## Aliases: ENABLE_ORIGINAL_PHOTO_UPLOAD
## Defaults to: False
UPLOAD_ENABLED = False

## The type of storage to store uploaded images with
## Aliases: ORIGINAL_PHOTO_STORAGE
## Defaults to: thumbor.storages.file_storage
UPLOAD_PHOTO_STORAGE = 'thumbor.storages.file_storage'

## Indicates whether image deletion should be allowed
## Aliases: ALLOW_ORIGINAL_PHOTO_DELETION
## Defaults to: False
UPLOAD_DELETE_ALLOWED = False

## Indicates whether image overwrite should be allowed
## Aliases: ALLOW_ORIGINAL_PHOTO_PUTTING
## Defaults to: False
UPLOAD_PUT_ALLOWED = False

## Default filename for image uploaded
## Defaults to: image
UPLOAD_DEFAULT_FILENAME = 'image'

################################################################################


################################ Result Storage ################################

## Expiration in seconds of generated images in the result storage
## Defaults to: 0
RESULT_STORAGE_EXPIRATION_SECONDS = 0

## Path where the Result storage will store generated images
## Defaults to: /tmp/thumbor/result_storage
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/tmp'

## Indicates whether unsafe requests should also be stored in the Result Storage
## Defaults to: False
RESULT_STORAGE_STORES_UNSAFE = False

################################################################################


############################## TC_AWS ##########################################
TC_AWS_REGION = 'us-west-2' # AWS Region

TC_AWS_STORAGE_BUCKET = 'xxxxxxxxxx' # S3 bucket for Storage
TC_AWS_STORAGE_ROOT_PATH = '/images' # S3 path prefix for Storage bucket

TC_AWS_LOADER_BUCKET = '' #S3 bucket for loader
TC_AWS_LOADER_ROOT_PATH = '' # S3 path prefix for Loader bucket

TC_AWS_RESULT_STORAGE_BUCKET = '' # S3 bucket for result Storage
TC_AWS_RESULT_STORAGE_ROOT_PATH = '' # S3 path prefix for Result storage bucket

# put data into S3 using the Server Side Encryption functionality to
# encrypt data at rest in S3
# https://aws.amazon.com/about-aws/whats-new/2011/10/04/amazon-s3-announces-server-side-encryption-support/
TC_AWS_STORAGE_SSE = False

# put data into S3 with Reduced Redundancy
# https://aws.amazon.com/about-aws/whats-new/2010/05/19/announcing-amazon-s3-reduced-redundancy-storage/
TC_AWS_STORAGE_RRS = False


# Enable HTTP Loader as well?
# This would allow you to load watermarks in over your images dynamically through a URI
# E.g.
# http://your-thumbor.com/unsafe/filters:watermark(http://example.com/watermark.png,0,0,50)/s3_bucket/photo.jpg
TC_AWS_ENABLE_HTTP_LOADER = False

TC_AWS_ALLOWED_BUCKETS = False # List of allowed bucket to be requested
TC_AWS_STORE_METADATA = False # Store result with metadata (for instance content-type)
################################################################################
`
in this configuration it is not storing results on the server, but it is still storing them on S3

**Comment by guilhermef** [comment]
It isn´t storing the result, it´s storing the loaded image.
You have to set this:
`STORAGE = 'thumbor.storages.no_storage'`

**Comment by heynemann** [comment]
That´s because of what storages and loaders do. I think you misunderstood
what they are for (or I do not understand your question).

A loader retrieves an original image. So if you want images to be loaded
from S3, then you should use a S3 Loader and not a storage.

A storage is used to store the result from the loader, so the next time a
request for that source image comes, you do not have to request it again
(potentially from a slow source).

A result storage stores the transformed image, after cropping, filters,
optimization, etc. This way you trade cpu cycles for storage space.

Which of them you use is up to you. A setup that only uses a S3 Loader is
perfectly ok. Just set both storages to no storage.

Very sorry for your experience so far. It's our fault that the docs do not
explain it properly.

Bernardo Heynemann
Gerente de Tecnologia - globo.com

**Comment by cerber717** [comment]
Thank you guys, I really appreciate the quick responses. 
I realised the difference between storage and loader, I changed my setting to this: 
`
LOADER = 'tc_aws.loaders.s3_loader'
STORAGE = 'thumbor.storages.no_storage'
TC_AWS_REGION = 'us-east-1' # AWS Region

TC_AWS_STORAGE_BUCKET = '' # S3 bucket for Storage
TC_AWS_STORAGE_ROOT_PATH = '' # S3 path prefix for Storage bucket

TC_AWS_LOADER_BUCKET = 'BUCKET' #S3 bucket for loader
TC_AWS_LOADER_ROOT_PATH = '/images' # S3 path prefix for Loader bucket

TC_AWS_RESULT_STORAGE_BUCKET = '' # S3 bucket for result Storage
TC_AWS_RESULT_STORAGE_ROOT_PATH = '' # S3 path prefix for Result storage bucket
`
Same bucket that was used in my previous config, I was using it as storage, its was loading the images from 'BUCKET/images' ( this is what confused me ) and storing them in BUCKET/images/PATH. 
Now I am using the loader and it not loading the images. 
I got this error: 
`2016-02-17 18:06:54 thumbor:WARNING ERROR retrieving image from S3 /images/10700529_970606069632018_6308605664490766430_o.jpg: {'ResponseMetadata': {'HTTPStatusCode': 404, 'HostId': 'bQE3kxs0A0HJpMzHr3b2Fwvn9SuF+sFttU6Liqw/DHfFVSkbJ8yKCMz/kXbqZabDFKKauzSoiYE=', 'RequestId': '2B1E43CFC279519E'}, 'Error': {'Message': 'The specified key does not exist.', 'Code': 'NoSuchKey', 'Key': '/images/10700529_970606069632018_6308605664490766430_o.jpg'}}`

Again I greatly appreciate your help. I hope we will figure this one out, and when we do I will share my config with extensive comments, so you can refer someone to it in the future.

**Comment by heynemann** [comment]
I'm not very familiar with the S3 Loader. Maybe @masom can help here?

**Comment by aoqfonseca** [comment]
Boto can't find you path in this bucket. Try take of "/"  in beginning of ROOT_PATH.

**Comment by cerber717** [comment]
Ok , everything is working fine!! Huge thanks guys ! 
I have the code for "thumbor/result_storages/no_storage.py" I will create the PR for it ! 
https://github.com/thumbor/thumbor/pull/669

**Comment by cerber717** [comment]
Bringing back this issue.
@guilhermef I went with your solution
`RESULT_STORAGE = 'thumbor.result_storages.file_storage'
RESULT_STORAGE_EXPIRATION_SECONDS = 0
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH='/tmp'
`
 and I can not say that is really working. A few days ago the server ran out of storage because /tmp folder was full with result images. I started digging and found that in `thumbor/thumbor/result_storages/file_storage.py 
def is_expired(self, path):
        expire_in_seconds = self.context.config.get('RESULT_STORAGE_EXPIRATION_SECONDS', None)

        if expire_in_seconds is None or expire_in_seconds == 0:
            return False

        timediff = datetime.now() - datetime.fromtimestamp(getmtime(path))
        return timediff.seconds > expire_in_seconds` 

the if `RESULT_STORAGE_EXPIRATION_SECONDS ` set to 0 it will never expere them (I want them to not be stored or atleast deleted after the processing ). which makes sense but, also if say `RESULT_STORAGE_EXPIRATION_SECONDS ` is set to `1` I think it will never delete the images either, because I did not find the part of the code that does the result deletion. Can someone confirm my findings ? 

My goal is to completely avoid storing the results, is it possible ?

**Comment by guilhermef** [comment]
@cerber717 are you the no_storage module ? 
```
RESULT_STORAGE = 'thumbor.result_storages.no_storage'
```

**Comment by kkopachev** [comment]
@guilhermef Yes, @cerber717 and I were using that. New `thumbor.result_storages.no_storage` works as expected. However, we decided to move to S3 storage, CDN caching was not enough. 

Regarding `thumbor.result_storages.file_storage`, clean up has to be done outside of thumbor.

**Comment by guilhermef** [comment]
Thanks @kkopachev

**Comment by nuschk** [comment]
@kkopachev I came here because I want to deploy thumbor behind a CDN, like you did, and thought it would be best to disable storage altogether. Might I ask, why was CDN caching not enough for you?

**Comment by kkopachev** [comment]
@nuschk We've seen a lot of queries even with CDN cache, so decided to store results in S3. Our CDN cache is set to 14 days, so that might be the issue. We store cuts on S3 for 60 days.
We also had nginx with 10 minutes caching in front of thumbor, in case of CDN dogpiling, but that hit us on disk performace. We are on EC2 with only ephemeral storage, and once in 2 days disk performance dropped 80 times. And since nginx cache was on disk, everything just stopped responding. So current setup is CDN (14d cache) + S3 storage (60 days ttl)

**Comment by nuschk** [comment]
@kkopachev Thanks for this very detailed information. Our setup will be a bit different though (gcloud LB/CDN + gke/kubernetes, no nginx), so I guess I'm going to try it first and see where it takes us.
