### ISSUE TITLE
Will the images uploaded in Thumbor File Storage expire ? If so, Can i make changes in config file for them to not expire ??

### ISSUE THREAD

**Issue by vishaalgc** [thumbor/thumbor#667]
I actually want the images in thumbor file storage to stay there and not be deleted automatically. So i just wanted to confirm once if they are permanent or not.

**Comment by heynemann** [comment]
They won't expire unless you specify an expiration. And even if they expire thumbor will not delete anything from your disk.

**Comment by vishaalgc** [comment]
Okay ... What is the name of the field in config that i should alter if i want to set the expiration ?

**Comment by heynemann** [comment]
https://github.com/thumbor/thumbor/wiki/Configuration#storage_expiration_seconds

**Comment by vishaalgc** [comment]
Thanks for the answer. And also i have installed thumbor using https://gist.github.com/okor/79c38cfb03b153bd4eb2 in 14.04 ubuntu .. 

Where can i find the thumbor.conf file so that i change upload_enabled to true. ?
