### ISSUE TITLE
image-uri format for uploaded images

### ISSUE THREAD

**Issue by mfilotto** [thumbor/thumbor#671]
Hi,
In the image Endpoint, what would be the `image-uri` format for an uloaded image 
`http://thumbor-server/hmac/trim/AxB:CxD/(adaptive-)(full-)fit-in/-Ex-F/HALIGN/VALIGN/smart/filters:FILTERNAME(ARGUMENT):FILTERNAME(ARGUMENT)/image-uri`
I can't find the proper URL format to filter images I uploaded.
Thanks for your help

**Comment by mfilotto** [comment]
Any idea ?

**Comment by guilhermef** [comment]
The image-uri will be on the location header of your upload response.

**Comment by mprzytulski** [comment]
after a lot of debugging it looks like `image-uri` for uploaded images should contain hash value and slug returned in `Location` header, so easiest way will be to strip `/image/` from original response.
Also slug can be changed.
I don't think that's the proper behaviour so I raised an issue: #693

**Comment by heynemann** [comment]
Commented on said issue.

If you have any further questions on this issue, please reopen it.
