### ISSUE TITLE
Add a configuration directive for custom DPI to be used when converting SVG to PNG

### ISSUE THREAD

**Issue by znerol** [thumbor/thumbor#674]
CairoSVG allows to specify the DPI value when [converting SVG to PNG](https://github.com/Kozea/CairoSVG/blob/4c3f4b9600ed7010fab2ac6726370a99eb889e2f/cairosvg/surface.py#L130). Let's introduce a configuration directive in order to allow users to control this value.

**Comment by sbaechler** [comment]
What is it supposed to do?

**Comment by znerol** [comment]
DPI = ratio between 1in and 1px, see help text of the cairosvg command line:

    $ cairosvg --help
    Usage: cairosvg filename [options]
    
    Options:
      --version             show program's version number and exit
      -h, --help            show this help message and exit
      -f FORMAT, --format=FORMAT
                            output format
      -d DPI, --dpi=DPI     ratio between 1in and 1px
      -o OUTPUT, --output=OUTPUT
                            output filename

**Comment by sbaechler** [comment]
So would this only apply to SVGs that have their size unit set to 'in' or 'cm'? 
Pretty much all SVGs that I came across had their size defined in pixels.

**Comment by znerol** [comment]
> So would this only apply to SVGs that have their size unit set to 'in' or 'cm'? 

Yes, indeed.

> Pretty much all SVGs that I came across had their size defined in pixels.

Problem is that those which come in units other than pixels tend to look like crap if you render them with 96 DPI (which is the CairoSVG default).

**Comment by guilhermef** [comment]
@znerol Can you make a PR ?
