### ISSUE TITLE
Video engine/optimizer

### ISSUE THREAD

**Issue by khelll** [thumbor/thumbor#678]
I need a very simple video engine/optimizer, kind of similar to the GIFV optimizer. My use case is simple:

- Load the file from HTTP url
- Generate a screenshot using FFmpeg, so it should it implement the `extract_cover()` filter mainly.
- Do normal operations on the cover above.
- Generate a video with some modifications using FFmpeg.

Is there a simple flow that I can use to let Thumbor do this?

**Comment by guilhermef** [comment]
I'm not sure that pillow support videos.
Em 25/02/2016 15:02, "Khaled alHabache" <notifications@github.com> escreveu:

**Comment by khelll** [comment]
Exactly, we need to skip pillow in such a case or apply it only on the cover image, not the raw video.

**Comment by guilhermef** [comment]
I think that's not thumbor responsibility, It only deals with images.
That's a whole new set of problems.
