### ISSUE TITLE
Omit part of url behind ? or %3F for the storages and result storages [feature]

### ISSUE THREAD

**Issue by gabn88** [thumbor/thumbor#680]
Since thumbor does not use this part, it can just as well be omitted.

This enables to store pre-signed (S3) keys in the resultstorage cache. See https://github.com/thumbor-community/aws/issues/55

**Comment by guilhermef** [comment]
I don't think this should be allowed on the default storage, it might result in a different asset.
@masom @heynemann ?

**Comment by masom** [comment]
It depends.

@gabn88 examples are actually invalid URIs.

```
https://mythumbsbucket.s3.amazonaws.com/MYSAFEURLKEY/fit-in/192x192/https%253A//mybucket.s3.amazonaws.com%253A443//SomeImage.png?Signature=SomeSignature&Expires=Sometime&AWSAccessKeyId=Somekey/webp```

The slashes and query string portion of the urls are part of a URIComponent and should be encoded.

If we want thumbor to ignore the query string as part of the source url then the storages need to check the request url and see if there is a query string they are interested in.

This also invalidates most upstream caches ( Varnish, CloudFront, etc. ).

Example with encoded path to image:
```http://thumbor/[token]/[operations]/http%3A%2F%2Fpath%2Fto%2Fimage.jpg%3Ftoken%3Dabc```

In this example the encoded query string is sent to the storages + upstream.

Example of unencoded query string sent to thumbor ( not the upstream  / storages):
```
http://thumbor/[token]/[operations]/http%3A%2F%2Fpath%2Fto%2Fimage.jpg?token=abc
```

In this case `token=abc` is the query string sent to thumbor itself, as intended by the HTTP RFCs.

**Comment by masom** [comment]
@guilhermef If I understand you correctly, we are saying the same thing.

The storage itself should not try to be intelligent and directly use the provided path to the asset.

**Comment by guilhermef** [comment]
@masom that's what I was trying to say, you've done it beautifully :)

**Comment by gabn88** [comment]
Thanks for the good explanation! :+1: 

However I have made a mistake when creating that post, I wanted to anonymize some things, but instead I copied the wrong stuff. I have updated it now to valid urls.

The point still stands I think?

**Comment by guilhermef** [comment]
@gabn88 that is valid only for your scenario. The best way to solve this is to use custom loaders and storages. We do it here at Globo, since we need more control over the image path.
You can inherit from the tc_aws and apply your logic to the normalize function.

**Comment by gabn88** [comment]
okay, thank you!
