### ISSUE TITLE
Omit SAFE key in resultstorage [feature]

### ISSUE THREAD

**Issue by gabn88** [thumbor/thumbor#681]
Make that, just like for the storage class, the resultstorage can omit the safe key when storing a file.

This enables that when requests come from different clients with different safe_url_keys, still the same image is found in the resultstorage cache.

There are many use cases for this.

Just to mention one: https://github.com/thumbor-community/aws/issues/55

**Comment by guilhermef** [comment]
That should be implemented on the tc_aws result_storage class, 
on file system and url(other than signed s3) scenarios, this behavior won't work.
