### ISSUE TITLE
GraphicMagic Crash on invalid free()

### ISSUE THREAD

**Issue by sumdog** [thumbor/thumbor#682]
So we're running a high volume instance of Thumbor and we occasionally see the following crash

```
*** Error in `/usr/bin/python': free(): invalid pointer: 0x0000000000e35778 ***
Magick: abort due to signal 6 (SIGABRT) "Abort"...
Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
```

We're using a version forked from commit 6ae666ca39 back in December. I'm not sure how far behind we are master. This is for a client I'm working for and I just kinda got here. If I can get some time, I'll attach a fuzzer and see if I can replicate it.

In any case the CPython wrappers for Graphic Magic seem to have a bug. It may or may not be a security issue. It is just on an invalid free (possibly a concurrency issue?) 

The other interesting thing is that Thumbor doesn't die after this error. (If it did, our containers would just restart it). The listening socket remains open. It seems like a thread doing the GraphicsMagick stuff is crashing and leaves the rest of the application in an inconsistent state.

**Comment by guilhermef** [comment]
We've solved a few bugs on the default Pillow engine to avoid seg fault.
Can you test this on the current master ?

**Comment by sumdog** [comment]
We're actually using GraphicsMagick as our backend; will try rebasing

**Comment by masom** [comment]
@sumdog The GraphicsMagick engine lives at https://github.com/thumbor/graphicsmagick-engine

I would try upgrading the GraphicsMagick library and rebuilding the python bindings and test the failing image.

**Comment by sumdog** [comment]
Never mind. It turns out our devs added some libExiv2 stuff and GraphicsMagick has a sig11 handler that was catching it. It's not coming from Thumbor or its dependencies, just in our custom branch.
