### ISSUE TITLE
IIIF support

### ISSUE THREAD

**Issue by gi11es** [thumbor/thumbor#684]
In would be nice to make Thumbor compatible with IIIF: http://iiif.io/ The standard is getting traction among public institutions.

**Comment by acdha** [comment]
This would be very nice for those of us in the cultural heritage space

**Comment by heynemann** [comment]
@gi11es can you elaborate on this? Little short on time to catch up. Is this still a "thing"?

Closing this for now. As soon as we get more understanding of this, we can reopen it.

**Comment by gi11es** [comment]
It's still a thing, its most interesting feature - beyond all the benefits of a standard - is the ability to support tiling of very high resolution images. This is something that's very useful when looking at archival content. You can check out a bunch of demos here: http://iiif.io/apps-demos/

**Comment by timrobertson100** [comment]
Time to revisit this? I see Zenodo have implemented it now for example.

Pan and zoom (similar to map tiles) and standardized thumbnailing are the two use cases we'd appreciate for dealing with specimen image data. [example here](https://www.gbif.org/occurrence/gallery?basis_of_record=PRESERVED_SPECIMEN&taxon_key=4342)
