### ISSUE TITLE
Thumbor installs Cython 0.22, scikit-image requires Cython 0.23

### ISSUE THREAD

**Issue by SapientGuardian** [thumbor/thumbor#685]
As of https://github.com/scikit-image/scikit-image/commit/e1c2ea29dd85b2207bbdc5d56c7139b125732b37 , scikit-image requires Cython 0.23, but Thumbor installs 0.22 in the makefile (https://github.com/thumbor/thumbor/blob/master/Makefile#L5), so installation fails.

Addressing #611 would prevent surprise breaking changes like this.

**Comment by guilhermef** [comment]
Thanks @SapientGuardian, fixed on https://github.com/thumbor/thumbor/commit/0e5a4083807d18901d28f313f4428e46faa4f505
