### ISSUE TITLE
Image Data deleted

### ISSUE THREAD

**Issue by vishaalgc** [thumbor/thumbor#688]
I have integrated thumbor in my production site. It was working fine but after some days suddenly when i tried to upload an image it threw a server error 500 and after some time i checked to see my image data folder in storage/thumbor there were no folders present and all my image urls were returning nothing. **what am i missing ?**

**Comment by masom** [comment]
Without more information it will be near impossible to help you debug the issue you are facing.

How did you setup thumbor? Which storage are you using?

**Comment by vishaalgc** [comment]
Im using the built-in file storage, followed up the same instruction as given. What im doing is, i managed to setup the thumbor server and by default the file storage path and result storage path were given to tmp/thumbor so i didnt change them. I started uploading images and the folders were generated accordingly in tmp/thumbor/storage, and i used the generated URLs in my applciations database.Everything was fine untill one day suddenly when i tried to upload an image my thumbor server threw 500 internal server error and after that i restarted my server and the data(folders) were gone in tmp/thumbor/storage which obviously led to receive No image when i load them with those urls present in database. So i didnt understand why the images were deleted from the storage. After a bit of research i saw this STORAGE_EXPIRATION attribute, set it to None today. Is it because my images were stored in tmp, that they were erased ?

**Comment by masom** [comment]
In linux / unix the `/tmp` folders are usually purged at certain intervals or at boot.

Thumbor itself has no mechanism to purge data, it will simply ignore what is on disk and fetch the original again.

**Comment by guilhermef** [comment]
This commit https://github.com/thumbor/thumbor/commit/d060beb3f2a8918e877b0150dbfbe6de03606d87 should avoid this mistakes.
