### ISSUE TITLE
Thumbor doesn't respect the query params and fragments of the image url if url not encoded?

### ISSUE THREAD

**Issue by hus787** [thumbor/thumbor#691]
E.g., for the url: `https://scontent.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/12065834_10154302676120101_4715594766818843446_n.jpg?oh=428df35da204548f852c883f07b31f12&oe=5782D8D8` if thumbor is queried with `/unsafe/400x400/smart/https://scontent.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/12065834_10154302676120101_4715594766818843446_n.jpg?oh=428df35da204548f852c883f07b31f12&oe=5782D8D8` it won't return the image because, probably, tornado would strip of the query params ( and the fragments).

In order to make that work the url has to be encode before sending the req.

Issue: This behaviour is not documented, so it should either be documented or the query params and fragments be respected.

**Comment by masom** [comment]
That's normal as of the HTTP RFC.

If you want the query parameters to be passed along to the image loader ( the source of the image ) the url must be encoded as a URI component.

**Comment by masom** [comment]
https://tools.ietf.org/html/rfc3986
https://en.wikipedia.org/wiki/Uniform_Resource_Identifier
