### ISSUE TITLE
Set Background Color on Transparency and convert to JPG

### ISSUE THREAD

**Issue by nek4life** [thumbor/thumbor#698]
I'm exploring using Thumbor for a site where we usually store product images as tiff files (or I'm thinking with Thumbor of storing them as pngs instead) then through an image service we request the image as jpg instead and set the BG color to match the site background which may vary from page to page. Is this possible with Thumbor? The fill filter only seems to fill in the edges when you resize the image.

**Comment by heynemann** [comment]
You can create your own filter and modify the background easily.

**Comment by nek4life** [comment]
Is there any documentation on extending the filter set? Is there an api for that or would I need to create my filter and submit a patch to thumbor to get it included? I just looked through the docs and did not find anything, but perhaps I'm missing something. Thanks!

**Comment by guilhermef** [comment]
@nek4life You should take a look on the already implemented filters

**Comment by vvh-empora** [comment]
so there is currently no way to set a background color for transparent area on converting from PNG to JPG ?

**Comment by scorphus** [comment]
We should update `fill`'s docs and include examples with the `fill_transparent` optional argument set to `True`.

**Comment by ajaypande88** [comment]
I am trying to fill transparent color inside the watermark but it doesn't work
