### ISSUE TITLE
Purge method to clear thumbnail cache for an individual image

### ISSUE THREAD

**Issue by nek4life** [thumbor/thumbor#699]
I'm looking into Thumbor for an e-commerce site and typically we load all of our product images for a season at the same time, but inevitably there are some that need to be updated throughout the season. I can't seem to find in the documentation if there is a way to expire the thumbnail cache of one particular item. Normally I'd use a unique filename, but these images are named according to the product variation ids so I can't change the names. I'd also would like to prevent expiring the cache on every image just to update a handful of images.

**Comment by masom** [comment]
You could link to the source image with a cache busting string:

```
http://thumbor/unsafe/200x200/http%3A%2F%2Fimage-source%2Fproduct_1_variant_2.jpg%3Fv%3D3333
```
The original url being `http://image-source/product_1_variant_2.jpg?v=3333` would allow you to update the `v` value to a newer one. Thumbor uses the entire image path to generate the cache keys.

**Comment by nek4life** [comment]
This may work. I think we'd have to rework our system a bit in order to make this work. This would also solve "clearing" the CDN cache as well. I'll have to set something up and see if it works. If you use the /image rest api and delete an image using the delete method does that purge the thumbnail cache as well?

**Comment by dhardy92** [comment]
if you have uploaded image to thumbor using REST API you can also use max size id (default 32) to generate garbage data in url : 

http://server/image/98a822a9feb5414da7e3744fb6b70577/image.jpg
is actually the same as http://server/image/98a822a9feb5414da7e3744fb6b70577 

By default only first 32 characters are significant and useful ID for Thumbor (not true with "loader" sourced images)
so you can use it with a timestamp for example.
```
http://<%thumborserver%>/<%hmac%>/100x100/98a822a9feb5414da7e3744fb6b70577/<%imestamp%>
```

**Comment by heynemann** [comment]
I'd say this is outside the scope of thumbor as this implies infrastructure outside thumbor's responsiblities (caching, storage, etc).

**Comment by nek4life** [comment]
I was looking at the thumbnail creation as a file system cache so I thought it might be in scope, especially when an image needs to be replaced in-place. I think this might be a fairly common e-commerce workflow, but perhaps not.

**Comment by Frexuz** [comment]
Same case here :/

**Comment by roelvanduijnhoven** [comment]
I also encountered this problem. At the moment it seems the only way to remove an image from the storage cache of Thumbor is by clearing the complete storage. There is no way to find out which individual file in the storage cache is associated with the individual image I want to delete!

**Comment by roelvanduijnhoven** [comment]
NginX solves this by allowing configuration of a secret header. That could also work for Thumbor. When you pass that header; it will assume the storage cache does _not_ contain the image. It will then download the image, and overwrite the one in the storage.

> curl -v https://url-to.thumbor/FMACJxIHhYG8QXwqQ-qhXmzy8_Q=/27x0:530x503/270x270/som-image.jpg -s -I -H "secret-purge-header:true"

Do you think that that would be difficult @heynemann; or something Thumbor does not want as a feature?

**Comment by heynemann** [comment]
@roelvanduijnhoven we have that implemented here at globo.com. The problem with doing purging of result images is that we would have to assume the way your storage works.

Keep in mind that thumbor is very extensible and you might be storing result images in a way that can't be traced back to a source image (hash of the URL is what comes to mind).

We actually had to modify quite a bit the way we do storage of both originals as well as result images to enable this service. @cristiandean can talk about it in more depth. It would be great if the team responsible for this could write a blog post on the way they did.

For now I'm closing this issue as we understand this is not a responsibility of thumbor itself. It might be as easy as storing all thumbnails of an image inside the folder with the image's name, and then deleting that folder. As previously mentioned the actual implementation would be heavily dependent on your own setup.

**Comment by cristiandean** [comment]
I'd love to talk a little bit more about it. Really, @heynemann is right that thumbor has no responsibility for purging the images, this is clear in the case of globo.com that we have more than one level of cache, in addition to thumbor storage. 

In this application (cache purge) that was done by my team, it was necessary to perform the removal of all these levels caches, making this implementation something very specific, as it can occur in several other Thumbor usage scenarios.

@roelvanduijnhoven if you have any questions regarding the implementation of this application, I'll be happy to help. I will also see the possibility of writing something about it.
