### ISSUE TITLE
Is it possible to override upload handlers, or implement custom security on top of it

### ISSUE THREAD

**Issue by faxal** [thumbor/thumbor#700]
Question pretty much sums it up

**Comment by masom** [comment]
Yes, thumbor is a tornado application, which means you can write your own application or add routes.

See https://github.com/thumbor-community/core and https://github.com/thumbor-community/shortener for examples.

**Comment by faxal** [comment]
Thanks a lot.

**Comment by masom** [comment]
@faxal while the upload handler works it's usually not being used. Thumbor can load files from HTTP(S) sources, AWS, etc. 

https://github.com/thumbor-community/aws

If you need better control on uploads it is often simpler to handle that outside of thumbor.
