### ISSUE TITLE
Document Frame Filter

### ISSUE THREAD

**Issue by nek4life** [thumbor/thumbor#701]
I'm trying to figure out how the frame filter works and it looks like there is no documentation for it or tests to look at for usage. I'm trying to see if I can set the size for an image then add padding inside the bounding box to shrink the image inside. Frame looks like it can add padding from the code, but I'm not fully understanding the url I need to create to make it work to test it out.

**Comment by guilhermef** [comment]
@nek4life I'm sorry, we still don't have any docs related to frame.

**Comment by nek4life** [comment]
@guilhermef No problem. I'm just trying to figure out if it is the right filter for my use case. Do you know how the url is supposed to be formatted to use it?

**Comment by guilhermef** [comment]
@nek4life, we have this test for the frame filter: https://github.com/thumbor/thumbor/blob/master/thumbor/integration_tests/urls_helpers.py#L82

**Comment by pld** [comment]
note the test is now here, https://github.com/thumbor/thumbor/blob/master/integration_tests/urls_helpers.py#L82

**Comment by heynemann** [comment]
If you have any further questions on this issue, please reopen it.
