### ISSUE TITLE
Add RideLink to who is using (documentation)

### ISSUE THREAD

**Issue by ericof** [thumbor/thumbor#703]
Hello,

    Here at [RideLink](https://ridelink.com/) we use Thumbor to serve images to our apps.

Best,
![ridelink](https://cloud.githubusercontent.com/assets/306014/14242873/8771528a-fa52-11e5-894c-0cdbf66580ce.png)

**Comment by guilhermef** [comment]
@rfloriano can you add this to rtd ?

**Comment by rfloriano** [comment]
@ericof  and @guilhermef I have integrated it to our Who's Using page.
Thank you @ericof.
