### ISSUE TITLE
Fetching images with query string from origin

### ISSUE THREAD

**Issue by dbiazus** [thumbor/thumbor#704]
Hey guys, 

I've already made a comment here regarding this behavior:

https://github.com/thumbor/thumbor/commit/a1db568b6ffdf5547700c6ad8036842fd42c4d36

I believe there is an issue fetching images with query string from origin, Ex:

1.2.3.4:8888/unsafe/myoriginhost.foo.bar/myapp.php?image=8842124

Considering the URL above, Thumbor will fetch the image without the parameter "?image=8842124", in this case, changing the behavior's origin app.

I'm not sure if it is expected, so I opened this issue. Better safe than sorry.

Best Regards,
Daniel

**Comment by guilhermef** [comment]
Hi @dbiazus, this issue is related to #691 .
You should always encode the query strings.
