### ISSUE TITLE
ignore requests to /favicon.ico

### ISSUE THREAD

**Issue by cweiske** [thumbor/thumbor#708]
When requesting a thumber URL in the browser, my browser (Chromium 49) always asks for a `favicon.ico` file. This clutters the debug log

### Thumbor request URL
http://localhost:8880/favicon.ico

### Expected behaviour
No log entries about favicon.ico

### Actual behaviour
Log entries:

```
2016-04-13 12:54:10 thumbor:WARNING URL does not have hash or unsafe, or has both: /favicon.ico
2016-04-13 12:54:10 tornado.access:WARNING 400 GET /favicon.ico (172.17.0.1) 1.77ms
```

### Operating system
Ubuntu 14.04

**Comment by heynemann** [comment]
There's no way to do that. Any URL that you request of thumbor that it can't find it will respond with 404. What did you expect it to respond with?

**Comment by jimas14** [comment]
I think this is a valid issue that should be looked at. My debug logs are also cluttered with these 400's to favicon, on every image requested.

**Comment by singhravi1** [comment]
@heynemann 
I did not request for favicon.ico, still it shows the lines in the logs as in the main description.
What could be the reason?

**Comment by cristiandean** [comment]
Some browsers, by default, when you access a web page it automatically make a request for http://page.domain/favicon.ico. This is usually done to add to your tab's icon.

Like this:


![image](https://user-images.githubusercontent.com/25023177/55506546-12794d00-562c-11e9-805c-5d5327f80682.png)

**Comment by singhravi1** [comment]
Thanks @cristiandean for the confirmation !
I too suspected this to be the reason.
