### ISSUE TITLE
Filter to produce solid single dominant colour version of image

### ISSUE THREAD

**Issue by jamus** [thumbor/thumbor#709]
### Idea

A dominant colour alternative / filter for images passed through Thumbor. One likely use case would be to provide a low resolution alternative use as place holders that could be swapped out for higher resolution versions when loaded. Examples of a similar effect can be found on pinterest.com.

Does this seem like a good idea? Would someone be able to assist?

**Comment by guilhermef** [comment]
That's an awesome idea.

**Comment by heynemann** [comment]
Sorry for the long time it took me to reply. Is something like this what you are trying to accomplish: https://medium.com/@kartikluke/implementing-the-frozen-picture-technique-using-thumbor-aa4409ce6d2f

For now closing this.

If you have any further questions on this issue, please reopen it.
