### ISSUE TITLE
Async optimizers proposal

### ISSUE THREAD

**Issue by ctcherry** [thumbor/thumbor#711]
Problem: It takes 10-20s for our optimizer stack to run when an image is requested, this is too long even for the first request.

Proposed solution: On the first request for an image we haven't seen before return the resized image without optimizers run on it, cache headers on this response should be set to a low value, so we will get another request again soon. At this point the optimizers kick in and optimize the image outside of the request/response cycle. When optimization is complete and any further requests arrive, we serve the optimized image with longer cache headers.

Are there any alternative solutions to the above problem?
What are your thoughts about the proposed solution?

**Comment by heynemann** [comment]
I think there's an "easy" solution to this problem. It's very akin to the problem we have with Detectors.

You should create a QueuedOptimizer that just adds the image to a queue to be optimized at a later point in time. Then you need a queue processor that optimizes the image and stores it in the Storage for you.

The only thing I'm not sure (help @masom and @guilhermef) is whether you could specify the expiration from inside an optimizer. I don't think it's possible. It should be, though.

**Comment by heynemann** [comment]
Any news here?

**Comment by heynemann** [comment]
If you have any further questions on this issue, please reopen it.
