### ISSUE TITLE
Disable jpeg subsampling and use quality filter

### ISSUE THREAD

**Issue by eknudtson** [thumbor/thumbor#712]
Hi,

I noticed when I use `PILLOW_JPEG_SUBSAMPLING = 0` to disable chroma subsampling of jpeg images, the quality filters are ignored in request URLs.

Would it be possible to separate this into two separate blocks such that quality is only ignored when setting `PILLOW_JPEG_QTABLES`?

https://github.com/thumbor/thumbor/blob/master/thumbor/engines/pil.py#L150.

**Comment by heynemann** [comment]
Since PR was closed, closing this as well. If this is something you want to move forward, just reopen please.
