### ISSUE TITLE
forward query string

### ISSUE THREAD

**Issue by dbiazus** [thumbor/thumbor#715]
Hey Guys,

### Thumbor request URL
http://mythumborhost.foo.bar/unsafe/myoriginhost.foo.bar/myimageapp.php?parameter=myimageid

### Expected behaviour
Should forward query string to source host with query string if the parameter FORWARD_QS=True is set in conf file.

### Actual behaviour
Just Ignore query string if it's not encoded

### Operating system
OSx, Ubuntu, etc

### Your thumbor.conf
Default thumbor 6.x conf file

Important: I'm aware that FORWARD_QS is not implemented yet, my point here is, If I submit a PR with this feature, Would it be approved ? 

Thanks & Best Regards,
Daniel

**Comment by guilhermef** [comment]
@dbiazus If you want the query string to forwarded to the image host, you should encode it, like 
```
mythumborhost.foo.bar/unsafe/myoriginhost.foo.bar%2Fmyimageapp.php%3Fparameter%3Dmyimageid
```
