### ISSUE TITLE
Mapping for image-uri

### ISSUE THREAD

**Issue by ryanwi** [thumbor/thumbor#718]
I believe this is related to #662 and the community shortener extension, but wanted to throw this out there.

What would you think of a mapping config for the image-uri which would allow you to name mapping shortcuts in the config that would expand to a full url before retrieving the source image?

The advantage I see with this vs the shortener is not making the API call for the shortener or need resources to store shortened urls. Our source image URL hosts will be only a handful, less than 5 likely.  These URL hosts are long though (Rackspace CDN urls) which results in a really long thumbor url.

So, whereas today, a thumbor request would look like

```
http://thumbor.thumborize.me/unsafe/500x330/filters:strip_icc()/http://www.hdwpapers.com/walls/kate_middleton_sweet_face_wallpaper-normal.jpg
```

A url with image-uri mapping could look like

```
http://thumbor.thumborize.me/unsafe/500x330/filters:strip_icc()/hdwpapers/walls/kate_middleton_sweet_face_wallpaper-normal.jpg
```

With a config for 

```
HTTP_LOADER_FOLDER_MAPPING = [['hdwpapers', 'http://www.hdwpapers.com'], ['other mapping','other_full_url']]
```

**Comment by heynemann** [comment]
This has been suggested a couple times. We do not feel this is a responsibility for thumbor.

Very sorry for taking so long to reply.

If you have any further questions on this issue, please reopen it.
