### ISSUE TITLE
Upscale and keeping ratio with the fill filter

### ISSUE THREAD

**Issue by COil** [thumbor/thumbor#726]
### Thumbor request URL

[http://localhost:8888/unsafe/80x40/filters:fill(white,true)/http%3A//assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif](http://localhost:8888/unsafe/80x40/filters:fill%28white,true%29/http%3A//assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif)

Original image: [Original image](http://assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif)
### Expected behaviour

Hi, I am trying to get a thumbnail of an exact size of 80x40, that's why I use the fill filter. I use the fit-in parameter if the original image if bigger in width or length than 80x40. 

In this case the original image is 50x37, (it can be smaller or bigger than the requested width or length)

It should generate a 80x40 image but not cropped. In fact want I want is: [this](http://assets.kelformation.com/img/m/1/organismes/3672/logo_centre_3672_1.gif)
### Actual behaviour

Image is cropped and bottom and top parts of the original image are loosed, but its 80x40 as requested. if I use 0x40 the ratio is Ok but the image is 55x40 not 80x40.

[Wrong generated logo](https://thbr.figarocms.net/external/t5QLV0owiGWOjLx049eMFf3uzag=/80x40/filters:fill%28white,true%29/http%3A//assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif)
### Operating system
- Ubuntu 14.04
- Thumbor 6.0.1

**Comment by hhankj2u** [comment]
Have you try smart crop option yet?

**Comment by kkopachev** [comment]
Looks like it's a bug when `USE_GIFSICLE_ENGINE=True`. It scales png images as you'd expect.

**Comment by COil** [comment]
Thank you, I'll give a try tuesday.

**Comment by COil** [comment]
I try with both values but it doesn't work. When changing this setting the difference is the quality of the generated image.

**Comment by kkopachev** [comment]
Sorry, forgot to mention that this works when you set `fit-in`. 
http://localhost:8000/unsafe/fit-in/80x40/filters:fill(white,true)/http%3A//assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif

and this is the output: 
![logo_centre_3672_1](https://cloud.githubusercontent.com/assets/2279051/16015439/80b34bc2-314a-11e6-9d67-166c412af84b.gif)

**Comment by COil** [comment]
Hi, I can't use "fit-in", because If I want the logo in 120x60 it stays the size it is and there is no upscale of the original image.

**Comment by COil** [comment]
Sorry perhaps I was not clear: the original image is 50x37 therefore in this case when asking for 80x40 , an upscale must be applied. I use "fit-in" when the original image is bigger in width or height than the requested size.

**Comment by scorphus** [comment]
@COil, is the following what you want but with a single request?

http://localhost:8888/unsafe/fit-in/80x40/filters:fill(white)/http://localhost:8888/unsafe/x40/http://assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif

Result is:

![coil](https://cloud.githubusercontent.com/assets/2112697/23583123/22ae324e-011a-11e7-84e1-222a3827f049.gif)
```
»»»» curl -s 'http://localhost:8888/unsafe/fit-in/80x40/filters:fill(white)/http://localhost:8888/unsafe/x40/http://assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif' | identify -
-=>/var/tmp/magick-54049NjFuApSA7yRS GIF 80x40 80x40+0+0 8-bit sRGB 256c 2.4KB 0.000u 0:00.000
```
