### ISSUE TITLE
Image opacity

### ISSUE THREAD

**Issue by chrismou** [thumbor/thumbor#729]
Hey

Sorry if I've missed something - I've read the wiki and trawled the internet reading tutorials - but I can't work out whether there's a way of changing an images opacity. I'm holding out hope that I may have missed something because I see you can specify transparency on watermarks.

My end goal is to take an image, knock it down to 50% opacity and then give it a black or blue background.  From what I can see I can set the background colour easily enough using filter:fill(black), but I can't puzzle out if there's a way of making the image partially transparent.

Is this possible?

**Comment by guilhermef** [comment]
I'm sorry but there's no opacity filter on thumbor.

**Comment by thejase** [comment]
You might try: `filters:colorize(50, 50, 50, 0000ff)` <-- colorize each RGB color 50% with blue.

**Comment by dhardy92** [comment]
would it be better to use CSS for this. ?

**Comment by thejase** [comment]
Agreed... just not sure if CSS is a tool/setup available to the OP, so just sticking with the original context.

**Comment by heynemann** [comment]
If you have any further questions on this issue, please reopen it.
