### ISSUE TITLE
Webp from result_storage is not setting Vary header

### ISSUE THREAD

**Issue by kkopachev** [thumbor/thumbor#731]
When request from Chrome comes in, thumbor (as configured) outputs webp image, stores it in result_storage and sets Vary: Accept header. When next time request from Chrome comes in for the same image, thumbor fetches result from result_storage (https://github.com/thumbor/thumbor/blob/e6a5a90ac635af6f152f0938179739d344c13b09/thumbor/handlers/__init__.py#L86)  and since engine.extension in that case would be = webp, it does not send Vary header https://github.com/thumbor/thumbor/blob/e6a5a90ac635af6f152f0938179739d344c13b09/thumbor/handlers/__init__.py#L353

The problem arises when we have 2 load-balanced sets of (thumbor+caching nginx) with shared result_storage. 
When request comes in for a first time (from Chrome) to instance A, it puts result into storage, sets Vary headers so nginx on instance A will include Accept as part of cache key. 
Now request for the same image comes to server B from Chrome. Thumbor pulls result from result_storage and does not set Vary header. Nginx on server B in front of thumbor creates a cache entry without Accept header as part of cache key.
Everything is messed up. When request coming in server A, it'll serve webp/jpeg based on Accept header. While server B will always serve webp regardless.

**Comment by cerber717** [comment]
👍

**Comment by guilhermef** [comment]
@kkopachev can you send a PR ?

**Comment by kkopachev** [comment]
@guilhermef Not sure how it should work. I am leaning toward letting it set Vary:Accept header regardless of engine.extension. But there is a test specifically for that: https://github.com/thumbor/thumbor/blob/master/tests/handlers/test_base_handler.py#L402
I don't see any ways `result_storage` can provide file's original mime and we can't get it without fetching original.
Thoughts?

**Comment by guilhermef** [comment]
We should start storing on result_storage the image headers, but for now, I agree with you, we should set the Vary header for every webp image.
@heynemann, @rfloriano what do you think ?

**Comment by guilhermef** [comment]
@kkopachev 6.0.2 should fix this issue, while we work on a better solution.

**Comment by kkopachev** [comment]
@guilhermef are you sure it is related to #727 ?

**Comment by guilhermef** [comment]
It's not related, I had to revert this breaking change to release a 6.0.2 version, otherwise it would be a major release, instead of a bug fix.

**Comment by kkopachev** [comment]
Ah, sorry, didn't notice that.
