### ISSUE TITLE
Missing parentheses in call to 'print' with Py 3

### ISSUE THREAD

**Issue by gratcliffe** [thumbor/thumbor#738]
After install it, when you try to run thumbor on console it fails.

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/thumbor/context.py", line 261
    print "Joining threads...."

### Operating system
OSx

**Comment by guilhermef** [comment]
@gratcliffe right now, thumbor doesn't work on python 3.
You need to run on python 2.7

**Comment by j127** [comment]
Can you add some way to [prevent it from installing on Python 3](https://www.python.org/dev/peps/pep-0345/#requires-python)? Right now, Thumbor installs on the latest versions of Python (3.5+) without errors. There is no mention of the requirement in the docs either. It would save people a lot of time if the installation failed when trying to install it on non-supported Python versions.
