### ISSUE TITLE
HttpLoader having problem with encoded url

### ISSUE THREAD

**Issue by paranpi** [thumbor/thumbor#739]
### Thumbor request URL

http://ec2-52-36-162-97.us-west-2.compute.amazonaws.com:8888/unsafe/300x240/smart/d1yb2nb3f2zet9.cloudfront.net/curation/1463636539021_%EC%98%A4%EC%82%AC%EC%B9%B4%EA%BF%80%ED%8C%813.jpg
### Expected behaviour

should get image from origin url and then resizing.
### Actual behaviour

can't get image from origin having encoded url
### Operating system

Amazon Linux AMI release 2016.03
### Your thumbor.conf

Nothing special. It is just default configuration.

**Comment by paranpi** [comment]
If remove the unquote function in quote_url , no problem.
like this
`
def quote_url(url):
    return url.decode('utf-8')
`

**Comment by guilhermef** [comment]
I'm not sure that our loader follows redirect:
```
➜  ~ curl -I "http://d1yb2nb3f2zet9.cloudfront.net/curation/1463636539021_%EC%98%A4%EC%82%AC%EC%B9%B4%EA%BF%80%ED%8C%813.jpg"
HTTP/1.1 200 OK
Content-Type: image/jpeg
Content-Length: 2339305
Connection: keep-alive
Date: Thu, 02 Jun 2016 11:04:11 GMT
Last-Modified: Thu, 19 May 2016 05:40:00 GMT
ETag: "f0f14beb7537033d4e553a7a4469f016"
Server: AmazonS3
X-Cache: Miss from cloudfront
Via: 1.1 10f355ed043b5642c0db2cb6dc9f89a1.cloudfront.net (CloudFront)
X-Amz-Cf-Id: _WhgXuU0kMnkODVueFhPGWBAKcgBV-KiCD8xcmOJgbiHIx7Fisy2Cg==

➜  ~ curl -I "http://d1yb2nb3f2zet9.cloudfront.net/curation/1463636539021_오사카꿀팁3.jpg"
HTTP/1.1 302 Moved Temporarily
Content-Length: 0
Connection: keep-alive
Date: Thu, 02 Jun 2016 11:04:33 GMT
Location: https://d254i4serkgq8u.cloudfront.net/uploadFiles/curation/1463636539021_오사카꿀팁3.jpg
Server: AmazonS3
X-Cache: Miss from cloudfront
Via: 1.1 10f355ed043b5642c0db2cb6dc9f89a1.cloudfront.net (CloudFront)
X-Amz-Cf-Id: AzgUJJadqRRh6o8-zLUqbng3dga8vRTD0DIH8sXxWeHBQASLmHmpEg==
```

**Comment by paranpi** [comment]
When not found file, the s3 configuration was configured to redirect second origin server
But now , changed setting to do nothing.

**Comment by heynemann** [comment]
Why has this been reopened? Closing this.

If you have any further questions on this issue, please reopen it.
