### ISSUE TITLE
Add ability to read multiple config files in a given folder

### ISSUE THREAD

**Issue by gi11es** [thumbor/thumbor#748]
Still in the context of trying to package https://github.com/thumbor-community/core separately from thumbor (see related #747) for debian, it would be helpful if thumbor could be passed a config folder instead of just a config file. Thumbor would read all the files in that folder and load their config sequentially. It would respect filename ordering, so that overrides between files can work reliably.

This would allow different OS packages to define their own thumbor configuration, while never changing the single systemd service definition, which would always point to the same config folder (eg. /etc/thumbor.d/).

If there are any objections to making this change, please let me know. I intend to work on it after I implement a solution for #747

**Comment by guilhermef** [comment]
It's a nice feature, we just need to still support reading a single conf file.

**Comment by gi11es** [comment]
The derpconf change should be enough. Right now if you point thumbor to a folder as the -c parameter, it errors and dies. After this derpconf change, it just works.
