### ISSUE TITLE
ALLOWED_SOURCES for combination of local uploaded images and restricted online sources

### ISSUE THREAD

**Issue by variable** [thumbor/thumbor#754]
### Thumbor request URL

http://fakethumbor.com/unsafe/100x100/https://images.com/asset/MkT1kkk7Ys
http://fakethumbor.com/unsafe/100x100/7b5513e1ca1c46c98c5db87a3137a0ad
### Expected behaviour

When I define ALLOWED_SOURCES = ['images.com'], the above 2 urls should work fine.
### Actual behaviour

When ALLOWED_SOURCES = ['images.com']
http://fakethumbor.com/unsafe/100x100/https://images.com/asset/MkT1kkk7Ys <--- works
http://fakethumbor.com/unsafe/100x100/7b5513e1ca1c46c98c5db87a3137a0ad <--- doesn't work

When ALLOWED_SOURCES = []
http://fakethumbor.com/unsafe/100x100/https://images.com/asset/MkT1kkk7Ys <--- works
http://fakethumbor.com/unsafe/100x100/7b5513e1ca1c46c98c5db87a3137a0ad <--- works
### Operating system

Ubuntu

**Comment by hhankj2u** [comment]
I think it's not a problem of `ALLOWED_SOURCES`.
Can you show me your `LOADER`?
If you want to use both local and online source, you should consider using this config:
```
LOADER="thumbor.loaders.file_loader_http_fallback"
```

**Comment by heynemann** [comment]
Since the requester hasn't responded in an year, I'm closing this.

If you have any further questions on this issue, please reopen it.
