### ISSUE TITLE
Thumbor over SSL?

### ISSUE THREAD

**Issue by mwkrieger** [thumbor/thumbor#760]
I'm trying to get Thumbor to serve files over HTTPS, but can't find a guide anywhere. 

Can someone point me in the right direction, please?

**Comment by xethorn** [comment]
HTTPS should be handled by your reverse proxy (nginx, haproxy). https://www.nginx.com/resources/admin-guide/reverse-proxy/

**Comment by mwkrieger** [comment]
Ok, understood. I was hoping to not use a reverse proxy to begin with. 

Thank you.
