### ISSUE TITLE
Thumbor SSL - no-check-certificate

### ISSUE THREAD

**Issue by linuxfragmente** [thumbor/thumbor#763]
Hello, 
i have a old Thumbor version (4.4.1) installed with Python 2.7.3. An update is now not possible. This Python version can not use TLS1.2.I would like use a self signed ssl certificate for internal connection. But i get a ssl error. How I can use  a self signed ssl certificate for Thumbor?

Thanks for your help

`thumbor9003.stderr.log:2016-06-22 15:09:09 tornado.general:WARNING SSL Error on 10 ('10.10.10.100', 443): [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
thumbor9003.stderr.log:2016-06-22 15:09:09 thumbor:WARNING ERROR retrieving image https://server.com/2014-04/saloppe.jpg: HTTP 599: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed`

**Comment by guilhermef** [comment]
Looks like you just need to update OpenSSL: https://docs.python.org/2/library/ssl.html

**Comment by yspanchal** [comment]
@guilhermef i am getting following error on ubuntu 14.04 

tornado.general:WARNING SSL Error on 9 ('2400:cb00:2048:1::681b:9204', 443, 0, 0): [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
2017-04-27 11:36:55 thumbor:WARNING ERROR retrieving image https://www.xyz.com/wp-content/uploads/2017/01/7-5.jpg: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

> sudo dpkg --list | grep openssl
ii  libgnutls-openssl27:amd64          2.12.23-12ubuntu2.7                        amd64        GNU TLS library - OpenSSL wrapper
ii  openssl                            1.0.2g-1ubuntu4                            amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  python-openssl                     0.13-2ubuntu6                              amd64        Python 2 wrapper around the OpenSSL library

**Comment by yspanchal** [comment]
@linuxfragmente did you find any solution for this ?

**Comment by masom** [comment]
Those errors should be reported to the OpenSSL project.
