### ISSUE TITLE
get query string back in image IDs

### ISSUE THREAD

**Issue by dhardy92** [thumbor/thumbor#765]
### Thumbor request URL

`http://localhost:8888/unsafe/80x80/member/1234567890?ts=1466433483000`
### Expected behaviour

HTTP 200

Since this change https://github.com/thumbor/thumbor/commit/a1db568b6ffdf5547700c6ad8036842fd42c4d36#diff-f0814d1615dc4fba57d2fce889be3402L182 image ids using query string are broken.
Can we make this available again (via some config toggle maybe) ?
what are the problems it may occurred ?
### Actual behaviour

HTTP 404
### Operating system

Debian weezy pip install

This prevent me from moving to Thumbor 6.x for now

**Comment by guilhermef** [comment]
@dhardy92  the URL should be: `http://localhost:8888/unsafe/80x80/member/1234567890%3Fts%3D1466433483000`

**Comment by dhardy92** [comment]
this wasn't the case until 6.x version should why it be ? any blocker ? as query string is never used by thumbor API I can't see the point.
My storage is now using ids with "?" and url in internet are allready broadcast using "?" for years
This prevent us from moving to thumbor 6.

**Comment by guilhermef** [comment]
We had a similar discussion, in order to simplify the way thumbor handles image urls and to respect the [RFC](https://tools.ietf.org/html/rfc3986), the best option is to ignore non encoded query string.

**Comment by guilhermef** [comment]
Can you send the uri encoded and then decode on you loader ?

**Comment by dhardy92** [comment]
I use aws_s3 storage and describe my problem on https://github.com/thumbor-community/aws/issues/59
I use storage instead of loader because loader was used for migration purpose (migration is now over)
But I  suspect the problem would be the same.

**Comment by heynemann** [comment]
Sorry Damien for the issues. Hope this is all fixed now.

If you have any further questions on this issue, please reopen it.
