### ISSUE TITLE
Upload storage and /image API endpoint storage engine

### ISSUE THREAD

**Issue by gferon** [thumbor/thumbor#767]
### Expected behaviour

I expect Thumbor to look for uploaded images (requesting with /image/) using the same storage engine as defined in UPLOAD_PHOTO_STORAGE and not the default STORAGE when UPLOAD_ENABLED is set to True.
### Actual behaviour

Upload is correctly made using the storage defined in UPLOAD_PHOTO_STORAGE, but then lookup from /images/ is made using `self.context.modules.storage` in `ImageResourceHandler`

From what I've seen in the code, the same would happen on DELETE. If one defines a different value for STORAGE and UPLOAD_PHOTO_STORAGE, and then issue a DELETE request, the file won't be deleted in the correct storage engine.

Did I miss something obvious? Basically, my use-case is to store cached images in redis, but also to leverage uploading capabilities of Thumbor to store our own images in the long-term (disk or s3).

**Comment by mojeto** [comment]
I agree. I spent a whole day to debugging it. 
I set UPLOAD_PHOTO_STORAGE value in configuration file to 'tc_aws.storages.s3_storage', but I forget on STORAGE variable which defaults to 'thumbor.storages.file_storage'.

I don't see the use case when STORAGE != UPLOAD_PHOTO_STORAGE, but I think in documentation should be explanation and in example thumbor.conf should be 
`
STORAGE = UPLOAD_PHOTO_STORAGE= 'thumbor.storages.file_storage'
`
so it's obvious those two storages are related.

**Comment by gferon** [comment]
For me, it's an inconsistency, I can easily submit a PR but I'd like to get the opinion from one of the project developers to make sure I didn't miss anything.

**Comment by heynemann** [comment]
I don't think it is an inconsistency at all.

Consider the following scenario:

UPLOAD_PHOTO_STORAGE = 'myphotostorage.QueuedPhotoProcessorStorage'
STORAGE = 'thumbor.storages.file_storage'

What's going on here? I have an upload storage that delegates the upload to a queue, that in turn processes the image and stores the processed image in the file system.

The next time someone requests the image, thumbor's file storage can load the image from the file system.

How can you do this if you have both storages be the same?

Closing this as the way thumbor works now is the most extensible.

If you have any further questions on this issue, please reopen it.

PS: Sorry for the long time it took me to reply. It's been a wild year.
