### ISSUE TITLE
[Suggestion] Seam carving - Crop algorithm

### ISSUE THREAD

**Issue by cicerocomp** [thumbor/thumbor#773]
Implement algorithm crop: [Seam carving](https://en.wikipedia.org/wiki/Seam_carving)

Python implementations: 
https://github.com/sameeptandon/python-seam-carving
https://github.com/NicolasT/python-scarving

**Comment by heynemann** [comment]
@cicerocomp this is really incredible!!! I'm sorry I'm only seeing this for the first time. In this 1 and a half year, did you get a chance to come up with something we can start a PR with? Can you do it?

For now we are really focused in getting thumbor 7.0 out of the door and it has a lot of fixing to do. I don't think we'll be able to tackle this without the help from the community.

Anyways, closing this for now.

If you have any further questions on this issue, please reopen it.
