### ISSUE TITLE
Question: OAuth-style authentication to replace SECRET_KEY?

### ISSUE THREAD

**Issue by grvhi** [thumbor/thumbor#774]
Does anyone know of a plugin/fork which allows for per-request authentication? 

For example, using a header value submitted with the request which can be used to validate the URL, instead of the secret key?

**Comment by guilhermef** [comment]
You could use a reverse proxy for that, e.g. https://github.com/bitly/oauth2_proxy

**Comment by Erve1879** [comment]
Thanks @guilhermef - I actually need something more simplistic than that. Essentially, I just want to use a different SECRET_KEY value for each incoming request to decode the URL. I guess the only solution is to fork and edit!

**Comment by jeffxor** [comment]
I would be really interested in potential authentication module that could be extended. In my situation I am looking to use this on a Singe Page Application which would mean client side would be generating the URLs. Currently I would need to expose my secret key which would mean to the security would be mute.

**Comment by masom** [comment]
@grvhi @jeffxor Thumbor supports pluggable signing, which means a different signing method can be used instead of hashes.
