### ISSUE TITLE
Can avoid Image.open for image from result storage?

### ISSUE THREAD

**Issue by kkopachev** [thumbor/thumbor#779]
Hey guys!

I noticed that each time thumbor retrieves an image from result storage[ it is opening it with engine](https://github.com/thumbor/thumbor/blob/e6a5a90ac635af6f152f0938179739d344c13b09/thumbor/handlers/__init__.py#L86) which might be not so cheap. 
From what I can seem this is used [only for deciding](https://github.com/thumbor/thumbor/blob/e6a5a90ac635af6f152f0938179739d344c13b09/thumbor/handlers/__init__.py#L350-L354) if we should add `Vary` header for an image. But even that part was stripped a bit in https://github.com/thumbor/thumbor/commit/07c9dba13cc835c1a4472090218df65edc3c5184 to resolve https://github.com/thumbor/thumbor/issues/731 (code is not in master, I'm afraid it get's dropped in next release)
So currently (as of 6.0.2) it only checks if image height or width is less then limit (for already resized image :fearful:)

I am questioning if this is in any way useful currently and is there anything could be done to avoid loading already resized image just to serve it back to client?

PS What was the reason for WEBP pixel side limit?

**Comment by cerber717** [comment]
👍

**Comment by guilhermef** [comment]
@kkopachev we're still working on some changes to store metadata on the result storage, to avoid setting the Vary Header every time.

That's the reason behind WEBP side limit: https://developers.google.com/speed/webp/faq#what_is_the_maximum_size_a_webp_image_can_be

**Comment by kkopachev** [comment]
closed via https://github.com/thumbor/thumbor/pull/839
