### ISSUE TITLE
some kind of warning for DecompressionBomp

### ISSUE THREAD

**Issue by phoet** [thumbor/thumbor#781]
in PR https://github.com/thumbor/thumbor/pull/614 there was a fix to handle the pil `DecompressionBomp` error, adding a new configuration setting `MAX_PIXELS` (`Config.define('MAX_PIXELS', 75e6, "Max pixel count for images read by thumbor", "Imaging")`).

unfortunately there is no way to actually see that an image-transformation ran into this. 

it would be great to have some kind of warning or statistic that this happened. otherwise the server returns a 400 and you know nothing 😢

**Comment by kkopachev** [comment]
It's in error logs, saying that size 123456xxx is greater then allowed 75e6.

**Comment by phoet** [comment]
Are you sure that is the case on Master? I saw that error on older versions though. https://github.com/thumbor/thumbor/blob/master/thumbor/engines/pil.py#L70

**Comment by rfloriano** [comment]
I've added some log when Image.DecompressionBombWarning happens.
https://github.com/thumbor/thumbor/commit/55d92fba6c2cff0c900e45b221c20ff12c4411b2

Thanks @phoet!
