### ISSUE TITLE
URL escaping not working with thumbor.loaders.file_loader

### ISSUE THREAD

**Issue by threehundred** [thumbor/thumbor#784]
### Thumbor request URL

http://host/unsafe/200x150/Image_0006%20625.jpg
NOTE: I've tried with files that don't have spaces in filenames, and they work correctly. 
### Expected behaviour

Should return the thumbnail. 
### Actual behaviour

tornado.access:WARNING 404
### Operating system

aps/thumbor docker image (debain)
### Your thumbor.conf

LOADER=thumbor.loaders.file_loader
FILE_LOADER_ROOT_PATH=/usr/src/app/data
THUMBOR_LOG_FORMAT='%(asctime)s %(name)s:%(levelname)s %(message)s'
THUMBOR_LOG_DATE_FORMAT='%Y-%m-%d %H:%M:%S'
MAX_WIDTH=0
MAX_HEIGHT=0
MIN_WIDTH=1
MIN_HEIGHT=1
ALLOWED_SOURCES=[]
QUALITY=80
WEBP_QUALITY=None
AUTO_WEBP=False
MAX_AGE=86400
MAX_AGE_TEMP_IMAGE=0
RESPECT_ORIENTATION=False
IGNORE_SMART_ERRORS=False
PRESERVE_EXIF_INFO=False
ALLOW_ANIMATED_GIFS=True
USE_GIFSICLE_ENGINE=False
USE_BLACKLIST=False
STORAGE='thumbor.storages.file_storage'
AWS_ACCESS_KEY_ID='' -> Note: New in version 5.2.1c
AWS_SECRET_ACCESS_KEY='' -> Note: New in version 5.2.1c
RESULT_STORAGE='thumbor.result_storages.file_storage'
ENGINE='thumbor.engines.pil'
SECURITY_KEY='MY_SECURE_KEY'
ALLOW_UNSAFE_URL=True
ALLOW_OLD_URLS=True
HTTP_LOADER_CONNECT_TIMEOUT=5
HTTP_LOADER_REQUEST_TIMEOUT=20
HTTP_LOADER_FOLLOW_REDIRECTS=True
HTTP_LOADER_MAX_REDIRECTS=5
HTTP_LOADER_FORWARD_USER_AGENT=False
HTTP_LOADER_DEFAULT_USER_AGENT='Thumbor/5.2.1'
HTTP_LOADER_PROXY_HOST=None
HTTP_LOADER_PROXY_PORT=None
HTTP_LOADER_PROXY_USERNAME=None
HTTP_LOADER_PROXY_PASSWORD=None
STORAGE_EXPIRATION_SECONDS=2592000
STORES_CRYPTO_KEY_FOR_EACH_IMAGE=False
FILE_STORAGE_ROOT_PATH='/data/storage'
UPLOAD_MAX_SIZE=0
UPLOAD_ENABLED=False
UPLOAD_PHOTO_STORAGE='thumbor.storages.file_storage'
UPLOAD_DELETE_ALLOWED=False
UPLOAD_PUT_ALLOWED=False
UPLOAD_DEFAULT_FILENAME='image'
MONGO_STORAGE_SERVER_HOST='mongo'
MONGO_STORAGE_SERVER_PORT='27017'
MONGO_STORAGE_SERVER_DB='thumbor'
MONGO_STORAGE_SERVER_COLLECTION='images'
REDIS_STORAGE_SERVER_HOST='redis'
REDIS_STORAGE_SERVER_PORT='6379'
REDIS_STORAGE_SERVER_DB=0
REDIS_STORAGE_SERVER_PASSWORD=None
REDIS_RESULT_STORAGE_SERVER_HOST='redis'
REDIS_RESULT_STORAGE_SERVER_PORT=6379
REDIS_RESULT_STORAGE_SERVER_DB=0
REDIS_RESULT_STORAGE_SERVER_PASSWORD=None
MEMCACHE_STORAGE_SERVERS=['localhost:11211',]
MIXED_STORAGE_FILE_STORAGE='thumbor.storages.no_storage'
MIXED_STORAGE_CRYPTO_STORAGE='thumbor.storages.no_storage'
MIXED_STORAGE_DETECTOR_STORAGE='thumbor.storages.no_storage'
META_CALLBACK_NAME=None
DETECTORS=[]
FACE_DETECTOR_CASCADE_FILE='haarcascade_frontalface_alt.xml'
OPTIMIZERS=[]
JPEGTRAN_PATH='/usr/bin/jpegtran'
PROGRESSIVE_JPEG=True
FILTERS=['thumbor.filters.brightness', 'thumbor.filters.contrast', 'thumbor.filters.rgb', 'thumbor.filters.round_corner', 'thumbor.filters.quality', 'thumbor.filters.noise', 'thumbor.filters.watermark', 'thumbor.filters.equalize', 'thumbor.filters.fill', 'thumbor.filters.sharpen', 'thumbor.filters.strip_icc', 'thumbor.filters.frame', 'thumbor.filters.grayscale', 'thumbor.filters.rotate', 'thumbor.filters.format', 'thumbor.filters.max_bytes', 'thumbor.filters.convolution', 'thumbor.filters.blur', 'thumbor.filters.extract_focal', 'thumbor.filters.no_upscale']
RESULT_STORAGE_EXPIRATION_SECONDS=0
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH='/data/result_storage'
RESULT_STORAGE_STORES_UNSAFE=False
REDIS_QUEUE_SERVER_HOST='redis'
REDIS_QUEUE_SERVER_PORT='6379'
REDIS_QUEUE_SERVER_DB='0'
REDIS_QUEUE_SERVER_PASSWORD=None
SQS_QUEUE_KEY_ID=None
SQS_QUEUE_KEY_SECRET=None
SQS_QUEUE_REGION='us-east-1'
USE_CUSTOM_ERROR_HANDLING=False
ERROR_HANDLER_MODULE='thumbor.error_handlers.sentry'
ERROR_FILE_LOGGER=None
ERROR_FILE_NAME_USE_CONTEXT='False'
SENTRY_DSN_URL=''
TC_AWS_REGION='eu-west-1'
TC_AWS_STORAGE_BUCKET=''
TC_AWS_STORAGE_ROOT_PATH=''
TC_AWS_LOADER_BUCKET=''
TC_AWS_LOADER_ROOT_PATH=''
TC_AWS_RESULT_STORAGE_BUCKET=''
TC_AWS_RESULT_STORAGE_ROOT_PATH=''
TC_AWS_STORAGE_SSE=False
TC_AWS_STORAGE_RRS=False
TC_AWS_ENABLE_HTTP_LOADER=False
TC_AWS_ALLOWED_BUCKETS=False
TC_AWS_STORE_METADATA=False

**Comment by 77akella** [comment]
Have the same issue - works with URL without spaces but gices an exception when there is a space.

**Comment by jaymzcd** [comment]
Seeing this also now, I get an HTTP 505 (http version not supported) back. The URL (which is encoded) works ok on it's own. Thumbor is also working ok on any other URL. 

In the request I can see that the part after the spaces is passed in the header as if it's part of the HTTP request itself and not the source URL. I"m running Thumbor 6.0.1:

```
ubuntu@thumbor:~$ thumbor --version
Thumbor v6.0.1 (22-Mar-2016)
```

**Comment by a5hay** [comment]
We see this issue too 
Logs:
```
2016-10-06 00:01:40 thumbor:WARNING ERROR retrieving image http://xxx-wordpress-www-dev.s3-website-us-west-2.amazonaws.com/uploads/2016/Driver Foundations Gallery/081316-NASCAR-Jimmie-Johnson-foundation.jpg: HTTP 505: HTTP Version not supported
2016-10-06 00:01:40 tornado.access:WARNING 404 GET /unsafe/700x700/http://xxx-wordpress-www-dev.s3-website-us-west-2.amazonaws.com/uploads/2016/Driver%20Foundations%20Gallery/081316-NASCAR-Jimmie-Johnson-foundation.jpg (172.17.0.3) 46.25ms
```

**Comment by mvdklip** [comment]
Bumped in this "issue" as well, but discovered that technically this is not an issue in Thumbor. You have to remember that the original URL of an image is being passed inside a Thumbor URL. This means that the space character (or any other special character) needs to be escaped once when put in the original URL and then twice when that URL is put in the Thumbor URL. Correct URL for this issue:

http://host/unsafe/200x150/Image_0006%2520625.jpg

Previous versions of Thumbor were actually broken in this respect. Recent versions of Thumbor are technically better at handling filenames with special characters although it may seem broken at first.

**Comment by TwanoO67** [comment]
Hello,

I have the same issue here, and I tried @mvdklip 's technique, and it's not working.

testing:

http://localhost:8000/unsafe/640x360/mytest.jpg (without any space in name) => OK
http://localhost:8000/unsafe/640x360/my test.jpg => not ok
http://localhost:8000/unsafe/640x360/my%20test.jpg => not ok
http://localhost:8000/unsafe/640x360/my%2520test.jpg => not ok

I don't know what to test next neither what to do...
Most of my images have space in names or in directory names, I'm pretty stuck with that...

**Comment by heynemann** [comment]
Is this still happening?

**Comment by Dylan-DutchAndBold** [comment]
Unfortunately, just ran into this issue myself. This is kind of a bummer. Was really looking forward to implementing Thumbor for my clients. But I just can't sell the fact that there can't be spaces in folder names.

With the file_loader

http://local.hidden-for-privacy.com:8000/unsafe/fit-in/200x200/test.png -> works
http://local.hidden-for-privacy.com:8000/unsafe/fit-in/200x200/tes%20t.png -> does not work (404)

@heynemann

**Comment by heynemann** [comment]
We'll merge it soon. Hope it helps.
