### ISSUE TITLE
Thumbor on AWS Lambda

### ISSUE THREAD

**Issue by muratcorlu** [thumbor/thumbor#786]
Can we use Thumbor as an AWS Lambda Function? Do you have tried that?

**Comment by rfloriano** [comment]
Do you referrer about [Thumbor community AWS project](https://github.com/thumbor-community/aws)?
If yes, maybe this issue is a issue of that project and the @phoet may help you.
Sorry @muratcorlu, in globo.com we do not use AWS project.

**Comment by phoet** [comment]
@muratcorlu i don't think it's feasible as it has quite some dependencies depending on your setup like graphicsmagick, gifsicle etc. 

i'd rather look at solutions using go with imagemagick bindings like this https://github.com/mat/gomagick
http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

**Comment by muratcorlu** [comment]
@rfloriano No, I didn't refer about Thumbor AWS project. I tried AWS Lambda as an image resizing service with a simple Nodejs function. It is very efficient and very simply scalable. As an experienced Thumbor user, I think about that, can I use Thumbor as an AWS Lambda function. Because it support Python scripts and it has Imagemagick support. I wondered anybody tried that or is there any plan to support that kind of platforms like AWS Lambda or Google Cloud Functions...

If nobody think about that, we can close issue. Or we can tag this as an idea and maybe some people write their ideas here in the future.

**Comment by ojdupuis** [comment]
@muratcorlu I would be interested in this setup. Many SaaS products that exist for cropping/optimizing/resizing images are quite expensive, having my own Thumbor/lambda architecture would be a good mean to manage costs efficiently.

**Comment by muratcorlu** [comment]
Actually, I started to use a simple Lambda function for my image resize needs for a few months instead of Thumbor. When I was using Thumbor, I paid some money for a server for Thumbor but also get some problems because of multiple image resize requests at once over my weak(but cheap) vps. But, when I moved to Lambda, scaling problem is automatically solved. And I paid no money for that service in last 3 months. Hassle-free...

I think services like Lambda and Google Functions are ideally suited for Thumbor-like on-the-fly image resize libraries.

**Comment by ianhartz** [comment]
Hey guys, I did port thumbor to AWS lambda + AWS API Gateway. I'm still testing, but until now I'm getting 100ms for warmed request and 500ms for cold requests. These number are fine for my cases, and still didn't test the cache layer from the API Gateway and CloudFront, that will speed up and bring cost down. 

I could share the source here soon, if you guys agree, or we can create a tc_aws_lambda repo for this.

**Comment by muratcorlu** [comment]
@ianhartz great news! I'll wait for your share. Did you make big changes in the thumbor core?

**Comment by Bladrak** [comment]
@ianhartz nice! Feel free to tell us if you wish to publish that under the thumbor-community organization, I'm sure we could work it out with @masom :)

**Comment by ianhartz** [comment]
@muratcorlu nothing invasive, we can use thumbor and it modules as is without any change. Just give me a week to finalize my tests and review my ugly code and I will share with you guys.

**Comment by ojdupuis** [comment]
@ianhartz can't wait to test it !

**Comment by guilhermebruzzi** [comment]
@ianhartz Nice! :D Did you create the repo with this code?

**Comment by Vmadmax** [comment]
Any news here?

**Comment by ihartz** [comment]
Hey guys, checkout here:
https://github.com/awslabs/serverless-image-handler
https://aws.amazon.com/answers/web-applications/serverless-image-handler/

**Comment by muratcorlu** [comment]
An official working example by AWS team, great! But I couldn't be sure, it's a good idea to running an http server inside a lambda function. I thought we should find much more simpler solution like running some utility functions of Thumbor by importing it to a lambda function like:

```python
from thumbor.utils import parseUrl, resize

# inside lambda function
resizeConfig = parseUrl(request.url)
outputFilePath = resize(resizeConfig)
return {'result': outputFilePath}
```

**Comment by heynemann** [comment]
Good work guys!

**Comment by muratcorlu** [comment]
Example of AWS is now using SharpJS instead of Thumbor. To see the latest version of Thumbor version you can check v3.1: https://github.com/awslabs/serverless-image-handler/tree/f47c7c7c8a29e605921297a4bf301a24637f10b1
