### ISSUE TITLE
Question: Inodes on resized file storage and resized files best practice

### ISSUE THREAD

**Issue by beenanner** [thumbor/thumbor#791]
We are using the file loader and storing all our resized images. Does anyone use this loader and what are the recommendations for storage of resized files. Since each file is stored in it's own multiple nested directories when a secret key(i.e. 1 file per nested directory), do you guys recommend not storing those resized files for extended periods of time? 

`/v2/aa/a0/aaa0HYNHukH0MAMXVmGpp7tVUik=/470x0/2014/07/18/google-borrar-historial-busquedas3.jpg`

I'm seeing about a 7 to 1 ratio in storage cost for the inodes per file and the actual resized files on disk. We could implement a custom storage class to reduce the # of directories used but wanted to run this issue by you all before going off and implementing something that isn't standard. Though it seems the hash being a directory is the actual root cause.

As the following would have all year, month, days, and 470x0 image requests live in the same directories. All 2014 in fist, all 07 in a subdirectory, etc.
`/v2/2014/07/18/470x0/google-borrar-historial-busquedas3.jpg`

Example directory structure on disk

```
2014
...
|
--- 07
      |
       --- 18
             |
              --- 470x0
                     |
                     --- google-borrar-historial-busquedas3.jpg
                     --- another-image.jpg
                     --- yet-another-image.jpg
|
--- 08
      |
      --- 01
....

```

The other question I had is there a way to disable the original cached image directory that thumbor uses after pulling in the original before applying the transformations? While this will give a huge performance benefit for the http(s) loader it doesn't give us much benefit since we are loading the images from the same disk. Currently we implemented a job to remove the cache directory at a set interval to recover disk space for those files.

**Comment by masom** [comment]
You could use a `no_storage` for the `STORAGE` which will not use any cache after downloading an image.

For `RESULT_STORAGE` and the `LOADER` custom code is probably what you are looking for.

Just make sure the python modules can be imported by thumbor and it will be able to use them.

**Comment by beenanner** [comment]
Thanks @masom. Outside of the inode question so am I correct to assume there is no need for the cache if you are reading source images and writing resized images from the same disk locally (aka using the file loader)? Setting the `STORAGE = no_storage` would have no impact on performance and would actually save disk space? :-)

**Comment by masom** [comment]
@beenanner Yes, if using `STORAGE = no_storage` then thumbor will not store an intermediary file.

The process is like this:
- Check the `result_storage` if the media is already available with the requested options
- If not, check the `storage` for a copy of the original
  - Process and store with the `result_storage`
- If not, use the `loader` to fetch the original.
  - Store the original with the `storage`
  - Process and store with `result_storage`

**Comment by beenanner** [comment]
Awesome thanks for the explanation!
