### ISSUE TITLE
GIFV in production?

### ISSUE THREAD

**Issue by cartrdgeproduct** [thumbor/thumbor#800]
Is anyone using GIFV functionality in production? With the recent rollout on Safari that supports autoplaying inline videos without audio tracks - GIFV seems like it can finally work in production.

The problem with Safari is that it requires support for byte range requests. Running Thumbor behind Nginx with mp4 psuedo streaming support doesn't work with requests that Thumbor handles. This seems to be because Nginx psuedo streaming / range requests - do not work in conjunction with the proxy pass directive.

That's how it appears to me at least. So I'm wondering if anyone is using GIFV in production and has it working on Safari? If so, how was that achieved?

I guess a follow up question is - Does thumbor support range requests? and If not, could/should it?

Thank you very much!

**Comment by masom** [comment]
@cartrdgeproduct https://popkey.co does run GIFV in production and we submitted many patches to improve scalability.

The trade-off with proxy and byte-range requests is to use a CDN like CloudFront or Fast.ly which will start working with byte-range on subsequent requests for the same file.

`Mobile < --- > CF < --- > Nginx < --- > Thumbor`

The first request will not support the byte-range but subsequent ones will.

**Comment by cartrdgeproduct** [comment]
@masom Thanks for the information there, I really appreciate it. 

I am however uncomfortable with the "first request will not support byte-range" option. Again, I appreciate the practicality of that suggestion but I don't think that will work for us. After digging deeper, I think the best way to handle this is on either the 1) Thumbor side or create a 2) custom proxy.

1) Supporting range requests in Thumbor makes a lot of sense to me. Different upstream caching layers (varnish/nginx/etc) whether local/CDN/both either don't support psuedo streaming on first request or require the downstream proxy to handle byte ranges. Which is annoying but they probably have their reasons. Nginx forums have people asking how to get around this limitation going back 6 or 7 years. Most seem to settle for a static file solution. But that doesn't work very well when you don't know what the client browser is going to request - large number of potential sizes.

2) The other option that comes to mind is some kind of light weight proxy that would be able to handle byte range requests of various types. Probably just place that in front of Thumbor for GIFV requests which would then add range options to the request without needing anything special from Thumbor. It's obviously just one more thing to have in the stack which is lame - but it should work.

Not really sure which is the better option. Also not sure what would be needed to support ranges in Thumbor directly. I looked into "tornado" which appears to be Thumbors application server and supposedly is does support range requests https://github.com/tornadoweb/tornado/issues/785 and has for some time. But attempting to do so locally always results in a full response instead of a range - probably need to pass some headers?? If you know where to look I can poke around but I don't know very much about this code.

**Comment by masom** [comment]
A custom proxy would probably be the simplest implementation. PopKey looked into it about a year ago and we were surprised to discover NGINX didn't support range requests when a file isn't available locally.

Implementing byte-range on thumbor has some performance implications. In a clustered environment instances might share a common cache but mostly do not store all possible files locally. Answering a byte-range means thumbor must reprocess the transformation (or luckily find the result in a cache) before answering with the requested range.

**Comment by masom** [comment]
Oh also, thumbor could support range-requests, it just needs to be implemented in the image handle to return a specific subset of bytes instead of the full response. It would come at a great cost given that thumbor needs to reprocess the entire resource before being able to serve it.

**Comment by cartrdgeproduct** [comment]
So, Fastly can actually respond to a range request correct even on a MISS (the first request). So, we are just going to run everything behind Fastly which solve a few problems at once.

But not everyone will want to do that, clearly. For me this issue is closed but for anyone searching for a solution you could try:

- A local cache that will respond to range requests on the first request - not sure if that's pure Varnish or custom functionality for Fastly. If I wasn't cool with the Fastly solution, I would start here.

- A custom proxy app as described above. Really small and light weight proxy app which could respond to range headers on first request - hacking around the lack of functionality in NGINX. But then put that file onto disk so range/MP4 stuff works for NGINX on later requests.
