### ISSUE TITLE
unrecognized raw mode for some GIFS

### ISSUE THREAD

**Issue by matolivier** [thumbor/thumbor#802]
### Thumbor request URL

iimgft01.int.local/8zX63EXcSQElm0aj9oyMa5Wd--U=/fit-in/80x40/filters:fill(white,true)/http%3A//assets.server.local/logos/organismes/150/logo_centre_150_1465552778.gif
### Expected behaviour

The GIF file is supposed to be downloaded locally by thumbor and then resized and served to the requester.
### Actual behaviour

Thumbor can't fetch the picture and outputs this stack trace:

```
2016-09-01 11:04:05 thumbor:DEBUG METRICS: inc: response.count:1
2016-09-01 11:04:05 thumbor:DEBUG METRICS: inc: storage.miss:1
2016-09-01 11:04:05 thumbor:DEBUG METRICS: timing: original_image.fetch.200.assets.server.local:56
2016-09-01 11:04:05 thumbor:DEBUG METRICS: inc: original_image.status.200:1
2016-09-01 11:04:05 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 142, in get_image
    self.context.request.image_url
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 575, in _fetch
    fetch_result.buffer = self.context.request.engine.read(extension)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/pil.py", line 200, in read
    self.image.save(img_buffer, FORMATS[ext], **options)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1657, in save
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 760, in load
    self.im.putpalette(*self.palette.getdata())
ValueError: unrecognized raw mode
```
### Operating system

Debian 8
thumbor=6.0.1 (fetched from pip). Same behaviour with thumbor 6.5.1 with pip dependencies up-to-date (on 09/01/2016).
### Your thumbor.conf

ENGINE = 'thumbor.engines.pil'
SECURITY_KEY = "toto"

I have seen [this issue from pillow github](https://github.com/python-pillow/Pillow/issues/646), but I'm not sure we are using pillow as the stack mentions PIL. And as the pictures come from many clients, the mentioned workaround can't be envisaged (and I haven't found much ressources about what is 'mode P' in gifs).

If I change the engine from 'thumbor.engines.pil' to 'graphicsmagick_engine' it works. But graphicsmagick_engine seems outdated and probabely vulnerable.

Any clue about what to do?

Regards,
Matthieu

**Comment by matolivier** [comment]
I answer to myself. A workaround is using the directive USE_GIFSICLE_ENGINE to bypass the engine by gifsicle.

There are a few drawbacks listed in the documents but they should now impact in my case.
http://thumbor.readthedocs.io/en/latest/configuration.html?highlight=smart%20crop#use-gifsicle-engine

**Comment by danielmotaleite** [comment]
Please reopen the ticket, i have the same problem and switching engines is just a workaround, not the solution. If the gif is corrupted, warn about it, if not, the bug should be fixed. Either way, a aborting and a stack makes hard to debug where and why it is happening

**Comment by danielmotaleite** [comment]
I just found that mine requests are usually .jpg urls, but at least in the few tests i have done, the image is really a gif... so probably this error show when the image is "corrupted" for the extension. At least thumbor should warn about bad image format and probably send back a broken image icon (so people can notice is bad and fix it)

**Comment by matolivier** [comment]
I don't know if it is about gif corruption. I had it with several gifs this way, and my developer had no issues at all with the same version of thumbor installed on his computer.

He was using no configuration (default settings so). When I tried the same way he did, I still had the stack trace on fetch. I haven't been able to figure out why.

**Comment by danielmotaleite** [comment]
for me it is gif renamed as jpg... but i suspect that this might also happen in gif engine, if the engine finds something different (animated gif maybe?). The other engine is more forgiving and of course, can manage just fine animated gif.

Anyway, thanks for reopening, lets see what the devs say

**Comment by JensVerneuer** [comment]
Happens also to me. Contact me in case you need real live examples.

**Comment by wiredfool** [comment]
FWIW, this is not related to https://github.com/python-pillow/Pillow/issues/646, but the underlying issue appears to be fixed in https://github.com/python-pillow/Pillow/pull/2374, which among other changes fixes the handling of palettes when saving.

**Comment by masom** [comment]
Closing this since it has been fixed in upstream package.

Cheers!

**Comment by matolivier** [comment]
@wiredfool, thank you for your update.

**Comment by wiredfool** [comment]
You're welcome.
