### ISSUE TITLE
Requests hang on exceptions in engine.read

### ISSUE THREAD

**Issue by joetempleman** [thumbor/thumbor#808]
If an exception is thrown in `engine.read`, the exception is not handled properly and the request hangs forever. It also takes a long time for the error to be logged and never logs the access log at all. To reproduce I just added `raise Exception()` in the beginning of the pil engine.read method (the original exception we encountered was from a custom engine). Any ideas on how to handle this error better? 
### Thumbor request URL

'localhost:8888/unsafe/smart/filters:quality(30)/https%3A%2F%2Fi.imgur.com/5Rz3K34.jpg'
### Expected behaviour

It should return a 500
### Actual behaviour

It hangs indefinitely
### Operating system

ubuntu
### Your thumbor.conf

```
FILTERS = [
    'thumbor.filters.quality'
]
ENGINE = 'thumbor.engines.pil'


STORAGE = 'thumbor.storages.no_storage'
STORAGE_EXPIRATION_SECONDS = 0
RESULT_STORAGE_EXPIRATION_SECONDS = 0
HTTP_LOADER_CURL_ASYNC_HTTP_CLIENT = True
LOADER = 'thumbor.loaders.http_loader'
```

**Comment by Savar** [comment]
please see my pull request #871 for "why" this happens..
