### ISSUE TITLE
Thumbor process on multi core

### ISSUE THREAD

**Issue by vishaalgc** [thumbor/thumbor#809]
I was actually trying to do a load test on my thumbor service to see the stability of my setup. I came to see that the thumbor process was only using one CPU core but not both. Can any one confirm the same ? If its the case, then is there a solution to run the thumbor service on multiple cores ?  YOu can see it here in my case http://imgur.com/a/MmuQZ

**Comment by dhardy92** [comment]
yes this is python threading design. https://docs.python.org/2/library/threading.html
You should run several python process (one per core -1)
then load balance it with a proxy like nginx running locally (for the last core)
see https://github.com/thumbor/thumbor/wiki/Hosting#production-environment
