### ISSUE TITLE
Thumbor storing things in /tmp even though storage is disabled

### ISSUE THREAD

**Issue by jeffjo** [thumbor/thumbor#811]
### Expected behaviour

Thumbor should not be storing anything in /tmp
### Actual behaviour

Our /tmp directory keeps filling up with temporary files that are 11.2MB in size, even though STORAGE is set to no_storage. Example filenames include /tmp/tmpabqjco, /tmp/tmpcN0kau. I thought it may be the resultant images and I see that RESULT_STORAGE defaults to None. I don't see a no_storage module under results_storages (at least for v6.0.1), so I'd assume its default is for it to be disabled or to use file_storage. If it's the latter, my understanding is that RESULT_STORAGE_FILE_STORAGE_ROOT_PATH defaults to /tmp/thumbor/result_storage, but that directory doesn't exist.
### Operating system

Ubuntu 16.04.1 LTS
### Your thumbor.conf

ALLOW_OLD_URLS               = False
ALLOW_UNSAFE_URL             = False
AUTO_WEBP                    = True
MAX_AGE                      = 31536000
MAX_SOURCE_SIZE              = 100000
QUALITY                      = 75
SECURITY_KEY                 = redacted
WEBP_QUALITY                 = 75
STORAGE                      = 'thumbor.storages.no_storage'

**Comment by Arthien** [comment]
What are the settings for your loaders and results? There's a chance it is not storages that is saving the files.

**Comment by jeffjo** [comment]
My original post contained the entire thumbor.conf, so I'm using the defaults. For LOADER, the default is `http_loader` and for RESULT_STORAGE, it is `None` (if I'm reading the code correctly).

**Comment by hhankj2u** [comment]
Why you sure that /tmp files created by Thumbor?

Some of thumbor's dependencies using /tmp folder to create tmp files. But it will delete that files very fast.
I think you situation related with /tmp partition. Maybe that partition had been mounted with noexec option. 
You can try to run thumbor under another tmp folder using this *TMPDIR=/path/to/another/tmp/folder *, put it before your thumbor command.

**Comment by jeffjo** [comment]
We figured it out. It turns out we were missing an executable that processes certain types of images, which resulted in thumbor throwing an error and leaving the files in /tmp. Thanks for looking.
