### ISSUE TITLE
If origin image is 403, Thumbor should respond with the same 403 response

### ISSUE THREAD

**Issue by okor** [thumbor/thumbor#827]
### Thumbor request URL
https://cdn0.vox-cdn.com/thumbor/eSW8vP8BwDWe8s2CXujIRhHGvA0=/0x45:480x315/1600x900/cdn0.vox-cdn.com/uploads/chorus_image/image/631/0.jpg

### Expected behaviour
Should respond with a 403.

### Actual behaviour
Responds with a 404.

### Operating system
Ubuntu

We are using the 5.2-master branch: https://github.com/thumbor/thumbor/commit/da5e1a60d7730cdd5aca2f9959f1ff4a92ae63ea

The issue is that the origin image `http://assets.sbnation.com/uploads/chorus_image/image/631/0.jpg` actually doesn't exist. If it did, it would be an S3 object. The request is clearly invalid and should return a non-200 response from Thumbor but I think it's a bit deceptive to mutate the 403 to a 404 and makes it more difficult to debug problems.

Here is the full request chain with all caching layers broken down into individual requests:
![404_does_not_cache_blur](https://cloud.githubusercontent.com/assets/142910/19906701/37313708-a052-11e6-89a3-27a19629e625.jpg)

**Comment by Arthien** [comment]
You are getting a 404, but because it's being mutated, but because the image does not exist on YOUR thumbor instance. Now I agree this can make debugging a bit confusing, but it would be best to keep the errors agnostic to their origin. While thumbor is getting a 403 from the source it is trying to retrieve from, it should not carry it over to the client. You should only get a 403 if the image stored on your instance returns 403. Otherwise, 404 is appropriate.

**Comment by masom** [comment]
@okor I remember asking about this a while ago when implementing LoaderResult.

It basically boils down to: https://github.com/thumbor/thumbor/blob/master/thumbor/loaders/http_loader.py#L67

Should thumbor just proxy the response/response code from upstream? This would potentially open security vulnerabilities.

**Comment by okor** [comment]
@masom I don't really grok how that could open up security vulnerabilities, assuming crypto signing is turned on it (and some jerk doesn't have your key) should short circuit the request before it tries the origin (if I remember correctly) so you couldn't for instance use it as a way to brute force `ls` some file system. Not sure what else security wise would be an issue. Though I'm far from a security expect and happy to close the ticket based on the quorum.
