### ISSUE TITLE
Incorrect link to docs

### ISSUE THREAD

**Issue by mklickman** [thumbor/thumbor#831]
### Thumbor request URL
http://thumbor.org/

### Expected behaviour
Clicking on the "documentation" link should bring the user to the current documentation at http://thumbor.readthedocs.io/en/latest/index.html

### Actual behaviour
Clicking the documentation link instead still brings the user to the outdated wiki at https://github.com/thumbor/thumbor/wiki

### Operating system
n/a

### Your thumbor.conf
n/a

**Comment by Savar** [comment]
@heynemann can you update the thumbor website?

**Comment by heynemann** [comment]
I can, but it will take some time. I think @rfloriano can update it easier.

**Comment by Savar** [comment]
@rfloriano can you take over?

**Comment by scorphus** [comment]
Done!
