### ISSUE TITLE
Request for the next release timeline

### ISSUE THREAD

**Issue by sshquack** [thumbor/thumbor#832]
Hello,

Sorry for creating this issue. I wasn't sure if there is a better way to reach out to the devs. We recently came across an uncaught exception issue, and it turned out that issue has already been fixed by @rfloriano in the commit https://github.com/thumbor/thumbor/commit/7e4f88d0a8a72bf2e6bf95fc6ae185c359dcd69e Thank you for fixing it super-fast!

Unfortunately, the most recently version that been published on PyPI, which is 6.1.5, does not have this fix that we would like to see. Could you please let us know when the next release is expected to be cut, and also how I can help with it?

Thanks!

**Comment by sshquack** [comment]
Thanks to @scorphus for releasing 6.2.0 in commit https://github.com/thumbor/thumbor/commit/53ed5fc84ccdc1d54b04ff9d3eff1deb70fa4d7f! Also, kudos to @eduherraiz for bumping Thumbor version of `apsl` docker images in commit https://github.com/APSL/docker-thumbor/commit/174630b32d02462d5ac2c4e873591cdf835a8319. Closing out this issue for now. Thank you :)

**Comment by kevbaldwyn** [comment]
Sorry for bringing this up again - I was looking around for some info on milestones or a release schedule and saw this issue.

We're in a similar position to @sshquack was when he opened this issue. There has been a particular issue fixed that affects smart crop and s3 storage that has been resolved by #721, #722 and #864. I appreciate that the devs don't want to release every little fix but for us it's currently a major blocker on getting thumbor into production.

**Comment by scorphus** [comment]
@kevbaldwyn: Good news! We're very close to releasing a new version, which might happen in a couple of days or so. Please, bare with us until we do so :-)

**Comment by kevbaldwyn** [comment]
@scorphus That would be amazing! How can I keep track of new releases?

**Comment by scorphus** [comment]
@kevbaldwyn: Our our Slack channels (thumbor.slack.com) I believe are a good resource to keep up-to-date.

**Comment by varshithr** [comment]
Is the slack invite only? If so, can you add me? UN : varshith@scriptbees.com
