### ISSUE TITLE
Thumbor fails to process escaped parenthesis 

### ISSUE THREAD

**Issue by carlos4ndre** [thumbor/thumbor#833]
Hi Thumbor Team! 

I'm new to Thumbor so ignore this if not an actual issue, so I'm currently using [branch.io SDK](https://dev.branch.io/getting-started/branch-universal-object/#parameters) to develop an IOS app that apparently doesn't like urls with parenthesis, except when encoded. 
After encoding the parenthesis, the url is valid but fails when reaching Thumbor, most likely due to the fact the format is not supported or expected.
Am I doing something wrong here? What options do I have to get around this?

My thumbor url is looking something this:
`http://thumbor.docker:8888/unsafe/fit-in/640x440/smart/filters:fill%28transparent%29/http://www.carlosandre.me/images/(revl).jpg`

And these are the error messages I'm getting:
```
thumbor_1        | 2016-11-17 11:12:55 thumbor:WARNING ERROR retrieving image http://filters:fill(transparent)/http://www.carlosandre.me/images/(revl).jpg: [Errno -2] Name or service not known
thumbor_1        | 2016-11-17 11:12:55 tornado.access:ERROR 504 GET /unsafe/fit-in/640x440/smart/filters:fill%28transparent%29/http://www.carlosandre.me/images/(revl).jpg (192.168.99.1) 39.30ms
```

Running on version *6.0.1* using the docker image from `apsl/thumbor`.

**Comment by masom** [comment]
It seems like the URL received by thumbor is invalid: `http://filters:fill(transparent)/http://www.carlosandre.me/images/(revl).jpg: [Errno -2] Name or service not known`

There is also something weird in how your request is made, the hostname is not part of the URL anymore.

The path to your image should also be URL encoded, otherwise the `http://` portion might confuse some URL parsers: `http%3A%2F%2Fwww.carlosandre.me%2Fimages%2F(revl).jpg`

**Comment by carlos4ndre** [comment]
Using parenthesis in the url is no longer an issue for me, but before closing this issue, it would like to highlight that Thumbor doesn't support escaped parenthesis on the its filters section. 

*** Working url ***
http://thumbor.docker:8888/unsafe/fit-in/640x440/smart/filters:fill(transparent)/http%3A%2F%2Fwww.carlosandre.me%2Fimages%2F%28revl%29.jpg

*** Broken url ***
http://thumbor.docker:8888/unsafe/fit-in/640x440/smart/filters:fill%28transparent%29/http%3A%2F%2Fwww.carlosandre.me%2Fimages%2F%28revl%29.jpg

Error message:
```
thumbor_1        | 2017-02-09 12:47:16 thumbor:WARNING ERROR retrieving image http://filters:fill(transparent)/http://www.carlosandre.me/images/(revl).jpg: [Errno -2] Name or service not known
thumbor_1        | 2017-02-09 12:47:16 tornado.access:ERROR 504 GET /unsafe/fit-in/640x440/smart/filters:fill%28transparent%29/http%3A%2F%2Fwww.carlosandre.me%2Fimages%2F%28revl%29.jpg (192.168.99.1) 35.37ms
```

This is something that can be improved in future releases. 
Thanks for your support @masom, much appreciated.
