### ISSUE TITLE
crop Face detection

### ISSUE THREAD

**Issue by kayyazka** [thumbor/thumbor#835]
Hello

 need help,
I want to cut a picture of a face it , how to ?
i  use opencv to crop image,this my configuration

DETECTORS =    [
    'thumbor.detectors.face_detector',
    'thumbor.detectors.feature_detector',
    #'thumbor.detectors.profile_detector',
    #'thumbor.detectors.glasses_detector',
    #'thumbor.detectors.queued_detector',
    ]

## Defaults to: 'haarcascade_frontalface_alt.xml'
FACE_DETECTOR_CASCADE_FILE = 'haarcascade_frontalface_alt.xml'

![nirvana](https://cloud.githubusercontent.com/assets/13530910/20586283/36365226-b235-11e6-8b51-babb560ca05c.PNG)

thank you in advance

**Comment by masom** [comment]
@kayyazka Could you elaborate on what you are trying to do?

**Comment by heynemann** [comment]
Since this was a long time ago and requester did not respond, closing it.
If you have any further questions on this issue, please reopen it.
