### ISSUE TITLE
Thumbor run on Pycharm Error: server.py: error: unrecognized arguments:

### ISSUE THREAD

**Issue by wangbaifeng** [thumbor/thumbor#836]
### Thumbor run Error

I am using the default installed， I don't know why，I don't know why there is an error。

I think server.py line 120 "server_parameters = get_server_parameters(arguments)" is error

### Actual behaviour
$ python server.py
Console:
usage: server.py [-h] [--version] [-p PORT] [-i IP] [-f FD] [-c CONF]
                 [-k KEYFILE] [-l LOG_LEVEL] [-a APP] [-d]
server.py: error: unrecognized arguments: server.py

### Operating system
Mac OS

### Your thumbor.conf
Default

**Comment by wangbaifeng** [comment]
@masom Please help me

**Comment by masom** [comment]
@wangbaifeng To run thumbor you just need to setup a virtualenv with python 2.7, enable it, `pip install .` in the source folder and type `thumbor`. `server.py` isn't made to be executed directly.

**Comment by wangbaifeng** [comment]
@masom Thanks!
 I have a question，Use opencv-engine can't watermark Chinese characters？

**Comment by masom** [comment]
That would depend on your python build (wide chars/narrow chars), OpenCV, etc.

You might also need to supply a specific font: http://stackoverflow.com/questions/24544461/chinese-encoding-in-python-opencvcv2-puttext-method
