### ISSUE TITLE
[Feature Proposal] Manual crop from image edge

### ISSUE THREAD

**Issue by nicysneiros** [thumbor/thumbor#853]
### Thumbor request URL
This is an example of a image that I want to crop 20 pixels from each side:
http://localhost:8888/unsafe/20x20:980x480/https://s3-us-west-1.amazonaws.com/powr/defaults/image-slider2.jpg

### Actual behaviour
I have some images that has a white border on top and bottom of it and I need to remove that. This is an example:
http://coremedia.mris.com/image/V2/1/e2XfORWO-dmQ8YG_DV2Fh4cB4H18licC9dRRcDaQO_5Mw_4Aop7qiUSoj4lErA9eGik1B57nvE2P--rN8C1I1Q.jpg

Now, lets say I don't know the size of the image before hand. According to the documentation, the cropping is done before resizing, so I can't resize the image before cropping in one call. I had done something like this:

http://localhost:8888/unsafe/20x20:980x480/http://localhost:8888/unsafe/1000x500/https://s3-us-west-1.amazonaws.com/powr/defaults/image-slider2.jpg

This solution means 2 requests to thumbor, which was deprecating the performance. I also tried using trim feature, but it didn't worked as I expected on my images.

### Proposed behaviour
The manual crop feature works fine, but it would be nice if we could also pass as parameter the amount of pixels we want to crop from each side. I have implemented a solution locally for this, but I was wondering if this is a feature worth adding to the project. Adding my solution, the URL for cropping, lets say 20 pixels from each side of a image would be:

http://localhost:8888/unsafe/E20x20:20x20/https://s3-us-west-1.amazonaws.com/powr/defaults/image-slider2.jpg

I added a parameter `E` in the URL right before the usual manual cropping  parameters. I also implemented this considering percentages, instead of pixels. In this way we crop the image according to its size. If we want to crop a image 10% from each side, we could add the parameter `P`:

http://localhost:8888/unsafe/P10x10:10x10/https://s3-us-west-1.amazonaws.com/powr/defaults/image-slider2.jpg

If you all think this is a valid feature to be added, I can create a pull request so we can discuss about this. Thanks!

**Comment by heynemann** [comment]
The [trim](http://thumbor.readthedocs.io/en/latest/usage.html#trim) parameter seems to be what you need, right?

**Comment by nicysneiros** [comment]
@heynemann, actually no. If I have the following image:
http://coremedia.mris.com/image/V2/1/e2XfORWO-dmQ8YG_DV2Fh4cB4H18licC9dRRcDaQO_5Mw_4Aop7qiUSoj4lErA9eGik1B57nvE2P--rN8C1I1Q.jpg

I want to remove the white border at the top and at the bottom. If I use the trim parameter, I'm only able to remove the top border, but not the bottom:
http://localhost:8888/unsafe/trim:top-left/coremedia.mris.com/image/V2/1/e2XfORWO-dmQ8YG_DV2Fh4cB4H18licC9dRRcDaQO_5Mw_4Aop7qiUSoj4lErA9eGik1B57nvE2P--rN8C1I1Q.jpg

I've also tried using `trim:bottom-right`, but no luck.

**Comment by heynemann** [comment]
On Wed, Feb 8, 2017 at 5:35 PM, Nicolle Cysneiros <notifications@github.com>
wrote:

> http://coremedia.mris.com/image/V2/1/e2XfORWO-dmQ8YG_
> DV2Fh4cB4H18licC9dRRcDaQO_5Mw_4Aop7qiUSoj4lErA9eGik1B57nvE2P--rN8C1I1Q.jpg


We can't trim that image. It has a copyright notice in the bottom left that
says "trend". Also the color in the top is not consistent, it's kind of a
gradient.

Percentage based cropping has been requested before, I just fail to see how
that's better than the actual pixels. I think percent based is very risky
in that you might end up cropping the wrong image.

Cheers,
Bernardo Heynemann

**Comment by nicysneiros** [comment]
Yep, you are right. If we remove the copyright, the trim tool does the job.

I understand your concern with percentage based cropping. To use that, one should always know what kind of image will be used in the application. However, the current manual crop feature requires you to know the size of the image beforehand. That's why I implemented a manual crop where you could tell the amount of pixels to be cropped from each side of the image.

For my application, the percentage based cropping did the trick, since we know what kind of images we are showing.

Thanks for your attention :)

**Comment by heynemann** [comment]
NP. Closing this.
If you have any further questions on this issue, please reopen it.

**Comment by timfernando** [comment]
> Yep, you are right. If we remove the copyright, the trim tool does the job.
> 
> I understand your concern with percentage based cropping. To use that, one should always know what kind of image will be used in the application. However, the current manual crop feature requires you to know the size of the image beforehand. That's why I implemented a manual crop where you could tell the amount of pixels to be cropped from each side of the image.
> 
> For my application, the percentage based cropping did the trick, since we know what kind of images we are showing.
> 
> Thanks for your attention :)

@nicysneiros hi, do you happen to still have your percentage code? :) 

We're hitting the same problem that you were, where we do not know the size of the source image but have a crop percentage stored in our DB and would rather avoid making a metadata request to get the data first.
