### ISSUE TITLE
Upscaling not working with fit-in

### ISSUE THREAD

**Issue by verglor** [thumbor/thumbor#856]
original image 152x152

### Thumbor request URL
/unsafe/fit-in/320x200/...
/unsafe/fit-in/320x200/filters:fill(aaa)/...

### Expected behaviour
The image should be upscaled to 200x200 to fit in 320x200 frame preserving aspect ratio.
If fill filter is used, then it should upscale to 200x200 with 60px padding on right and left to create desired 320x200 image.

### Actual behaviour
The image stays in original size 152x152 as if no_scale filter was applied.
If fill filter is used, then original size 152x152 is padded to 320x200 (padding all over the original image)

**Comment by Savar** [comment]
I think the documentation is misleading here.
The old wiki (https://github.com/thumbor/thumbor/wiki/Usage) says:

```
fit-in means that the generated image should not be auto-cropped and otherwise just fit in an imaginary box specified by ExF. If a full fit-in is specified, then the largest size is used for cropping (width instead of height, or the other way around). If adaptive fit-in is specified, it inverts requested width and height if it would get a better image definition;
```
and the newer one http://thumbor.readthedocs.io/en/latest/usage.html?highlight=fit-in
is saying in the "overview" the same
```
fit-in means that the generated image should not be auto-cropped and otherwise just fit in an imaginary box specified by ExF;
```
but below in the more exact explanation it states:
```
The fit-in argument specifies that the image should not be auto-cropped and auto-resized to be EXACTLY the specified size, and should be fit in an imaginary box of “E” width and “F” height, instead.
```
which isn't correct but should say "not be auto-cropped and if required auto-resized to fit in an imaginary box of the specified "E" width and "F" height..."

**Comment by Savar** [comment]
`no_upscale` is only used if you ask for a specific size `/320x200/` but without the `/fit-in/` and the `fill` filter acts as documented http://thumbor.readthedocs.io/en/latest/filling.html?highlight=fill

**Comment by heynemann** [comment]
This will be present in thumbor's next release.

If you have any further questions on this issue, please reopen it.
