### ISSUE TITLE
Thumbor not deleting the files into /tmp/thumbor/storage

### ISSUE THREAD

**Issue by fmunteanu** [thumbor/thumbor#857]
### Expected behaviour
Temporary files should be deleted after 1 minute, into /tmp/thumbor/storage directory. There are no error messages into supervisord logs, expect the usual stuff of a missing image.

### Actual behaviour
The files and directories are not deleted, example of files left in place, older than 5 minutes:
```
# find /tmp/thumbor/storage -mmin 5 -exec ls -lahrt {} + | wc -l
1228

# find /tmp/thumbor/storage -mmin 5 -exec ls -lahrt {} + | head -n 5
-rw-r--r--. 1 nginx nginx 1.7K Feb 10 16:27 /tmp/thumbor/storage/6f/8e9c44dbd187a01e721bd10e7dc0a35866dff0.detectors.txt
-rw-r--r--. 1 nginx nginx 1.7K Feb 10 16:27 /tmp/thumbor/storage/fe/a8955d962207fdeec011c27ae5768503f9ca95.detectors.txt
-rw-r--r--. 1 nginx nginx  19K Feb 10 16:27 /tmp/thumbor/storage/ea/3bdeed829d1149fe132305533e4d18155b7ac0
-rw-r--r--. 1 nginx nginx 1.7K Feb 10 16:27 /tmp/thumbor/storage/ea/3bdeed829d1149fe132305533e4d18155b7ac0.detectors.txt
-rw-r--r--. 1 nginx nginx  37K Feb 10 16:27 /tmp/thumbor/storage/3f/3984458e423c62c07da5dac854e14cb3d2197b

# find /tmp/thumbor/storage -mmin 5 -exec ls -lahrt {} + | tail -n 5
-rw-r--r--. 1 nginx nginx  25K Feb 10 16:28 /tmp/thumbor/storage/c6/56f235c3bbbb839e7671103e290464d867f0b4
-rw-r--r--. 1 nginx nginx 1.7K Feb 10 16:28 /tmp/thumbor/storage/99/5e323ab2b9526bfb05fdb399e74354ad77e640.detectors.txt
-rw-r--r--. 1 nginx nginx  35K Feb 10 16:28 /tmp/thumbor/storage/72/389e19945c59bebe007742c9c0de35b01223bf
-rw-r--r--. 1 nginx nginx 1.7K Feb 10 16:28 /tmp/thumbor/storage/c6/56f235c3bbbb839e7671103e290464d867f0b4.detectors.txt
-rw-r--r--. 1 nginx nginx  24K Feb 10 16:28 /tmp/thumbor/storage/09/402bdfae5e3df8bd55e41a6d480ca4b2390584
```

### Operating system
CentOS 7.3 64 bits

### Your thumbor.conf
```
# cat /etc/thumbor.conf
ALLOW_OLD_URLS = False
ALLOW_UNSAFE_URL = False
DETECTORS = [
	'thumbor.detectors.face_detector',
	'thumbor.detectors.feature_detector',
	'thumbor.detectors.glasses_detector',
	'thumbor.detectors.profile_detector'
]
HTTP_LOADER_MAX_CLIENTS = 1024
MAX_AGE = 2592000
MAX_AGE_TEMP_IMAGE = 60
STORAGE = 'thumbor.storages.file_storage'
```

**Comment by masom** [comment]
Thumbor currently does not reap files once their max age has expired, it simply re-process them.

Right now you could run your `find ...` command as a cron job with `-exec rm {} \;` instead of ls.

**Comment by fmunteanu** [comment]
Thank you! I did not know. The [documentation](https://github.com/thumbor/thumbor/wiki/Configuration#storage_expiration_seconds) says:
> STORAGE_EXPIRATION_SECONDS
> This options specifies the default expiration time in seconds for the storage.
> i.e.: 60 (1 minute), 0 (never caches) or None (never expires)

**Comment by TheNha** [comment]
Hi @fmunteanu. I configed STORAGE_EXPIRATION_SECONDS=60 in thumbor.config. But It not work. 
All file in folder /data/storage/ not deleted. How did you make it work? Thanks you.
