### ISSUE TITLE
wrong face detect for crop (headless)

### ISSUE THREAD

**Issue by conghai** [thumbor/thumbor#860]
**# I was try crop with this image:** 
![Image Orginal](https://vcdn01.vietstar.net/source/fb/2017-02/235/15/52f88945db61ccc164c10068ddb12719.jpg)

**# I try crop size: 350x200 and result is headless:**
![Image croped](http://image.prntscr.com/image/13c949f1ef294a9285a04fcc400339f8.png)

**Comment by okor** [comment]
@conghai Please include the request url and your Thumbor config ... just like the issue template specifies. Otherwise we won't have no idea how to debug the problem.

**Comment by heynemann** [comment]
Since this was opened in February and reporter failed to respond I'm closing it.

If you have any further questions on this issue, please reopen it.
