### ISSUE TITLE
Watermark Not Scaling Down

### ISSUE THREAD

**Issue by r0bdiabl0** [thumbor/thumbor#874]
### Thumbor request URL
http://localhost/unsafe/400x400/filters:watermark(http://localhost/very_large_watermark.png,-1,-1,50)/http://localhost/photo.jpg

### Expected behaviour
When using the watermark filter, I would create a large watermark image that can be used for large and small images. The watermark image should scale down to fit the size of the output image.

### Actual behaviour
When using the watermark filter along with any resizing of an image, the watermark does not scale to the output image. If I have a small image at 100x100 and my watermark is 1000x10, the watermark is too big for the image. If I have large image at 1000x1000 and my watermark is small, then it is too small to see on the big image.

### Operating system
Ubuntu

### More detail

The watermark image I am using has a logo to the left and copyright information to the right. It is 1000x30 (300 dpi) in size. Images on our site very from 4096x4096 to 100x100. By using a large watermark, it ensures that it can be seen on any of these images. But it has to scale down to fit the image output for this to work.

I can resize the image on the fly using thumbor for the watermark itself but this ends up putting a huge load on the server because it has to recreate the watermark for every image. If I'm displaying 20 or more images, the server starts to lag and crash. So this is not a very efficient work-around.

It should be built into thumbor that the watermark auto scales with the image.

Am I doing something wrong?

**Comment by mpilar** [comment]
You can always use thumbor to scale the watermark (use a thumbor URL as the argument to watermark filter).

**Comment by r0bdiabl0** [comment]
I mentioned that in the More Detail section. It causes performance issues because of all the hits when accessing a lot of images.

It should be real simple to add a check to the watermark.py that gets the height and width of the image being watermarked and comparing it against the watermark sizes. Then if the watermark is larger, reduces the watermark to fit within the image size.

I'll try to look at it but my Python skills are nil.

**Comment by mpilar** [comment]
@r0bdiabl0 
How does the watermark filter know the size to use? 
Are you going to end up with the whole image watermarked  if the watermark is too big? 

Maybe add an argument to watermark that scales to a certain percent of the size of the crop. Perhaps an option to maintain the original aspect ratio or not.

**Comment by r0bdiabl0** [comment]
So I was able to pinpoint why using thumbor to resize the watermark was having a performance hit. It was because I was calculating the height from the width and it was adding a decimal, which was breaking the thumbor url. Now things are moving faster and I'm good with this option.

However, I still think it would be nice to have some sort of flag on the watermark filter that if set to true, it will scale down the watermark with the image. With this flag, the watermark filter would just read in the original dimensions of the watermark image and compare them against the image having the watermark added to it.

Again, I'll try to play with this but if someone else knows how to do it, please, that would be great.

**Comment by Savar** [comment]
@r0bdiabl0 please see the referenced pull request
