### ISSUE TITLE
URL shortener to prevent filter issues?

### ISSUE THREAD

**Issue by fmunteanu** [thumbor/thumbor#876]
I noticed there are some URL issues when filters are used with latest Android version of Google Chrome. URL sample pasted from a link received into an email opened on my Android phone:
```
https://thumbor.domain.com/unsafe/filters:grayscale%28%29/domain.com/images/test.jpg
```

Desktop version of Chrome does not have this issue. How difficult could be to implement a Tornado URL shortener, similar to:
https://github.com/nellessen/tornado-shortener/

I believe it will be beneficial in providing a short URL and also solve the compatibility link format issues with various browsers.

**Comment by Savar** [comment]
are you talking about something like that? https://github.com/thumbor-community/shortener

**Comment by fmunteanu** [comment]
I saw that. I think your implementation will be cleaner? It would be nice to have an option which automatically provides the shorter and stores it in Redis.

**Comment by masom** [comment]
Thumbor is currently unaware of uploaded files, making automatic shortened urls somewhat hard. https://github.com/thumbor-community/shortener can be extended to support a few more things.
