### ISSUE TITLE
Add docs for the distributed_collage filter

### ISSUE THREAD

**Issue by scorphus** [thumbor/thumbor#891]
Add documentation to the new [`distributed_collage`](https://github.com/thumbor/thumbor/blob/master/thumbor/filters/distributed_collage.py) filter.

**Comment by HectorNM** [comment]
Thanks for noticing this!

It looks like distributed_collage filter mooved to [a separated project.](https://github.com/globocom/thumbor-distributed-collage-filter), so I think the project team can close this issue.
