### ISSUE TITLE
502 on http://thumborize.me/

### ISSUE THREAD

**Issue by sibelius** [thumbor/thumbor#900]
502 on http://thumborize.me/

![image](https://cloud.githubusercontent.com/assets/2005841/24252459/468dbe22-0fbc-11e7-9237-ee2ea0edda5b.png)

**Comment by DominikAngerer** [comment]
Still the same - http://thumborize.me/?url=https%3A%2F%2Fwww.storyblok.com

**Comment by Savar** [comment]
I guess @heynemann needs to check that..

**Comment by gabellini** [comment]
Any news about this issue?

**Comment by andreaugusto** [comment]
Heya, @gabellini. We are going to take a look at it. Will update this issue as soon as a fix arises.

**Comment by SergioJorge** [comment]
Hey @sibelius.
Thanks for feedback !

Now thumborize.me came back to life ;)

**Comment by sibelius** [comment]
awesome, tks

**Comment by mate-h** [comment]
This is still happening.

**Comment by arouca** [comment]
Hey @mate-h it's working now :)
