### ISSUE TITLE
Delay in last GIF frame is incorrect when using gifv

### ISSUE THREAD

**Issue by okor** [thumbor/thumbor#903]
### Thumbor request URL
https://cdn0.vox-cdn.com/thumbor/BbnJ1AHcTSqqFdPKSVuyJgf_yr8=/0x0:2432x1556/1720x0/filters:focal(0x0:2432x1556):gifv():no_upscale()/cdn0.vox-cdn.com/uploads/chorus_asset/file/8251197/7GPW_LivingRoom.gif

### Expected behaviour
The resulting GIFv video should be 4 seconds in duration.

### Actual behaviour
The video is 2 seconds in duration.

### Operating system
OSx & Ubuntu

### Your thumbor.conf
```
...
OPTIMIZERS = [
    # 'thumbor.optimizers.jpegtran',
    'thumbor.optimizers.gifv',
]
...
```

### Source of the bug
I did some debugging and have discovered that this issue is being caused by the `scale` filter used in the ffmpeg command. The scale filter we are using ensures that the video has an even number of pixels for both width and height - because odd pixel numbers in mp4 at least is not valid and ffmpeg will puke.

I have submitted a bug with ffmpeg https://trac.ffmpeg.org/ticket/6294#ticket

However, in the mean time (which could be an hour or years in ffmpeg world) we have some options on our end as well. Mainly, we could drop the scale filter from the command and instead enforce even number of pixels ourselves before we perform the transformation to mp4/webm format. I have confirmed that removing the filter option fixes this problem.

So, I'd like to get some opinions on what we should do.

**Comment by Savar** [comment]
This is kind of tricky, because it somehow will create a bad situation as soon as the bug is fixed.

Is there any chance to first scale with the gif engine the gif into an even width/height and then push it to ffmpeg?

**Comment by Savar** [comment]
something like this could handle the issue as long as ffmpeg cannot scale correctly, but this is really not good tested.. I'm not sure if it is a problem to reload the image into the `context.request.engine` and also I'm not sure if this would crash if gifsicle is enabled and the opencv-engine is being used, because if `context.request.engine` is opencv-engine it cannot handle the image.

```diff
diff --git a/thumbor/optimizers/gifv.py b/thumbor/optimizers/gifv.py
index 21525a7..98e97f4 100644
--- a/thumbor/optimizers/gifv.py
+++ b/thumbor/optimizers/gifv.py
@@ -22,6 +22,29 @@ class Optimizer(BaseOptimizer):
     def optimize(self, buffer, input_file, output_file):
         format, command_params = self.set_format()

+        scale = True
+
+        if format == 'mp4':
+            engine = self.context.request.engine
+
+            # I actually would need the result engine to not
+            # change the request engines content
+            # and also to be sure that it can handle gif (see: opencv engine)
+            engine.load(buffer, '.gif')
+
+            width, height = engine.size
+
+            if width % 2 != 0 or height % 2 != 0:
+                engine.resize((width/2)*2, (height/2)*2)
+
+            buffer = engine.read('.gif')
+
+            with open(input_file, 'wb') as f:
+                f.write(buffer)
+
+            scale = False
+
+
         command = [
             self.context.config.FFMPEG_PATH,
             '-y',
@@ -49,13 +72,18 @@ class Optimizer(BaseOptimizer):
             '23',
             '-maxrate',
             '500k',
-            '-vf',
-            'scale=trunc(iw/2)*2:trunc(ih/2)*2',
             output_file,
             '-loglevel',
             'error'
         ]

+        if scale:
+            logger.info("adding scale filter")
+            command += [
+                '-vf',
+                'scale=trunc(iw/2)*2:trunc(ih/2)*2'
+            ]
+
         with open(os.devnull) as null:
             subprocess.call(command, stdin=null)
         self.context.request.format = format
```

**Comment by Savar** [comment]
besides that a quick test with pillow and gifsicle enabled worked on your example (by using the even one as well as requesting 1721x0 for the uneven which triggered a resize)

**Comment by okor** [comment]
@Savar Yeah, we're on the same page here, I came up with something similar https://github.com/thumbor/thumbor/compare/master...voxmedia:gif-frame-fix?expand=1

The main difference is that it happen higher up in the code path and doesn't require an additional image transform operation, which should be faster and produce higher quality results. Just thinking out loud here.

And I agree that ffmpeg could fix the problem like tomorrow and then we'd have a work around in a branch/release. However, I think that's acceptable. I'll be monitoring the status of the ffmpeg bug and welcome others to do the same. If the status should change we could revert the workaround. I did try the ffmpeg `crop` filter as well with the same results - frame timings incorrect. So it may be a bug with several/all filters.

**Comment by okor** [comment]
@Savar Don't have tests yet but I'll probably put a PR in either later today or Monday as I'm busy atm. If you have time to create a PR you're welcome to steal my code and add some tests.

**Comment by Savar** [comment]
as you were able to see, I didn't have the time ;)

**Comment by okor** [comment]
Merged fix. Made a new release https://github.com/thumbor/thumbor/releases/tag/6.3.2
