### ISSUE TITLE
how to convert a gif image to animated webp？Support?

### ISSUE THREAD

**Issue by wangbaifeng** [thumbor/thumbor#909]
### Thumbor request URL
http://(thumborServer)/unsafe/filters:format(webp)/imageUrl://xxx.gif

### Expected behaviour
out animated webp

### Actual behaviour
ERROR 504 POST

### Operating system
OSx EI Capitan

### Your thumbor.conf
ENGINE = 'opencv_engine'

**Comment by okor** [comment]
Animated webp is not yet currently supported but has been talked about https://github.com/thumbor/thumbor/issues/583

Someone just needs to do the work.
