### ISSUE TITLE
png to jpeg not working

### ISSUE THREAD

**Issue by antiloopgmbh** [thumbor/thumbor#911]
### Thumbor request URL
The request url for the issue you are having, you can swap the host name with a fake
http://example.com/unsafe/trim:top-left:50/fit-in/634x794/filters:fill(white,true):format(jpeg):quality(80)/http%3A%2F%2Fcdn.aboutyou.de%2Ffile%2Fea7f87cbdc1121a0bb08251efc0c7b17%3Fwidth%3D1024%26height%3D1024

### Expected behaviour
Tell us what should happen
the source file is a png file and i would like to get a jpg file

### Actual behaviour
Tell us what happens instead
everything works, except it doesn't convert it to jpg

### Operating system
OSx, Ubuntu, etc
Debian

### Your thumbor.conf
Your config file (WARNING: replace your SECURITY_KEY key with a dummy key or your key will become public)

**Comment by okor** [comment]
@antiloopgmbh 
- Please include your config (sanitize your secrets)
- Please let us know what version of thumbor you are using, if you're not sure you can run `thumbor --version`

We need your config because you may not have the `format` plugin activated. You seem to be using at least 3 filters. So you should have at least these three activated like so:
```
FILTERS = [
    'thumbor.filters.quality',
    'thumbor.filters.fill',
    'thumbor.filters.format',
]
```

**Comment by okor** [comment]
With those 3 filters active, I get a jpeg response:

![http- 2f 2fcdn aboutyou](https://cloud.githubusercontent.com/assets/142910/25184896/becb3cba-24e9-11e7-96d4-1b990fd6749f.jpg)

**Comment by okor** [comment]
Since we haven't heard back and I can't replicate this behavior, I'm closing. Feel free to reopen if issues persists.

**Comment by antiloopgmbh** [comment]
I have checked my FILTERS setting and sure enough i missed to enable the filter... Thanks a lot!
Gerold
