### ISSUE TITLE
Result file storage file deletion strategy

### ISSUE THREAD

**Issue by Frexuz** [thumbor/thumbor#912]
I can't seem to find any suggestions on this:

How would you suggest me to delete unused files in my result file storage? (As files are kept on the disk forever). The total size of the result storage on disk is about 100GB.

An example would be if I change a specific image to a new size, from 100x100 -> 120x120 for example. In some cases, I will KNOW that 100x100 won't be used anymore.

Except for manually going into the result storage directory and `rm -r` all "100x100" directories, is there maybe a smarter way? :)

**Comment by okor** [comment]
There has never been an official solution. But something like a cron job that `rm`s images that are older than whatever amount of time makes sense to you.

**Comment by Frexuz** [comment]
I thought so... just checking :) I'll close.

**Comment by okor** [comment]
If you come up with a good solve we could probably include in our docs as a suggestion. You're not the first person to ask and it is tricky.

In part to avoid this issue completely we use local Varnish in front of Thumbor and another Varnish as a proxy cache for origin images [via a custom plugin](https://github.com/voxmedia/thumbor_rewrite_loader). This way Varnish which has a fixed capacity will use a LRU algorithm to kick out cache as needed. And all results are also cached by CDN but each POP may hit thumbor several times for the same images so it's still helpful to have a local cache.

**Comment by masom** [comment]
PopKey used Redis as a shared storage with LRU eviction.
