### ISSUE TITLE
Incorrect crop of GIF image, image shifted outside view

### ISSUE THREAD

**Issue by MattBlissett** [thumbor/thumbor#913]
### Thumbor request URL

The source image is [from Wikimedia commons](https://commons.wikimedia.org/wiki/File:River_gambia_Niokolokoba_National_Park.gif).

Run through Thumbor without any modifications it looks like this:

![River](http://api.gbif.org/v1/image/SXA1AuaMtj-svAgEv30RxwNnhDk=/https://upload.wikimedia.org/wikipedia/commons/d/d5/River_gambia_Niokolokoba_National_Park.gif)

I request a 150x150px crop:

![crop](http://api.gbif.org/v1/image/y2cCzHBnQMAyUZsvRojis_DrhDQ=/150x150/https://upload.wikimedia.org/wikipedia/commons/d/d5/River_gambia_Niokolokoba_National_Park.gif)

http://api.gbif.org/v1/image/y2cCzHBnQMAyUZsvRojis_DrhDQ=/150x150/https://upload.wikimedia.org/wikipedia/commons/d/d5/River_gambia_Niokolokoba_National_Park.gif

### Expected behaviour
150x150px extent of image

### Actual behaviour
The image is shifted 42 pixels to the right.

```
$ identify River_gambia_Niokolokoba_National_Park.gif
River_gambia_Niokolokoba_National_Park.gif GIF 150x150 150x150+42+0 8-bit sRGB 256c 19.4KB 0.000u 0:00.000
```

Opening it in GIMP shows a 150x150px layer, shifted 42px outside the "view".

### Operating system
CentOS Linux release 7.3.1611 (Core)

```
Package                          Version
-------------------------------- ---------
backports-abc                    0.5
backports.ssl-match-hostname     3.5.0.1
boto                             2.42.0
CairoSVG                         1.0.7
certifi                          2017.4.17
chardet                          2.2.1
configobj                        4.7.2
decorator                        3.4.0
derpconf                         0.8.1
futures                          3.1.1
graphicsmagick-engine            0.1.1
iniparse                         0.4
IPy                              0.75
kitchen                          1.1.1
libthumbor                       1.3.2
numpy                            1.11.1
perf                             0.1
pexif                            0.15
pgmagick                         0.6.2
Pillow                           3.4.2
pip                              9.0.1
policycoreutils-default-encoding 0.1
pycrypto                         2.6.1
pycurl                           7.43.0
pygobject                        3.14.0
pygpgme                          0.3
pyliblzma                        0.5.3
python-dateutil                  2.5.3
pytz                             2017.2
pyudev                           0.15
pyxattr                          0.5.1
seobject                         0.1
sepolicy                         1.1
setuptools                       0.9.8
singledispatch                   3.4.0.3
six                              1.10.0
slip                             0.4.0
slip.dbus                        0.4.0
statsd                           3.2.1
thumbor                          6.3.1
tornado                          4.5
urlgrabber                       3.10
yum-metadata-parser              1.1.4
```

### Your thumbor.conf

```
AUTO_WEBP = False
MAX_AGE = 31536000
LOADER = 'thumbor.loaders.http_loader'
AWS_ACCESS_KEY   = ''
AWS_SECRET_KEY   = ''
S3_LOADER_BUCKET = ''
STORAGE_BUCKET = ''
RESULT_STORAGE_BUCKET = ''
STORAGE = 'thumbor.storages.file_storage'
RESULT_STORAGE = 'thumbor.result_storages.file_storage'
ENGINE = 'graphicsmagick_engine'
ALLOW_UNSAFE_URL = False
ALLOW_OLD_URLS = False
HTTP_LOADER_CONNECT_TIMEOUT = 120
HTTP_LOADER_REQUEST_TIMEOUT = 120
FILE_STORAGE_ROOT_PATH = '/mnt/auto/image-cache/thumbor/storage'
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/mnt/auto/image-cache/thumbor/result_storage'
RESULT_STORAGE_STORES_UNSAFE = True
```

**Comment by okor** [comment]
Super weird. Have never seen this before and would strongly suspect this is an issue with the `graphicsmagick_engine` https://github.com/thumbor/graphicsmagick-engine You might want to submit a bug with that project. Also worth mentioning that `graphicsmagick_engine` hasn't been updated since 2014 and might be totally busted.

If the `graphicsmagick_engine` engine is not truly required or you are open to experimenting, I'd suggest using the default engine `thumbor.engines.pil` and use gifsicle (requires external package on host) and enable gifsicle with `USE_GIFSICLE_ENGINE=True`. Anecdotally I have found that gifsicle is much more reliable and gives higher quality results and PIL ... but I haven't seen the PIL engine ever mess up the dimensions like this.

**Comment by MattBlissett** [comment]
Thanks okor, using `thumbor.engines.pil` has avoided the problem.

**Comment by heynemann** [comment]
I also opened the image you mention and in Photoshop CS6 it looks perfectly fine.

If you have any further questions on this issue, please reopen it.
