### ISSUE TITLE
Specify allowed sizes and origins

### ISSUE THREAD

**Issue by lazerscience** [thumbor/thumbor#914]
Instead of signing URLs I would rather specify a list of allowed sizes and image origins (eg. domains), so that my javascript client is able to request the sizes that are needed. I don't think that this is possible yet, but maybe somebody could quickly point me into the right direction how this would be possible to implement?

**Comment by okor** [comment]
You have not included your config. In the future, please mind the suggested format for submitting an issue. It helps us folks who give our free time to the project, faster responses to issues means we can help more people. Thanks 😄 

Check out the configuration documentation: http://thumbor.readthedocs.io/en/latest/configuration.html 

Specifically:

`ALLOW_UNSAFE_URL` => [allows unsigned urls](http://thumbor.readthedocs.io/en/latest/configuration.html#allow-unsafe-url)

`ALLOWED_SOURCES` => [a whitelist of origin image domains ](http://thumbor.readthedocs.io/en/latest/configuration.html#allowed-sources)

`MAX_WIDTH' and 'MAX_HEIGHT` => [This means that no image that thumbor generates will have a width larger than MAX_WIDTH or height larger than MAX_HEIGHT](http://thumbor.readthedocs.io/en/latest/configuration.html#max-width-and-max-height)

^ That last one might not be what you were looking for, it restricts the output image dimensions. Not the input file in bytes or pixels. I don't *think* that's currently possible. Though I question the utility of that idea, if you control the source images you should be able to only allow images that meet your requirements to be uploaded to your storage system.

But if you are uploading directly to Thumbor, you can restrict by bytes. Check out `UPLOAD_MAX_SIZE` [here](http://thumbor.readthedocs.io/en/latest/configuration.html#upload)

**Comment by okor** [comment]
@lazerscience I have an amendment. 

There **IS** a way to refuse source images over a certain size. As stated in the config:
```
# maximum size of the source image in Kbytes.
# use 0 for no limit.
# this is a very important measure to disencourage very
# large source images.
# THIS ONLY WORKS WITH http_loader.
MAX_SOURCE_SIZE = 0
```

So with that last option you should be good to go : )
