### ISSUE TITLE
Image not upscaling

### ISSUE THREAD

**Issue by ruediggger** [thumbor/thumbor#915]
### Thumbor request URL
The request url for the issue you are having, you can swap the host name with a fake
http://example.com/unsafe/trim:top-left:50/fit-in/634x794/filters:fill(white,true):format(jpeg):quality(80)/source.jpg

### Expected behaviour
Tell us what should happen
I would like to first trim the white surroundings of the source image and then scale it up to the size i supplied in the url. 

### Actual behaviour
Tell us what happens instead
Actually it does work if the source image is big enough, but with smaller source images it doesn't work. For example with the image https://img.depauli.com/pimages/239/239728_norm.jpg i get a result image with 634x794, but the shirt itself doesn't take up the whole canvas space. I understand that this may usually be a good thing, since the image doesn't get scaled up, but in my case i would like it to behave that way.

### Operating system
OSx, Ubuntu, etc

### Your thumbor.conf
Your config file (WARNING: replace your SECURITY_KEY key with a dummy key or your key will become public)

**Comment by Savar** [comment]
see https://github.com/thumbor/thumbor/pull/878

**Comment by antiloopgmbh** [comment]
Thanks! Since i have installed Version Thumbor v6.3.2 (10-Apr-2017) i suppose i have to wait for the next release for the upscale() filter to be available.

**Comment by cristianbratu** [comment]
For those having issues with the pip thumbor package (thumbor 6.3.2), install from git source as the upscale filter is not included in the official pip package.

**Comment by heynemann** [comment]
If you have any further questions on this issue, please reopen it.
