### ISSUE TITLE
Redis setup issue

### ISSUE THREAD

**Issue by vishaalgc** [thumbor/thumbor#916]
I have setup thumbor over tc_redis. Added all the mentioned configuration in [this](https://github.com/thumbor-community/redis) link. Now im able to upload an image and its working fine but when doing a get using the obtained reponse Location. Its not showing the image.

  how do i physically see the uploaded images in tc_redis. And any methods to resolve this issue ?

Below is my thumbor configuration file

PRESERVE_EXIF_INFO = False
MAX_AGE = 24 * 60 * 60
MAX_AGE_TEMP_IMAGE = 0
SEND_IF_MODIFIED_LAST_MODIFIED_HEADERS = False
LOADER = 'thumbor.loaders.http_loader'
MAX_SOURCE_SIZE = 0
UPLOAD_ENABLED = True
UPLOAD_PHOTO_STORAGE = 'thumbor.storages.file_storage'
UPLOAD_PUT_ALLOWED = True
UPLOAD_DELETE_ALLOWED = True
UPLOAD_DEFAULT_FILENAME = 'image'
#STORAGE = 'thumbor.storages.file_storage'
#FILE_STORAGE_ROOT_PATH = '/etc/ImageData'
#STORAGE_EXPIRATION_SECONDS = None
#RESULT_STORAGE = 'thumbor.result_storages.file_storage'
#RESULT_STORAGE_EXPIRATION_SECONDS = None  
#RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/tmp/thumbor/result_storage'
RESULT_STORAGE_STORES_UNSAFE = False
STORES_CRYPTO_KEY_FOR_EACH_IMAGE = True
ENGINE = 'thumbor.engines.pil'
SECURITY_KEY = "MY_SECURE_KEY"
ALLOW_UNSAFE_URL = True

STORAGE='tc_redis.storages.redis_storage'
REDIS_STORAGE_IGNORE_ERRORS = True
REDIS_STORAGE_SERVER_PORT = 6379
REDIS_STORAGE_SERVER_HOST = 'localhost'
REDIS_STORAGE_SERVER_DB = 0
REDIS_STORAGE_SERVER_PASSWORD = None
RESULT_STORAGE='tc_redis.result_storages.redis_result_storage'
REDIS_RESULT_STORAGE_IGNORE_ERRORS = True
REDIS_RESULT_STORAGE_SERVER_PORT = 6379
REDIS_RESULT_STORAGE_SERVER_HOST = 'localhost'
REDIS_RESULT_STORAGE_SERVER_DB = 0
REDIS_RESULT_STORAGE_SERVER_PASSWORD = None

**Comment by masom** [comment]
> UPLOAD_PHOTO_STORAGE = 'thumbor.storages.file_storage'
I believe for this to work the files would have to be uploaded to the redis storage, not the file_storage.
