### ISSUE TITLE
Strip huge binary metadata

### ISSUE THREAD

**Issue by mijamo** [thumbor/thumbor#917]
### Thumbor request URL
http://thumbor-server/120x120/https://storage.googleapis.com/objektia-production.appspot.com/_/resources/5732694713434112/profile_pic/4HHS4D3EOU8ARRD5.jpg

### Expected behaviour
The final file should be really small and not have any huge binary metadata.

### Actual behaviour
The final file is around 640KB, among which 630KB or so is just binary metadata. The binary metadata has seen by exiftool is
```
A To B0                         : (Binary data 89958 bytes, use -b option to extract)
A To B2                         : (Binary data 89958 bytes, use -b option to extract)
A To B1                         : (Binary data 89958 bytes, use -b option to extract)
B To A0                         : (Binary data 145588 bytes, use -b option to extract)
B To A1                         : (Binary data 145588 bytes, use -b option to extract)
B To A2                         : (Binary data 145588 bytes, use -b option to extract)
Gamut                           : (Binary data 37009 bytes, use -b option to extract)
```
Thumbor removes already a lot of metadata but for some reason those are kept, which is really a problem for me. I am not exactly sure of what this metadata is supposed to be for but it also seems to have some weird color effect, and is not removed either by `strip_icc()`

### Your thumbor.conf
```
PRESERVE_EXIF_INFO=False
```

**Comment by kkopachev** [comment]
Looks like that's ICC profile `Profile-icc: 654352 bytes`
Adding `strip_icc()` filter works as expected and removes all these bytes. Make sure you enable the filter in config.

**Comment by mijamo** [comment]
I have 

```
FILTERS = ['thumbor.filters.brightness', 'thumbor.filters.contrast', 'thumbor.filters.rgb', 'thumbor.filters.round_corner', 'thumbor.filters.quality', 'thumbor.filters.noise', 'thumbor.filters.watermark', 'thumbor.filters.equalize', 'thumbor.filters.fill', 'thumbor.filters.sharpen', 'thumbor.filters.strip_icc', 'thumbor.filters.frame', 'thumbor.filters.grayscale', 'thumbor.filters.rotate', 'thumbor.filters.format', 'thumbor.filters.max_bytes', 'thumbor.filters.convolution', 'thumbor.filters.blur', 'thumbor.filters.extract_focal', 'thumbor.filters.no_upscale']
```

So if I'm not mistaken `strip_icc()` should be active, yet when I request `/unsafe/filters:strip_icc()/https://storage.googleapis.com/objektia-production.appspot.com/_/resources/5732694713434112/profile_pic/4HHS4D3EOU8ARRD5.jpg` I have the 650KB file with all that binary metadata in it.

Was there any other configuration needed to have `strip_icc` working?

**Comment by kkopachev** [comment]
Here's what I'm using:
```
docker run --rm -it -p 8000:8000 -e RESULT_STORAGE=thumbor.result_storages.no_storage \
 -e STORAGE=thumbor.storages.no_storage -e LOG_LEVEL=DEBUG \
 apsl/thumbor:6.3.0-simd-sse4
```

then downloaded file is just 16kb:
```
wget 'http://localhost:8000/unsafe/filters:strip_icc()/https://storage.googleapis.com/objektia-production.appspot.com/_/resources/5732694713434112/profile_pic/4HHS4D3EOU8ARRD5.jpg'
--2017-05-24 09:23:21--  http://localhost:8000/unsafe/filters:strip_icc()/https://storage.googleapis.com/objektia-production.appspot.com/_/resources/5732694713434112/profile_pic/4HHS4D3EOU8ARRD5.jpg
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16330 (16K) [image/jpeg]
Saving to: ‘4HHS4D3EOU8ARRD5.jpg’

4HHS4D3EOU8ARRD5.jpg               100%[===============================================================>]  15.95K  --.-KB/s    in 0s      

2017-05-24 09:23:21 (326 MB/s) - ‘4HHS4D3EOU8ARRD5.jpg’ saved [16330/16330]

```

**Comment by masom** [comment]
@mijamo The ICC profile is kinda useful and should usually not be randomly removed. The ICC profile can sometime be huge. There is a way to convert an image with an ICC profile to the Adobe RGB profile with ImageMagick, and then strip the ICC profile, giving a good enough representation.

Thumbor offers the `strip_icc()` filter if you want to remove it.

**Comment by kkopachev** [comment]
@masom image in question is in CMYK. Thumbor converts it to RGB anyway, so embedded CMYK profile is just useless.

**Comment by mijamo** [comment]
Thank you for your input and your time, now I guess my task is to understand what is the thing in my configuration that breaks the `strip_icc()` filter.

My setup is also built on top of `apsl/thumbor` so I will try to isolate what broke the feature and if there is a bug associated I will create a new issue. Otherwise I will just update this issue with the cause once I find it in case somebody encounters the same problem some day. meanwhile I guess this issue can be closed as it is not an actual issue.
