### ISSUE TITLE
MongoDB storage issue

### ISSUE THREAD

**Issue by vishaalgc** [thumbor/thumbor#918]
Hi,
  i have been trying to integrate tc-mongodb with thumbor. i have used needed conf changes from tc-mongodb and trying to upload images. Im getting a url and am able to access image with that url. When tried to physically access images im finding no data in my database. What am i doing wrong ?

PRESERVE_EXIF_INFO = False
MAX_AGE = 24 * 60 * 60
MAX_AGE_TEMP_IMAGE = 0
SEND_IF_MODIFIED_LAST_MODIFIED_HEADERS = False
LOADER = 'thumbor.loaders.http_loader'
MAX_SOURCE_SIZE = 0
UPLOAD_ENABLED = True
#UPLOAD_PHOTO_STORAGE = 'thumbor.storages.file_storage'
UPLOAD_PUT_ALLOWED = True
UPLOAD_DELETE_ALLOWED = True
UPLOAD_DEFAULT_FILENAME = 'image'
#STORAGE = 'thumbor.storages.redis_storage'
#FILE_STORAGE_ROOT_PATH = '/etc/ImageData'
STORAGE_EXPIRATION_SECONDS = None
#RESULT_STORAGE = 'thumbor.result_storages.file_storage'
RESULT_STORAGE_EXPIRATION_SECONDS = None  
#RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/tmp/thumbor/result_storage'
RESULT_STORAGE_STORES_UNSAFE = False
STORES_CRYPTO_KEY_FOR_EACH_IMAGE = True
ENGINE = 'thumbor.engines.pil'
ALLOW_UNSAFE_URL = True

# MONGO STORAGE OPTIONS
MONGO_STORAGE_SERVER_HOST = '192.168.6.153' # MongoDB storage server host
MONGO_STORAGE_SERVER_PORT = 27017 # MongoDB storage server port
MONGO_STORAGE_SERVER_DB = 'thumbor' # MongoDB storage server database name
MONGO_STORAGE_SERVER_COLLECTION = 'images' # MongoDB storage image collection

**Comment by Savar** [comment]
You probably didn't enable the storage for mongodb.. you only commented the file storage out but this is probably the default

Am 27. April 2017 02:56:38 MESZ schrieb Vishaal <notifications@github.com>:
>Hi,
>i have been trying to integrate tc-mongodb with thumbor. i have used
>needed conf changes from tc-mongodb and trying to upload images. Im
>getting a url and am able to access image with that url. When tried to
>physically access images im finding no data in my database. What am i
>doing wrong ?
>
>PRESERVE_EXIF_INFO = False
>MAX_AGE = 24 * 60 * 60
>MAX_AGE_TEMP_IMAGE = 0
>SEND_IF_MODIFIED_LAST_MODIFIED_HEADERS = False
>LOADER = 'thumbor.loaders.http_loader'
>MAX_SOURCE_SIZE = 0
>UPLOAD_ENABLED = True
>#UPLOAD_PHOTO_STORAGE = 'thumbor.storages.file_storage'
>UPLOAD_PUT_ALLOWED = True
>UPLOAD_DELETE_ALLOWED = True
>UPLOAD_DEFAULT_FILENAME = 'image'
>#STORAGE = 'thumbor.storages.redis_storage'
>#FILE_STORAGE_ROOT_PATH = '/etc/ImageData'
>STORAGE_EXPIRATION_SECONDS = None
>#RESULT_STORAGE = 'thumbor.result_storages.file_storage'
>RESULT_STORAGE_EXPIRATION_SECONDS = None  
>#RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/tmp/thumbor/result_storage'
>RESULT_STORAGE_STORES_UNSAFE = False
>STORES_CRYPTO_KEY_FOR_EACH_IMAGE = True
>ENGINE = 'thumbor.engines.pil'
>ALLOW_UNSAFE_URL = True
>
># MONGO STORAGE OPTIONS
>MONGO_STORAGE_SERVER_HOST = '192.168.6.153' # MongoDB storage server
>host
>MONGO_STORAGE_SERVER_PORT = 27017 # MongoDB storage server port
>MONGO_STORAGE_SERVER_DB = 'thumbor' # MongoDB storage server database
>name
>MONGO_STORAGE_SERVER_COLLECTION = 'images' # MongoDB storage image
>collection
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/thumbor/thumbor/issues/918

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by vishaalgc** [comment]
@Savar  what file storage options should i use in case of mongodb ?

**Comment by Savar** [comment]
probably `STORAGE = 'tc_mongodb.storages.mongo_storage'`

**Comment by lionants02** [comment]
LOADER compat tc_mongodb https://github.com/lionants02/thumbor_mongodb
