### ISSUE TITLE
Instagram filters

### ISSUE THREAD

**Issue by JoschaP** [thumbor/thumbor#919]
This project is really great.

If we focus to constribute more instagram filters, this project will be a huge success!

Nice work!

**Comment by andreaugusto** [comment]
Thanks for the feedback, @JoschaP! We really appreciate it!

We have some [built-in filters](http://thumbor.readthedocs.io/en/latest/filters.html#) and could always use some more :)

Making a filter is not a hard thing. We usually have a [Python module](https://github.com/thumbor/thumbor/blob/master/thumbor/filters/colorize.py) that calls a [C bind](https://github.com/thumbor/thumbor/blob/master/thumbor/ext/filters/_colorize.c) (for performance sake). The only issue here is getting the C optimization right. 

We are willing to make some new additions to Thumbor as new filters, new engines and stuff. Right now we are counting on the community to help us here. Should you want to contribute with a new filter or any other thing, just open a PR and we will help you out. Any help is appreciated!
