### ISSUE TITLE
background-size: contain

### ISSUE THREAD

**Issue by victornpb** [thumbor/thumbor#925]
what I'm trying to accomplish is something like the css property `background-size: contain` with thumbor.

I failed at every attempt, the closest I could came up is using `fit-in/WxH/filters:fill(white)` except that when W or H is greater than the picture dimensions it does not scale up, it only scale the picture down to the canvas. so if I have a picture of 500x500 and ask for 800x600 I expect a image of 800x600 with the original picture upscaled to 600x600 with pillarbox. 

I made an example what kind of behavior I want.
https://jsfiddle.net/Victornpb/x0hodtvv/show

----
I tried the undocumented `full-fit-in`  `adaptive-fit-in` `adaptive-full-fit-in` but none seems to do it. And their intents are not clear to me.

full-fit-in almost work, it does the job of scaling the image up, but when I use full-fit-in/1500x1000/filters:fill(white) I would expect a image with 250px of fill either side, but it doesn't, it CROPS the image for no reason.

**Comment by Savar** [comment]
please see #878 .. so either you try to use the master branch to get the bleeding edge of thumbor or you wait for the next release..

**Comment by heynemann** [comment]
We'll release a new version soon. Just have to get my head around thumbor before doing it :)

If you have any further questions on this issue, please reopen it.

**Comment by antiloopgmbh** [comment]
Hi @victornpb ,

i want to accomplish exactly the same thing. I also have install thumbor from master branch, but was not able to get the desired result. Did you have any luck?

Thanks,
Gerold
