### ISSUE TITLE
One-Time Upload Token #FeatureRequest

### ISSUE THREAD

**Issue by webdeb** [thumbor/thumbor#935]
Is there an Option in Thumbor to get an OneTime image Upload Token? 

cause I
- don't want to open the upload endpoint to the whole world
- don't want to proxy the images through my app-server

Instead, I think about a common scenario: 
- The client makes a request to the app-server, the app-server creates an One-Time Token for the Thumbor Service (could be based on some shared key, or the App-Server asks the thumbor for the Token directly)
- The client then sends the image with the Token to the Thumbor service

The Token could be a hash, for example expiration timestamp signed by some shared key between the app and thumbor. So very fast creation / verification should be possible, maybe a JWT, which can contain some additional information in the payload.

Or how would you suggest to handle it?

**Comment by mpilar** [comment]
Why not use [S3 form uploads](https://aws.amazon.com/articles/1434/) and then allow Thumbor off that S3 bucket?

**Comment by webdeb** [comment]
@mpilar sure, for me, the main idea for using thumbor, was to be able, to host the images on my own (cheap) server, but this is definitely an option for the future, thanks

**Comment by mpilar** [comment]
@webdeb I just think the feature is out of the scope of Thumbor, this can be easily handled by creating a form on your favorite web language and have it upload to Thumbor (or simply create a URL pointing to the folder it uploaded to).

**Comment by webdeb** [comment]
@mpilar thanks, but your suggestion would mean upload the image to the -> app -> to thumbor. So the image is first uploaded to the application, and at the second step securely to thumbor. 

Theoretically it should be possible, to let the user upload the image directly to thumbor in a simple and secure way, the only thing we would need, is a one-time (time-limited) token. This could be signed timestamp, which is valid for 30secs only.. 

So this would mean, my application generates a token which is signed with the secret. I am sending the image directly to thumbor, with the token. Thumbor just needs to verify that token, that is was signed by with the secret and voila.

**Comment by heynemann** [comment]
As I said in previous requests for uploading features, we'll probably remove uploading from thumbor to another project. As of today uploading is a very stitched version of what the actual uploading feature set should be. As such, we won't be implementing this in thumbor's codebase.
As soon as we release the uploading code in a different project, this may very well be a feature we'll implement.

If you have any further questions on this issue, please reopen it.

**Comment by webdeb** [comment]
this sounds great, thx!
