### ISSUE TITLE
Image processing on upload

### ISSUE THREAD

**Issue by MindFreeze** [thumbor/thumbor#938]
It should be possible to transform images before they are stored when uploading.

### Use case
I receive huge images and I want to store them in thumbor. But I do not need/want them to be stored full size and take up space. AFAIK thumbor does not allow resizing on upload and I have to do it on my own before upload.
So now I have an image server that can resize images, but need to resize my images without it and then send them to the image server.

**Comment by heynemann** [comment]
As I said in previous requests for uploading features, we'll probably remove uploading from thumbor to another project. As of today uploading is a very stitched version of what the actual uploading feature set should be. As such, we won't be implementing this in thumbor's codebase.
As soon as we release the uploading code in a different project, this may very well be a feature we'll implement.

If you have any further questions on this issue, please reopen it.

**Comment by kkopachev** [comment]
multiple decoding/encoding will create quality loss, so it's preferred to perform desired operations on a best quality image you have.
