### ISSUE TITLE
new feature: colour thief integration

### ISSUE THREAD

**Issue by osigida** [thumbor/thumbor#941]
it would be nice to have colour thief functionality integrated: https://github.com/fengsp/color-thief-py

this allows to get dominant colour and colour pallet for an image.

**Comment by masom** [comment]
There is also https://github.com/99designs/colorific

All that said, this is kinda out of scope for thumbor.

**Comment by osigida** [comment]
Hi @masom thanks a lot for the link.

I have a question so, why it is out of scope for thumbor? 
getting dominant colour is one of the common operation, and instead of creating yet_another_service we could use thumbor, who is responsible for the image management (croping, resizing, etc) 
sounds logical, or I get the idea wrongly?

**Comment by masom** [comment]
Thumbor itself is just a media processing server, it can be extended with https://github.com/thumbor-community/core ( see http://thumbor-community-core.readthedocs.io/en/latest/ ) to support more than that.

If you have the resources to contribute an extension that adds an endpoint to fetch dominant colours I would be happy to create a repository on https://github.com/thumbor-community

Extensions have full access to Tornado and Thumbor. Ex: https://github.com/thumbor-community/shortener

**Comment by osigida** [comment]
@masom oh, right, missed this part :-)
will have a look, thanks a lot!

**Comment by masom** [comment]
@osigida we've also been trying to reduce thumbor base dependencies, moving things out of thumbor/thumbor and into separate community packages. This allows/forces us to write thumbor in a more modular way.
