### ISSUE TITLE
thumbor:WARNING URL does not have hash or unsafe, or has both: /favicon.ico

### ISSUE THREAD

**Issue by automationninja** [thumbor/thumbor#942]
### Thumbor request URL
https://some-google-load-balancer.com/unsafe/4000x4000/754d56478a162948baf97e1b0c5d3f50/3_c892b2c2d8eb4a85337148dc3e030f40.jpg

### Actual behaviour

```
thumbor --version
Thumbor v6.3.2 (10-Apr-2017)
```

supervisord is starting 8 instances of thumber behind nginx.
The request to the image works and shows the re-sized image correctly, but I see the below error on the supervisor log.

```
2017-07-03 10:16:15 thumbor:WARNING URL does not have hash or unsafe, or has both: /favicon.ico
2017-07-03 10:16:15 tornado.access:WARNING 400 GET /favicon.ico (35.186.224.155) 1.32ms

```
### Operating system
```
Linux thumbor-ondemand 4.8.0-56-generic #61~16.04.1-Ubuntu SMP Wed Jun 14 11:58:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

### Your thumbor.conf
```
MAX_WIDTH = 50000
MAX_HEIGHT = 50000
MAX_PIXELS = 9000000000
PROGRESSIVE_JPEG = True
AUTO_WEBP = True
MAX_AGE = 7776000
RESPECT_ORIENTATION = True
ALLOW_ANIMATED_GIFS = False
ALLOW_UNSAFE_URL = True
RESULT_STORAGE_STORES_UNSAFE = False
LOADER = 'thumbor_cloud_storage.loaders.cloud_storage_loader'
CLOUD_STORAGE_PROJECT_ID = 'blabla'
CLOUD_STORAGE_BUCKET_ID = 'blabla'
```

```
Nginx:

upstream thumbor {
    server 127.0.0.1:8000;
    server 127.0.0.1:8001;
    server 127.0.0.1:8002;
    server 127.0.0.1:8003;
    server 127.0.0.1:8004;
    server 127.0.0.1:8005;
    server 127.0.0.1:8006;
    server 127.0.0.1:8007;
}

server {
    listen 80;
    listen [::]:80 ipv6only=on;

    server_name _;
    location / {
        proxy_pass http://thumbor;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ipv6only=on ssl;
    server_name _;

    ssl                  on;
    ssl_certificate      /etc/nginx/ssl/a.crt;
    ssl_certificate_key  /etc/nginx/ssl/b.key;

    ssl_session_timeout  5m;

    ssl_protocols  SSLv2 SSLv3 TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers   on;


    location / {
        proxy_pass http://thumbor;
    }
    location = /favicon.ico {
        log_not_found off;
    }
}
```

**Comment by Savar** [comment]
Do you test the image in your browser? Your browser will try automatically to find a /favicon.ico and this is not a valid url for thumbor. I see that you switch the logoff for /favicon.ico but I guess nginx is still passing it to the thumbor Backend which doesn't like that.

Am 3. Juli 2017 12:32:40 MESZ schrieb automationninja <notifications@github.com>:
>### Thumbor request URL
>https://some-google-load-balancer.com/unsafe/4000x4000/754d56478a162948baf97e1b0c5d3f50/3_c892b2c2d8eb4a85337148dc3e030f40.jpg
>
>### Actual behaviour
>
>```
>thumbor --version
>Thumbor v6.3.2 (10-Apr-2017)
>```
>
>supervisord is starting 8 instances of thumber behind nginx.
>The request to the image works and shows the re-sized image correctly,
>but I see the below error on the supervisor log.
>
>```
>2017-07-03 10:16:15 thumbor:WARNING URL does not have hash or unsafe,
>or has both: /favicon.ico
>2017-07-03 10:16:15 tornado.access:WARNING 400 GET /favicon.ico
>(35.186.224.155) 1.32ms
>
>```
>### Operating system
>```
>Linux thumbor-ondemand 4.8.0-56-generic #61~16.04.1-Ubuntu SMP Wed Jun
>14 11:58:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
>No LSB modules are available.
>Distributor ID: Ubuntu
>Description:    Ubuntu 16.04.2 LTS
>Release:        16.04
>Codename:       xenial
>```
>
>### Your thumbor.conf
>```
>MAX_WIDTH = 50000
>MAX_HEIGHT = 50000
>MAX_PIXELS = 9000000000
>PROGRESSIVE_JPEG = True
>AUTO_WEBP = True
>MAX_AGE = 7776000
>RESPECT_ORIENTATION = True
>ALLOW_ANIMATED_GIFS = False
>ALLOW_UNSAFE_URL = True
>RESULT_STORAGE_STORES_UNSAFE = False
>LOADER = 'thumbor_cloud_storage.loaders.cloud_storage_loader'
>CLOUD_STORAGE_PROJECT_ID = 'blabla'
>CLOUD_STORAGE_BUCKET_ID = 'blabla'
>```
>
>```
>Nginx:
>
>upstream thumbor {
>    server 127.0.0.1:8000;
>    server 127.0.0.1:8001;
>    server 127.0.0.1:8002;
>    server 127.0.0.1:8003;
>    server 127.0.0.1:8004;
>    server 127.0.0.1:8005;
>    server 127.0.0.1:8006;
>    server 127.0.0.1:8007;
>}
>
>server {
>    listen 80;
>    listen [::]:80 ipv6only=on;
>
>    server_name _;
>    location / {
>        proxy_pass http://thumbor;
>    }
>}
>
>server {
>    listen 443 ssl;
>    listen [::]:443 ipv6only=on ssl;
>    server_name _;
>
>    ssl                  on;
>    ssl_certificate      /etc/nginx/ssl/a.crt;
>    ssl_certificate_key  /etc/nginx/ssl/b.key;
>
>    ssl_session_timeout  5m;
>
>    ssl_protocols  SSLv2 SSLv3 TLSv1 TLSv1.1 TLSv1.2;
>    ssl_ciphers  HIGH:!aNULL:!MD5;
>    ssl_prefer_server_ciphers   on;
>
>
>    location / {
>        proxy_pass http://thumbor;
>    }
>    location = /favicon.ico {
>        log_not_found off;
>    }
>}
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/thumbor/thumbor/issues/942

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by kkopachev** [comment]
Does load balancer hits origin server on port 80? In that case you have to add `location = /favicon.ico` in that section too.

**Comment by automationninja** [comment]
@Savar and @kkopachev, I restricted access to nginx location via some regex conditions, so the problem solved itself, thanks for your help.
