### ISSUE TITLE
resizing causes PNGs to lose transparent background

### ISSUE THREAD

**Issue by ryuuseijin** [thumbor/thumbor#943]
### Thumbor request URL

    curl -v 'http://...../unsafe/fit-in/400x/filters:format(png)/.......' >out.png

Any PNG with transparency should work. Here is a test image: 
![scribble.png](https://user-images.githubusercontent.com/25781945/27951758-500e2398-6349-11e7-8c68-b9cd5e39e166.png)

### Expected behaviour
The background of out.png should be transparent.

### Actual behaviour
The background of out.png is black.

### Operating system
Debian Linux

### Your thumbor.conf
[thumbor.conf.txt](https://github.com/thumbor/thumbor/files/1124006/thumbor.conf.txt)

Scaling the image seems to be causing it. When I specify a width larger than the original, transparency is not lost.

**Comment by ryuuseijin** [comment]
Trying without fit-in and just resizing the image will also cause transparency to be lost.

**Comment by ryuuseijin** [comment]
I was able to isolate the issue to this line: https://github.com/thumbor/thumbor/commit/f945871a3673b1be9340ef9c1e3ac78d9f9fd359#diff-4766ae01206209cf72a83c6784669e00R134

**Comment by ryuuseijin** [comment]
Here is another issue which is probably caused by the same change: https://github.com/thumbor/thumbor/issues/945

**Comment by phunehehe** [comment]
@ryuuseijin yeah I found this issue too but wasn't sure whether it's really the same. If it's the same I don't mind moving my issue over here.

**Comment by phunehehe** [comment]
BTW I couldn't reproduce this issue.

Request URL: http://thumbor-vbox/unsafe/fit-in/400x/filters:format(png)/https://user-images.githubusercontent.com/25781945/27856360-3afeaf34-61b1-11e7-8445-32b0587c7c6f.png

Output looks good to me:
![6 3 2](https://user-images.githubusercontent.com/627831/27946048-8893e922-6322-11e7-8fc2-58a2a8949ede.png)

My configuration is the same as posted in https://github.com/thumbor/thumbor/issues/945.

**Comment by ryuuseijin** [comment]
Thanks! There was an additional step in our pipeline that changed the image's color depth. I've updated the image.

**Comment by rafaelfragosom** [comment]
@ryuuseijin is this solved? Is there a bug or not?

**Comment by ryuuseijin** [comment]
@rafaelfragosom it is a bug as far as I can tell. It can be reproduced with the updated example image (https://user-images.githubusercontent.com/25781945/27951758-500e2398-6349-11e7-8c68-b9cd5e39e166.png).

It only happens with images that have an indexed color mode.

**Comment by kkopachev** [comment]
Fixed in Pillow: https://github.com/python-pillow/Pillow/issues/2702

**Comment by phunehehe** [comment]
Just want to say I can now confirm this issue (I'm slow :)). Here's the resulting image using Thumbor 6.3.2:

![actual](https://user-images.githubusercontent.com/627831/30011491-3f392f46-916a-11e7-8c65-5b666038bb89.png)

**Comment by kkopachev** [comment]
If you upgrade pillow, it'll work as expected. Other option is to wait for next release of thumbor which includes https://github.com/thumbor/thumbor/pull/988

**Comment by kkopachev** [comment]
This issue should be resolved now with 6.4.0 released
