### ISSUE TITLE
PNG transparency problem since 6.3.0

### ISSUE THREAD

**Issue by phunehehe** [thumbor/thumbor#945]
### Thumbor request URL

http://thumbor-vbox/unsafe/fit-in/60x60/filters:no_upscale()/http://fake.net/cms/app/f/c/sg.png

### Expected behaviour

Here's the original:
![original](https://user-images.githubusercontent.com/627831/27906384-e9b7fd86-6275-11e7-873e-b50493c99063.png)

The image should be scaled down:
![expected](https://user-images.githubusercontent.com/627831/27906380-e02d49ce-6275-11e7-9eda-61b856d2c9db.png)

### Actual behaviour

The image appears mostly transparent, except around the edges:
![actual](https://user-images.githubusercontent.com/627831/27906334-b8044df8-6275-11e7-9a61-fa0846b262ea.png)

This seems to have started since 6.3.0. 6.2.1 doesn't have the issue.

### Operating system

NixOS

### Your thumbor.conf

```
SECURITY_KEY = 'dummy'
ALLOW_UNSAFE_URL = True
LOADER = 'thumbor.loaders.http_loader'
STORAGE = 'thumbor.storages.no_storage'
THUMBOR_LOG_FORMAT = '%(asctime)s %(name)s:%(levelname)s %(message)s'
THUMBOR_LOG_DATE_FORMAT = '%Y-%m-%d %H:%M:%S %s'
QUALITY = 90
OPTIMIZERS = [
    'thumbor.optimizers.jpegtran'
]
JPEGTRAN_PATH = '/nix/store/4ss2dmv9igk3z5xv88la9f38pzcdi2l6-mozjpeg-3.1/bin/jpegtran'
```

**Comment by heynemann** [comment]
Is this still happening?

**Comment by phunehehe** [comment]
I just tried using 8cebe1228cf2d78d6de84888b788dcbd7380854e (the tip of master as of now). It's still the same.

**Comment by phunehehe** [comment]
it seems like the fix is just waiting to be merged: https://github.com/thumbor/thumbor/pull/988

**Comment by phunehehe** [comment]
\o/
