### ISSUE TITLE
MAX_ID_LENGTH causes duplicate requests when using S3 storage

### ISSUE THREAD

**Issue by eerootsus** [thumbor/thumbor#946]
### Thumbor request URL
http://example.org/unsafe/901x485/smart/nginx/o/2017/07/06/6863821t1h7fe6.jpg

### Expected behaviour
A single request is issued to S3 for file `nginx/o/2017/07/06/6863821t1h7fe6.jpg`

### Actual behaviour
Seeing two requests to S3:
`nginx/o/2017/07/06/6863821t1h7fe` (obviously 404) and second one for `nginx/o/2017/07/06/6863821t1h7fe6.jpg`

### Your thumbor.conf
MAX_ID_LENGTH is set to 32 (apsl/docker-thumbor default)

Using community tc_aws module. Currently I can work around this by setting MAX_ID_LENGTH to 0.
But it seems unwanted overhead when using remote storages.

**Comment by masom** [comment]
The MAX_ID_LENGTH is only used if you use the Upload feature of Thumbor.

Setting it to 0 actually disables the check for uploaded files.

**Comment by heynemann** [comment]
If you have any further questions on this issue, please reopen it.
