### ISSUE TITLE
WARNING URL does not have hash or unsafe

### ISSUE THREAD

**Issue by mmoulou** [thumbor/thumbor#950]
Thumbor request URL

http://thumbor/image/819187fa2d3642cebb382a4070bfa911/toto

Expected behaviour
I've: 
a public thumbor configured as read only
a private thumbor configured with upload
Upload on Google cloud storage using: https://github.com/arielsalvo/thumbor-cloud-storage
When i Upload image using private Thumbor, the uri location returned starts with /image/*. Or according to : https://github.com/thumbor/thumbor/blob/master/thumbor/app.py
/image/* is not reachable when upload is disabled. So i can not access to the image url from the read thumbor.

Actual behaviour
http 404 
& log:url malformed 

Operating system

Debian: Jessie, Docker

## Defaults to: 'libthumbor.url_signers.base64_hmac_sha1'
URL_SIGNER = 'libthumbor.url_signers.base64_hmac_sha1'

################################################################################

## Defaults to: MY_SECURE_KEY
SECURITY_KEY = 'MY_SECURE_KEY'

## Defaults to: True
ALLOW_UNSAFE_URL = True

## Defaults to: True
ALLOW_OLD_URLS = True

## AWS access keys - used in thumbor_aws storage
AWS_ACCESS_KEY = ''
AWS_SECRET_KEY = ''

################################################################################

## Defaults to: True
ENABLE_ETAGS = True

################################################################################

## Defaults to: 32
MAX_ID_LENGTH = 32

################################################################################

## Defaults to: None
STATSD_HOST = None

## Defaults to: 8125
STATSD_PORT = 8125

## Defaults to: None
STATSD_PREFIX = None

################################################################################

## Defaults to: /tmp
FILE_LOADER_ROOT_PATH = '/data/loader'

################################################################################

## Defaults to: 5
HTTP_LOADER_CONNECT_TIMEOUT = 5

## Defaults to: 20
HTTP_LOADER_REQUEST_TIMEOUT = 20

## Defaults to: True
HTTP_LOADER_FOLLOW_REDIRECTS = True

## Defaults to: 5
HTTP_LOADER_MAX_REDIRECTS = 5

## Defaults to: 10
HTTP_LOADER_MAX_CLIENTS = 10

## Defaults to: False
HTTP_LOADER_FORWARD_USER_AGENT = False

## Defaults to: Thumbor/6.3.0
HTTP_LOADER_DEFAULT_USER_AGENT = 'Thumbor/6.3.0'

## Defaults to: None
HTTP_LOADER_PROXY_HOST = None

## Defaults to: None
HTTP_LOADER_PROXY_PORT = None

## Defaults to: None
HTTP_LOADER_PROXY_USERNAME = None

## Defaults to: None
HTTP_LOADER_PROXY_PASSWORD = None

## Defaults to: None
HTTP_LOADER_CA_CERTS = None

## Defaults to: True
HTTP_LOADER_VALIDATE_CERTS = True

## Defaults to: None
HTTP_LOADER_CLIENT_KEY = None

## Defaults to: None
HTTP_LOADER_CLIENT_CERT = None

## Defaults to: False
HTTP_LOADER_CURL_ASYNC_HTTP_CLIENT = False

################################################################################

## Defaults to: 2592000
STORAGE_EXPIRATION_SECONDS = 2592000

## Defaults to: False
STORES_CRYPTO_KEY_FOR_EACH_IMAGE = False

## Defaults to: /tmp/thumbor/storage
FILE_STORAGE_ROOT_PATH = '/data/storage'

################################################################################

## Defaults to: 0
UPLOAD_MAX_SIZE = 0

## Defaults to: False
UPLOAD_ENABLED = True

## Defaults to: thumbor.storages.file_storage
UPLOAD_PHOTO_STORAGE = 'thumbor_cloud_storage.storages.cloud_storage'

## Defaults to: False
UPLOAD_DELETE_ALLOWED = False

**Comment by mmoulou** [comment]
UP

**Comment by mmoulou** [comment]
UP

**Comment by heynemann** [comment]
I think you should create this issue in the project you are using to rewrite thumbor's URL. Since this is not the default way thumbor works its quite hard for us to help. Maybe @masom can help. 

I'm closing this as this probably is not an issue with thumbor.

If you have any further questions on this issue, please reopen it.
