### ISSUE TITLE
thumbor:ERROR Ignored error handling exif for reorientation

### ISSUE THREAD

**Issue by devopsberlin** [thumbor/thumbor#954]
### Thumbor request URL
https://foo.bar.com/unsafe/<any_size>x<any_size>/2a49ab01534574e8b8f9d7441/0_dd2099f123c8f03ba75bc85f1698.jpg

### Expected behaviour
Tell us what should happen

### Actual behaviour

I often see the following error in the Thumbor logs:

	2017-07-29 14:48:55 thumbor:ERROR Ignored error handling exif for reorientation
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/__init__.py", line 239, in _get_exif_segment
		segment = ExifSegment(None, None, self.exif, 'ro')
	  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 856, in __init__
		DefaultSegment.__init__(self, marker, fd, data, mode)
	  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 150, in __init__
		self.parse_data(data)
	  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 900, in parse_data
		ifd = IfdTIFF(self.e, offset, self, self.mode, tiff_data)
	  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 416, in __init__
		actual_data = self.embedded_tags[tag][1](e, the_data, exif_file, self.mode, data)
	  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 416, in __init__
		actual_data = self.embedded_tags[tag][1](e, the_data, exif_file, self.mode, data)
	  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 621, in ifd_maker_note
		if exif_file.make == "Canon":
	AttributeError: ExifSegment instance has no attribute 'make'

list of installed packages installed with pip:

	# pip freeze
	backports-abc==0.5
	boto==2.38.0
	certifi==2017.4.17
	chardet==2.3.0
	crcmod==1.7
	derpconf==0.8.1
	enum34==1.1.6
	future==0.16.0
	futures==3.1.1
	gax-google-logging-v2==0.8.3
	gax-google-pubsub-v1==0.8.3
	gcloud==0.18.3
	google-compute-engine==2.3.7
	google-gax==0.12.5
	googleapis-common-protos==1.5.2
	grpc-google-logging-v2==0.8.1
	grpc-google-pubsub-v1==0.8.1
	grpcio==1.4.0
	httplib2==0.10.3
	libthumbor==1.3.2
	meld3==1.0.2
	numpy==1.11.0
	oauth2client==4.1.2
	pexif==0.15
	Pillow==3.4.2
	ply==3.8
	protobuf==3.3.0
	psutil==3.4.2
	pyasn1==0.2.3
	pyasn1-modules==0.0.9
	pycrypto==2.6.1
	pycurl==7.43.0
	python-apt==1.1.0b1
	pytz==2017.2
	requests==2.9.1
	rsa==3.4.2
	setproctitle==1.1.8
	simplejson==3.8.1
	singledispatch==3.4.0.3
	six==1.10.0
	statsd==3.2.1
	supervisor==3.2.0
	thumbor==6.3.2
	thumbor-cloud-storage==3.0.0
	tornado==4.5.1
	urllib3==1.13.1

Thumbor conf:

	# cat /etc/thumbor.conf
	MAX_WIDTH = 50000
	MAX_HEIGHT = 50000
	MAX_PIXELS = 9000000000
	PROGRESSIVE_JPEG = True
	AUTO_WEBP = True
	MAX_AGE = 7776000
	RESPECT_ORIENTATION = True
	ALLOW_ANIMATED_GIFS = False
	ALLOW_UNSAFE_URL = True
	RESULT_STORAGE_STORES_UNSAFE = True
	LOADER = 'thumbor_cloud_storage.loaders.cloud_storage_loader'
	CLOUD_STORAGE_PROJECT_ID = 'foo-1277'
	CLOUD_STORAGE_BUCKET_ID = 'bar'
	RESULT_STORAGE = 'thumbor_cloud_storage.result_storages.cloud_storage'
	RESULT_STORAGE_CLOUD_STORAGE_PROJECT_ID = 'foo-1277'
	RESULT_STORAGE_CLOUD_STORAGE_BUCKET_ID = 'foo_result_storage'
	#RESULT_STORAGE_CLOUD_STORAGE_ROOT_PATH = 'result_storage'
	#RESULT_STORAGE_EXPIRATION_SECONDS
	QUALITY = 80

	
Ubuntu Version:
	
	# lsb_release -a
	No LSB modules are available.
	Distributor ID: Ubuntu
	Description:    Ubuntu 16.04.2 LTS
	Release:        16.04
	Codename:       xenial
	
	Linux thumbor-instance-group-us-east1-d-q4dp 4.10.0-27-generic #30~16.04.2-Ubuntu SMP Thu Jun 29 16:07:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by marcelometal** [comment]
Hi @devopsberlin, Is this still happening?

'pexif' was replaced by 'piexif'  (ref: 1d7f67c)
