### ISSUE TITLE
Failing to process further HTTP requests during connection timeout

### ISSUE THREAD

**Issue by tempuser14** [thumbor/thumbor#957]
### Thumbor request URL
http://thumbor/unsafe/200x0/http://user:password@remote-host/{picture-id}

### Actual behaviour
We currently experience an interesting behaviour of Thumbor when the outgoing connection times out (after the default 5s). Currently a Thumbor instance gets on average 2-3 requests/second, but when an outgoing connection gets a timeout then neither new outgoing (to `remote-host`) nor incoming (to Thumbor) TCP connections  are being created (and the established connections hang). We tracked with `netstat` the connections made to `remote-host` and basically before a `HTTP 599: Timeout while connecting` is logged:

1. no new TCP connections are built to the remote server and also no new incoming connections are established
2. during these 5 seconds only the already established connections are displyed (often there are only 2 connections, so HTTP_LOADER_MAX_CLIENTS is not reached)

Right after timeout `netstat` displays 10 established incoming connections (the thumbor is configured by default with HTTP_LOADER_MAX_CLIENTS=10). Because our Thumbor instances use the default configurations I suppose the Tornado's simple_httpclient is used.

### Expected behaviour
I expected that new connections are made to the remote host and not blocked in the queue during the connection timeout.

### Operating system
Ubuntu 16.04

### Your thumbor.conf
> #!/usr/bin/python
> ALLOWED_SOURCES = ['.+.my-domain']
> QUALITY = 85
> MAX_PIXELS = 100e6
> 
> MAX_AGE = False
> MAX_AGE_TEMP_IMAGE = 0
> LOADER = 'thumbor.loaders.http_loader'
> 
> MAX_SOURCE_SIZE = 0
> 
> UPLOAD_ENABLED = False
> UPLOAD_PHOTO_STORAGE = 'thumbor.storages.file_storage'
> UPLOAD_PUT_ALLOWED = False
> UPLOAD_DELETE_ALLOWED = False
> 
> STORAGE = 'thumbor.storages.no_storage'
> RESULT_STORAGE_STORES_UNSAFE=True
> STORES_CRYPTO_KEY_FOR_EACH_IMAGE = True
> 
> ENGINE = 'thumbor.engines.pil'
> ENGINE_THREADPOOL_SIZE = 12
> DETECTORS = [
> ]
> SECURITY_KEY = "MY_SECURE_SECRET_KEY"
> ALLOW_UNSAFE_URL = True
> FILTERS = [
>     'thumbor.filters.brightness',
>     'thumbor.filters.contrast',
>     'thumbor.filters.rgb',
>     'thumbor.filters.round_corner',
>     'thumbor.filters.quality',
>     'thumbor.filters.noise',
>     'thumbor.filters.watermark',
>     'thumbor.filters.equalize',
>     'thumbor.filters.fill',
>     'thumbor.filters.sharpen',
>     'thumbor.filters.strip_icc',
>     'thumbor.filters.frame',
> ]
>

**Comment by masom** [comment]
@tempuser14 Were all the requests made to the same source url? Thumbor uses a mutex on upstream requests to the same url.

**Comment by tempuser14** [comment]
@masom No, all requests are made to different URLs, like Req1 => remote-host/picture-id1, Req2 => remote-host/picture-id2, Req3 => remote-host/picture-id3

**Comment by tempuser14** [comment]
The underlying cause for this problem was that the outgoing connections were too slow (technical problems on the remote side). 
I will close the issue because our problem is now solved (through solving the underlying problem).
