### ISSUE TITLE
We are testing against Python 2.7.3, not 2.7.13

### ISSUE THREAD

**Issue by cclauss** [thumbor/thumbor#959]
https://github.com/thumbor/thumbor/blob/master/.travis.yml#L3

I do not understand well enough to fix it but we should not test against such an old version.

**Comment by masom** [comment]
Some of it has to do with supporting Ubuntu precise on TravisCI. We could probably look at refreshing the CI pipeline or just also support 2.7.13

**Comment by cclauss** [comment]
We are [now on trusty](https://travis-ci.org/thumbor/thumbor/jobs/271430245#L4), not precise.

**Comment by hugovk** [comment]
This can be closed, Python 2.7.13 is now being tested.

https://travis-ci.org/thumbor/thumbor/jobs/301103433#L560

**Comment by cclauss** [comment]
Just in time for Python 2.7.14 ;-)
