### ISSUE TITLE
Feature request: add (optional) hostname header

### ISSUE THREAD

**Issue by danielmotaleite** [thumbor/thumbor#965]
When using several dockers, if one thumbor starts to act weird, it very hard to find what docker is the guilty one. A simple solution is a optional parameter (off by default) that adds the ```X-Thumbor: $HOSTNAME``` header.

This way the final test user can check where the problem is comming , or better yet, any reverse proxy can log the status code vs thumbor backend and drop the header, allowing one can quickly find and kill/debug any bad thumbor. by checking the logs

**Comment by heynemann** [comment]
Do you think you can provide a PR with this?
