### ISSUE TITLE
Convert PNG to JPG & filling transparency while keeping original ratio

### ISSUE THREAD

**Issue by nhapke** [thumbor/thumbor#971]
Hi guys,

First of all, thanks a lot to everyone involved for maintaining thumbor. I was reading the documentation back and forth, but couldn't find anything related. Hope you can help me out.

### Thumbor request URL
https://test.com/K38xu2hHOwxjLThgGPcg-PKAnDI=/fit-in/800x800/filters:format(jpeg):fill(FFFFFF,true)/path/to/image.png

### Expected behaviour
The original file is a PNG and I want to convert it to JPG. I want transparent pixels to become white. I want to keep the ratio of the original PNG file. So 1600x800 should resize to 800x400.

### Actual behaviour
The `fill_in` filter prevents keeping the original ratio. So the output image is always 800x800 

Counting on you! Thanks a lot,
Niels

**Comment by nhapke** [comment]
Sorry guys, would be great to get some input here. We are definitely happy to contribute, but in thise case a bit stuck. @heynemann @cezarsa ?

**Comment by heynemann** [comment]
I'm not sure we should change the fill filter to do that. :/ It's actually doing what it's intended to: filling.

I think the format filter should get a transparent color instead. That way if we're to drop the alpha channel we can replace all the transparent pixels with the specified color. 

What do you think?

**Comment by kkopachev** [comment]
I used this image http://pngimg.com/uploads/broccoli/broccoli_PNG2820.png
and request like this: `/unsafe/fit-in/800x600/filters:format(jpg):background_color(white)/broccoli_PNG2820.png`
to get what you'd expect

**Comment by nhapke** [comment]
Oh dear. We were not aware of the `background_color` filter. Could this be new? If it works as expected, it will definitely solve our issue! Thanks a lot @kkopachev !

**Comment by heynemann** [comment]
http://thumbor.readthedocs.io/en/latest/background_color.html

I totally forgot! Closing this...
