### ISSUE TITLE
Format filter not working

### ISSUE THREAD

**Issue by matheusrufca** [thumbor/thumbor#976]
Hello!

Format filter is not working, the output is always the same of the original format.
Am I missing something?

### Thumbor request URL
https://thumbor-server/unsafe/filters:format(webp)/https://i.imgur.com/8RYMnIH.jpg
https://thumbor-server/unsafe/filters:format(gif)/https://i.imgur.com/8RYMnIH.jpg
https://thumbor-server/unsafe/filters:format(png)/https://i.imgur.com/8RYMnIH.jpg

### Expected behaviour
WebP image
Gif image
Png image

### Actual behaviour
All return a jpeg image

### Operating system
Heroku

### Your thumbor.conf
```
STORAGE = "thumbor.storages.mixed_storage"

MIXED_STORAGE_FILE_STORAGE = "thumbor.storages.no_storage"
MIXED_STORAGE_CRYPTO_STORAGE = "thumbor.storages.no_storage"
MIXED_STORAGE_DETECTOR_STORAGE = "thumbor.storages.no_storage"

FILTERS = [
    'thumbor.filters.brightness',
    'thumbor.filters.contrast',
    'thumbor.filters.rgb',
    'thumbor.filters.round_corner',
    'thumbor.filters.quality',
    'thumbor.filters.noise',
    'thumbor.filters.watermark',
]

QUALITY = 80
AUTO_WEBP = True

OPTIMIZERS = [
	'thumbor.optimizers.jpegtran'
]
JPEGTRAN_PATH = '/usr/bin/jpegtran'
```

**Comment by Savar** [comment]
I don't see that you enabled the 'format' filter.. so it cannot work, do it?

Am 8. September 2017 16:05:18 MESZ schrieb Matheus Rufca <notifications@github.com>:
>Format filter is not working, the output is always the same of the
>original format.
>
>### Thumbor request URL
>https://vizzto-thumbor.herokuapp.com/unsafe/filters:format(webp)/https://i.imgur.com/8RYMnIH.jpg
>https://vizzto-thumbor.herokuapp.com/unsafe/filters:format(gif)/https://i.imgur.com/8RYMnIH.jpg
>https://vizzto-thumbor.herokuapp.com/unsafe/filters:format(png)/https://i.imgur.com/8RYMnIH.jpg
>
>### Expected behaviour
>WebP image
>Gif image
>Png image
>
>### Actual behaviour
>All return a jpeg image
>
>### Operating system
>Heroku
>
>### Your thumbor.conf
>```
>STORAGE = "thumbor.storages.mixed_storage"
>
>MIXED_STORAGE_FILE_STORAGE = "thumbor.storages.no_storage"
>MIXED_STORAGE_CRYPTO_STORAGE = "thumbor.storages.no_storage"
>MIXED_STORAGE_DETECTOR_STORAGE = "thumbor.storages.no_storage"
>
>FILTERS = [
>    'thumbor.filters.brightness',
>    'thumbor.filters.contrast',
>    'thumbor.filters.rgb',
>    'thumbor.filters.round_corner',
>    'thumbor.filters.quality',
>    'thumbor.filters.noise',
>    'thumbor.filters.watermark',
>]
>
>QUALITY = 80
>AUTO_WEBP = True
>
>OPTIMIZERS = [
>	'thumbor.optimizers.jpegtran'
>]
>JPEGTRAN_PATH = '/usr/bin/jpegtran'
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/thumbor/thumbor/issues/976

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by matheusrufca** [comment]
@Savar sorry and thanks, I followed docs and didn't notice I have to manually enable filters.
It's now working but when I try to download image browser recognize as original format. Is it a normal behavior?

I'm getting the message on console:
> Resource interpreted as Document but transferred with MIME type image/gif: "https://vizzto-thumbor.herokuapp.com/unsafe/1000x1000/filters:format(gif)/https://i.imgur.com/8RYMnIH.jpg".

![image](https://user-images.githubusercontent.com/8710641/30217252-f64db85e-948b-11e7-94da-6de7ad920a36.png)

**Comment by Savar** [comment]
If you download the image and check it with the 'file' command you should see type gif...

Am 8. September 2017 16:56:35 MESZ schrieb Matheus Rufca <notifications@github.com>:
>@Savar sorry and thanks, I followed docs and didn't notice I have to
>manually enable filters.
>It's now working but when I try to download image browser recognize as
>original format. Is it a normal behavior?
>
>I'm getting the message on console:
>> Resource interpreted as Document but transferred with MIME type
>image/gif:
>"https://vizzto-thumbor.herokuapp.com/unsafe/1000x1000/filters:format(gif)/https://i.imgur.com/8RYMnIH.jpg".
>
>![image](https://user-images.githubusercontent.com/8710641/30217252-f64db85e-948b-11e7-94da-6de7ad920a36.png)
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/thumbor/thumbor/issues/976#issuecomment-328126028

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
