### ISSUE TITLE
There's a way to work with Google Storage?

### ISSUE THREAD

**Issue by nandosangenetto** [thumbor/thumbor#978]
My question is on title. I was searching in issues and the documentation, I didn't find anything mentioning that.

**Comment by kkopachev** [comment]
maybe this could help https://github.com/Superbalist/thumbor-cloud-storage or it's original version

**Comment by heynemann** [comment]
I don't think anyone has done it, so it would be very valuable to the community.

Closing this as this is not an issue with thumbor.

If you have any further questions on this issue, please reopen it.
