### ISSUE TITLE
Loader 'ERROR retrieving image' from S3 for first time an image is processed

### ISSUE THREAD

**Issue by achrafSallemi** [thumbor/thumbor#979]
### My Config
    LOADER: tc_aws.loaders.presigning_loader
    TC_AWS_LOADER_BUCKET: BUCKET
    TC_AWS_LOADER_ROOT_PATH: PATH

    STORAGE: thumbor.storages.mixed_storage
    MIXED_STORAGE_FILE_STORAGE: tc_aws.storages.s3_storage

### Expected behaviour
Source Images are saved on S3 and LOADER load source images from S3.

### Issue
When Image does not exist on S3(on the first call), the Loader throws an error and Thumbor stops

tornado.curl_httpclient:DEBUG Connection #1 to host s3.eu-central-1.amazonaws.com left intact
thumbor:DEBUG METRICS: timing: original_image.fetch.404.s3.eu-central-1.amazonaws.com:129
thumbor:DEBUG METRICS: inc: original_image.status.404:1
thumbor:WARNING ERROR retrieving image HTTP 404: Not Found

### Expected behaviour 
If the LOADER doesn't find source image on S3, it should get it from URL as fallback.

**Comment by heynemann** [comment]
It seems this issue should be filed in tc_aws, right?

If you have any further questions on this issue, please reopen it.
