### ISSUE TITLE
How to crop / resize only? (don't change quality or apply optimizers)

### ISSUE THREAD

**Issue by ahmed-sigmalux** [thumbor/thumbor#990]
What is the syntax to crop / resize an image only, without applying any quality changes or optimizers? Since JPEG, PNG, and WEBP quality are defined as 80 in my thumbor conf, that quality is always applied, even when I don't want to apply it. Furthermore, I've added the jpegtran and pngquant optimizers in my conf, so they are also applied to all images regardless of any other settings.

**Comment by heynemann** [comment]
http://thumbor/unsafe/100x100:800x800/300x200/quality:100/my/image.jpg

http://thumbor.readthedocs.io/en/latest/usage.html#image-endpoint

Please remember to read thumbor's docs as they are really comprehensive.

If you have any further questions on this issue, please reopen it.

**Comment by ahmed-sigmalux** [comment]
Using the quality:100 filter generates images that are **larger** than the original and **doesn't** skip the optimizer...

I'm asking how to return the untouched, non-optimized original image.

**Comment by heynemann** [comment]
We do not support it. Optimizers are run automatically.
