### ISSUE TITLE
Sharpened png's occassionally become very ugly

### ISSUE THREAD

**Issue by arjenm** [thumbor/thumbor#994]
We are evaluating Thumbor as a replacement for custom php + imagick code. So far it worked well, but we did encounter some issues. One of which is that the combination of fit-in + sharpen seems to generate very ugly images in certain circumstances. We use latest pip thumbor (6.3.3rc0).

We tested:
- With or without fit-in; this, combined with sharpen to be causing it.
- With or without sharpen; see above
- With/without fill; no change
- With/without optimizers; no change

### Thumbor request URL
JPG Original, works well:
https://ic.tweakimg.net/ext/i/2000901906.jpeg
Ok small:
https://tweakers.net/i/zr6E5c-1V0NgKeZC5caisOKLDL8=/fit-in/188x141/filters:sharpen(0.5,0.1,false):fill(white)/i/2000901906.jpeg
OK large:
https://tweakers.net/i/P7T_4jjD_pHh0kZZjHODE_MObWU=/fit-in/x800/filters:sharpen(0.5,0.1,false):fill(white)/i/2000901906.jpeg

Slightly different PNG original, yields ugly results (should be similar to jpeg variant):
https://ic.tweakimg.net/ext/i/2000898817.png
Ugly small:
https://tweakers.net/i/TXqY_ifj_ihNHzqYeBhiY5X5QhA=/fit-in/188x141/filters:sharpen(0.5,0.1,false):fill(white)/i/2000898817.png
Ugly large:
https://tweakers.net/i/6vrEynF5YSPHpPLryX3P8nojmMA=/fit-in/x800/filters:sharpen(0.5,0.1,false):fill(white)/i/2000898817.png

Very different PNG, also ugly (so its not just that source):
https://ic.tweakimg.net/ext/i/2001289161.png
Ugly small:
https://tweakers.net/i/QSngFDAOnEeXt3NcDXok7oeaZZc=/fit-in/188x141/filters:sharpen(0.5,0.1,false):fill(white)/i/2001289161.png

But not every PNG images is ugly:
https://ic.tweakimg.net/ext/i/2000898817.png
Ok small:
https://tweakers.net/i/YxinlthCI0LoMqK3U47EFqt-thU=/fit-in/188x141/filters:sharpen(0.5,0.1,false):fill(white)/i/2000898818.png
Ok large:
https://tweakers.org/i/n3TpPMLgr0HqcB7q4KmOtIhkFL0=/fit-in/x800/filters:sharpen(0.5,0.1,false):fill(white)/i/2000898818.png

### Expected behaviour
I'd expect all thumbnails to be roughly similar to the first one ;)

### Actual behaviour
See images.

### Operating system
Ubuntu

### Your thumbor.conf (on a test server, production has similar, but without unsafe)
QUALITY = 95
MAX_AGE = 86400
MAX_AGE_TEMP_IMAGE = 0
USE_GIFSICLE_ENGINE = True
LOADER = 'thumbor.loaders.file_loader_tweakers_http_fallback'
STORAGE = 'thumbor.storages.no_storage'
RESULT_STORAGE = 'thumbor.result_storages.file_storage'
URL_SIGNER = 'libthumbor.url_signers.base64_hmac_sha1'
SECURITY_KEY = '...'
ALLOW_UNSAFE_URL = True
ENABLE_ETAGS = False
FILE_LOADER_ROOT_PATH = '...'
HTTP_LOADER_CONNECT_TIMEOUT = 5
HTTP_LOADER_REQUEST_TIMEOUT = 20
FILE_STORAGE_ROOT_PATH = '...'
OPTIMIZERS =     [
'thumbor.optimizers.jpegtran', 
'thumbor_plugins.optimizers.pngcrush',
'thumbor_plugins.optimizers.optipng',
'thumbor_plugins.optimizers.pngquant',
    ]
JPEGTRAN_PATH = '/usr/bin/jpegtran'
PNGCRUSH_PATH = '/usr/bin/pngcrush'
PNGQUANT_PATH = '/usr/bin/pngquant'
OPTIPNG_PATH = '/usr/bin/optipng'
OPTIPNG_LEVEL = 2
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '...'
RESULT_STORAGE_STORES_UNSAFE = False

Could this be related to (or even a duplicate of) #945 ?

**Comment by kkopachev** [comment]
Not related to #945. 
In short, filter expects rgb data to work with, but engine returns palletted mode image.

**Comment by arjenm** [comment]
@kkopachev thanks for clarifying that.

We also found some jpeg's that have similar behavior, do you have any idea whether this is the same issue or (yet another)?
https://tweakers.net/i/JLOD1XhH9IN0iwUQX1Jm0SYWrJw=/fit-in/84x63/filters:sharpen(0.5,0.1,false):fill(white)/i/2001707895.jpeg
Original: https://ic.tweakimg.net/ext/i/2001707895.jpeg

https://tweakers.net/i/HnX2SooaDc0b87qpqUOKeFjPy7I=/fit-in/188x141/filters:sharpen(0.5,0.1,false):fill(white)/i/2001501717.jpeg
Original: https://ic.tweakimg.net/ext/i/2001501717.jpeg

It occurs with Thumbor 6.3.3rc0 with Pillow 4.3.0

**Comment by kkopachev** [comment]
@arjenm that's not related to original issue. Not sure how sharpen works, but setting last parameter to true solves issue for me.
