### ISSUE TITLE
thumbor can not load config from file 

### ISSUE THREAD

**Issue by mohammadmojrian** [thumbor/thumbor#998]
hi,
### Expected behaviour
after the install thumbor i created config file with this command:
`/usr/local/bin/thumbor-config > /etc/thumbor.conf`
and i use this command to run thumbor via supervisor
`command=/usr/local/bin/thumbor --ip=127.0.0.1 --port=800%(process_num)s --conf=/etc/thumbor.conf
`
i so test **-C** and **--keyfile=...** too
and i test it on shell without supervisor

i set my security key and disable unsafe url with this value : 
`
SECURITY_KEY = 'UJwHAZLsRejTyLI88lAriHL7xAXa6q0umiwwpPcP'
ALLOW_UNSAFE_URL = False
ALLOW_OLD_URLS = False

`
But at runtime, these changes do not apply and they use the default settings of thumber

### Operating system
Ubuntu 14.04 64bit
Thumbor ver : 6.3

**Comment by mohammadmojrian** [comment]
@heynemann @cezarsa @fabiomcosta @guilhermef
please help to me

**Comment by heynemann** [comment]
How did you install thumbor? APT?

**Comment by mohammadmojrian** [comment]
no i install it from pip ,

[https://gist.github.com/guilhermef/297680f457f82fb27b3d](https://gist.github.com/guilhermef/297680f457f82fb27b3d)

and 

[https://www.dadoune.com/blog/best-thumbnailing-solution-set-up-thumbor-on-aws/](https://www.dadoune.com/blog/best-thumbnailing-solution-set-up-thumbor-on-aws/)

**Comment by heynemann** [comment]
@mohammadmojrian did you manage to fix this?

**Comment by andreaugusto** [comment]
Hi @mohammadmojrian,

Since loading the conf file via cmd is a known feature and AFAIK there is no issue associated with it, it probably is just the way things are set on your server. Let's try debugging it then.

If you change any other parameter, does it also change Thumbor's behavior? For instance, try to change the IP address to see if it binds to another IP on your server.

**Comment by tanrax** [comment]
`thumbor -c /root/thumbor.conf -p 8888`
same results

**Comment by heynemann** [comment]
Is there a `SECURITY_KEY` key in the thumbor.conf file?

**Comment by tanrax** [comment]
That's right, I fixed it by upgrading to version 7.0

**Comment by elinaldosoft** [comment]
Fixed it installing the latest version
`pip3 install git+https://github.com/thumbor/thumbor.git`

**Comment by mirzap** [comment]
I have the sam issue on `v6.7.5 (9-Mar-2020)` and I have specified `SECURITY_KEY` in my `thumbor.conf`.

I downloaded latest release, installed it with `pip install .`. I'm running thumbor with `thumbor -c /etc/thumbor/thumbor.conf -p 8888`
